### ISSUE TITLE
Valid assertions missing from cbmc output

### ISSUE THREAD

**Issue by allredj** [diffblue/cbmc#1002]
When running cbmc on the following java class:
```java
public class test
{
    public static void main(int x)
    {
        assert 1 + 1 == 2;
        if (x == 2){
            assert x == 2;
        }
    }
}
```
I get the following output:
```
...
** Results:
[java::test.main:(I)V.pointer_dereference.1] reference is null in *new_tmp0: SUCCESS
[java::test.main:(I)V.assertion.1] assertion at file test.java line 7 function java::test.main:(I)V bytecode_index 10: SUCCESS
...
```
That is, the first (statically true) assertion is discarded from the output, and the second one is assigned identifier `1`. In my opinion, this is potentially misleading and makes the writing of regression tests difficult, as we do not know in advance which assertions will be omitted. For instance, in the following example:
```java
      String s = new String("Abc");
      int length = s.length();
      assert(length == 3);
```
the assertion is removed from the output, which I would not immediately expect.
Although these simplifications by symex are totally correct, the removal of the validated assertions from cbmc's output make it a little inconsistent.

Should cbmc's output be specified somewhere?

=============
Version to reproduce:
CBMC version: 4b9f42ecfc944771dcfa11550d2692da2c35dc87 (test-gen-support branch)

**Comment by tautschnig** [comment]
Could you please check whether adding `--no-simplify` to the command line yields the output you are looking for?

**Comment by allredj** [comment]
So, `--no-simplify --unwind 5` does show me the assertion in the String example. But not in the `assert 1 + 1 ==2` case, which is not very far from `assert true`.

**Comment by tautschnig** [comment]
This is not a problem in JBMC: it's the Java compiler that removes this assertion. Here is the output of `javap -l -v -c test.class`:
```
  public static void main(int);
    descriptor: (I)V
    flags: (0x0009) ACC_PUBLIC, ACC_STATIC
    Code:
      stack=2, locals=1, args_size=1
         0: iload_0
         1: iconst_2
         2: if_icmpne     24
         5: getstatic     #2                  // Field $assertionsDisabled:Z
         8: ifne          24
        11: iload_0
        12: iconst_2
        13: if_icmpeq     24
        16: new           #3                  // class java/lang/AssertionError
        19: dup
        20: invokespecial #4                  // Method java/lang/AssertionError."<init>":()V
        23: athrow
        24: return
      LineNumberTable:
        line 6: 0
        line 7: 5
        line 9: 24
      StackMapTable: number_of_entries = 1
        frame_type = 24 /* same */
```
Observe that line 5 isn't included at all.
