### ISSUE TITLE
static member in class

### ISSUE THREAD

**Issue by mgudemann** [diffblue/cbmc#105]
In the following program the function ```f``` verifies div-by-zero, ```g``` correctly fails this property.
```
public class StaticMember
{
  static int xs;
  int x;
  public void f()
  {
    int d = 1 / (1 + xs);
  }
  public void g()
  {
    int d = 1 / (1 + x);
  }
}
```
When using either function as entry point, the value of the non-local variable should be considered non-deterministic.

**Comment by kroening** [comment]
This is debatable; one may wish to take a view where the object has been properly initialised, perhaps with a nondeterministically chosen constructor.

**Comment by mgudemann** [comment]
> This is debatable; one may wish to take a view where the object has been properly initialised, perhaps with a nondeterministically chosen constructor.

Definitively. But should there be a difference between static and non-static?

> BTW, assert would be the best way to test for nondeterminism, instead of the div-by-zero-check.

ok, thanks!

**Comment by kroening** [comment]
Given that the object will be constructed only once, there won't be a difference between static and non-static.
