### ISSUE TITLE
smt2_conv does not handle update of objects with variable size

### ISSUE THREAD

**Issue by peterschrammel** [diffblue/cbmc#122]
run for example with --unwind 2 --z3

array theory should be used, but "failed to get width of byte_update" is thrown 

array index expressions are translated correctly for arrays of variable size

```
#include <assert.h>

unsigned nondet_unsigned();

int main() {
  unsigned n = nondet_unsigned();
  __CPROVER_assume(n>0);
//  unsigned p[n]; // (1)
  unsigned *p = (unsigned *)malloc(sizeof(unsigned) * n); // (2)

  for (int i=0; i<n; i++) {
    p[i] = i; // correctly translated for (1), error thrown for (2)
  }
  assert(p[n-1] == n-1);

  return 0;
}

```

byte_update is used for p[i] although the type of p in the goto program is array of size (const * variable). Couldn't an index expression be generated if the access is obviously aligned?

**Comment by tautschnig** [comment]
Just to say that I'm investigating why malloc builds a char array (instead of an array of unsigned) here.

**Comment by tautschnig** [comment]
Investigation and debugging completed, see #126, which actually also fixes further bugs.
