### ISSUE TITLE
Implement settingst object

### ISSUE THREAD

**Issue by LAJW** [diffblue/cbmc#1309]
A data structure that would replace `optionst` and be the primary way of providing arguments for constructing modules. Should have following properties:

 - Key-value map
 - Value can be of type `int`, `bool`, `string`, (and potentially reference to an object) or an array of one of each.
 - Cheap copy and value override by sharing values with old instances.

Requested by @peterschrammel.

**Comment by LAJW** [comment]
I'd assign myself If I could.

**Comment by TGWDB** [comment]
Closing as this does not appear to be happening.
