### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by peterschrammel** [diffblue/cbmc#1314]
- [ ] replace asserts
- [ ] define basic exceptions (util/error.h / https://github.com/diffblue/cbmc/pull/1280) 
- [ ] replace throws
- [ ] replace integer return codes where appropriate
- [ ] replace boolean return codes where appropriate
- [ ] clean up catches (lift to top-level and report to user in a single place)

**Comment by TGWDB** [comment]
Closing as this appears to be an idea/architecture request that is beyond the scope of a ticket here. Observations are that some of this is done/being done anyway. Please reopen if you believe this is erroneous.

**Comment by martin-cs** [comment]
Quite a lot of this was implemented with the introduction of the `INVARIANTS` and various clean-ups associated with it.  There is still work to be done on this area though.  I guess it depends how you feel about issues that are "This would be good to do at some point".
