### ISSUE TITLE
Replace partial inline

### ISSUE THREAD

**Issue by peterschrammel** [diffblue/cbmc#1316]
@tautschnig, @kroening, why is https://github.com/diffblue/cbmc/blob/develop/src/cbmc/cbmc_parse_options.cpp#L825 done?

This makes the coverage goal instrumentation non-compositional, which is troublesome.

**Comment by tautschnig** [comment]
I believe this is done for the same reason that functions in ansi-c/library/* are marked as "inline": it should avoid confusion in the counterexample by displaying the point-of-call source location instead of "<built-in-library...".

**Comment by peterschrammel** [comment]
Has been cleaned up in #1372.
