### ISSUE TITLE
Factor out replacement of calls to bodyless functions into separate pass

### ISSUE THREAD

**Issue by peterschrammel** [diffblue/cbmc#1317]
...to enable custom replacements (assume(false), return nondet, full nondet sideeffects and returns, summaries, etc).

**Comment by tautschnig** [comment]
Note that there already is "undefined-function-is-assume-false" in `goto-instrument`. While I do agree that some factoring-out would be good, there is a risk of introducing even more command-line options to control the behaviour. I would strongly suggest that any such pass is done via `goto-instrument`.

**Comment by TGWDB** [comment]
Closing as a feature we're not actively working on (and have not been considering for a long time). Please reopen if you believe this is erroneous.
