### ISSUE TITLE
Some CORE regression tests do not complete when CBMC is built with Glucose

### ISSUE THREAD

**Issue by reuk** [diffblue/cbmc#1366]
Discovered on #1293.

Using the Glucose/CMake build of CBMC (enabled by passing `-Dsat_impl=glucose` when running the initial configure), some CORE regression tests appear not to complete:

- strings-smoke-tests/java_int_to_string/test2.desc
- strings-smoke-tests/java_int_to_string_with_radix/test_decimal.desc
- strings-smoke-tests/java_long_to_string/test1.desc

**Comment by tautschnig** [comment]
This doesn't seem to be a problem any longer. As of #5709 we use Glucose in one of our GitHub actions.
