### ISSUE TITLE
Replace static_analysis by ai

### ISSUE THREAD

**Issue by peterschrammel** [diffblue/cbmc#14]
extract patch from new lock analysis implementation

**Comment by tautschnig** [comment]
Is this issue actually still open, or has #27 properly addressed it? If not, what is still missing?

**Comment by peterschrammel** [comment]
Let's close this. This seems to be done in master.
Extensions (thread- and context-sensitive analysis) have been done in the deadlock-analysis branch. The two branches have largely diverged and there is no reason for pulling in changes from there at the moment.
