### ISSUE TITLE
Incorrect verification failed when using pointers to pointers inside structs

### ISSUE THREAD

**Issue by ldr709** [diffblue/cbmc#144]
Both CBMC 5.4 and the current development version (master branch) incorrectly output "VERIFICATION FAILED" when run on the following test case.

```
#include <assert.h>
#include <stdbool.h>
#include <stdlib.h>

struct list_entry {
    struct list_entry *next;
};

struct linked_list {
    struct list_entry *head;
    struct list_entry **tail;
};

struct linked_list_container {
    struct linked_list list;
};

int main(int argc, char* argv[])
{
    struct linked_list_container container;
    struct linked_list *list = &container.list;
    struct list_entry head;

    list->head = NULL;
    list->tail = &list->head;

    *list->tail = &head;
    list->tail = &head.next;

    assert(list->head);

    return 0;
}
```

I have uploaded CBMC's output for this program to [this](https://gist.github.com/ldr709/e1e88b824653fecf05210f672dcbc37e) gist. It looks CBMC thinks that `list->tail` points to an invalid object at line 27 of test_case.c.

**Comment by tautschnig** [comment]
The underlying problem was fixed sometime before 5.10. Closing.
