### ISSUE TITLE
Refactor bmct into a more convenient API

### ISSUE THREAD

**Issue by peterschrammel** [diffblue/cbmc#15]
bmct and incremental_bmct can be easily used interchangeably in other BMC-based tools (like cegis)
most of that has already been done in the peter-incremental-unwinding branch

**Comment by peterschrammel** [comment]
Also @karkhaz's path-explorer needs to be separated out and based on a common safety-checker/BMC interface. The current integration into bmct itself is very hard to maintain.

**Comment by karkhaz** [comment]
@peterschrammel bmct is certainly more unwieldy and less elegant than it used to be given the path explorer stuff, sorry about that. Is there anything specific that you'd like me to do or help with? I won't be free to work on CBMC for the next month or so, but if you have some specific suggestions I can start thinking about how to get them done.

**Comment by peterschrammel** [comment]
has been done
