### ISSUE TITLE
Make goto binaries work with java

### ISSUE THREAD

**Issue by peterschrammel** [diffblue/cbmc#16]
currently,
`goto-cc class-file -o goto-binary`
produces a goto-binary, but
`cbmc goto-binary` 
fails with "Multi-language linking not supported", and
`goto-instrument goto-binary --show-goto-functions`
fils with "symbol `_start' has unknown mode 'java'"

**Comment by danpoe** [comment]
I'm looking into that.

**Comment by kroening** [comment]
Done with e31bacb
