### ISSUE TITLE
Error `identifier __CPROVER_memory not found`

### ISSUE THREAD

**Issue by mgudemann** [diffblue/cbmc#161]
For thie [file](https://github.com/v-l-a-d/java-driver/blob/2.1/driver-core/src/main/java/com/datastax/driver/core/querybuilder/Utils.java) the following `cbmc --unwind 3 --function "com.datastax.driver.core.querybuilder.Utils.containsBindMarker:(Ljava/lang/Object;)Z" com/datastax/driver/core/querybuilder/Utils.class` returns `identifier __CPROVER_memory not found`

**Comment by peterschrammel** [comment]
Fixed. See https://github.com/diffblue/cbmc/issues/197
