### ISSUE TITLE
Using mallinfo, CBMC does not print out the memory consumption correctly.

### ISSUE THREAD

**Issue by jungyh0218** [diffblue/cbmc#1619]
When printing out the memory consumption of the program by giving verbosity 10, I found out that there was a variable overflow. As the result, a negative integer value was printed. Is there any other way to check the memory consumption?

**Comment by martin-cs** [comment]
Not within the tool.  I tend to use GNU time using -v to capture peak memory usage and time externally of the tool.  I presume you were allocating more than 2GB of RAM?
