### ISSUE TITLE
Discussion : context-sensitive abstract interpretation

### ISSUE THREAD

**Issue by martin-cs** [diffblue/cbmc#1638]
@chrisr-diffblue and myself have to implement something like this in the next month or so.  The following is a write up of a discussion @chrisr-diffblue , @NlightNFotis and I had on the topic.  I thought it would be good to make it public as I know @danpoe and @peterschrammel have experience of how to approach this and I think maybe @smowton , @tautschnig and @thk123  might care about the solution being generally useful and not dreadfully limited.

Just so we are on the same page, consider the following piece of (shonky) C:

```C
int do_io (void *thing, size_t amount, int mode) {
        char *working = thing;
        if (mode == READ) {
                for (size_t i = 0; i < amount; ++i)
                    if (!mmu_read(working + i))  // Does change working!
                        return READ_FAILED;
                return READ_SUCCEEDED;
        } else if (mode == WRITE) {
                for (size_t i = 0; i < amount; ++i)
                    if (!mmu_write(working[i]))    // Doesn't change working!
                        return WRITE_FAILED;
                return WRITE_SUCCEEDED;
        } else if (mode == ATOMIC_SWAP) {
                 // Other stuff
        } else {
                return UNKNOWN_MODE;
        }
}

int handle_CAN_bus (struct CAN_bus_packet *s) {
        // ... whatever ...

        do_io(s, sizeof(CAN_bus_packet), READ);

        s.enabled = 0xFF;

        int ret = do_io(s, sizeof(CAN_bus_packet), WRITE);

        assert(ret == WRITE_SUCCEEDED || ret == WRITE_FAILED);
        assert(s.enabled == 0xFF);

        // ... whatever ...
}
```

Ignoring (for now) the non-type-safe updates and the challenges about pointer handling and thinking about abstract interpretation with constant domain, the two assertions will fail because the second call to do_io will merge the two possible values for mode, so the analysis will then consider all paths, including the ones that wipe the structure and those that return "obviously" wrong status codes.

This is because ait maintains a map ```location -> domain``` but does not (cannot) distinguish between calling contexts.  So we need to add some kind of notion of context so we have ```location * context -> domain```.  At this point it is worth noticing a subtle point; location is used for two different things in ait:
1. Finding which domain to use.
2. Expressing which instructions to interpret next.

This gives three different approaches to implementation:
A. Context is part of domain  (  ```location -> (context -> domain)``` )
B. Location is part of context (  ```(context -> location) -> domain```)
C. Context is it's own thing ( ```location * context -> domain```)

What Does A Look Like?
-------------------------------

```C++
class contextt {
  void push(cont call_site_info &);
  bool operator= (const context &) const;
}

class context_aware_domaint : public ai_base_domaint {
  std::map<context, ai_base_domaint*> domains;

  void transform(locationt from, locationt to, ai_base &ai, const namespacet &ns) {
    foreach (context, domain) in domains {
      domain.transform(from, to, ai, ns);
      if (from->is_function_call()) {
        context.push( from );
    }
  }

  bool merge (const context_aware_domaint &other, location from, location to) {
    foreach (ocontext, odomain) in other.domains {
      if (domains.contains(ocontext, domain))
        domain.merge(odomain, from, to);
      else
        domains.push((ocontext, odomain))
    }
  }
}
```

+ Simple to implement
+ Contained, doesn't require any changes to the ait / ai_baset infrastructure
- Rather misses the idea of domains a light-weight object
- Performance impact is not clear
- Different contexts are rather buried and difficult to access

What Does B Look Like?
-------------------------------

The key idea I had when considering this is that the context is actually an abstraction / representation of a set of possible control flow histories.  Using a locationt is, in effect, saying "any sequence of execution that gets me here"  However there are many other possibilities; the number of iterations of various loops (which gives unwinding or widening), the call sequence, the thread configuration, etc.  ( For some reason saying the words "abstraction of control flow histories" makes me think of @cesaro )

This requires an interface for these:

```C++
class ai_history_baset {
public:
  virtual void step(locationt from, locationt to) = 0;
  virtual locationt current_pc(void) const = 0;
}

class ahistoricalt : public ai_history_baset {
private:
  locationt current;
public:
 ahistoricalt (locationt start) : current(start) {}
 void step(location from, location to) { current = to; }
 locationt current_pc(void) const { return current; }
}
```

Now we need to adapt ```ai_baset```, this is essentially just ```s/locationt/historyt/``` with visit becoming:

```
class ai_baset {
typedef ai_history_baset historyt;
historyt start_history(locationt bang) const = 0;
// ...
}

bool ai_baset::visit(
  historyt &h,
  working_sett &working_set,
  const goto_programt &goto_program,
  const goto_functionst &goto_functions,
  const namespacet &ns)
{
  bool new_data=false;

  statet &current=get_state(h);
  location l = h.current_pc();

  for(const auto &to_l : goto_program.get_successors(l))
  {
    if(to_l==goto_program.instructions.end())
      continue;

    std::unique_ptr<statet> tmp_state(
      make_temporary_state(current));
    statet &new_values=*tmp_state;

    std::unique_ptr<historyt> tmp_history(
      make_temporary_state(h));
    historyt &new_history= *tmp_history;

    bool have_new_values=false;

    if(l->is_function_call() &&
       !goto_functions.function_map.empty())
      // Boring...
    else
    {
      // initialize state, if necessary
      get_state(h);

      new_values.transform(l, to_l, *this, ns);
      new_history.step(l, to_l);

      if(merge(new_values, l, to_l) || ???)      // Not quite clear how to do this?
        have_new_values=true;
    }

    if(have_new_values)
    {
      new_data=true;
      put_in_working_set(working_set, new_history);
    }
  }

  return new_data;
}
```

Separate from this we implement storage (the other role of the history):

```
template <typename historyT, typename domainT>
class ai_base_history_based_storaget : public ai_baset {
  typedef std::unordered_map<historyT, domainT, const_target_hash> state_mapt;
  state_mapt state_map;

}
```

Finally, we need to fix up ait so it keeps it's current behaviour:

```C++
template <typename domainT>
class ait : public ai_baset {
  historyt start_history(locationt bang) const { return ahistoricalt(); }

  virtual statet &get_state(historyt h) override
  {
    return state_map[h.current_PC()]; // calls default constructor
  }
  // ...
}
```

To use a more elaborate history but still only store on domain per location (for example for widening), inherit from ait<domainT> and override start_history().  To alter the storage do something like:

```C++
template <typename domainT>
class location_insensitive_ait : public ai_baset {
  typedef std::unordered_map<irep_idt, domainT, irep_id_hash> state_mapt;
  state_mapt state_map;

  historyt start_history(locationt bang) const { return ahistoricalt(); }

  virtual statet &get_state(historyt h) override
  {
    return state_map[h.current_PC().function]; // calls default constructor
  }
  // ...
}

template <typename historyT, typename domainT>
class context_sensitive_ait : public ai_baset {
  typedef std::unordered_map<historyT, domainT, typename historyT::hash_function> state_mapt;
  state_mapt state_map;

  historyt start_history(locationt bang) const { return historyT(); }

  virtual statet &get_state(historyt h) override
  {
    return state_map[dynamic_cast<historyT>(h)]; // calls default constructor
  }
  // ...
}
```

+ Conceptually really clean
- Non-trivial implementation
+ Contained, doesn't require any changes to any public interfaces.
+ Really versatile
+ Integrates with unwinding / widening (both loops and recursion)

What Does C Look Like?
-------------------------------

I'm guessing something like this:
https://github.com/diffblue/cbmc/blob/deadlock-analysis/src/analyses/ai_cs.h
https://github.com/diffblue/cbmc/blob/deadlock-analysis/src/analyses/ai_cs.h#L134
https://github.com/diffblue/cbmc/blob/deadlock-analysis/src/analyses/ai_cs.h#L418
https://github.com/diffblue/cbmc/blob/deadlock-analysis/src/analyses/ai_cs.cpp#L534

This version is somewhat more involved as it is tracking not only the calling context but thread states but a similar idea of having the working stack contain pairs of context and location could handle context as well.

- Requires similar implementation / threading through as B but less versatile
+ Might be a bit simpler than B to understand

Things to do next
----------------------
*. Look at how recursive functions work in each of these.
*. @chrisr-diffblue and I will have a go at B on Thursday and see if there is any life in it.
*. Read everyones insightful commentary below vvvvvvvvv

**Comment by smowton** [comment]
I already have an implementation of (B) for the particular case of value-set analysis: https://github.com/diffblue/security-scanner/pull/259

In essence, we maintain a tree of contexts, each of which are standard function-scoped `ait` instances. Recursive calls feed up the tree; other calls have corresponding child contexts.

**Comment by tautschnig** [comment]
I believe (C) is the approach that CPA/CPAchecker seeks to implement and promote. The concept of modular domains and being able to combine them is appealing as it would, e.g., also be useful for a much more precise function-pointer analysis. See [CAV'07](https://www.sosy-lab.org/research/pub/2007-CAV.Configurable_Software_Verification.pdf) for the description of the concepts.

In practice, this might be implemented via a meta-domain that takes several domains as template parameters and then invokes the individual domain operations. There shouldn't be any changes required to the existing code, just adding this new meta-domain and then doing suitable template instantiations. Well, actually you do need to add the context domain as another new domain, but then @smowton's implementation may provide almost all that's needed.

**Comment by martin-cs** [comment]
A quick follow up:

*. I discussed this with Chris and I seemed to have miscommuncated, I think we came to the conclusion that there solution is an instance of (C).  He is interested in the option of (B) and might make use of it.

*. @tautschnig Thanks for the link.  I think what I am proposing is subtly different and a little more general but, operationally, very much that kind of thing.

@chrisr-diffblue and I are working on a version of (B) and I'll link this issue when we get to PR stage.

**Comment by martin-cs** [comment]
Follow up with (what I think is) an interesting observation.  (B) is straight forward and elegant apart from one thing -- function return.  I tried to implement this a number of times before I came to something of a realisation.  Function return (and exceptions to some degree, but *not* normal branch) is history sensitive control flow.  Consequences:

*. If you are really doing analysis without history then you have to merge the end of the function with *all* possible call sites.

*. The existing infrastructure does not do this and thus is implementing a kind of history sensitive analysis.  However rather than keeping the information for this in the analyzer data structures, it is encoded in the call-stack / recursion of the analyzer itself.  This makes integrating an explicit version of the history ... a bit tricky.  So (B) requires significantly more changes than you would expect and the "default" history abstraction that produces the same behaviour is ... more complex than just location, it requires a call stack as well.

*. Merging of histories is more involved than you might think because you are merging their return address stacks as well.  The CPAChecker papers notably omit this (significant!) detail.

*. I suspect this wrinkle affects approaches (C) and (A) as well ... it's just less clear how (perhaps that was what @peterschrammel was referring to when he said about problems with function calls in approach (A)).

Thoughts, observations and suggestions welcome from all.  @tautschnig @peterschrammel @smowton @chrisr-diffblue @danpoe @cesaro @marcelosousa 's contributions would be particularly interesting to me.

**Comment by smowton** [comment]
My implementation used a call tree-ish data structure, so return was simply flow-to caller contexts, which number exactly one except when this function is the root of a recursive subgraph, at which point return flowed to all callsites within this subgraph. That latter was a little inaccurate but is fairly rare in the grand scheme of things.

For example, `f { g(); g(); } g { h(); } h { g(); }` would result in the graph:

```
f -> g1
g1 -> h1
h1 -> g1
f -> g2
g2 -> h2
h2 -> g2
```

So returns from `g1` and `g2` would be the only imprecise ones, which would flow values to the callsite in `h1` or `h2` respectively plus the relevant call in `f`, but not the *other* call in `f` or the *other* instance of `h`.

**Comment by marcelosousa** [comment]
I don't know much about the current infrastructure but the _standard_ way of solving context sensitivity heavily relies on graphs implemented using memory efficient data-structures -- the prime example being Patricia trees. It could be interesting to look at Merkel trees as well. 

Regarding the three options, it seems clear to me that the most general choice is C -- from the literature (work by Reps, Cousot, Logozzo, Vechev, etc) this choice also seems to be norm.

AFAIK, the most practical result is still the IFDS framework (Reps, Horwitz, Sagiv, POPL'08 paper).

Regarding the last comment by @smowton; the precise representation has been extensively studied for _Dyck reachability_. The following works are relevant:

Subcubic Algorithms for Recursive State Machines - Swarat Chaudhuri.
Finding Fix Locations for CFL-Reachability Analyses via Minimum Cuts - Andrei Marian Dan et al.
Optimal Dyck Reachability for Data-dependence and Alias Analysis - Krishnendu Chatterjee et al.

**Comment by martin-cs** [comment]
In case anyone is following this:

https://github.com/diffblue/cbmc/pull/5036 implements the general framework.

https://github.com/diffblue/cbmc/pull/5072 implements context sensitivity in general.

**Comment by martin-cs** [comment]
Both PRs merged; I think this is done.
