### ISSUE TITLE
Make `goto_convert_functionst::convert_function` const

### ISSUE THREAD

**Issue by NathanJPhillips** [diffblue/cbmc#1675]
`goto_convert_functionst` has internal state that it changes during the course of conversion. Strictly speaking it should make that state mutable or recreate it for each conversion. Once that is done `goto_convert_functionst::convert_function` can be made const.
The fact this currently doesn't happen means that `lazy_goto_functions_mapt` currently stores an instance of `goto_convert_functionst` as a mutable field. This should be amended once this issue is addressed.

**Comment by TGWDB** [comment]
Closing as this does not appear to be progressing/in imminent future plans. Please reopen if you believe this is erroneous.
