### ISSUE TITLE
Extending --show-loops to display information about recursive calls

### ISSUE THREAD

**Issue by peterschrammel** [diffblue/cbmc#1680]
Running CBMC with --show-loops on
```
void foo(unsigned int a) {
  if(a==0)
    return;

  for(int i=0; i < a; ++i);

  foo(a - 1);
}
```
displays 
```
Loop foo.0:
  file test.c line 5 function foo
```
It would be useful to show also information on the recursive function foo.

(request from cprover mailing list)

**Comment by TGWDB** [comment]
Closing as this is not in the imminent future plans, although the idea/feature is nice. Please reopen if you believe this is erroneous.
