### ISSUE TITLE
Possible bug in left shift of bitvectors

### ISSUE THREAD

**Issue by polgreen** [diffblue/cbmc#1683]
left shift "<<" on signed and unsigned __CPROVER_bitvectors produces odd behaviour if the operator is used inside the __CPROVER_assert statement, and the number being shifted has a 1 in the MSB. 

In the following example, both assertions should be the same, but one passes and one fails:
~~~
typedef unsigned __CPROVER_bitvector[4] bv4;

void main(void)
{
  bv4 should_be_zero = 8u << 1;
  __CPROVER_assert(should_be_zero==0u, "");
  __CPROVER_assert((8u << 1)==0u ,"");
}
~~~
~~~
Trace for main.assertion.2:

State 18 file left_shift2.c line 6 function main thread 0
----------------------------------------------------
  should_be_zero=0 (0000)

State 19 file left_shift2.c line 6 function main thread 0
----------------------------------------------------
  should_be_zero=0 (0000)

Violated property:
  file left_shift2.c line 8 function main
  assertion
  8u << 1 == 0u



** 1 of 2 failed (2 iterations)
VERIFICATION FAILED
~~~

I'm running cbmc/develop at commit 7b06a006b0d55c2d17812feca1a04fa6d66303d9

**Comment by peterschrammel** [comment]
Not sure, I see the problem:
`(8u << 1)` in line 8 has more than 4 bits. Therefore, it does not overflow.

**Comment by polgreen** [comment]
Oh.. that's obvious once I've summarised my example that much. My original example had everything as explicitly being a bv. 

Ok, nevermind.. I just need to rethink how to translate smt bitvectors into cbmc bitvectors.
~~~
typedef unsigned __CPROVER_bitvector[16] bv;

void main(void)
{
  bv number_to_shift;
  bv number_to_shift_by = 1;
  bv result = number_to_shift << number_to_shift_by;
  __CPROVER_assert(result == (number_to_shift << number_to_shift_by), "");
}
~~~
