### ISSUE TITLE
Get rid of parameter_identifiers

### ISSUE THREAD

**Issue by tautschnig** [diffblue/cbmc#1695]
... because these are never used. See #1688.

**Comment by danpoe** [comment]
I think `parameter_identifiers` (in `goto_functiont`) was introduced as the identifiers shouldn't be part of the type. Should instead the parameter identifiers be removed from `code_typet` and the code base be refactored to fill in and use the `parameter_identifiers` in `goto_functiont`?

**Comment by tautschnig** [comment]
Fixed in #4167.
