### ISSUE TITLE
Move solver factory into src/solvers to unify solver instantiation

### ISSUE THREAD

**Issue by peterschrammel** [diffblue/cbmc#1700]
CBMC uses its solver factory cbmc_solverst to configure and instantiate solvers. 
As made apparent by https://github.com/diffblue/cbmc/pull/1501, solvers are instantiated in many more places (goto-instrument, solvers/flattening, solvers/refinement, ...). 
There should be a single factory to instantiate solver objects and configure them through optionst.

Therefore, I suggest to move the CBMC-independent part of cbmc_solverst into src/solvers. CBMC can still derive from that to implement CBMC-specific instantiation variants.

**Comment by TGWDB** [comment]
This appears to be have been done.
