### ISSUE TITLE
Core dump on --smt2

### ISSUE THREAD

**Issue by alipourm** [diffblue/cbmc#1723]
On CBMC 5.8, `cbmc minmized.c --smt2` for the following code crashes with a core dump. It works fine without `--smt2` option. 
`int a, b = &a;
int **c = b;
main() {
  int d = *c;
  assert(0);
}`

**Comment by tautschnig** [comment]
Thanks a lot for this report. I'm adding a somewhat sanitised version:
````c
#include <assert.h>

int main()
{
  int a;
#if 1
  // causes an assertion failure in SMT1 and SMT2 back-ends
  int b = &a;
#else
  int *b = &a;
#endif
  int **c = &b;
  int *d = *c;
  assert(0);
}
````
which leads to:
```
cbmc: smt2/smt2_conv.cpp:1712: void smt2_convt::convert_expr(const exprt&): Assertion `it!=defined_expressions.end()' failed.
```
or
```
cbmc: smt1/smt1_conv.cpp:1313: void smt1_convt::convert_expr(const exprt&, bool): Assertion `it!=array_expr_map.end()' failed.
```

**Comment by martin-cs** [comment]
Thanks both.  We should fix it anyway but this doesn't look like valid C to me.

@alipourm : is this a blocking issue for you?

**Comment by alipourm** [comment]
The failure occurs on all data structures that I have. 

The reported failure happened on an AVLTree implementation which was reduced by `creduce`. The original code is [here](http://alipourm.github.io/tmp/harness2.c). 
To reproduce, run `cbmc tmp/harness2.c -DMAX_ITEMS=2 --unwind 2 --smt2`.

**Comment by TGWDB** [comment]
Closing as no longer reproducible. Please reopen if you believe this is erroneous.
