### ISSUE TITLE
`simplify_expr` incorrectly simplifies equality between syntactically equivalent expressions

### ISSUE THREAD

**Issue by hannes-steffenhagen-diffblue** [diffblue/cbmc#1752]
When passing equals of two non-constant but syntactically equivalent expressions - such as `get_some_value() == get_some_value()` to `simplify_expr`, they will be simplified based on being syntactically equivalent. This is unsound because there is no guarantee the LHS and RHS are going to evaluate to the same value just because they are syntactically equivalent (obvious counterexample would be `rand() == rand()`).

This currently does not cause any problems in cbmc because expressions with side effects are usually rewritten to something like

```
lhs = get_some_value()
rhs = get_some_value()
lhs == rhs
```

before being simplified, but `simplify_expr` probably shouldn't rely on this.

**Comment by tautschnig** [comment]
I'm not entirely sure of the context of this report, but I would maintain that expressions should be free from side effects. Notably, a function call cannot guarantee such freedom, and thus is not an expression. Where has this come up?

**Comment by TGWDB** [comment]
Closing as this appears not to be followed up upon for more than three years and no example provided (`rand() == rand()` does not hold for current version of `cbmc`). If you believe this is erroneous please reopen.
