### ISSUE TITLE
Function Pointer Removal uses a redundant set

### ISSUE THREAD

**Issue by nmanthey** [diffblue/cbmc#1783]
Dear CBMC team,

I just looked into the function pointer removal code to implement a related functionality. While reading, I spotted a redundancy in the code. The marked line shows that a set "functions" and a set "done" is created, which are both filled at the same time. For checking whether the function is "done", the done set is used, while the functions set is finally returned.

I think one of the two sets can be removed, reducing run time as well as memory consumption.

https://github.com/diffblue/cbmc/blob/b0cb1ee59cb7bf46fa6dd040ed5f6c26c7699465/src/goto-programs/compute_called_functions.cpp#L83

Best,
Norbert

**Comment by martin-cs** [comment]
Thanks for this; I'll see what can be done.
