### ISSUE TITLE
Goto program and SSA validation

### ISSUE THREAD

**Issue by peterschrammel** [diffblue/cbmc#1880]
Introduce a --validate option to check goto programs and SSA for consistency.

* https://github.com/diffblue/cbmc/pull/1875#issuecomment-367995675
(to be refined)

**Comment by tautschnig** [comment]
In #918 I made some first attempts in this direction, which immediately raised problems in the internal data structures.

**Comment by martin-cs** [comment]
Sounds like a great idea!

**Comment by tautschnig** [comment]
Additional suggestion: also check the symbol table for consistency, for example that every symbol has a non-empty `mode` field.

**Comment by tautschnig** [comment]
When working on this reverting (parts of) #2110 should be considered, and the same is true for #2046.

**Comment by tautschnig** [comment]
Closing this in favour of #3152. We have since made a lot of progress in this direction, and #3152 has pointers to various in-progress PRs.
