### ISSUE TITLE
Byte-extract operations on pointer arrays can produce incorrect constraints?

### ISSUE THREAD

**Issue by smowton** [diffblue/cbmc#189]
See comments on #188; opening this to track a different possible bug involving byte-extract operations and array constraints.

**Comment by smowton** [comment]
Further observations:

- If the latest program in #188 is rewritten to use `void**` everywhere (so all array indexing uses `void**` and only elements are cast) it gives the incorrect solution `{ .x=0, .x=0 }`
- If it is rewritten instead to use `unsigned long*` it gives the *correct* answer!

**Comment by kroening** [comment]
Please check whether 7d78d58 fixes this.

**Comment by smowton** [comment]
Seems fixed.
