### ISSUE TITLE
Inconsistency for the macro __CPROVER__?

### ISSUE THREAD

**Issue by theyoucheng** [diffblue/cbmc#190]
There is some sort of inconsistency between `cbmc` and `goto-cc` when dealing with the macro `__CPROVER__`. At first, let us have a look at the following program, namely `main.c`.

```
void main()
{
  #ifdef __CPROVER__
  assert(0);
  #endif
}
```

The verification by `cbmc main.c` will return a failure because of the statement `assert(0)`; an equivalent run is that

```
goto-cc main.c -D__CPROVER__ -o main.goto && cbmc main.goto
```

However, if we do not explicitly specify `-D__CPROVER__`, that is, we use the following call

```
goto-cc main.c -o main.goto && cbmc main.goto

```

then, the `assert(0)` will not be detected.

An explanation for such an inconsistency can be that `goto-cc` tries to keep the default option of `gcc`. Still, does it make sense to trigger the `-D__CPROVER__` by default for `goto-cc`?

**Comment by tautschnig** [comment]
Hi,

This is the intended behaviour, i.e., goto-cc behaves like GCC by default. Thus I'd view your request as a documentation bug rather than an implementation issue.

Best,
Michael

**Comment by tautschnig** [comment]
Hi,

This is the intended behaviour, i.e., goto-cc behaves like GCC by default. Thus I'd view your request as a documentation bug rather than an implementation issue.

Best,
Michael

**Comment by theyoucheng** [comment]
Thanks Michael. I agree with you and that makes sense.

Best,
Youcheng

**Comment by martin-cs** [comment]
On Tue, 2016-08-02 at 03:02 -0700, Youcheng Sun wrote:
> Thanks Michael. I agree with you and that makes sense.

Youcheng : please could you prepare a patch to the manual, probably the
CPROVER API Reference part is best, that explains __CPROVER__ and when
it is defined.

Cheers,
 - Martin

**Comment by theyoucheng** [comment]
> Youcheng : please could you prepare a patch to the manual, probably the
CPROVER API Reference part is best, that explains __CPROVER__ and when
it is defined.


Sure.

Best,
Youcheng
