### ISSUE TITLE
Can't run cbmc on a very basic C example

### ISSUE THREAD

**Issue by touisteur** [diffblue/cbmc#1921]
Hi,

newbie question, I'm sure I'm doing something wrong.

I have downloaded the 5.8 source archive (https://github.com/diffblue/cbmc/archive/cbmc-5.8.tar.gz), launched "make" (no error during the build process), then tried to launch cbmc on a (very ?) simple C example :

```
// from "A Survey of Symbolic Execution Techniques", Figure 1
#include <assert.h>
void foobar(int a, int b) {
   int x = 1, y = 0;
   if (a != 0) {
       y = 3+x;
       if (b == 0)
          x = 2*(a+b);
   }
   assert(x-y != 0);
}

int main(int argc, char** argv) {
   foobar(/*a*/ 1, /*b*/ 0);
}
```

When just launch : 
`$ src/cbmc/cbmc example/example.c `
I get : 
```
CBMC version 5.8 64-bit x86_64 linux
Parsing example/example.c
file <command-line> line 0: <command-line>:0:0: warning: "__STDC_VERSION__" redefined
<built-in>: note: this is the location of the previous definition
file gcc_builtin_headers_ia32.h line 9 function __gcc_v8qi: syntax error before `__builtin_ia32_paddb'
PARSING ERROR
```

Any idea on what I'm doing wrong ? I thought at first it was all the assert stuff, and tried to comment the include & call to assert, but it didn't change anything. Also tried the --gcc option (just in case) to no avail. I'm on linux x86_64.

Thanks a lot in advance for any help.
Please let me know if this question should be on another medium (mailing-list, chatroom...).
Regards

**Comment by tautschnig** [comment]
Thank you very much for your feedback! May I ask you whether the same problem arises with the current development head? That would be https://github.com/diffblue/cbmc/archive/develop.zip.

Thanks a lot!

**Comment by touisteur** [comment]
Hi Michael,

thanks for quick (flash !) feedback.

I just (as fast as I could) finished downloading/building the tip of the develop branch, and it is indeed looking far better:

`$ src/cbmc/cbmc example/example.c`

gives me:

```
CBMC version 5.8 64-bit x86_64 linux
Parsing example/example.c
file <command-line> line 0: <command-line>:0:0: warning: "__STDC_VERSION__" redefined
<built-in>: note: this is the location of the previous definition
Converting
Type-checking example
Generating GOTO Program
Adding CPROVER library (x86_64)
Removal of function pointers and virtual functions
Generic Property Instrumentation
Running with 8 object bits, 56 offset bits (default)
Starting Bounded Model Checking
size of program expression: 52 steps
simple slicing removed 0 assignments
Generated 1 VCC(s), 0 remaining after simplification
VERIFICATION SUCCESSFUL
```

I even went further and did: 
`src/cbmc/cbmc example/example.c --function foobar`

(to start directly in foobar and check that yes, the assertion /could/ happen): 

```
CBMC version 5.8 64-bit x86_64 linux
Parsing example/example.c
file <command-line> line 0: <command-line>:0:0: warning: "__STDC_VERSION__" redefined
<built-in>: note: this is the location of the previous definition
Converting
Type-checking example
Generating GOTO Program
Adding CPROVER library (x86_64)
Removal of function pointers and virtual functions
Generic Property Instrumentation
Running with 8 object bits, 56 offset bits (default)
Starting Bounded Model Checking
size of program expression: 51 steps
simple slicing removed 3 assignments
Generated 1 VCC(s), 1 remaining after simplification
Passing problem to propositional reduction
converting SSA
Running propositional reduction
Post-processing
Solving with MiniSAT 2.2.1 with simplifier
581 variables, 1450 clauses
SAT checker: instance is SATISFIABLE
Runtime decision procedure: 0.00301742s

** Results:
[foobar.assertion.1] assertion x-y != 0: FAILURE


** 1 of 1 failed (1 iteration)
VERIFICATION FAILED
```

Now I can start playing around to find out how to generate counter examples, etc.

Thanks for the great help.
BR
