### ISSUE TITLE
Expressions in array sizes that are not statically evaluated cause problems in linking

### ISSUE THREAD

**Issue by martin-cs** [diffblue/cbmc#196]
@kroening @tautschnig 

Given the following program (inline because github can't attach actual code to bug reports):

```
#include <assert.h>

int a[(int)(10./1.)];
int b[(int)2] = { 10, 20 };
int c[(int)(10./1.)] = { 10, 20 };
int d[(int)(10/1)] = { 10, 20 };

int main (void) {
  if (a[0]) {
    assert(b[1] + c[2] > 20);
  }

  return 1;
}

extern int g_array[];
int array[(int)(10./1)];

int array2[(int)(10./1)];
```

We get the following error (with added pretty()) form the zero initialisation in the linker:

cbmc --show-vcc examples.c
CBMC version 5.4 64-bit x86_64 linux
Parsing examples.c
Converting
Type-checking examples
file examples.c line 4: symbol
  * type: signedbv
      * width: 64
      * #constant: 1
      * #c_type: signed_long_int
  * identifier: a$array_size0
failed to zero-initialize array of non-fixed size `a$array_size0'
CONVERSION ERROR

What seems to be happening is that somewhere in the front-end `(int)(10./1.)` is not being  constant folded, thus it is replaced with `a$array_size0` leading to problems in the linker.

As best I can work out, this is not valid C90 and may not be valid in later versions and is potentially tricky as there are all of the usual issues about evaluating floating-point numbers at compile time.  However, this is a "pain point" for a major customer so it would be nice if we could do something.

**Comment by kroening** [comment]
Please check whether 8be4c7a fixes this. The rounding mode to use is obviously tricky, and right now simply hard-wired to RNE.

**Comment by martin-cs** [comment]
On Thu, 2016-08-11 at 08:43 -0700, Daniel Kroening wrote:
> Please check whether 8be4c7a fixes this. The rounding mode to use is obviously tricky, and right now simply hard-wired to RNE.


Fix works; thank you.

I had a look at ISO-9899:1999 to see if we are doing the right thing.
Just for the sake of ... if anyone ever reports a bug in this ... to
improve the comments ...


If this valid C?

<quote>
6.2.5.20  Array types are characterized by their element type and by the
number of elements in the array.

6.7.5.2.1 In addition to optional type qualifiers and the keyword
static, the [ and ] may delimit an expression or *. If they delimit an
expression (which specifies the size of an array), the expression shall
have an integer type. If the expression is a constant expression, it
shall have a value greater than zero.

6.7.5.2.4 If the size is an integer constant expression and the element
type has a known constant size, the array type is not a variable length
array type.

6.6.6 An integer constant expression96) shall have integer type and
shall only have operands that are integer constants, enumeration
constants, character constants, sizeof expressions whose results are
integer constants, and floating constants that are the immediate
operands of casts. Cast operators in an integer constant expression
shall only convert arithmetic types to integer types, except as part of
an operand to the sizeof operator.
</quote>

So; no, it isn't C, but it's a reasonable extension.


How / when should it be evaluated?

<quote>
6.6.5 An expression that evaluates to a constant is required in several
contexts. If a floating expression is evaluated in the translation
environment, the arithmetic precision and range shall be at least as
great as if the expression were being evaluated in the execution
environment.

F.7.4 Constant expressions
1 An arithmetic constant expression of floating type, other than one in
an initializer for an object that has static storage duration, is
evaluated (as if) during execution; thus, it is affected by any
operative floating-point control modes and raises floating-point
exceptions as required by IEC 60559 (provided the state for the
FENV_ACCESS pragma is on).

F.7.2 Translation
1 During translation the IEC 60559 default modes are in effect:
  * The rounding direction mode is rounding to nearest.
  * The rounding precision mode (if supported) is set so that results
are not shortened.
  * Trapping or stopping (if supported) is disabled on all
floating-point exceptions.
</quote>

I say we:

*. Allow any constant expression with integer type (slightly more
general than an 'integer constant expression') to be used for array
length.

*. Evaluate the float parts of these at translation time as initialisers
of static variables are.

In which case the code is right.  Patch to the comments and docs
attached.

Cheers,
 - Martin
