### ISSUE TITLE
auto variable in loop reported as dead object 

### ISSUE THREAD

**Issue by bg1729** [diffblue/cbmc#200]
Hi

I'm seeing behaviour which I can't explain relating to pointers to local variables within loops. Specifically, for iterations of a loop after the first, a pointer to an in-scope automatic variable defined inside the loop body appears to be considered dead by CBMC.

I'm not sure if this is my fault, maybe I'm missing a command line option? Despite searching and reading I've been unable to work out why this is occurring so I've included an example which elicits this behaviour below.

I've tried CMBC from the cprover website and the Ubuntu / Debian repositories and experience this behaviour with both releases. 

Any help with this would be much appreciated. Please accept my apologies for filing a bug report if this is not an issue.

```
#include <string.h>
#define NUM_LOOPS 2 

void foo(void)
{
    char data[4];
    for (int i=0; i<NUM_LOOPS; i++){
        char data2[sizeof(data)];
        memcpy(data2, data, sizeof(data2));
    }   
} 
```

```
../cbmc bar.c --function foo --pointer-check
 (...)
Violated property:
  file bar.c line 9 function foo
  dereference failure: dead object in ((char *)dst)[(signed long int)i]
  !(POINTER_OBJECT(dst) == POINTER_OBJECT(__CPROVER_dead_object))
```

**Comment by bg1729** [comment]
Hi 

I've noticed something else which seems odd; assertions on static or global variables seem to be ignored when preceded by an assumption. This does not appear to happen when that variable is defined on the stack. 

I've condensed this down to the example code below, which I believe should fail verification irrespective of whether "BARLOCAL" and/or "ASSUME" are defined. However, it passes verification with one configuration of these two preprocessor guards.

I'll file a separate issue for this if you wish?

BR
Gareth

```
#include <assert.h>
#ifndef BARLOCAL
static int bar;
#endif

void foo(void)
{
#ifdef BARLOCAL
    int bar;
#endif
#ifdef ASSUME 
    /* bar must be between 1 and 9 */
    __CPROVER_assume((bar > 0) && (bar < 10));
#endif
    /* assert that bar is greater than 1000 */
    assert(bar > 1000);
}
```

```
gareth@snares:~$ cbmc test.c --function foo | tail -n 1
file <command-line> line 0: <command-line>:0:0: warning: "__STDC_VERSION__" redefined
file <command-line> line 0: <built-in>: note: this is the location of the previous definition
VERIFICATION FAILED
gareth@snares:~$ cbmc test.c --function foo -DBARLOCAL | tail -n 1
file <command-line> line 0: <command-line>:0:0: warning: "__STDC_VERSION__" redefined
file <command-line> line 0: <built-in>: note: this is the location of the previous definition
VERIFICATION FAILED
gareth@snares:~$ cbmc test.c --function foo -DBARLOCAL -DASSUME | tail -n 1
file <command-line> line 0: <command-line>:0:0: warning: "__STDC_VERSION__" redefined
file <command-line> line 0: <built-in>: note: this is the location of the previous definition
VERIFICATION FAILED
gareth@snares:~$ cbmc test.c --function foo -DASSUME | tail -n 1
file <command-line> line 0: <command-line>:0:0: warning: "__STDC_VERSION__" redefined
file <command-line> line 0: <built-in>: note: this is the location of the previous definition
VERIFICATION SUCCESSFUL <-- I don't think this should pass
```

**Comment by peterschrammel** [comment]
Regarding your last comment: 
Note that static and global variables are initialised to 0 in C. Hence, your assumption blocks all executions and makes the assertion unreachable (=pass).

**Comment by bg1729** [comment]
Thanks Peter, I'm somewhat embarrassed I didn't think of that! I should probably wait until a more lucid time of the day and week before commenting again... :)

Just a thought - it would be nice if assumptions which cannot possibly be met resulted in an error or warning.

BR 

Gareth

**Comment by martin-cs** [comment]
On Fri, 2016-08-19 at 16:46 -0700, bg1729 wrote:
> Thanks Peter, I'm somewhat embarrassed I didn't think of that! I should probably wait until a more lucid time of the day and week before commenting again... :)

Don't worry; we'd rather questions we can answer easily than people not
getting in touch :-)

> Just a thought - it would be nice if assumptions which cannot possibly be met resulted in an error or warning.

We're working on our abstract interpreter so it can highlight
unreachable instructions.  In the mean time the reachability slicer will
sort-of do this.

Cheers,
 - Martin

**Comment by thomasspriggs** [comment]
The issue reported in this issue seems to be fixed when I attempt to reproduce this using the current version of CBMC in the `develop` branch. Therefore I am going to close out this ticket. The output from cbmc when attempting to reproduce is below for posterity.
<details>
<summary>Click to expand cbmc output</summary>

```
$ cbmc example.c --function foo --pointer-check
CBMC version 5.25.0 (cbmc-5.25.0-dirty) 64-bit x86_64 linux
Parsing example.c
Converting
Type-checking example
Generating GOTO Program
Adding CPROVER library (x86_64)
Removal of function pointers and virtual functions
Generic Property Instrumentation
Running with 8 object bits, 56 offset bits (default)
Starting Bounded Model Checking
Unwinding loop foo.0 iteration 1 file example.c line 7 function foo thread 0
Unwinding loop foo.0 iteration 2 file example.c line 7 function foo thread 0
Runtime Symex: 0.00527044s
size of program expression: 117 steps
simple slicing removed 37 assignments
Generated 18 VCC(s), 2 remaining after simplification
Runtime Postprocess Equation: 2.1303e-05s
Passing problem to propositional reduction
converting SSA
Runtime Convert SSA: 0.000414294s
Running propositional reduction
Post-processing
Runtime Post-process: 1.8545e-05s
Solving with MiniSAT 2.2.1 with simplifier
411 variables, 130 clauses
SAT checker inconsistent: instance is UNSATISFIABLE
Runtime Solver: 3.9504e-05s
Runtime decision procedure: 0.000493857s

** Results:
<builtin-library-memcpy> function memcpy
[memcpy.pointer.1] line 33 same object violation in (const char *)(const void *)data >= (const char *)(void *)data2 + (signed long int)sizeof(char [4l]) /*4ul*/ : SUCCESS
[memcpy.pointer_arithmetic.1] line 33 pointer relation: dead object in (const char *)(const void *)data: SUCCESS
[memcpy.pointer_arithmetic.2] line 33 pointer relation: dead object in (const char *)(void *)data2 + (signed long int)sizeof(char [4l]) /*4ul*/ : SUCCESS
[memcpy.pointer.2] line 34 same object violation in (const char *)(void *)data2 >= (const char *)(const void *)data + (signed long int)sizeof(char [4l]) /*4ul*/ : SUCCESS
[memcpy.pointer_arithmetic.3] line 34 pointer relation: dead object in (const char *)(void *)data2: SUCCESS
[memcpy.pointer_arithmetic.4] line 34 pointer relation: dead object in (const char *)(const void *)data + (signed long int)sizeof(char [4l]) /*4ul*/ : SUCCESS

example.c function foo
[foo.precondition_instance.1] line 9 memcpy src/dst overlap: SUCCESS
[foo.precondition_instance.2] line 9 memcpy source region readable: SUCCESS
[foo.precondition_instance.3] line 9 memcpy destination region writeable: SUCCESS

** 0 of 9 failed (1 iterations)
VERIFICATION SUCCESSFUL
```

</details>
