### ISSUE TITLE
many versions of out of date documentation exist

### ISSUE THREAD

**Issue by polgreen** [diffblue/cbmc#2012]
The documentation found here is fine
http://cprover.diffblue.com/cbmc-user-manual.html#man_install-cbmc

But the documentation found here has broken links, including the one for the compilation instructions
http://www.cprover.org/cprover-manual/installation-cbmc.html
I got to that documentation by following the link from the github readme to the cprover wiki, and then clicking on CBMC tutorial, which I don't think is an unreasonable thing to do.
I could also have got there by following the "more information" link on the github readme to the cbmc homepage.

The documentation found by googling "CBMC manual" is out of date:
https://www.cprover.org/cbmc/doc/manual.pdf

**Comment by polgreen** [comment]
This is still a pretty irritating issue. 

- Please could the out of date documentation be removed (namely https://www.cprover.org/cbmc/doc/manual.pdf).
- Please could the link "to compile the source code, follow these instructions" at the bottom of this page be updated: http://www.cprover.org/cprover-manual/installation-cbmc.html

**Comment by martin-cs** [comment]
As far as I know only @kroening has the access rights to fix this.  Sorry :-\

**Comment by peterschrammel** [comment]
The documentation on http://cprover.diffblue.com is entirely auto-generated from files in the CBMC repository. Fixing issues there is a matter of creating a PR; it will then be automatically updated by travis on merge.

The other documentation on cprover.org requires @kroening to perform a clean-up.

**Comment by polgreen** [comment]
The documentation on http://cprover.diffblue.com is the only one that's up to date!

**Comment by polgreen** [comment]
So, I'm going through and closing issues I've filed that have been resolved. Is there anyone that can remove the out of date documentation?

It's here:
https://www.cprover.org/cbmc/doc/manual.pdf
http://www.cprover.org/cprover-manual/installation-cbmc.html

**Comment by martin-cs** [comment]
As before, I think only @kroening can help you here.

**Comment by TGWDB** [comment]
Closing as (most?) are now fixed.
