### ISSUE TITLE
Fully model __builtin_bswap to re-enable Linux kernel builds

### ISSUE THREAD

**Issue by tautschnig** [diffblue/cbmc#202]
It would be great if the simplifier were able to deal with bswap of constants, similar to how popcount is handled. This is nowadays used in the linux kernel:

http://lxr.free-electrons.com/source/include/linux/sctp.h#L169

Best,
Michael

**Comment by kroening** [comment]
Coming!

**Comment by kroening** [comment]
Please look at 69d7911.

**Comment by tautschnig** [comment]
Apologies for the delay! Indeed, this is fixed as of 69d7911. Thank you!
