### ISSUE TITLE
An unexpected verification result.

### ISSUE THREAD

**Issue by muchang** [diffblue/cbmc#2057]
```
void main(){
  int arg[5];
  int i = 0;
  while (arg[i] != 0) {
    i = i + 1;
  }
  if (arg[i] != 0) {
    assert(0);
  }
}
```
The `assert(0);` is infeasiable in this case, while the CBMC gives FALSE verification result which means `assert(0);` is feasible.  I ran CBMC-5.6 with the command "./cbmc ~/simple_replace_172.c --unwind 6 --depth 350 -function main --trace".  I would like to know if I ran CBMC with the wrong command line arguments so that I got the unexpected verification result?

**Comment by mgudemann** [comment]
@muchang, with `--unwind 6` you effectively force the `while` loop to exit.

You can see with `--unwinding-assertions` that this cannot be proven from the program alone though. When you assume (via `__CPROVER_assume`) at least one element of the array actually being `0`, the 'assert false` cannot be reached any more.

**Comment by muchang** [comment]
Thank you so much for your reply. It is very helpful to me.
Actually, CBMC works well on a simpler case, for example:
```
 void main(){
   int a = 0;
   while(a <= 0) {a--;}
   if(a <= 0)
       assert(0);
 }
```
In this case, CBMC-5.6 with the command `./cbmc ~/simple_replace_172.c --unwind 6 --depth 350 -function main --trace` can give the TRUE verification result which means the `assert(0)` cannot be reached. However, I think CBMC should give the same verification results on this one and the prior one.  Could you tell me why the difference occurs?

**Comment by tautschnig** [comment]
The problem of your example is that it will yield an out-of-bounds memory access. Each such access yields a non-deterministic result, which means that reading `arg[5]` two times (in the condition of the `while` as well as in the condition of the `if`) does not mean the result will be the same each time.

**Comment by muchang** [comment]
Thank you so much for your clear explanation. 
It is reasonable that the result won't be the same each time.
So it is the feature of CBMC rather than an issue, right?

**Comment by tautschnig** [comment]
It's a feature, but arguably the user interface may not be sufficiently clear here.

**Comment by muchang** [comment]
I got it, thanks a lot!

**Comment by muchang** [comment]
I met another unexpected verification result case.
Consider about this piece of code:
```
int main ()
{
    char c;
    for (c = 1; c != 0; c++) 
    { /* do nothing */ } 
    if (c == 0) 
       assert (0);
    return 0;  
}
```
The program will throw out an Assertion failed when compiled by gcc or clang, but CBMC gives the TRUE verification result on this case.

What should I do if I want to use CBMC to find the bug?

**Comment by tautschnig** [comment]
Would you mind posting the exact command line you are using, and possibly also the platform you are running on? I'm running the following on Ubuntu 14.04:
```
$ cbmc bug.c
[...]
Unwinding loop main.0 iteration 254 file bug.c line 4 function main thread 0
Unwinding loop main.0 iteration 255 file bug.c line 4 function main thread 0
size of program expression: 800 steps
simple slicing removed 5 assignments
Generated 1 VCC(s), 1 remaining after simplification
Passing problem to propositional reduction
converting SSA
Running propositional reduction
Post-processing
Solving with MiniSAT 2.2.1 with simplifier
16 variables, 11 clauses
SAT checker: instance is SATISFIABLE
Runtime decision procedure: 0.00319181s

** Results:
[main.assertion.1] assertion 0: FAILURE


** 1 of 1 failed (1 iteration)
VERIFICATION FAILED
```
as it should be?!

**Comment by muchang** [comment]
Yes, I just tried your command line and got the excepted result.
I guess I got the unexpected result before because I used the unwind configuration.
Thanks for your reply! It's solved.

**Comment by muchang** [comment]
Hi, another unexpected case is coming:
```
#include<string.h>
int main ()
{
  char a1[] = {1, 2, 3, 4};
  char a2[] = {1, 2, 3, 4};
  int res = memcmp (a1, a2, 5);
  if(res != 0){
    assert(0);
  }
  return res;
}
```
For this case, the `assert(0)` is reachable when it is compiled by gcc.
But CBMC gives the VERIFICATION SUCCESSFUL result which means the `assert(0)` is unreachable for the case.
The command is `cbmc file.c`. On MacOS 10.13.

**Comment by tautschnig** [comment]
As far as I can tell your above example has undefined behaviour (the value `5` take the comparison out of bounds), and thus any result is technically ok. You really want to use `--bounds-check` with such a code.

**Comment by tautschnig** [comment]
Resolving as `--bounds-check` should be used.
