### ISSUE TITLE
Memory consumption when modelchecking Java programs

### ISSUE THREAD

**Issue by vladrich** [diffblue/cbmc#211]
I appreciate the latest fixes. I no longer get incorrect results, but I do run out of memory now. CBMC gets stuck in "post-processing" and after ~17 minutes crashes with OOM, having consumed 128G of memory. Would anyone be willing to look at this? I would provide the source. The memory hunger is in line with my experience with checking other Java projects. Is it possible to say which Java program features have the highest impact on memory consumption?

Thanks!

**Comment by kroening** [comment]
The obvious candidate for this are large arrays.

**Comment by martin-cs** [comment]
On Tue, 2016-08-23 at 07:57 -0700, Daniel Kroening wrote:
> The obvious candidate for this are large arrays.

vladrich : We've had "improve our handling of large arrays" on the todo
list for a while but it's not currently the top priority.  That said
we've done consultancy work on very similar problems for a number of
companies; specifically about improving performance and reducing memory
consumption for their specific use case.  One we got about 50-60% memory
reduction and, I don't recall exactly but I think it was about an order
of magnitude in performance.  Another was about 75% reduction in memory
and similar in performance.

When we get on to improving the array performance we'll happily look at
it.  If you want that to be sooner rather than later we can probably
sort something out.

Cheers,
 - Martin

**Comment by vladrich** [comment]
Many thanks for your remarks, Martin. I feel I should add more context.

I understand perfectly that it is always possible to come up with a
benchmark that will choke the verifier. Yet, I was surprised by the
following.

I've been looking at various PRNGs and the size of the CNF encoding
their behavior in a certain scenario was always under 100M for the five
of them written in C. For the two written in Java, one is 989M, and for
the other no CNF can be generated, even on a machine with 128G RAM
(first time I've experienced something like that).

At the moment, I have no idea what causes such a disparity. Is it

a) the way one typically programs in Java is sufficiently different to
cause the performance gap (from the high-level design perspective,
there is nothing outstanding with the Java PRNGs)

or

b) the encoding of Java programs in CBMC is less efficient than of ones
in C. If it is, and if it is not just a small bug that is easy to fix,
then I am perfectly fine with it.

Or is it something else?

Furthermore, I have no idea as to how to narrow down the issue. How can
I test, for instance, the large array hypothesis? (By the way: is it the
total size of the arrays, the number of reads/writes, the aliasing
situation, the number of allocations, all of the above?) The only metric
that CBMC currently exposes is the number of symbolic execution steps.
This number does not correlate strongly with performance in my
benchmarks. Is it possible to expose other metrics to understand the
issue better? That could benefit other users too in making the tool
behavior more predictable.

Anyway, this issue does not create serious problems for me - we already
got more than enough mileage out of the tool. :) It's more the thrill of
the mystery behind it. 

Thanks!

**Comment by martin-cs** [comment]
On Sat, 2016-08-27 at 09:23 -0700, vladrich wrote:
> Many thanks for your remarks, Martin. I feel I should add more context.

(Sorry; I've just connected the username to the person.  Good to hear
from you again.)

> I understand perfectly that it is always possible to come up with a
> benchmark that will choke the verifier. Yet, I was surprised by the
> following.
> 
> I've been looking at various PRNGs and the size of the CNF encoding
> their behavior in a certain scenario was always under 100M for the five
> of them written in C. For the two written in Java, one is 989M, and for
> the other no CNF can be generated, even on a machine with 128G RAM
> (first time I've experienced something like that).
> 
> At the moment, I have no idea what causes such a disparity. Is it
> 
> a) the way one typically programs in Java is sufficiently different to
> cause the performance gap (from the high-level design perspective,
> there is nothing outstanding with the Java PRNGs)
> 
> or
> 
> b) the encoding of Java programs in CBMC is less efficient than of ones
> in C. If it is, and if it is not just a small bug that is easy to fix,
> then I am perfectly fine with it.
> 
> Or is it something else?

My suspicion is that it is more likely to be b). than a).   Somewhere in
the conversion (via JVM bytecode) I think the front-end if picking up
some extra overhead that is not simplified out.

One quick check; are these char arrays?  On most architectures C's char
is 8 bit, while Java's char is 16 bit.

> Furthermore, I have no idea as to how to narrow down the issue. How can
> I test, for instance, the large array hypothesis?
Instantiating the array axioms is pretty much all that happens in the
post-processing step so it is likely to be this.

>  (By the way: is it the
> total size of the arrays,
Big factor if allocated locally.  To generate run-able test-cases we
have to fully instantiate these.

>  the number of reads/writes,
Fixed position reads are reasonably cheap, variable position ones ...
can be more expensive.  Writes can add to the search space but shouldn't
be too costly in terms of variables and clauses.

>  the aliasing
> situation,
Increases the search space but relatively few clauses.

>  the number of allocations,
Also a linear factor

>  all of the above?
Plus more :-)  Size of entry and index types, which of them can be
simplified, etc.

> ) The only metric
> that CBMC currently exposes is the number of symbolic execution steps.
> This number does not correlate strongly with performance in my
> benchmarks.
For the same program I would expect that memory used would increase
monotonically with symex steps.  Run time ... may increase with them
but ... it's not a certain thing.  Between different programs or
different versions of the same program I wouldn't expect any
correlation.

>  Is it possible to expose other metrics to understand the
> issue better?
We used to give variables and clauses for the SAT solver; I think
verbose may still do that.

>  That could benefit other users too in making the tool
> behavior more predictable.
I know what you mean but ... there are currently no known, useful
metrics for predicting SAT solver performance.  (There are also obvious
theoretical limits for how good any predictor can be that is faster than
just solving the problem).  I'm working on something but ... it will
take time.

> Anyway, this issue does not create serious problems for me - we already
> got more than enough mileage out of the tool. :) It's more the thrill of
> the mystery behind it. 
If you want to chase this further then the next steps is to come up with
the smallest possible test case (in both Java and C) and comparing the
output of --show-goto-functions and --show-vcc.  After that it's going
to require getting into the internals.

Cheers,
 - Martin
