### ISSUE TITLE
regression/ansi-c/Universal_characters1 fails

### ISSUE THREAD

**Issue by tautschnig** [diffblue/cbmc#216]
... since a587a303c6f5, where it has been switched from KNOWNBUG to CORE.

**Comment by kroening** [comment]
This may be a clang vs. gcc thing.

**Comment by tautschnig** [comment]
Looking at https://travis-ci.org/diffblue/cbmc, it seems to be a MacOS vs Linux issue: both clang and gcc are ok for MacOS, and both of them fail for Linux.

**Comment by kroening** [comment]
Fixed with 8f47419
