### ISSUE TITLE
Human-targetted output should abbreviate large arrays

### ISSUE THREAD

**Issue by tautschnig** [diffblue/cbmc#2183]
Creating this as an issue as the entire pretty-printing appears to be in flux: `expr2ct` will presently print all elements of an array, even when all of them are them same (e.g., `0`) and there are millions of them. The result is valid C, but hardly human-readable. Instead printing should be done like, e.g., `gdb` does, where expressions are abbreviated after a certain number of characters by default. The output might say: `{ 0, 0, 0, ... (1000 more elements) }` or `{ 0, 0, 0, ... (repeats 1000 times) }`.

**Comment by martin-cs** [comment]
+1 does want but I note that this may make parsing of these things harder.  Should we say if people want to parse things then they should use the JSON or XML formats?

**Comment by kroening** [comment]
Yes, we've always recommended that people use JSON/XML if they want to parse (but I know of at least one commercial user who decided to parse the text output).

**Comment by TGWDB** [comment]
Closing this as a feature request that seems not to be of interest at the moment (also I suspect there are still users who parse the text output).
