### ISSUE TITLE
Is --cover path working?

### ISSUE THREAD

**Issue by martin-cs** [diffblue/cbmc#223]
From the code it looks like it is not finished.  Is this the case as I might have found users for it?

**Comment by kroening** [comment]
No, not finished.

**Comment by martin-cs** [comment]
On Thu, 2016-09-08 at 04:56 -0700, Daniel Kroening wrote:
> No, not finished.

OK; thanks.  When it is, we will have people who want to try it.

Cheers,
 - Martin

**Comment by TGWDB** [comment]
Closing this as there is no progress or update in many years. Please reopen if you believe this is erroneous.
