### ISSUE TITLE
Better function pointer removal

### ISSUE THREAD

**Issue by martin-cs** [diffblue/cbmc#224]
A major industrial partner has a problem with a code-base that is running out of memory during function pointer removal.  It makes heavy of dispatch tables and so has lots of functions with identical signatures.  Unfortunately this is all of the information I have so far, so I guess this is more a place-holder / if other people were thinking about this (for vtables perhaps).

**Comment by smowton** [comment]
I recently improved remove-virtuals to generate a call per callee, not per type in the hierarchy, and to only generate branches per type that is the child of an type that overrides, allowing the common huge cases (`java.lang.Object.hashCode` for example) to be very cheap. Here's the commit, currently untested [https://github.com/smowton/cbmc/commit/d3e55cec8e53d2377e0fa52601b806ded2bb8132]

I'm supposed to be putting a pull request together for improvements to remove-virtuals / remove-instanceof, so if I can convince myself I haven't done anything too silly there I'll include it with that.

**Comment by martin-cs** [comment]
On Tue, 2016-11-01 at 07:58 -0700, Chris Smowton wrote:
> I recently improved remove-virtuals to generate a call per callee, not per type in the hierarchy, and to only generate branches per type that is the child of an type that overrides, allowing the common huge cases (`java.lang.Object.hashCode` for example) to be very cheap. Here's the commit, currently untested [https://github.com/smowton/cbmc/commit/d3e55cec8e53d2377e0fa52601b806ded2bb8132]
> 
> I'm supposed to be putting a pull request together for improvements to remove-virtuals / remove-instanceof, so if I can convince myself I haven't done anything too silly there I'll include it with that.
> 

Brilliant!  Thank you for doing this and keep me posted.  When it is in
a state that you think it will work, I'll ask them to test it out on
their problematic code base.

Cheers,
 - Martin

**Comment by smowton** [comment]
PR here: https://github.com/diffblue/cbmc/pull/404

**Comment by thomasspriggs** [comment]
Given that Chris' PR is merged I am going to close this out. If the industrial partner is still having problems with running out of memory during function pointer removal then feel free to reopen.
