### ISSUE TITLE
Remove `experimental support for Java bytecode` from CBMC website

### ISSUE THREAD

**Issue by mgudemann** [diffblue/cbmc#2285]
The [CBMC](http://www.cprover.org/cbmc/) webpage states that `We have recently added experimental support for Java Bytecode.` This should be removed or replaced with a link to [JBMC](http://www.cprover.org/jbmc/).

**Comment by tautschnig** [comment]
This wording has since been changed. It now says "A variant of CBMC that analyses Java bytecode is available as JBMC."
