### ISSUE TITLE
Crash when using core models and comparing two inputs

### ISSUE THREAD

**Issue by thk123** [diffblue/cbmc#2307]
Given the following Java:

```java
class Test2Class {
  static void test(Object a, Object b) {
    assert(a == b);
  }
}
```

When running jbmc with the core models: `jbmc Test2Class.class --function Test2Class.test --classpath ../../../src/java_bytecode/library/core-models.jar:.`

The following error is generated:

```
struct: component type does not match: signedbv
  * width: 32
  * #c_type: signed_int vs. 
terminate called after throwing an instance of 'int'
Aborted (core dumped)
```

The component that is specifically the wrong type is `monitorCount` from `java.lang.Object` model.

**Comment by Degiorgio** [comment]
The following PR when merged should fix this: https://github.com/diffblue/cbmc/pull/2280
