### ISSUE TITLE
Fix temporarily invalid instructions in goto convert 

### ISSUE THREAD

**Issue by peterschrammel** [diffblue/cbmc#2357]
See https://github.com/diffblue/cbmc/pull/2356 for the context

A couple of initial suggestions to fix this:
1. Use an explicit dummy target to be passed to make_goto()
    - very simple
    - helps avoiding wrongly incomplete initialisations
    - allows checking that a converted goto program does not have incompletely initialised instructions
2. Refactor goto_convert to perform single-step initialisation of goto instructions
    - quite some work
3. Keep NO_INSTRUCTION_TYPE and move if-then-else optimisation into a goto pass
    - doable, but doesn't feel right
    - makes invalid instructions explicit and the absence of incompletely initialised instructions can be easily checked
4. ?

In any case also https://github.com/diffblue/cbmc/blob/develop/src/goto-programs/goto_program.h#L495 should be removed.

**Comment by tautschnig** [comment]
Fixed via #2361.
