### ISSUE TITLE
Some goto-cc regression tests fail when native compiler is clang-6.0

### ISSUE THREAD

**Issue by smowton** [diffblue/cbmc#2370]
Failing tests:

`regression/ansi-c/MMX2`:

```
/usr/lib/llvm-6.0/lib/clang/6.0.0/include/emmintrin.h: In function '_mm_avg_epu8':
/usr/lib/llvm-6.0/lib/clang/6.0.0/include/emmintrin.h:2280:1: error: operator `+' not defined for types `unsigned short int __attribute__((vector_size (16l*sizeof(unsigned short int))))' and `signed int'
```

`regression/ansi-c/gcc_builtins4`: `STATIC_ASSERT(__builtin_classify_type((_Bool)0)==4)` fails. Someone expected Clang would classify `_Bool` as a logical rather than an integer type, which may be true for some Clangs, but evidently not 6.0, at least not 6.0 + glibc-2.27 (if libc is even responsible for defining `_Bool`). Need to check which compilers classify it which way.

`regression/cbmc/ts18661_typedefs`: conflicting type modifiers when trying to overwrite a builtin type (`_Float128`) with a typedef. This is expected, as cbmc doesn't use `gcc_versiont` yet to check what the native compiler defines -- when it does, it should mimic Clang's support or otherwise for `_Float128` et al.

**Comment by smowton** [comment]
I also repeated these tests with clang-3.9, the oldest Clang readily available to me, and found the MMX2 test does not fail, but the gcc_builtins4 and ts18661 tests fail in the same way.

**Comment by kroening** [comment]
BTW, is this now fixed?

**Comment by smowton** [comment]
No, all three failures are as described still
