### ISSUE TITLE
Error simplify_expr_boolean.cpp:154:29: error: no matching function for call to ‘std::vector<exprt>::erase(std::vector<exprt>::const_iterator&)’  it=operands.erase(it);

### ISSUE THREAD

**Issue by tr4nc3** [diffblue/cbmc#2378]
Seems like I am getting a compilation error with the following GCC
gcc version 4.8.5 20150623 (Red Hat 4.8.5-28) (GCC) .

```
simplify_expr_boolean.cpp:154:29: error: no matching function for call to ‘std::vector<exprt>::erase(std::vector<exprt>::const_iterator&)’
         it=operands.erase(it);
```
                             ^
Any ideas?

**Comment by mgudemann** [comment]
@tr4nc3 please note that you need gcc 5.0 or higher (cf. https://github.com/diffblue/cbmc/blob/develop/COMPILING.md)

**Comment by tr4nc3** [comment]
I had to install devtoolset-7 and zlib-static libraries to fix the issue.  Thanks @mgudemann .
