### ISSUE TITLE
sat/satcheck_minisat2.cpp:53:33: error: ‘l_True’ was not declared in this scope

### ISSUE THREAD

**Issue by tr4nc3** [diffblue/cbmc#2394]
Using gcc version 7.3.1 20180303 (Red Hat 7.3.1-5) (GCC) :

```
I am getting the following compilation error.
sat/satcheck_minisat2.cpp:53:33: error: ‘l_True’ was not declared in this scope
   if(solver->model[a.var_no()]==l_True)
                                 ^~~~~~
sat/satcheck_minisat2.cpp:53:33: note: suggested alternative:
In file included from /usr/local/include/minisat/core/Solver.h:29:0,
                 from sat/satcheck_minisat2.cpp:22:
/usr/local/include/minisat/core/SolverTypes.h:128:15: note:   ‘Minisat::l_True’
   const lbool l_True ((uint8_t)0);
               ^~~~~~
```

**Comment by tr4nc3** [comment]
If I follow the suggestion mentioned i.e., changing ``l_True`` to ``Minisat::l_True`` the problem goes away.  But then the linker fails.

I think I made the initial mistake by not doing first the following: 
``make minisat2-download``

**Comment by tautschnig** [comment]
So are you still facing the problem you posted above? If you haven't done `make minisat2-download`, how did you install Minisat instead?

**Comment by tr4nc3** [comment]
I installed minisat via the yum install ... and it seemed to have worked but seems like it messes something with how cbmc expects it.  No longer a problem now - the key was to follow the instructions exactly.
