### ISSUE TITLE
Backwards goto for Java loops goes to skip

### ISSUE THREAD

**Issue by danpoe** [diffblue/cbmc#248]
For "for" and "while" loops in Java programs the generated goto program contains a backwards goto that jumps to a skip:

```
1: SKIP
   IF local1i >= (int)10 THEN GOTO 2
   local1i = local1i + (int)1;
   GOTO 1
2:
```

This is different than for C where the backwards goto would directly go to the "IF ..." statement. The Java translation can trip up loop analyses that assume that the loop condition is contained either in the loop head (for- and while-loops) or the backwards goto (do-while-loops). We might thus want to alter the translation so that it is the same as for C.

**Comment by peterschrammel** [comment]
In my opinion, you shouldn't make such assumptions.

**Comment by danpoe** [comment]
It may be unnecessarily complicated for some analyses to assume unstructured gotos. For example, the loop bounds computation looks for the loop condition in the head and the backwards goto. If it doesn't find a condition there it simply reports no bound, i.e., it is still sound. Given that most backwards gotos come from actual loops, it would add little to also handle other shapes (apart from exits via break).

In the particular case a simple solution is of course to just check if the loop head is a skip and then just take the condition from the next line. But it would still be nice if the translation were consistent between C and Java.

**Comment by martin-cs** [comment]
On Thu, 2016-10-06 at 09:37 -0700, danpoe wrote:
> It may be unnecessarily complicated for some analyses to assume unstructured gotos. For example, the loop bounds computation looks for the loop condition in the head and the backwards goto. If it doesn't find a condition there it simply reports no bound, i.e., it is still sound. Given that most backwards gotos come from actual loops, it would add little to also handle other shapes (apart from exits via break).
> 
> In the particular case a simple solution is of course to just check if the loop head is a skip and then just take the condition from the next line. But it would still be nice if the translation were consistent between C and Java.

FWIW I think I agree with Peter that we shouldn't make that assumption
but:

1. We should probably put the 'branch location' logic into some of the
loop identification utilities so that people don't have to do /
re-invent this.

2. For now, would remove_skip() give a work around for this problem?

Cheers,
 - Martin

**Comment by peterschrammel** [comment]
question answered
