### ISSUE TITLE
Make output of --dump-c --use-system-headers compilable

### ISSUE THREAD

**Issue by peterschrammel** [diffblue/cbmc#249]
In order to compile dumped C files with the original header files, we have to
- retain typedefs involving anonymous structs/unions
- prevent the output of structs/unions defined in system headers
- prevent the output of built-ins
- ...

A quick hack is here:
https://github.com/peterschrammel/cbmc/commit/ff6a7d1dd637c4f17bcb9e4a82d77e790b0d027f

More to come...

**Comment by tautschnig** [comment]
@peterschrammel Has this been fully addressed by #858?

**Comment by tautschnig** [comment]
I'm inclined to close this issue as dump-c's output appears to work fine these days. It's certainly not perfect, but #5700 shows that it does generally work. I think we need concrete examples of failures to drive further fixes.
