### ISSUE TITLE
Test behaviour of --cover in the presence of unreachable functions and assumes

### ISSUE THREAD

**Issue by peterschrammel** [diffblue/cbmc#255]
for C programs

**Comment by peterschrammel** [comment]
@kroening, what is the "problem with location coverage"?

**Comment by lucasccordeiro** [comment]
@kroening: in addition to Peter's question, which coverage criterion should we further test together --cover (location, branch, decision, condition, path, mcdc, assertion)?

**Comment by lucasccordeiro** [comment]
@peterschrammel and @kroening: I have created about 15 test cases to check the behaviour of the location coverage. I was unable to find any issue related to this feature. I have just made a pull request in the repository so that you can evaluate the test cases.

**Comment by lucasccordeiro** [comment]
@kroening and @peterschrammel: Is there something else to be done in this issue? otherwise, may I ask you to close it?

**Comment by forejtv** [comment]
This is done in https://github.com/diffblue/cbmc/pull/290 which is merged.
