### ISSUE TITLE
Minimise test suites

### ISSUE THREAD

**Issue by peterschrammel** [diffblue/cbmc#257]
PR to master
with regression tests for C

**Comment by cristina-david** [comment]
PR done in diffblue/cbmc#285. However, it only has regression tests for Java. I'll add some for C.

**Comment by cristina-david** [comment]
Added 2 regression tests for C to the pull request.

**Comment by forejtv** [comment]
This is done in https://github.com/diffblue/cbmc-testgen/pull/46
