### ISSUE TITLE
--bounds-check problem with malloc

### ISSUE THREAD

**Issue by guyio** [diffblue/cbmc#2573]
take this code for example:

#include <stdlib.h>
void main(){
int* a = malloc(4);
a[10]=1;
}

if i run cbmc with these clauses: --function main --bounds-check
it results in VERIFICATION SUCCESSFUL.

what am i doing wrong? do i need another configuration?

**Comment by peterschrammel** [comment]
You need `--pointer-check` in this case.

`--bounds-check` would work for cases such as
```
#include <stdlib.h>
void main(){
  int a[4];
  a[10]=1;
}
```

**Comment by guyio** [comment]
Thank you! I've mistakenly assumed accessing allocations with index will be checked within 'bounds-check'
