### ISSUE TITLE
problem regarding memcpy bound check

### ISSUE THREAD

**Issue by guyio** [diffblue/cbmc#2578]
Hey, consider this code:

#include <string.h>
#include <stdlib.h>
int main()
{
  char* a = malloc(10);
  char* b = malloc(10);
  memcpy(b, a, 100);
}

using the following options:
    --bounds-check --pointer-check
results in success.

what am i doing wrong? is it a known issue?

**Comment by martin-cs** [comment]
Thanks for the bug report!

On Sun, 2018-07-15 at 04:58 -0700, Guy Inbar wrote:
> Hey, consider this code:
> 
> #include <string.h>
> #include <stdlib.h>
> int main()
> {
>   char* a = malloc(10);
>   char* b = malloc(10);
>   memcpy(b, a, 100);
> }
> 
> using the following options:
>     --bounds-check --pointer-check
> results in success.
> 
> what am i doing wrong? is it a known issue? 

Which version are you using?  I've just tried the current master and
got:

$ cbmc ./bug-2578.c --bounds-check --pointer-check

CBMC version 5.9 (cbmc-5.9-318-g87c2a6891) 64-bit x86_64 linux
Parsing ./bug-2578.c
Converting
Type-checking bug-2578
Generating GOTO Program
Adding CPROVER library (x86_64)
Removal of function pointers and virtual functions
Generic Property Instrumentation
Running with 8 object bits, 56 offset bits (default)
Starting Bounded Model Checking
size of program expression: 111 steps
simple slicing removed 17 assignments
Generated 17 VCC(s), 4 remaining after simplification
Passing problem to propositional reduction
converting SSA
Running propositional reduction
Post-processing
Solving with MiniSAT 2.2.1 with simplifier
697 variables, 40 clauses
SAT checker: instance is SATISFIABLE
Solving with MiniSAT 2.2.1 with simplifier
697 variables, 2 clauses
SAT checker: instance is SATISFIABLE
Solving with MiniSAT 2.2.1 with simplifier
697 variables, 0 clauses
SAT checker inconsistent: instance is UNSATISFIABLE
Runtime decision procedure: 0.00315668s

** Results:
[main.precondition_instance.1] memcpy src/dst overlap: SUCCESS
[memcpy.pointer_dereference.1] dereference failure: pointer NULL in
*((char *)dst): SUCCESS
[memcpy.pointer_dereference.2] dereference failure: pointer invalid in
*((char *)dst): SUCCESS
[memcpy.pointer_dereference.3] dereference failure: deallocated dynamic
object in *((char *)dst): SUCCESS
[memcpy.pointer_dereference.4] dereference failure: dead object in
*((char *)dst): SUCCESS
[memcpy.pointer_dereference.5] dereference failure: pointer outside
dynamic object bounds in *((char *)dst): SUCCESS
[memcpy.pointer_dereference.6] dereference failure: pointer outside
object bounds in *((char *)dst): SUCCESS
[memcpy.pointer_dereference.7] dereference failure: pointer NULL in
*((const char *)src): SUCCESS
[memcpy.pointer_dereference.8] dereference failure: pointer invalid in
*((const char *)src): SUCCESS
[memcpy.pointer_dereference.9] dereference failure: deallocated dynamic
object in *((const char *)src): SUCCESS
[memcpy.pointer_dereference.10] dereference failure: dead object in
*((const char *)src): SUCCESS
[memcpy.pointer_dereference.11] dereference failure: pointer outside
dynamic object bounds in *((const char *)src): SUCCESS
[memcpy.pointer_dereference.12] dereference failure: pointer outside
object bounds in *((const char *)src): SUCCESS
[memcpy.pointer_dereference.13] dereference failure: pointer outside
dynamic object bounds in *(((char *)dst + (signed long int)n) - (signed
long int)1): FAILURE
[memcpy.pointer_dereference.14] dereference failure: pointer outside
object bounds in *(((char *)dst + (signed long int)n) - (signed long
int)1): SUCCESS
[memcpy.pointer_dereference.15] dereference failure: pointer outside
dynamic object bounds in *(((const char *)src + (signed long int)n) -
(signed long int)1): FAILURE
[memcpy.pointer_dereference.16] dereference failure: pointer outside
object bounds in *(((const char *)src + (signed long int)n) - (signed
long int)1): SUCCESS


** 2 of 17 failed (3 iterations)
VERIFICATION FAILED

**Comment by guyio** [comment]
On version 5.8.
entered this:
cbmc test.c --function main --bounds-check --pointer-check

and got 
CBMC version 5.8 64-bit x86_64 windows
Parsing test.c
test.c
Converting
Type-checking test
Generating GOTO Program
Adding CPROVER library (x86_64)
tmp.stdin12156.mWmaaa.c
Removal of function pointers and virtual functions
Partial Inlining
Generic Property Instrumentation
Starting Bounded Model Checking
size of program expression: 55 steps
simple slicing removed 0 assignments
Generated 1 VCC(s), 0 remaining after simplification
VERIFICATION SUCCESSFUL

**Comment by tautschnig** [comment]
Would you be able to confirm that release 5.9 fixes this problem for you (as you are running Windows)? Thanks! (There have been numerous changes in the relevant parts of the code, and missing bounds checks was a known problem that has however been addressed.)

**Comment by martin-cs** [comment]
5.8 is incorrect and misses these bug.  Thanks for reporting this.  5.9
works for me and gives the same results as master.  As Michael says,
please could you try 5.9 and let us know?  If it works, is moving to
5.9 a solution for your use-case?

**Comment by guyio** [comment]
Yes, just verified on 5.9 and it's working properly.
Thank you!

**Comment by martin-cs** [comment]
On Mon, 2018-07-16 at 05:25 -0700, Guy Inbar wrote:
> Hey, I've tackled a new problem in cbmc 5.9:
> 
> #include <string.h> // memcpy
> #include <stdlib.h> //realloc
> 
> void main(){
> 	char* a = malloc(10);
>     char* b = malloc(10);
> 	if(a == 0 || b == 0)
> 	{
> 		return;
> 	}
>     memcpy(b, a, 5);
> }
> 
> results in 

This works for me with 5.9.  Are you seeing a problem?

**Comment by guyio** [comment]
Oh, I'm sorry.. I've deleted it instantly, I accidentally changed the wrong input file.
It's working now!

**Comment by martin-cs** [comment]
No worries; glad you've got things working.
