### ISSUE TITLE
Test MC/DC coverage instrumentation

### ISSUE THREAD

**Issue by peterschrammel** [diffblue/cbmc#258]
for C programs

**Comment by lucasccordeiro** [comment]
@kroening: can you please provide some additional information about this task? what is the expected result for testing MC/DC coverage instrumentation? What are the options that we have to use in CBMC? Is there some particular test suite that I should consider?

**Comment by kroening** [comment]
Please identify suitable publication/reports/definitions with examples to use as tests and identify any existing test suites.

**Comment by lucasccordeiro** [comment]
@kroening: for a comparator like "x > comparison_point", CBMC is generating 2 test cases to confirm MC/DC: one test case with a TRUE outcome and one test case with a FALSE outcome. Although MC/DC only requires two tests, minimum good requirements-based testing for a comparator would also require 3 additional tests: one input value slightly above, one input value slightly below, and one input value equal to the comparison point. I have talked to Youcheng and it seems that he has already implemented this feature for another project. Should we integrate that code into CBMC?

**Comment by kroening** [comment]
Yes, but under a different name. What would be the usual name for this?

**Comment by peterschrammel** [comment]
It's called boundary value analysis, maybe call it --cover boundary-values?

**Comment by kroening** [comment]
--cover boundary-values sounds good

**Comment by kroening** [comment]
There is now the possibility to instrument multiple criteria simultaneously, but there is still interaction between them.

**Comment by lucasccordeiro** [comment]
Youcheng has mailed me a patch that implements "--cover boundary-values". I'll review it and create another issue in github so that we can track this activity.

**Comment by lucasccordeiro** [comment]
The option "--cover boundary-values" (implemented by Youcheng) is integrated and tested at:
https://github.com/lucasccordeiro/cbmc/tree/boundary-value-analysis

**Comment by kroening** [comment]
Can you do a pull request, please?

**Comment by lucasccordeiro** [comment]
Done.

**Comment by peterschrammel** [comment]
MC/DC tests have been written in https://github.com/diffblue/cbmc/tree/develop/regression/cbmc-cover.

**Comment by peterschrammel** [comment]
Boundary value analysis is a different issue. PR is here for reference: https://github.com/diffblue/cbmc/pull/298
