### ISSUE TITLE
Take libraries out of test coverage

### ISSUE THREAD

**Issue by peterschrammel** [diffblue/cbmc#259]
@kroening, is this about built-ins or user-specified libraries?

**Comment by kroening** [comment]
built-ins

**Comment by peterschrammel** [comment]
The problem is a combination of the following:
1. partial inlining is done **before** instrumenting coverage goals
2. goto_inline tries to replace the source locations of hidden functions (i.e. built-ins) (not quite -- because it seems that locations are re-introduced through remove_returns -- I haven't investigated that further)
3. instrument_cover_goals is unable to know where the inlined code came from

@kroening, is there any reason why 2. is necessary?

**Comment by kroening** [comment]
2: To hide them -- in particular, the goal is to have assertions appear in the place where the function is called.

**Comment by peterschrammel** [comment]
Ok. Then I use ID_hide or introduce a new flag to mark code from built-ins.
