### ISSUE TITLE
goto-instrument --accelerate does not seem to be accelerating loops.

### ISSUE THREAD

**Issue by EtiChaudhary** [diffblue/cbmc#2632]
Giving the GOTO Binary Produced by goto-cc for the following C file as input to _**goto-instrument**_ with the _**--accelerate**_ option:

```C
int main() {
	int i = 0 ;
	int n  = 10 ;
	int x = 0 ;

	while(i<=n) {
		i = i+1 ;
		if(i<=n/2)
			x = x +1 ;
	}
	assert(x==i && i>10);
}
```
The GOTO-program corresponding to the output produced is as follows:
```
1: overflow_0 = FALSE;
    IF !(i <= n) THEN GOTO 4
        overflow_0 = overflow_0 || overflow("+", signed int, i, 1);
        overflow_0 = overflow_0 || overflow("+", signed int, i, 1);
        i = i + 1;
        overflow_0 = overflow_0 || n == -2147483648 && 2 == -1;
        IF !(i <= n / 2) THEN GOTO 2
        overflow_0 = overflow_0 || overflow("+", signed int, x, 1);
        x = x + 1;
2: IF !overflow_0 THEN GOTO 3
 3: GOTO 1
4: ASSERT x == i && i > 10 // assertion x == i && i > 10
```
_As one may note, there is no accelerated path inserted into the GOTO-program as should be._

**Comment by martin-cs** [comment]
Thanks for the bug report.  Despite it's considerable utility, the loop accelerator is currently without a maintainer and the test for it are comparatively sparse.  As I recall, the accelerator is underapproximate, so it adds accelerated paths when it can but if it can't find any it won't add them.  Have you tried simpler loops?

**Comment by EtiChaudhary** [comment]
Yes, I also tried it on a simple example as follows:
```c
int main()
{
	int i = 0 ;
	int n = 100000 ;
	int x = 0 ;

	while(i<=n)
	{
		i = i+1 ;
		x = x +1 ;
	}

	assert(x==i && i>10);
}
```
The corresponding GOTO-program for the output produced is as follows:

```
     1: overflow_0 = FALSE;
        IF !(i <= n) THEN GOTO 3
        overflow_0 = overflow_0 || overflow("+", signed int, i, 1);
        overflow_0 = overflow_0 || overflow("+", signed int, i, 1);
        i = i + 1;
        overflow_0 = overflow_0 || overflow("+", signed int, x, 1);
        x = x + 1;
        IF !overflow_0 THEN GOTO 2
     2: GOTO 1
     3: ASSERT x == i && i > 10 // assertion x == i && i > 10
```
As visible, there are no under-approximated paths added as should be.

_One problem that I observed is the following:_
Call to (Path Enumerator's) _next_ function, called in _enumerating_loop_accelerationt_'s accelerate function, never returns true. Inside the next function, I printed the goto program constructed for Path Selection phase. It seems to be in coherence with the research paper's description. However, the call to check_sat() in the _next()_ function mentioned above is never succeeding.

**Comment by martin-cs** [comment]
It is sad this has bit-rotted.  Given there shouldn't have been functional changes, it might be useful to see which was the last version of CBMC that this worked with.  Can you try with the following program:

```
int main()
{
	int i = 0 ;
	int n = 100000 ;

	while(i<=n)
	{
		i = i+1 ;
	}

	assert(i>10);
}
```

and would you be willing to try to patch this?

**Comment by EtiChaudhary** [comment]
With some further inspection I realized that _scratch_programt_ objects specifically create objects for Z3 only (which had some installation issue in my system). Hence, even though when I manually set _use_Z3_ option (argument in _accelerate_functions_) to FALSE, it didn't have an effect.
As soon as I fixed that part, the accelerator worked smoothly.

Thanks!
