### ISSUE TITLE
JBMC crash on getClass()

### ISSUE THREAD

**Issue by krobelus** [diffblue/cbmc#2696]
This example causes JBMC to crash.
It would be great if there was a more detailled error message in this case, so clients can choose how to handle it.

`A.java`
```java
class A {
  void clazz() {
    this.getClass();
  }
}
```

```sh
$ javac A.java
$ jbmc --function 'A.clazz:()V' A.class
JBMC version 5.9 (cbmc-5.9-372-g569c8540a) 64-bit x86_64 linux
Parsing A.class
Java main class: A
failed to load class `java.lang.Class'
failed to load class `java.lang.Object'
failed to load class `java.lang.Throwable'
failed to load class `java.lang.String'
failed to load class `java.lang.Comparable'
failed to load class `java.lang.CharSequence'
failed to load class `java.io.Serializable'
Converting
stub class symbol java::java.lang.Object already exists
Java: added 0 String or Class constant symbols
terminate called after throwing an instance of 'std::out_of_range'
  what():  _Map_base::at
fish: “jbmc” terminated by signal SIGABRT (Abort)
````

**Comment by martin-cs** [comment]
Thanks for the bug report.  This is an internal error, so there probably isn't too much a user can do with it.  What kind of information would you think was useful in the report?

**Comment by krobelus** [comment]
I see, if this crash were fixed, then there would actually be no need for an error message.
In case that it's not easily fixable, I think there should be a hint to the user that they can add a model of `java.lang.Object` to the classpath, then it seems to work.

**Comment by martin-cs** [comment]
Paging JBMC code owners @smowton @mgudemann @cristina-david @cesaro @pkesseli @peterschrammel -- can you help here?

**Comment by peterschrammel** [comment]
> I think there should be a hint to the user that they can add a model of java.lang.Object to the classpath

Yes, this would be desirable.

**Comment by TGWDB** [comment]
Closing as I can no longer reproduce this crash.
