### ISSUE TITLE
remove_vector and remove_complex break all irep sharing even when the program doesn't use those features

### ISSUE THREAD

**Issue by smowton** [diffblue/cbmc#275]
Suggested patch https://github.com/smowton/cbmc/commit/274e2ea3b36e1595aa23ed903dfad299499f5a88 checks whether the features are in use at all before using `subtype`, `Forall_operands` and other functions that break sharing. Processing Sakai (a Java program that obviously can't use either feature) this saved at least 20% of goto-analyzer's memory usage (maybe more, it exhausted by available memory before completing).

One caveat: in programs that do make heavy use of complex and vector types and which have highly nested expressions this may be costly due to repeated re-checking of sub-expressions.

**Comment by martin-cs** [comment]
On Thu, 2016-10-27 at 03:25 -0700, Chris Smowton wrote:
> Suggested patch https://github.com/smowton/cbmc/commit/274e2ea3b36e1595aa23ed903dfad299499f5a88 checks whether the features are in use at all before using `subtype`, `Forall_operands` and other functions that break sharing. Processing Sakai (a Java program that obviously can't use either feature) this saved at least 20% of goto-analyzer's memory usage (maybe more, it exhausted by available memory before completing).

From what you've said it seems like this would also affect C and C++.


> One caveat: in programs that do make heavy use of complex and vector types and which have highly nested expressions this may be costly due to repeated re-checking of sub-expressions.

More generally, we should be performing sharing-aware traversal and
modification of expressions.  There was a move to use a visitor for
this; I think the infrastructure should still be there.

**Comment by tautschnig** [comment]
@smowton We should work out to what extent your proposed patch and #150 do exactly the same thing.

**Comment by smowton** [comment]
100%, looks like.

**Comment by smowton** [comment]
Duplicate of https://github.com/diffblue/cbmc/pull/150
