### ISSUE TITLE
Remove one of `empty_typet` or `void_typet`

### ISSUE THREAD

**Issue by tautschnig** [diffblue/cbmc#2780]
Those are defined the same way, meaning `empty_typet() == void_typet()` actually evaluates to true.

**Comment by NlightNFotis** [comment]
Could it be that the removal of this might hinder support for other languages in the future? Is it possible that we might want to support a language that needs support for both of these?

**Comment by tautschnig** [comment]
`void_typet` has been removed in #4102.
