### ISSUE TITLE
call graph does not show "printf"

### ISSUE THREAD

**Issue by nmanthey** [diffblue/cbmc#2827]
Dear CBMC Team,

I have a small piece of C code that I wanted to use as a test case for a call graph extension. I tried to print the default call graph, and noticed that the function "printf" is dropped. Replacing printf with malloc works as expected.

Is this a bug, or a feature because you assume printf is not relevant for the task of CBMC?

The source is attached below.

Best,
Norbert

#include <stdio.h>

typedef void (*void_fp)(void);

struct ops
{
  void_fp a;
  void_fp b;
};

void f0(void)
{
  printf("%i\n", 0);
}
void f1(void)
{
  printf("%i\n", 1);
}
void f2(void)
{
  printf("%i\n", 2);
}
void f3(void)
{
  void_fp a = f0;
  printf("%i\n", 3);
}
void f4(void)
{
  printf("%i\n", 5);
}
void f5(void)
{
  f4();
}
int f7() {
	return 5;
}
void f6(void)
{
  printf("%d\n", f7());
}

const void_fp fp_tbl[] = {f2, NULL, f1};

void func()
{
  fp_tbl[0]();
  fp_tbl[1]();
}

int main()
{
  struct ops o;

  o.a = f4;
  o.b = f5;

  func();

  o.a();

  return 0;
}

**Comment by peterschrammel** [comment]
The reason is that `printf` has special handling inside CBMC (it's not treated as a function call instruction) and never appears as a function in the goto model. `call_grapht` would have to take this into account if this is desired.

**Comment by nmanthey** [comment]
Okay, I see. This explains what I am seeing. Can you also shed some light
on the why, please? Thanks!

Best,
Norbert

**Comment by peterschrammel** [comment]
CBMC prints output produced by `printf` as part of the trace (at least in PLAIN format).
This could probably be done while still keeping it as a function in the goto model, but currently the replacement of printf happens very early in the frontend (before generating the goto program).
