### ISSUE TITLE
Several unit tests in jbmc/unit are marked mayfail without explanation

### ISSUE THREAD

**Issue by tautschnig** [diffblue/cbmc#2887]
At present, 5 tests (with 76 assertions) are permitted to fail, polluting the output and making it really hard to identify genuine failures/regressions. While this isn't great, there isn't a clear path forward either: there are no links to issues or other comments that would explain why failing is acceptable, or what kind of fix is due.

**Comment by thomasspriggs** [comment]
`mayfail` is no longer in use. `XFAIL` is now used for tests which must fail in order for the test run to be successful. This macro combines `[!shouldfail]` tag for this behaviour with the `[.]` tag which removes the test from the default set of tests, to avoid polluting the output. The `XFAIL` macro is documented in `use_catch.h` line 39. My understanding is that catch units tests are usually expected to fail (marked as `XFAIL`) in the case where the unit tests for a new feature or bug fix are merged in advance of the feature being added or the bug being fixed.

I think this has been addressed but if you think there are remaining issues then please feel free to re-open it.
