### ISSUE TITLE
Problem Verifying Accelerated Code (containing Arrays)  in CBMC 5.8 Release

### ISSUE THREAD

**Issue by EtiChaudhary** [diffblue/cbmc#2921]
I have been trying to verify an 'accelerated' GOTO Program making use of 'Arrays' using Z3 and other solvers but haven't succeeded.
Here's the sample program:
```cpp
int main(void) {
  int A[10];
  int i;

  for (i = 0; i < 5; i++) {
    A[i] = i;
  }

  assert(A[4] == 4);
}

```
Here's the sequence of steps followed:
```
 goto-cc <path_to_test_file> -o <path_to_output>
 goto-instrument --accelerate <path_to_test_file> <path_to_accelerated_output>
 cbmc --unwind 6 --<solver_option> <accelerated_output_file>  
```

Here's the result when I issue the last command listed above:
_- z3 (Version 4.7.1 64 Bit)_ : Gets stuck
_- yices (Version 2.6 )_
     &nbsp; &nbsp; &nbsp; &nbsp;"Running SMT2 QF_AUFBV using Yices
      &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;SMT2 solver returned error message:
     &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;"quantifiers are not allowed in logic QF_AUFBV""
_- cvc4 (Version 1.6)_	
    &nbsp; &nbsp; &nbsp; &nbsp; "Running SMT2 QF_AUFBV using CVC4
     &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;SMT2 solver returned error message:
    &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "The logic was specified as QF_AUFBV, which doesn't   include THEORY_QUANTIFIERS, but got a preprocessing-time fact for that theory.""

**NOTE:** 
This problem comes up ONLY in case of assignments involving arrays. Accelerated forms of such assignments get converted to expressions such as 'assume forall'
```
ASSUME forall { unsigned int k_26; k_26 < (unsigned int)(signed long int)(1 * (int)stash_19 + 1 * (int)0) || k_26 >= (unsigned int)(signed long int)(1 * (int)stash_19 + 1 * (int)loop_counter_9) ==> array_25[(signed long int)(1 * (int)stash_19 + 1 * (int)k_26)] == A[(signed long int)(1 * (int)stash_19 + 1 * (int)k_26)] }
```

_RELATED OBSERVATION:_
I noticed that when specifying logics for these solver, CBMC always uses 'QF_AUFBV' mode which specifically asks for "Quantifier Free" formulae. However, there is an if..case in the convert_expr procedure in 'smt2_conv.cpp' that checks and performs conversion for ID_forall and ID_exists.

_Kindly clarify where things are going wrong or if I am missing out on something during the process._

**Comment by TGWDB** [comment]
Closing as no longer reproducible.
