### ISSUE TITLE
failing and passing traces for concurrent programs

### ISSUE THREAD

**Issue by mtabaei** [diffblue/cbmc#299]
For our bug explanation tool, we need failing and passing traces for concurrent programs.
We wonder if we can get them from CBMC?

**Comment by martin-cs** [comment]
On Tue, 2016-11-08 at 02:37 -0800, mtabaei wrote:
> For our bug explanation tool, we need failing and passing traces for concurrent programs.
> We wonder if we can get them from CBMC?

How do you determine if a traces passes of fails?  If these can be
written as assertions in the code then can (modulo issues with code size
and computation) give you traces where the assertion fails.

Also, what kind of concurrency are you interested in?  We support
'pthread' style asynchronous, pre-emptive concurrency.  If your interest
is in synchronous or non-pre-emptive models then there may be more
efficient approaches.

Cheers,
 - Martin

**Comment by mtabaei** [comment]
Thanks Martin for your comment.
We can use assertions for distinguishing between failing and passing traces. 
We wonder if in addition to traces where the assertion fails we can also have traces
in which the assertion does not fail.
Currently, we focus on multi-threaded shared variables programs and our
benchmarks are pthread C/C++ programs.

**Comment by martin-cs** [comment]
You could just negate the assertion.  For example, if you use a macro, like PROPERTY(X) and have in a header:

#ifdef FAILING_TRACES
#define PROPERTY(X) assert((X))
#endif

#ifdef PASSING_TRACES
#define PROPERTY(X) assert(!(X))
#endif

Then you can run:

$ cbmc -DPASSING_TRACES program.c
$ cbmc -DFAILING_TRACES program.c

Does this solve your problem?

**Comment by mtabaei** [comment]
yes, great. Thanks a lot!

**Comment by peterschrammel** [comment]
Question has been answered.
