### ISSUE TITLE
Stack memory is assumed to not be shared by cbmc

### ISSUE THREAD

**Issue by danpoe** [diffblue/cbmc#304]
In the partial order concurrency encoding cbmc currently assumes that stack memory is not shared. This seems to be a reasonable assumption, but some svcomp benchmarks make use of this:

sv-benchmarks/c/ldv-races/race-2_2-container_of_false-unreach-call.c
sv-benchmarks/c/ldv-races/race-2_3-container_of_false-unreach-call.c
sv-benchmarks/c/ldv-races/race-2_4-container_of_false-unreach-call.c
sv-benchmarks/c/ldv-races/race-2_5-container_of_false-unreach-call.c
sv-benchmarks/c/ldv-races/race-3_2-container_of-global_false-unreach-call.c

For a distilled example see regression/cbmc-concurrency/stack1 in #303.

**Comment by tautschnig** [comment]
We've had a patch to address this lingering around for a while - I'll submit the pull request this evening.
