### ISSUE TITLE
Example for improvement of guard simplification

### ISSUE THREAD

**Issue by martin-cs** [diffblue/cbmc#306]
Supporting material for feature request : not bug.

@tautschnig I remember we talked ages ago about improving the simplification of guard expressions (to help a problem Pascal was having with switch).  It seems that:

sv-benchmarks/c/recursive-simple/id_o1000_false-unreach-call.c

(from SV-COMP) gives a good example of guards that look like they should be simplifable.

**Comment by tautschnig** [comment]
@martin-cs If you've got the time to give this SV-COMP example a try with #310 applied that would be good to gather feedback. I've been using those bdd patches for quite a while.

**Comment by martin-cs** [comment]
Have done and that does indeed simplify things.  Most appreciated.

**Comment by tautschnig** [comment]
Might need some poke so as to get #310 merged then...

**Comment by tautschnig** [comment]
Though there is room for even further improvement by using bddt in simplify_exprt::simplify_boolean.

**Comment by peterschrammel** [comment]
Requested feature has been implemented.
