### ISSUE TITLE
Location numbers not unique across functions

### ISSUE THREAD

**Issue by danpoe** [diffblue/cbmc#313]
I noticed that the location numbers in the goto binaries produced by goto-cc are only unique per function (but not globally unique). Also when reading a goto binary (via, e.g., get_goto_program() in goto-instrument), the resulting goto functions do not contain globally unique location numbers even when the binary one read from had unique location numbers.

Is this all expected behavior? As it currently works we'd need to call goto_functions.update() immediately after reading a goto binary to make sure it has unique location numbers.

**Comment by peterschrammel** [comment]
After linking goto-binaries, location numbers, loop numbers etc should be updated.

**Comment by tautschnig** [comment]
The problem is that this update is only done locally, per goto program, but not at global level: goto-programs/read_bin_goto_object.cpp:158

**Comment by tautschnig** [comment]
All that it takes is adding a `functions.compute_location_numbers();` before returning from read_bin_goto_object_v3.
