### ISSUE TITLE
Incompatibility with VS community 2017

### ISSUE THREAD

**Issue by gnakibli** [diffblue/cbmc#3240]
CBMC version: 5.10
Operating system: Windows 7 64bit, VS Community 2017
Exact command line resulting in the issue: any command line from VS command prompt
What behaviour did you expect: 
What happened instead:
CBMC version 5.10 (cbmc-5.10) 32-bit i386 windows
Parsing file1.c
'CL' is not recognized as an internal or external command,
operable program or batch file.
CL Preprocessing failed
PARSING ERROR
Numeric exception : 0

CL.EXE is not present on my system. When I downgraded to VS 2013 the issue was resolved.

**Comment by tautschnig** [comment]
I have recently worked on a system with Visual Studio Community 2017 installed and found no such issue. This is obviously a very late response, but can you please confirm that you have been running in a Visual Studio command prompt (or had the PATH set up in a different way)?

**Comment by tautschnig** [comment]
Closing as not reproducible.
