### ISSUE TITLE
Regression test ansi-c/float_constant1 is failing on develop

### ISSUE THREAD

**Issue by hannes-steffenhagen-diffblue** [diffblue/cbmc#3271]
The test `regression/ansi-c/float_constant1` gives me this output:

```
main.c:16:1: error: array size must not be negative, but got -1
 STATIC_ASSERT(__builtin_types_compatible_p(_Float32, __typeof(1.0f32)));
CONVERSION ERROR
EXIT=1
SIGNAL=0
```

This worked before 72957a9128d597e3d2f315df39f5396232f2a53c (which does make changes relating to floating point numbers, but nothing that immediately jumps out as "wrong" to me)

Note that so far I've only seen this happen on machines that have upgraded to Ubuntu 18.04, so maybe this is related to different versions of the default gcc being visible? (`gcc` itself has no issue with `_Float32`, i.e.
```
_Static_assert(__builtin_types_compatible_p(_Float32, __typeof(1.0f32)), "Floating point numbers should work");
``` 
compiles fine with gcc)

**Comment by NlightNFotis** [comment]
Can confirm for me this is not visible on Ubuntu 16.04, all tests passing:

```
$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.5 LTS

$ gcc --version
gcc (Ubuntu 5.5.0-12ubuntu1~16.04) 5.5.0 20171010
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by smowton** [comment]
@hannes-steffenhagen-diffblue your gcc version?

**Comment by hannes-steffenhagen-diffblue** [comment]
@smowton `gcc (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0`

**Comment by smowton** [comment]
Thanks, successfully reproduced, taking a look now

**Comment by smowton** [comment]
Fix: https://github.com/diffblue/cbmc/pull/3280
