### ISSUE TITLE
java_string_library_preprocesst::make_argument_for_format may use nil_exprt

### ISSUE THREAD

**Issue by tautschnig** [diffblue/cbmc#3304]
As highlighted in https://github.com/diffblue/cbmc/pull/3301/files#r232243707, `make_argument_for_format` uses the return value of `get_primitive_value_of_object` to construct an assignment - but that return value may be `nil_exprt`. It seems that a resulting assignment would be invalid.

**Comment by TGWDB** [comment]
Closing as this code seems to be long gone. Please reopen if you believe this is erroneous (ideally with a pointer to where the new instance of this is).
