### ISSUE TITLE
ansi-c/get-gcc-builtins.sh gives an error

### ISSUE THREAD

**Issue by martin-cs** [diffblue/cbmc#336]
$ ./get-gcc-builtins.sh 
Downloading http://gcc.gnu.org/svn/gcc/trunk/gcc/builtin-types.def
Downloading http://gcc.gnu.org/svn/gcc/trunk/gcc/builtins.def
Downloading http://gcc.gnu.org/svn/gcc/trunk/gcc/sync-builtins.def
Downloading http://gcc.gnu.org/svn/gcc/trunk/gcc/omp-builtins.def
Downloading http://gcc.gnu.org/svn/gcc/trunk/gcc/gtm-builtins.def
Downloading http://gcc.gnu.org/svn/gcc/trunk/gcc/cilk-builtins.def
Downloading http://gcc.gnu.org/svn/gcc/trunk/gcc/cilkplus.def
Downloading http://gcc.gnu.org/svn/gcc/trunk/gcc/sanitizer.def
Downloading http://gcc.gnu.org/svn/gcc/trunk/gcc/chkp-builtins.def
builtins.h:1053:28: fatal error: hsa-builtins.def: No such file or directory
compilation terminated.
<stdin>:7:13: error: expected identifier or ‘(’ before ‘,’ token
<stdin>:476:36: error: unknown type name ‘TYPE_QUAL_CONST’
<stdin>:477:37: error: unknown type name ‘TYPE_QUAL_CONST’
<stdin>:478:37: error: unknown type name ‘TYPE_QUAL_CONST’
<stdin>:478:61: error: unknown type name ‘TYPE_QUAL_CONST’
<stdin>:521:57: error: unknown type name ‘const_tm_ptr_type_node’

Also, the resultant gcc-builtins.h does not define isgreater, isgreaterequal, etc. as described in:

https://gcc.gnu.org/onlinedocs/gcc/Other-Builtins.html

**Comment by tautschnig** [comment]
I should probably put my patch collection on get-gcc-builtins.sh out as a pull request... Will do in a few moments!

**Comment by martin-cs** [comment]
Ping?  I'm down to the last 6 issues on the SV-COMP benchmarks I'm fixing.  They all appear to be issues with __builtin_ functions not being declared so I wonder if / hope this might fix them.

**Comment by tautschnig** [comment]
I've updated #337 to include declarations (as far as these are actually possible), but it seems one of #363 or #365 is necessary as well.

**Comment by tautschnig** [comment]
Closing as #337 has been merged.
