### ISSUE TITLE
SVCOMP-benchmark wrong result in Floats

### ISSUE THREAD

**Issue by peterschrammel** [diffblue/cbmc#3438]
SVCOMP command line: 
`./cbmc --graphml-witness witness.graphml --32 --propertyfile ../../sv-benchmarks/c/ReachSafety.prp ../../sv-benchmarks/c/loop-floats-scientific-comp/loop4_true-unreach-call.c.i`

Requires models for `sin` and `cos` with the property `for all x |sin(x)-cos(x)|<=1`

**Comment by martin-cs** [comment]
On Sat, 2018-11-17 at 06:53 -0800, Peter Schrammel wrote:
> SVCOMP command line: 
> `./cbmc --graphml-witness witness.graphml --32 --propertyfile
> ../../sv-benchmarks/c/ReachSafety.prp ../../sv-benchmarks/c/loop-
> floats-scientific-comp/loop4_true-unreach-call.c.i`
> 
> Requires models for `sin` and `cos` with the property `for all x
> |sin(x)-cos(x)|<=1`

That isn't guaranteed by ISO 9899.  Given the inaccuracies of hardware
implementations I doubt it is true for many real systems.

**Comment by martin-cs** [comment]
On Sat, 2018-11-17 at 06:53 -0800, Peter Schrammel wrote:
<snip>
> Requires models for `sin` and `cos` with the property `for all x
> |sin(x)-cos(x)|<=1`

Do you mean |sin(x)^2 - cos(x)^2| <= 1 ?  Because as written it is not
true for:

1/2 (4 \pi n + \pi) < x < 2 \pi n + \pi

( if Wolfram Alpha is to be believed).

**Comment by tautschnig** [comment]
See https://github.com/sosy-lab/sv-benchmarks/issues/693: there is further claim that the benchmark simply is mislabelled.

**Comment by tautschnig** [comment]
Closing as this does not seem to be an issue in CBMC.
