### ISSUE TITLE
Const qualifier is not applied to structs or unions

### ISSUE THREAD

**Issue by thk123** [diffblue/cbmc#355]
Const qualifiers seem to be lost on tagged structs and unions. Consider the following code:

    struct struct_tag_name
    {
      int x;
      float y;
    };
    
    int main()
    {
      const struct struct_tag_name my_struct_var = {.x =  1, .y = 3.15};
      const double z = 4;
      return 0;
    }

In the symbol table for the compiled GOTO program, you get the following symbols for the two variables in `main`:

    Symbol......: main::1::my_struct_var
    Pretty name.: main::1::my_struct_var
    Module......: main
    Base name...: my_struct_var
    Mode........: C
    Type........: struct struct_tag_name
    Value.......: { .x=1, .y=(float)3.150000e+0 }
    Flags.......: lvalue thread_local file_local
    Location....: file main.c line 10 function main
    
    Symbol......: main::1::z
    Pretty name.: main::1::z
    Module......: main
    Base name...: z
    Mode........: C
    Type........: const double
    Value.......: (const double)4
    Flags.......: lvalue thread_local file_local
    Location....: file main.c line 11 function main

Note `z`'s type is correctly marked as a `const double` but `my_struct_var` only has type `struct struct_tag_name`. 

This happens independently of whether you run goto-cc then goto-instrument or run the file straight through cbmc.

**Comment by thk123** [comment]
This comment appears to point to where the fix needs to be applied:

https://github.com/diffblue/cbmc/pull/345#pullrequestreview-12680366

**Comment by thk123** [comment]
Got something working for this, need to test the following cases:

- [ ] unions 
- [ ] anonymous structs
- [ ] make the tests checked in in #356 actually fail pre this fix (they were marked as KNOWBUG but weren't checking the correct output but instead validating the _incorrect_ output
- [ ] check what #358 is doing (i.e. does it check for const typedef'd structs correctly)

**Comment by tautschnig** [comment]
This seems to have been fixed for a long time (the oldest binary I found lying around was one built for #1855). Just for completeness the current output (using 1eb1df68):
```
Symbol......: main::1::my_struct_var
Pretty name.: main::1::my_struct_var
Module......: const
Base name...: my_struct_var
Mode........: C
Type........: const struct struct_tag_name
Value.......: { .x=1, .y=(float)3.15 }
Flags.......: lvalue thread_local file_local
Location....: file const.c line 9 function main

Symbol......: main::1::z
Pretty name.: main::1::z
Module......: const
Base name...: z
Mode........: C
Type........: const double
Value.......: (const double)4
Flags.......: lvalue thread_local file_local
Location....: file const.c line 10 function main
```
