### ISSUE TITLE
Assertion parsing any Java program

### ISSUE THREAD

**Issue by smowton** [diffblue/cbmc#383]
https://github.com/diffblue/cbmc/commit/18c614e715ec9199ca5c882b5f84a00c899ac763 is bad -- turns out range-for with a string literal includes the null terminator, and `java_array_type('\0')` throws. To reproduce, try `make test` in `regression/cbmc-java`. Recommend reverting that commit.

**Comment by tautschnig** [comment]
How about std::string instead of the C string literal? That should do, I believe, but testing would be appreciated.

**Comment by smowton** [comment]
That works too.

**Comment by smowton** [comment]
Created PR above.
