### ISSUE TITLE
Incorrect SMT2 generation when using C structs

### ISSUE THREAD

**Issue by david-k** [diffblue/cbmc#398]
The following program is correctly verified by CBMC but fails with Z3 (outputs `sat`) using the generated SMT2 file:

	typedef struct
	{
		char val;
	} Struct;

	int main()
	{
		char a;
		Struct r;
		r.val = a;

		__CPROVER_assert(r.val == a, "equal");
	}

On the other hand, if you directly initialize `r` (`Struct r = {a};`) then Z3 outputs the correct result. The SMT2 file is a bit above my head so I couldn't really figure out what's wrong.

**Comment by kroening** [comment]
I get UNSAT with either minisat or Z3; can you confirm that you are using the latest version of CBMC, please?

**Comment by david-k** [comment]
I can confirm this for CBMC 5.6 and for master from a couple of days ago. Also, it's only SMT2 that seems to be wrong, DIMACS works fine.

Here is the incorrect SMT2 file:
[smt2.txt](https://github.com/diffblue/cbmc/files/691774/smt2.txt)

**Comment by tautschnig** [comment]
This works fine with today's version of CBMC, and perhaps any version since 5.7.
