### ISSUE TITLE
CBMC PARSE ERROR

### ISSUE THREAD

**Issue by nmanthey** [diffblue/cbmc#3990]
Hi all,
I tried to compile upstream Xen with upstream CBMC via my one-line-scan tool, and noticed the following error. I will attach the faultyInput that is generated during the process.

CBMC version: gcc (goto-cc 5.11 (cbmc-5.11-941-g88f5a3f)) 5.4.0
Operating system: Ubuntu 16.04 (docker container)
Exact command line resulting in the issue: goto-cc -x c CBMC/faultyInput/faulty-goto-gcc-input-for-103448.8EdG6O
What behaviour did you expect: no PARSE ERROR
What happened instead: a PARSE ERROR

**Comment by nmanthey** [comment]
I attached the zipped input file.

[faulty-goto-gcc-input-for-103448.8EdG6O.zip](https://github.com/diffblue/cbmc/files/2812548/faulty-goto-gcc-input-for-103448.8EdG6O.zip)

**Comment by tautschnig** [comment]
We do not seem to accept `__attribute__` in this (procedure-local) declaration:
```
    struct {
        unsigned long align;
        unsigned int order;
    } static const __attribute__((__section__(".init.rodata"))) orders[] = {

        { .align = ((((1ULL) << 30)) >> 12), .order = 18 },
        { .align = ((((2ULL) << 20)) >> 12), .order = 9 },
        { .align = ((((4ULL) << 10)) >> 12), .order = 0 },
    };
```

Taking a look.
