### ISSUE TITLE
Verification result changes when using smt2

### ISSUE THREAD

**Issue by batchenRothenberg** [diffblue/cbmc#4002]
I am running CBMC version 5.11 (cbmc-5.11-33-g053ae9c) on a Linux Ubuntu 16.04 virtual machine.
I run it on the following file:
[sum.txt](https://github.com/diffblue/cbmc/files/2816379/sum.txt)
which calls two functions with identical code and then asserts that the results are equal.
The functions compute the sum of an array,

When running:
./cbmc sum.c 
I get 
[main.assertion.1] line 24 assertion res1 == res2: SUCCESS
as expected.

But, when running 
./cbmc sum.c --smt2 
I get 
[main.assertion.1] line 24 assertion res1 == res2: ERROR

Is this a bug?

Thanks,
Bat-Chen

**Comment by tautschnig** [comment]
@batchenRothenberg It seems you snipped all the interesting output - quite likely there was something along the lines of
```
Passing problem to SMT2 QF_AUFBV using Z3
converting SSA
Running SMT2 QF_AUFBV using Z3
line 1: unexpected end of file
decision procedure has failed
```
? If so, is z3 on your PATH?

**Comment by batchenRothenberg** [comment]
OMG I feel so silly...
Yeah, that was the problem. I have added z3 to my path and now it returns SUCCESS as expected.
Thanks for the quick response!

**Comment by tautschnig** [comment]
We really need to start colouring the errors I guess!
