### ISSUE TITLE
02/2019 regression on sv-benchmarks/c/array-tiling/skippedu_false-unreach-call.i

### ISSUE THREAD

**Issue by peterschrammel** [diffblue/cbmc#4110]
Observed on f02417343fbb22ff258b5e9c96876a53f28b718e
Still working on baaabc80e5ce72aaba4649869b2de1d2a04c2b25 (might be due to missing validation, tough)

http://svcomp.cprover.org/svcomp19/benchexec/results-ReachSafety-Arrays/diff.html

--- begin invariant violation report ---
Invariant check failed
File: goto_symex_state.cpp:359 function: rename
Condition: (expr.id() != ID_with || expr.type() == to_with_expr(expr).old().type()) && (expr.id() != ID_if || (expr.type() == to_if_expr(expr).true_case().type() && expr.type() == to_if_expr(expr).false_case().type()))
Reason: Type of renamed expr should be the same as operands for with_exprt and if_exprt

**Comment by tautschnig** [comment]
I've got a branch that fixes this, but I need to figure out which commit exactly makes the difference.

**Comment by tautschnig** [comment]
It seems that enabling field sensitivity solves this problem. Quite possibly the problem always existed and we just didn't notice due to the lack of validation. But it will go away once #2574 is merged.

**Comment by tautschnig** [comment]
Closing as #2574 has been merged.
