### ISSUE TITLE
Add starter projects from wiki to mini-projects list

### ISSUE THREAD

**Issue by tautschnig** [diffblue/cbmc#4111]
As discussed in #3930: it would seem like a good idea to add several projects from https://web.archive.org/web/20150530010030/http://www.cprover.org/wiki/doku.php?id=starter_projects to the in-tree projects list, possibly introducing several levels (from actual "mini" projects to larger ones).

**Comment by NlightNFotis** [comment]
I can do this. I will try to get a PR as soon as possible for this.
