### ISSUE TITLE
02/2019 regression on sv-benchmarks/c/ntdrivers/diskperf_false-unreach-call.i.cil.c

### ISSUE THREAD

**Issue by peterschrammel** [diffblue/cbmc#4116]
Observed on [f024173](https://github.com/diffblue/cbmc/commit/f02417343fbb22ff258b5e9c96876a53f28b718e)
Still working on [baaabc8](https://github.com/diffblue/cbmc/commit/baaabc80e5ce72aaba4649869b2de1d2a04c2b25)

```
Passing problem to propositional reduction
converting SSA
cbmc-binary: ../nonstd/optional.hpp:730: nonstd::optional_lite::optional<T>::value_type& nonstd::optional_lite::optional<T>::operator*() & [with T = BigInt; nonstd::optional_lite::optional<T>::value_type = BigInt]: Assertion `has_value()' failed.
EC=134
```

http://svcomp.cprover.org/svcomp19/benchexec/results-ReachSafety-ControlFlow/diff.html

**Comment by tautschnig** [comment]
This will be fixed by #2068 (or more likely a PR breaking out the next commit from it, the fix for this problem is actually the next in line).
