### ISSUE TITLE
Dependency on Visual Studio on Windows

### ISSUE THREAD

**Issue by theyoucheng** [diffblue/cbmc#413]
As emphasized in the [CPROVER manual](http://www.cprover.org/cprover-manual/installation-cbmc.shtml), running the Windows version CBMC requires the installation of Microsoft Visual Studio. This puts difficulty for third-party application to call CBMC in Windows. Any suggestion to remove this dependency?

**Comment by tautschnig** [comment]
It's ok to use Cygwin or MinGW, which just require using `cbmc --gcc <usual command line>` - does this do the trick?

**Comment by theyoucheng** [comment]
Thanks very much Michael! This solves the problem.
