### ISSUE TITLE
Why CBMC is reporting this program as safe?

### ISSUE THREAD

**Issue by niyasc** [diffblue/cbmc#42]
Hi,
I'm using CMBC 5.3 to check pointer safety of following program.
```
#include<stdio.h>
#include<stdlib.h>
int main()
{
        char *c = malloc(1);
        printf("%p\n", c);
        c = c + 20;

        printf("%p\n", c);
        printf("%d\n", *c);

        free(c - 20);
        return 0;
}
```
Here I'm dereferencing a pointer which is 20 unit away from legally allocated memory. Why CBMC is not reporting this program as unsafe? Am I missing something?

**Comment by kroening** [comment]
You need to give it the options --pointer-check --bounds-check

It will then report the following:
  file test.c line 10 function main
  dereference failure: dynamic object bounds in *c

We are contemplating to make --pointer-check imply --bounds-check.
