### ISSUE TITLE
Make --function work with non-static functions (Java)

### ISSUE THREAD

**Issue by peterschrammel** [diffblue/cbmc#43]
For non-static (in the Java sense) functions, we need to create a valid `this` object (with 'non-deterministic or null' members) in the _start function before invoking a method. 
We should refuse to use --function with an interface or abstract class methods.

**Comment by smowton** [comment]
Addressed in https://github.com/smowton/cbmc/commit/19e930cf1fc4e34fd836219366b933863b13277c
