### ISSUE TITLE
Handling of ."cc" file extension in c_preprocess.cpp

### ISSUE THREAD

**Issue by cliffordwolf** [diffblue/cbmc#4358]
The `.cc` suffix is missing in this code:
https://github.com/diffblue/cbmc/blob/develop/src/ansi-c/c_preprocess.cpp#L583

I think this is a bug, because it is present here:
https://github.com/diffblue/cbmc/blob/develop/src/goto-cc/gcc_mode.cpp#L308
https://github.com/diffblue/cbmc/blob/develop/src/goto-cc/compile.cpp#L144
https://github.com/diffblue/cbmc/blob/develop/src/cpp/cpp_language.cpp#L39

**Comment by tautschnig** [comment]
Thank you very much for the detailed report, this will be fixed in #4363.
