### ISSUE TITLE
04/2019 performance regression on sv-benchmarks/c/floats-cdfpl/newton_2_(1|3|4)_true-unreach-call_true-termination.i

### ISSUE THREAD

**Issue by peterschrammel** [diffblue/cbmc#4487]
`>875s` (timeout) on ba576c4
`<700s` on f5483b2

http://svcomp.cprover.org/svcomp19/benchexec/results-ReachSafety-Floats/diff.html

**Comment by tautschnig** [comment]
I will try to bisect this, but my suspicion is that propagating equalities as constants may have a negative impact on floats. I am actually already in the process of bisecting the converse impact: we had a 40% improvement in points in ReachSafety-ECA over the last month.

**Comment by peterschrammel** [comment]
Yes, the effects are not consistent across the categories. For instance, there are visible gains in ControlFlow.

**Comment by peterschrammel** [comment]
05/2019: additionally, we have now also the following timeouts:
- sv-benchmarks/c/floats-cdfpl/newton_2_2_true-unreach-call_true-termination.i 
- sv-benchmarks/c/floats-cdfpl/newton_3_6_false-unreach-call_true-termination.i

**Comment by martin-cs** [comment]
Hmmm... not good...  When I have time I may try to look at these...

**Comment by TGWDB** [comment]
I'm closing this due to age and lack of updates for a couple of years (and thus on the assumption this is not going to be looked into specifically). Please reopen if you believe this is erroneous and this particular set of benchmarks should be investigated for performance.
