### ISSUE TITLE
output format of warnings and errors does not match gcc style

### ISSUE THREAD

**Issue by nmanthey** [diffblue/cbmc#459]
When compiling with goto-gcc, warnings are produced in the following way:

file <relative-path-to-source> line <line-number> message

gcc reports warnings and errors in the following format:

<relative-path-to-source>:<line-number>: message

To better work with a code base that is compiled per directory and finally linked into a single binary, an even more convenient format would use the absolute path to the source files. This way, analysis can be run from the common base directory and all files are found without the need to know the current work directory of the compiler process.

Best,
Norbert

**Comment by kroening** [comment]
Please try PR #463

**Comment by tautschnig** [comment]
Fixed in #517.
