### ISSUE TITLE
CBMC malloc should be able to non-determinstically fail

### ISSUE THREAD

**Issue by danielsn** [diffblue/cbmc#4605]
```
#include <assert.h>
#include <stdlib.h>
#include <stdint.h>

int main() {
    char*p = malloc(100);
    assert(p);
}
```
the assertion never triggers, tho it ought to be able to, given that real malloc can fail.

**Comment by hannes-steffenhagen-diffblue** [comment]
This has been implemented with the `--malloc-may-fail` and the `--malloc-fail-null` flags.
