### ISSUE TITLE
05/2019 regression: sv-benchmarks/c/ldv-regression/test27_true-unreach-call_true-termination.c

### ISSUE THREAD

**Issue by peterschrammel** [diffblue/cbmc#4655]
true (expected): ba576c479126f9ae3e42b32b1efc7c9b7d550200
false: 3d94a62d83c7cbf999abcd9460e6ad3d9c75853a

http://svcomp.cprover.org/svcomp19/benchexec/results-ReachSafety-Heap/diff.html

**Comment by tautschnig** [comment]
I believe the “bug” label should rather be applied to https://github.com/sosy-lab/sv-benchmarks/issues/767.

**Comment by TGWDB** [comment]
I'm closing this due to age and lack of updates for a couple of years (and thus on the assumption this is not going to be looked into specifically). Please reopen if you believe this is erroneous and this particular bug is a cbmc bug/issue.
