### ISSUE TITLE
05/2019 regression sv-benchmarks/c/ldv-memsafety-bitfields/test-bitfields-1_false-valid-deref.i

### ISSUE THREAD

**Issue by peterschrammel** [diffblue/cbmc#4737]
expected: false (valid-deref): ba576c4
actual: false (valid-free): 3d94a62

http://svcomp.cprover.org/svcomp19/benchexec/results-MemSafety-Heap/diff.html

**Comment by tautschnig** [comment]
This actually is a bug in the benchmark, which is ambiguous as it contains multiple violated properties. Reported and fix PR'ed in https://github.com/sosy-lab/sv-benchmarks/pull/805.

**Comment by peterschrammel** [comment]
I don't think it's a bug in the benchmark, but a bug in the SV-COMP rules about undefined behaviour. I've commented on sosy-lab/sv-benchmarks#805. I recommend to make assertions about undefined behaviour fatal for the purpose of SV-COMP.
