### ISSUE TITLE
CBMC on Windows: --gcc options does not work with GNAT gcc

### ISSUE THREAD

**Issue by theyoucheng** [diffblue/cbmc#475]
Trying to run ``cbmc main.c --gcc`` on the following dummy code with in Cygwin
```
#include <stdlib.h>
void main()
{
  assert(0);
}
```
The ``gcc`` comes from the ``GNAT GPL`` 
```
gcc.exe (GCC) 4.9.4 20160426 (for GNAT GPL 2016 20160515)
```
Consequently, I got a PARSING ERROR
```
CBMC version 5.5 32-bit i386 windows
Parsing main.c
file c:\gnat\2016\i686-pc-mingw32\include\stdlib.h line 136: syntax error before `uintptr_t'
PARSING ERROR
```
Here is the code at line 136:
```
  typedef void (__cdecl *_invalid_parameter_handler)(const wchar_t *,const wchar_t *,const wchar_t *,unsigned int,uintptr_t);
```

Does this mean the ``--gcc`` option must work with a vanilla gcc? Any idea to fix this?

Youcheng

**Comment by theyoucheng** [comment]
Solved by specifying the `-I` option to a directory of standard gcc header files.

**Comment by thomasspriggs** [comment]
Closing this issue out, as it was reported as solved by the person who originally raised it.
