### ISSUE TITLE
Field sensitivity appears to have broken display of counterexamples

### ISSUE THREAD

**Issue by hannes-steffenhagen-diffblue** [diffblue/cbmc#4882]
CBMC version: develop (acb3abaf5cd863c4e37df0a79db7680c21037a27)
Operating system: Linux (Ubuntu 18.04)
Exact command line resulting in the issue: cbmc --trace test.c
What behaviour did you expect: It should show a counterexample with the field set to a non-0 value
What happened instead: The counterexample had its field set to 0

Here we have a test with a failing assertion:

```
//test.c
struct SomeStruct
{
  int x;
};

int main(void)
{
  struct SomeStruct x;
  assert(x.x == 0);
}
```

`cbmc` finds the problem (`x.x` can be non-zero) just fine, but in the produced trace we have

```
State 21 file test.c function main line 8 thread 0
----------------------------------------------------
  x={ .x=0 } ({ 00000000 00000000 00000000 00000000 })

Violated property:
  file test.c function main line 9 thread 0
  assertion x.x != 0
  x.x != 0
```

A git bisect revealed that this issue was introduced in 6e514deeebdbd47493d218c37ef5692371bd7591.

**EDIT**: issue had it wrong before, the problem appears with `assert(x.x == 0)`, not `!=`

**Comment by smowton** [comment]
Fixed by #4964
