### ISSUE TITLE
Internal function to check if all the bytes in a block of memory are zero

### ISSUE THREAD

**Issue by angelhof** [diffblue/cbmc#4892]
It would be really useful to have a function that checks if all bytes in a block of memory are zero without using a loop.

**Comment by tautschnig** [comment]
What is a "block" and what does "check" mean? Could you please provide a loop-based variant of this as a specification?

**Comment by hannes-steffenhagen-diffblue** [comment]
Also, useful for what?

**Comment by tautschnig** [comment]
Here's how we implemented this in C Common: https://github.com/awslabs/aws-c-common/blob/1a2050eed4c1f9e02105e7d22743b0e7b8598691/include/aws/common/zero.h#L44

**Comment by angelhof** [comment]
Thanks @tautschnig :)
