### ISSUE TITLE
cbmc invariant violation in rewrite_with_to_field_symbols

### ISSUE THREAD

**Issue by andreast271** [diffblue/cbmc#4933]
CBMC version: 5.12 (cbmc-5.12-d8598f8-557-g1edf4d91f)
Operating system: CentOS Linux 7
Exact command line resulting in the issue: cbmc struct_array.c
What behaviour did you expect: no invariant violation
What happened instead: invariant violation

cbmc symbolic simulation fails with an invariant violation in function rewrite_with_to_field_symbols when it tries to simulate the following c code:
```c
typedef struct _MyStruct {
    int m_a;
} MyStruct;

typedef struct _MyArrayStruct {
    MyStruct m_ar[2];
} MyArrayStruct;

int main()
{
  MyArrayStruct mas;
  int a, i;
  i = 1;
  (mas.m_ar + i)->m_a = a;
  //(mas.m_ar + 1)->m_a = a;
  //mas.m_ar[i].m_a = a;
  return 0;
}
```
The failure is caused in `expr_skeletont::clear_innermost_member_expr`  when `deepest_not_nil` returns a byte_extract expression and the code expects it to return a member expression.
Either of the two lines that are commented out in the code above do not lead to an invariant failure.

**Comment by smowton** [comment]
https://github.com/diffblue/cbmc/pull/4917 would fix this by virtue of deleting the offending code entirely -- @tautschnig @romainbrenguier @kroening would you mind reviewing?

**Comment by smowton** [comment]
(confirmed the given test program works fine with #4917)

**Comment by andreast271** [comment]
https://github.com/diffblue/cbmc/pull/4917 works on the test program, but introduces a different problem on another test case, where the constant offset of a byte extract operation exceeds the width of the first operand. I am trying to get a self-contained test case for this problem.

**Comment by smowton** [comment]
@andreast271 I haven't been able to reproduce that with some fiddling around with byte-extract ops, any luck on that test-case? If you have a non-reduced test-case I'm also happy to have a go at minimising it myself.

**Comment by andreast271** [comment]
The problem with offset exceeding the operand width is probably not a bug after all. It occurs in C code that has been automatically translated from C++. Which such code, function pointers cannot always be resolved statically or by constant propagation, so symex has to guess. Symex will then occasionally execute a method of a derived class on an object of the base class. This can easily lead to offset overflows, for example if the code accesses a member of the derived class that is not present in the base class. However, these execution paths are infeasible, so the out-of-range access does no harm.

**Comment by tautschnig** [comment]
Closing as #4917 has been merged.
