### ISSUE TITLE
Invariant Check failed while dumping the SMT formula

### ISSUE THREAD

**Issue by sayakray** [diffblue/cbmc#4938]
CBMC version: 5.11
Operating system: Ubuntu
Exact command line resulting in the issue: ./cbmc <source files> -I <include files> --function <target function name> --smt2 --outfile myfile.smt
What behaviour did you expect: CBMC will prove/disprove properties and will dump the SMT representation of the program and proof objectives in myfile.smt
What happened instead: CBMC reported an invariant violation and crashed. The problem is reported as follows:

--- begin invariant violation report ---
Invariant check failed
File: smt2/smt2_conv.cpp:4406 function: convert_type
Condition: array_type.size().is_not_nil()
Reason: Check return value

--- end invariant violation report ---
Aborted (core dumped)

**Comment by TGWDB** [comment]
Closing this due to time and inactivity.

If you wish to reopen please provide an example input file since this cannot be reproduced in the current version of cbmc.
