### ISSUE TITLE
cbmc works only when there is a call to assert function?

### ISSUE THREAD

**Issue by aishaaldosery** [diffblue/cbmc#4952]
CBMC version: 5.6
Operating system: ubuntu
Exact command line resulting in the issue: timeout 10 cbmc testfile.c --unwind 5 --function Fake --z3 --outfile testfile.z3
What behaviour did you expect: to get some information in .z3 file
What happened instead: it's running without any error but the .z3 file is empty

filetest.c
int Fake(int w)
{
  if ((w >= w) && ((w % w) == 0))
    printf("YES");
  else
    w = 7;

  w = 0;
  return 0;
}

filetest.z3
1

However, if I add assert(0)  for the program and run it again its work very well and I got a .z3 with a full information
int Fake(int w)
{
  if ((w >= w) && ((w % w) == 0))
  {
    assert(0);
    printf("YES");
  }
  else
  {
    assert(0);
    w = 7;
  }

  w = 0;
  return 0;
}

**Comment by tautschnig** [comment]
As a verification tool, CBMC requires some form of specification so that it knows what to prove. CBMC can auto-generate assertions, or use user-defined assertions. In absence of either of those there really is nothing for CBMC to do. You may have seen http://www.cprover.org/cprover-manual/cbmc/tutorial/ ?

**Comment by aishaaldosery** [comment]
"CBMC can auto-generate assertions", why it didn't in my case?

if I don't want to include the assertion, how could I solve this?
Sorry, I am new to cbmc

**Comment by tautschnig** [comment]
> "CBMC can auto-generate assertions", why it didn't in my case?

See the tutorial that I linked in my earlier message for command-line options such as `--bounds-check`, etc.

> if I don't want to include the assertion, how could I solve this?
Sorry, I am new to cbmc

We'd be more than happy to help you get started, but would you mind telling us what you are trying to achieve?
