### ISSUE TITLE
missing operands for "cpp_not_typechecked"

### ISSUE THREAD

**Issue by mgudemann** [diffblue/cbmc#501]
In `cpp_typecheck_compound_type.cpp`, the `op0` of an `exprt` with id `cpp_no_typechecked` is passed to another function, but `cpp_not_typechecked` does not have operands and therefore the call to `front()` returns a `nullptr`.

This is shown for example in `cpp/Decltype2`.

**Comment by NlightNFotis** [comment]
This appears to be fixed.

`cpp/Decltype2` is a test marked `CORE` and running on CI, passing.

As I'm unable to reproduce this, I will be closing this issue for now. If you believe this issue persists, please feel free to reopen it and we will investigate further.
