### ISSUE TITLE
Idea: command-line options compatible with LLVM sanitizer

### ISSUE THREAD

**Issue by tautschnig** [diffblue/cbmc#502]
It may help uptake to support [LLVM sanitizer's options](https://clang.llvm.org/docs/UndefinedBehaviorSanitizer.html#ubsan-checks), in addition to `--pointer-check` et al. Some of those options also suggest additional assertions to be generated.

**Comment by mgudemann** [comment]
please have a look at #512 ; we could probably have a different set of additional options for gcc and clang

**Comment by mgudemann** [comment]
we could add `leak` and `address` sanitizers, too

**Comment by tautschnig** [comment]
One clarification though, while the efforts of #512 and follow-up are great: I'd like CBMC etc to support those command-line options when running CBMC on source code to be scrutinised.

**Comment by mgudemann** [comment]
ok, I understood this differently, sounds like an excellent idea

we had a short discussion about `--undefined-shift-check` recently which would also be affected by this

**Comment by thomasspriggs** [comment]
To my knowledge there are no plans within diffblue to implement this feature request. Given that there have been no comments of this issue for the last 3 years, I am going to close it out as part of an effort to reduce the number of stale open issues.
