### ISSUE TITLE
CBMC handles assumption incorrectly, leading to spurious null dereference

### ISSUE THREAD

**Issue by danielsn** [diffblue/cbmc#5052]
CBMC version: 5.12 (cbmc-5.12-d8598f8-709-gf2742bad2)
Operating system: OSX 10.12.6
Exact command line resulting in the issue: 
1. clone the repo and branch https://github.com/danielsn/aws-encryption-sdk-c/tree/cprover-5052
1. Make sure you're on branch cprover-5052
1. `cd .cbmc-batch/jobs/aws_cryptosdk_edk_init_clone.`
1. `make report`

What behaviour did you expect: When I run the code with the direct assignment
```
    struct aws_allocator *alloc; = can_fail_allocator();  // Precondition: valid allocator
```
there are no null pointer issues.  When I run it with the check 

```
    struct aws_allocator *alloc; 
    __CPROVER_assume(aws_allocator_is_valid(alloc));
```
where
```
bool aws_allocator_is_valid(const struct aws_allocator *alloc) {
    return alloc == can_fail_allocator();
}
```
I get a null dereference violation.  But the effect of these two should be identical.

**Comment by tautschnig** [comment]
Likely the same issue as #5004.

**Comment by feliperodri** [comment]
@danielsn @tautschnig there was no update from #5004 should we close this issue?

**Comment by hannes-steffenhagen-diffblue** [comment]
This is fundamentally the same issue is #5004, closing for the same reason.
