### ISSUE TITLE
CBMC invariant failure in lower_byte_extract

### ISSUE THREAD

**Issue by dominic-mulligan-arm** [diffblue/cbmc#5080]
CBMC version: 5.12 (cbmc-5.12-d8598f8-951-g73e410ab6)
Operating system: macOS 10.15 Catalina
Exact command line resulting in the issue: cbmc -I<include-path> -unwind 2 -D CPROVER_FORMAL --bounds-check --pointer-check --memory-leak-check --div-by-zero-check --signed-overflow-check --unsigned-overflow-check --pointer-overflow-check --conversion-check --undefined-shift-check --float-overflow-check --nan-check --no-assertions --no-assumptions <FILES>
What behaviour did you expect: CBMC to perform a static analysis
What happened instead: invariant failure during conversion to SSA, with report:

> --- begin invariant violation report ---
> Invariant check failed
> File: lowering/byte_operators.cpp:1168 function: lower_byte_extract
> Condition: subtype_bits.has_value() && *subtype_bits == 8
> Reason: offset bits are byte aligned
> Backtrace:
> 0   cbmc                                0x00000001022c0bca _Z15print_backtraceRNSt3__113basic_ostreamIcNS_11char_traitsIcEEEE + 74
> 1   cbmc                                0x00000001022c1182 _Z13get_backtracev + 210
> 2   cbmc                                0x000000010206c03c _Z29invariant_violated_structuredI17invariant_failedtJRKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEEEENS1_9enable_ifIXsr3std10is_base_ofIS0_T_EE5valueEvE4typeES9_S9_iS9_DpOT0_ + 44
> 3   cbmc                                0x0000000102061db9 _Z25invariant_violated_stringRKNSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEES7_iS7_S7_ + 9
> 4   cbmc                                0x000000010218d65e _Z18lower_byte_extractRK18byte_extract_exprtRK10namespacet + 11150
> 5   cbmc                                0x000000010212bd5e _ZN7boolbvt20convert_byte_extractERK18byte_extract_exprt + 110
> 6   cbmc                                0x0000000102120537 _ZN7boolbvt17convert_bitvectorERK5exprt + 1831
> 7   cbmc                                0x000000010215c0b5 _ZN12bv_pointerst17convert_bitvectorERK5exprt + 2213
> 8   cbmc                                0x000000010211f7d0 _ZN7boolbvt10convert_bvERK5exprtN6nonstd13optional_lite8optionalImEE + 240
> 9   cbmc                                0x000000010213c937 _ZN7boolbvt10convert_ifERK8if_exprt + 135
> 10  cbmc                                0x00000001021200c4 _ZN7boolbvt17convert_bitvectorERK5exprt + 692
> 11  cbmc                                0x000000010215c0b5 _ZN12bv_pointerst17convert_bitvectorERK5exprt + 2213
> 12  cbmc                                0x000000010211f7d0 _ZN7boolbvt10convert_bvERK5exprtN6nonstd13optional_lite8optionalImEE + 240
> 13  cbmc                                0x000000010213c95d _ZN7boolbvt10convert_ifERK8if_exprt + 173
> 14  cbmc                                0x00000001021200c4 _ZN7boolbvt17convert_bitvectorERK5exprt + 692
> 15  cbmc                                0x000000010215c0b5 _ZN12bv_pointerst17convert_bitvectorERK5exprt + 2213
> 16  cbmc                                0x000000010211f7d0 _ZN7boolbvt10convert_bvERK5exprtN6nonstd13optional_lite8optionalImEE + 240
> 17  cbmc                                0x000000010213c95d _ZN7boolbvt10convert_ifERK8if_exprt + 173
> 18  cbmc                                0x00000001021200c4 _ZN7boolbvt17convert_bitvectorERK5exprt + 692
> 19  cbmc                                0x000000010215c0b5 _ZN12bv_pointerst17convert_bitvectorERK5exprt + 2213
> 20  cbmc                                0x000000010211f7d0 _ZN7boolbvt10convert_bvERK5exprtN6nonstd13optional_lite8optionalImEE + 240
> 21  cbmc                                0x000000010213c95d _ZN7boolbvt10convert_ifERK8if_exprt + 173
> 22  cbmc                                0x00000001021200c4 _ZN7boolbvt17convert_bitvectorERK5exprt + 692
> 23  cbmc                                0x000000010215c0b5 _ZN12bv_pointerst17convert_bitvectorERK5exprt + 2213
> 24  cbmc                                0x000000010211f7d0 _ZN7boolbvt10convert_bvERK5exprtN6nonstd13optional_lite8optionalImEE + 240
> 25  cbmc                                0x0000000102124b88 _ZN7boolbvt27boolbv_set_equality_to_trueERK11equal_exprt + 200
> 26  cbmc                                0x0000000102124c65 _ZN7boolbvt6set_toERK5exprtb + 101
> 27  cbmc                                0x0000000102057e64 _ZN22symex_target_equationt19convert_assignmentsER19decision_proceduret + 196
> 28  cbmc                                0x0000000102057b74 _ZN22symex_target_equationt7convertER19decision_proceduret + 36
> 29  cbmc                                0x0000000101f0dce6 _Z29convert_symex_target_equationR22symex_target_equationtR19decision_proceduretR16message_handlert + 342
> 30  cbmc                                0x0000000101f0fb89 _Z24prepare_property_deciderRNSt3__113unordered_mapI8dstringt14property_infotNS_4hashIS1_EENS_8equal_toIS1_EENS_9allocatorINS_4pairIKS1_S2_EEEEEER22symex_target_equationtR28goto_symex_property_decidertR19ui_message_handlert + 441
> 31  cbmc                                0x0000000101f175d8 _ZN25multi_path_symex_checkertclERNSt3__113unordered_mapI8dstringt14property_infotNS0_4hashIS2_EENS0_8equal_toIS2_EENS0_9allocatorINS0_4pairIKS2_S3_EEEEEE + 264
> 32  cbmc                                0x0000000102359583 _ZN43all_properties_verifier_with_trace_storagetI25multi_path_symex_checkertEclEv + 51
> 33  cbmc                                0x0000000102351ce2 _ZN19cbmc_parse_optionst4doitEv + 4018
> 34  cbmc                                0x00000001022da1b2 _ZN19parse_options_baset4mainEv + 242
> 35  cbmc                                0x000000010234d4ad main + 45
> 36  libdyld.dylib                       0x00007fff6d6b32f5 start + 1
> 37  ???                                 0x0000000000000018 0x0 + 24
> 
> 
> --- end invariant violation report ---
>

**Comment by tautschnig** [comment]
This stacktrace suggests that this will likely have been fixed by #5750. Please re-open if the issue still reproduces for you.
