### ISSUE TITLE
goto_check takes a long time even if it isn't needed

### ISSUE THREAD

**Issue by owen-mc-diffblue** [diffblue/cbmc#5084]
goto_check creates a local_bitvector_analysist even if it won't be needed because none of the command line options that are dealt with in goto_check have been set. As the code you are analysing gets large, this begins to take a long time, e.g. 30s in the last example I looked at. I suggest that goto_check should make its local_bitvector_analysist lazily, so it's only constructed if it's actually used.

This is particularly an issue when using jbmc, because the java frontend creates a lot of the assertions that you would otherwise have to pass a command line option for, like null checks.

CBMC version:
Operating system:
Exact command line resulting in the issue:
What behaviour did you expect:
What happened instead:

**Comment by tautschnig** [comment]
While we still create the analysis even when not needed, the analysis itself has been improved in 38604cf6fe and 472a3934bad5c (those commits contain performance data for a function of 160822 instructions).
