### ISSUE TITLE
Failing tests due to full-slice

### ISSUE THREAD

**Issue by peterschrammel** [diffblue/cbmc#515]
Failing tests have been committed as part of #479.
Please mark failing tests as KNOWNBUG unless there is a PR that fixes them.

**Comment by lucasccordeiro** [comment]
@peterschrammel: can you please specify which test cases are failing? I have marked all failing tests as KNOWNBUG.

**Comment by peterschrammel** [comment]
https://travis-ci.org/diffblue/cbmc/jobs/199721828#L1781

**Comment by lucasccordeiro** [comment]
Thanks, @peterschrammel. This PR #518 should fix the problem.
