### ISSUE TITLE
CBMC solver iteration counting has off-by-one error

### ISSUE THREAD

**Issue by tautschnig** [diffblue/cbmc#5161]
CBMC version: 5.12-d8598f8-1211-gafac9c7
Operating system: Linux (Ubuntu 16.04)
Exact command line resulting in the issue: cbmc assertion.c --function quartile
What behaviour did you expect: CBMC printing "** 1 of 1 failed (1 iteration)" (as it did in the past)
What happened instead: CBMC prints "** 1 of 1 failed (2 iterations)"

Here is the full output:
```
CBMC version 5.12 (cbmc-5.12-d8598f8-1211-gafac9c7) 64-bit x86_64 linux
Parsing assertion.c
Converting
Type-checking assertion
Generating GOTO Program
Adding CPROVER library (x86_64)
Removal of function pointers and virtual functions
Generic Property Instrumentation
Running with 8 object bits, 56 offset bits (default)
Starting Bounded Model Checking
size of program expression: 62 steps
simple slicing removed 6 assignments
Generated 1 VCC(s), 1 remaining after simplification
Passing problem to propositional reduction
converting SSA
Running propositional reduction
Post-processing
Solving with MiniSAT 2.2.1 with simplifier
370 variables, 873 clauses
SAT checker: instance is SATISFIABLE
Runtime decision procedure: 0.00123209s

** Results:
assertion.c function quartile
[quartile.assertion.1] line 20 assertion y != 4: FAILURE

** 1 of 1 failed (2 iterations)
VERIFICATION FAILED
```

For all that I can tell there only was a single SAT solver iteration, or at least SAT instance satisfiability was only reported once.

For completeness, this is the contents of assertion.c (though the particular example does not seem very relevant):
```
#include <assert.h>

int quartile(int x) {
  int y;

  if (x < 0 || x > 99)
    return 0;

  if (x < 50)
    if (x < 25)
      y = 1;
    else
      y = 2;
  else
    if (x < 75)
      y = 3;
    else
      y = 4;

  assert (y != 4);
  return y;
}
```

**Comment by peterschrammel** [comment]
Hm... interesting. It seems I've changed the semantics of `iterations`.

The current semantics is 'how many times did I call `incremental_goto_checkert`, which might not coincide with the number of solver calls when no call was needed to determine that all work has been done (like in your case: 1st iteration: found violation, 2nd iteration: all properties decided). When refinements were enabled then `iterations` also didn't coincide with solver calls in the past.

Maybe we should find a useful definition of `iterations`. What is the information you'd like to get from `iterations`?

**Comment by TGWDB** [comment]
Closing this as it seems to be no longer of interest, please reopen if you believe this is erroneous.
