### ISSUE TITLE
glucose-download requires SSL

### ISSUE THREAD

**Issue by emptylambda** [diffblue/cbmc#5169]
Hello glucose dev team, 

Thank you for developing & maintaining the system. 
I've stumbled upon SSL issue while using the `glucose-download` inside Makefile 

```
make -C src glucose-download -j4
Downloading glucose-syrup
lwp-download5: 500 Can't verify SSL peers without knowing which Certificate Authorities to trust
make: *** [glucose-download] Error 1
```
Operating system: osx 

Maybe this issue should be resolved from the glucose side with an alternative tar? 

Thank you in advance and Best Regards
Jeff

**Comment by martin-cs** [comment]
( FWIW we aren't the glucose dev team, we just use it. )

Thank you for reporting this.  I have tried to reproduce but it seems to work on Linux and I don't have an OS X machine.  Maybe @chrisr-diffblue or @thk123 can help?  I think they are Mac users.

**Comment by kroening** [comment]
This is a problem with Apple's Perl setup.
http://blogs.perl.org/users/vsespb/2014/07/broken-lwp-in-the-wild.html
Consider using `curl` instead of lwp-download.

**Comment by chrisr-diffblue** [comment]
Confirmed, this happens on both OSX 10.14.6, and OSX 10.15.1 for me.

**Comment by thomasspriggs** [comment]
> ( FWIW we aren't the glucose dev team, we just use it. )
> 
> Thank you for reporting this. I have tried to reproduce but it seems to work on Linux and I don't have an OS X machine. Maybe @chrisr-diffblue or @thk123 can help? I think they are Mac users.

thk123 is not currently an active CBMC developer. The current team within diffblue working on CBMC includes myself, NlightNFotis, hannes-steffenhagen-diffblue, piotr-grabalski, and our newest member TGWDB. Of these Fotis is probably the most enthusiastic Mac user.
