### ISSUE TITLE
Warning (treated as error) when compiling with instruction in Compiling.md

### ISSUE THREAD

**Issue by jparsert** [diffblue/cbmc#5216]
When running `make -C src`

I ran into the following warning which is being treated as an error.

g++ -c -DSATCHECK_MINISAT2 -MMD -MP -std=c++11 -O2 -DHAVE_MINISAT2 -Wall -pedantic -Werror -Wno-deprecated-declarations -Wswitch-enum  -I .. -o complexity_limiter.o complexity_limiter.cpp
complexity_limiter.cpp: In member function ‘bool complexity_limitert::are_loop_children_too_complicated(call_stackt&)’:
complexity_limiter.cpp:101:60: error: ‘*((void*)& loop_to_blacklist +8)’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
  101 |   optionalt<std::reference_wrapper<lexical_loopst::loopt>> loop_to_blacklist;
      |                                                            ^~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
make[1]: *** [../common:222: complexity_limiter.o] Error 1

CBMC version: current main (develop) branch
Operating system: Fedora

**Comment by tautschnig** [comment]
Thank you for this report. The problem was fixed in #5355 (specifically in f022757801909).
