### ISSUE TITLE
`c_typecheck_expr` does not work with compound literals

### ISSUE THREAD

**Issue by hannes-steffenhagen-diffblue** [diffblue/cbmc#5256]
This somehow gets avoided most of the time, but I don’t suppose there’s a good reason why it wouldn’t work?

I think this would “fix” it by basically doing nothing.
```
diff --git a/src/ansi-c/c_typecheck_expr.cpp b/src/ansi-c/c_typecheck_expr.cpp
index eb081c8c1..b4966aaac 100644
--- a/src/ansi-c/c_typecheck_expr.cpp
+++ b/src/ansi-c/c_typecheck_expr.cpp
@@ -171,6 +171,14 @@ void c_typecheck_baset::typecheck_expr_main(exprt &expr)
     typecheck_expr_side_effect(to_side_effect_expr(expr));
   else if(expr.id()==ID_constant)
     typecheck_expr_constant(expr);
+  else if(expr.id() == ID_compound_literal)
+  {
+    // do nothing
+  }
+  else if(expr.id() == ID_struct)
+  {
+    // do nothing
+  }
   else if(expr.id()==ID_infinity)
   {
     // ignore
```

CBMC version:
Operating system:
Exact command line resulting in the issue:
What behaviour did you expect:
What happened instead:

**Comment by tautschnig** [comment]
@hannes-steffenhagen-diffblue Was there a test to demonstrate what actually was going wrong?

**Comment by tautschnig** [comment]
I am now actually seeing such a case while working on #5913. Will include that fix.

**Comment by tautschnig** [comment]
Actually changing my course of action here: those expressions are exclusively generated by the type checker, and thus should not be seen in type checking again. It's most likely a bug (as was the case in my work in #5913). If re-typechecking is expected/unavoidable, use `make_already_typechecked`.

Closing, but please do re-open if my claims turn out to be wrong.
