### ISSUE TITLE
Webpage and releases are confusing and incomplete

### ISSUE THREAD

**Issue by PhilippWendler** [diffblue/cbmc#5260]
The information about which CBMC version is the latest and how to get it is incomplete and inconsistent, and there are no binaries of the latest version:

- The last version advertised via the [mailing list](https://groups.google.com/forum/#!forum/cprover) was version **5.10**.
- The [website](http://www.cprover.org/cbmc/) says `NEW: Version 5.11 released`.
- The [website](http://www.cprover.org/cbmc/) has a binary of **5.10** as latest version for Windows.
- The [website](http://www.cprover.org/cbmc/) has a binary of **5.11** as latest version for Linux and MacOS X.
- The [project readme](https://github.com/diffblue/cbmc#versions) and thus the GitHub repo links to the [GitHub releases](https://github.com/diffblue/cbmc/releases) for getting the latest version, but that page lists version **5.8** as latest release, and it does not provide any binaries.
- The [git tags](https://github.com/diffblue/cbmc/tags) has a version **5.12** but of course also no binaries.

Please provide consistent information and binaries of the latest release. It would also be nice to provide an archive of binaries for all previous releases. The [GitHub releases](https://github.com/diffblue/cbmc/releases) could be a convenient place for storing such artifacts.

Two other important things I noticed while looking for releases:
- The GitHub repo links to the webpage in several places, but the webpage never links to the GitHub repo. So users who find CBMC via the webpage for example do not how where to report bugs.
- While the website is available via HTTPS, there are no redirects from HTTP to HTTPS and all the links in the GitHub repo point to the HTTP version. So people will mostly use the HTTP version of the webpage and download the binaries via an untrusted connection, which is not optimal. Note that already this year browsers will forbid unencrypted downloads! ([source](https://www.thesslstore.com/blog/browser-watch-google-chrome-to-block-http-downloads/))

**Comment by jimgrundy** [comment]
We've gotten more systematic about our approach to releases this year, so I'm going to close this.
