### ISSUE TITLE
Crash on pointer dereference for pointer constrained with assumption

### ISSUE THREAD

**Issue by danpoe** [diffblue/cbmc#5328]
```
#include <assert.h>
#include <stdlib.h>

void main()
{
  char *p;
  __CPROVER_assume(__CPROVER_r_ok(p - 1, 1));
  *p;
}
```

CBMC version: 03ab5c75aa59c7c2d349136a14db0e130889126d
Operating system: Ubuntu
Exact command line resulting in the issue: cbmc --pointer-check --no-simplify --no-propagation main.c
What behaviour did you expect: verification failed
What happened instead: crash

**Comment by danielsn** [comment]
May be related to https://github.com/diffblue/cbmc/issues/5293
