### ISSUE TITLE
Add CI builds for Windows and Visual Studio

### ISSUE THREAD

**Issue by forejtv** [diffblue/cbmc#533]
Use AppVeyor to build master and PRs under Windows and Microsoft Visual Studio.

Depends on #531 and #532. For now we will just set up compilation and not run tests, because quite a few tests fail, at least on AppVeyor.

**Comment by tautschnig** [comment]
I don't think we'd actually expect tests to fail, except that we might not have access to Bash and thus any of the directories using, e.g., chain.sh might cause problems.

**Comment by forejtv** [comment]
@tautschnig Most tests in ansi-c fail, and they don't seem to use any .sh files. But it is indeed likely to be a configuration problem, because the same tests fail also on the commit that this tagged with the last release.

I will close this issue for now, because a compile-only version of CI is running. When I or somebody else get a bit of time, we can look into the failing tests.

**Comment by tautschnig** [comment]
My suspicion is that we'd have to invoke goto-cl instead of goto-cc on the ansi-c tests. I believe that @kroening has been doing regular runs of the test suite under Visual Studio, hence should have the necessary experience and insight!
