### ISSUE TITLE
Bug with pointer and non-trivial class layout

### ISSUE THREAD

**Issue by lookfwd** [diffblue/cbmc#535]
On the following code:

    #include <assert.h>

    unsigned cnt = 0;

    struct Foo {
        //int i;
    };

    class Box
    {
        unsigned * monitor;
        Foo f;

        void op()
        {
            assert(monitor == &cnt);

            *monitor = 1;
        }
    };

    class Container
    {
        Box boxes[1];
    };

    int main()
    {
        Container c;

        c.boxes[0].monitor = &cnt;
        c.boxes[0].op();

        assert(cnt == 0u);

        return 0;
    }

depending on if `Foo f;` exists (try commenting it out), the checker does or doesn't work (despite the fact that `Foo` is empty.

**Comment by TGWDB** [comment]
Not reproducible in current version.

If you believe this has been closed erroneously please reopen.
