### ISSUE TITLE
Memory Snapshot Harness tests are marked KnownBug

### ISSUE THREAD

**Issue by NlightNFotis** [diffblue/cbmc#5351]
During work done in #5343 we discovered that changing the output of `goto-harness` to C code instead of GOTO binaries breaks the tests for the memory snapshot harness because the C harness we generate contains a modified version of the harness function so we can no longer link them.

**Comment by tautschnig** [comment]
@NlightNFotis What is the status here? It seems that a number of tests were marked `KNOWNBUG` yet they appear to work perfectly fine at the moment. It seems the problem is somewhere outside what's being tested?

**Comment by NlightNFotis** [comment]
Hi @tautschnig, sorry, this fell through the cracks before (I didn't see the notification among others), so I'm updating you on this now.

This was definitely a problem back when we changed `goto-harness` to work with C programs instead of GOTO ones. IIRC this broke the memory snapshot one. Looks like https://github.com/diffblue/cbmc/commit/af01532409533aba21378f779876d3dec4218bd5 fixed it, so thank you very much!
