### ISSUE TITLE
CBMC doesn't catch unsigned overflow with sizeof()

### ISSUE THREAD

**Issue by feliperodri** [diffblue/cbmc#5382]
CBMC version: 5.12 (cbmc-5.12.1)
Operating system: macOS Mojave Version 10.14.6
Exact command line resulting in the issue: `cbmc main.c --unsigned-overflow-check`
What behaviour did you expect: CBMC should detect an arithmetic overflow on unsigned + in (unsigned long int)y + sizeof(uint32_t) /*4ul*/.
What happened instead: CBMC reports success for this check.

```c
#include <stdint.h>
#include <assert.h>

int main() {
    uint32_t x;
    uint32_t y;

    assert(sizeof(uint32_t) == 4);
    x = y + sizeof(uint32_t); // success
    // x = y + 4; // failed
    assert(x > y);
    return 0;
}
```

**Comment by peterschrammel** [comment]
Note that the type of the `sizeof(x)` expression is `size_t` (see C11 6.5.3.4).

**Comment by feliperodri** [comment]
I got it, thanks @peterschrammel!
