### ISSUE TITLE
--export-file-local-symbols should also mangle static variables

### ISSUE THREAD

**Issue by karkhaz** [diffblue/cbmc#5392]
Currently it only mangles static functions.

There is a workaround meanwhile, as long as we can change the file where the static variable is defined. Just write an accessor function (doesn't need to be static) that returns the static variable's value (for reading) or a pointer to it (for mutating). So this isn't a such a high-priority request.

**Comment by karkhaz** [comment]
@danielsn ping

**Comment by feliperodri** [comment]
@karkhaz is there any updates on this issue? Should we close it? @hannes-steffenhagen-diffblue is there anybody working on this issue?

**Comment by jimgrundy** [comment]
@markrtuttle can you please comment on soundness risk here? If there is any please add the soundness label.

**Comment by jimgrundy** [comment]
@markrtuttle (2nd request) can you please comment on soundness risk here? If there is any please add the soundness label.

**Comment by feliperodri** [comment]
Might be affected by https://github.com/diffblue/cbmc/pull/6339

**Comment by tautschnig** [comment]
This would have been addressed by #6339, but we instead decided to make `crangler` the tool to use for this kind of workflow.
