### ISSUE TITLE
goto-cc cannot compile two files with the same name together

### ISSUE THREAD

**Issue by karkhaz** [diffblue/cbmc#5417]
When compiling two files with the same name in a single invocation of goto-cc, only one of the files' functions are included in the resulting goto-binary.
```c
// 1/c.c
int foo1(){ return 0; }
```
```c
// 2/c.c
int foo2(){ return 0; }
```
What happens:
```sh
> goto-cc -o a.out 1/c.c 2/c.c
> goto-instrument --show-goto-functions a.out
Reading GOTO program from 'a.out'
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

foo2 /* foo2 */
        // 0 file 2/c.c line 1 function foo2
        return 0;
        // 1 file 2/c.c line 1 function foo2
        GOTO 1
        // 2 file 2/c.c line 1 function foo2
     1: END_FUNCTION

>
```
What I expected to happen: the binary should also contain an implementation of `foo1()`.
CBMC version: cd3c603d8fe2d5b0572dd761532dd76d37f89d33

**Comment by karkhaz** [comment]
@danielsn ping

**Comment by hannes-steffenhagen-diffblue** [comment]
Yep, can easily reproduce. Really weird.

FWIW this _only_ seems to happen if you do this with source files directly, compiling with `goto-cc -c` and then linking them together later seems to work even if the object files have the same name, which is probably how that slipped past us for so long.

Tracking this internally as ADA-574

**Comment by hannes-steffenhagen-diffblue** [comment]
The referenced PR here should’ve fixed this issue.
