### ISSUE TITLE
RAM exhaustion on reading binary GOTO

### ISSUE THREAD

**Issue by mgudemann** [diffblue/cbmc#543]
the attached (likely incorrect) binary GOTO of 48 bytes causes CBMC to consume > 8G of RAM on reading

[endless-loop-8G.zip](https://github.com/diffblue/cbmc/files/772197/endless-loop-8G.zip)

**Comment by TGWDB** [comment]
Fix PR closed, also mentioned in other commits. Cannot reproduce now.

Closing as it is unclear that this is still a problem, please reopen if you believe this is erroneous.
