### ISSUE TITLE
Add cmake macro for installation symlinks

### ISSUE THREAD

**Issue by markrtuttle** [diffblue/cbmc#5430]
In the pull request [5419](https://github.com/diffblue/cbmc/pull/5419), @hannes-steffenhagen-diffblue proposes a macro to create the symlinks during installation to installed binaries and man pages.  This will make the cmake files easier to read and be less error prone than the current cut-and-paste implementation.  This will also give an opportunity to warn about using DESTDIR on Windows: The use of [DESTDIR is not recommended on Windows](https://cmake.org/cmake/help/latest/envvar/DESTDIR.html).

**Comment by hannes-steffenhagen-diffblue** [comment]
@markrtuttle I've actually thought a bit more about this issue and realised there is a much simpler way to accomplish what we were trying to do here, this is now merged as https://github.com/diffblue/cbmc/pull/5460

**Comment by hannes-steffenhagen-diffblue** [comment]
Since apparently the simpler way works just as well (as far as I know), I will close this. Please open another issue if there is anything else to sort out here.
