### ISSUE TITLE
shift exponent too large in left shift

### ISSUE THREAD

**Issue by mgudemann** [diffblue/cbmc#544]
when supplying a carefully crafted GOTO, it is possible to have a left shift showing potentially undefined behavior, as more than bit-width bits are left shifted
```
  while(in.good())
  {
    unsigned char ch=in.get();
    res|=(size_t(ch&0x7f))<<shift_distance;
    shift_distance+=7;
    if((ch&0x80)==0) break;
  }
```
[wrong_left_shift.zip](https://github.com/diffblue/cbmc/files/772309/wrong_left_shift.zip)

**Comment by tautschnig** [comment]
A check was added in #3116.
