### ISSUE TITLE
What do CBMC version numbers mean?

### ISSUE THREAD

**Issue by hannes-steffenhagen-diffblue** [diffblue/cbmc#5453]
We’re trying to move to a more frequent release cycle right now. One issue that’s come up for me is that I’m not quite sure how to interpret the current CBMC version numbers;

For example, we’re currently on CBMC 5.12.6? What would it take to go from there to 5.13? What would have to change for us to call it 6.0?

Just trying to gather opinions here for now, because ideally we should be in agreement on what these numbers mean if we’re going to change them. So far for the biweekly releases we’ve been just increasing the last number (5.12.5 →5.12.6 etc), and in a pinch we can just keep doing that, but I’d prefer if we just agreed on a scheme for this.

Related: https://github.com/diffblue/cbmc/issues/5448

**Comment by martin-cs** [comment]
I think 4.x->5.0 co-coincided with / was for incompatible changes to the goto-program format.  Minor numbers were for major features, entry to SV-COMP, releases to significant customers.  At the risk of being a stuck record; this is a social issue, the numbers are just arbitrary.

**Comment by hannes-steffenhagen-diffblue** [comment]
@martin-cs I do agree that this is a social issue, which is why I’m trying to kick off some discussion with people who are interested in this sort of thing so we can pick _one_ arbitrary convention and stick with it.

@peterschrammel @kroening @chrisr-diffblue @smowton any thoughts?

**Comment by smowton** [comment]
None whatsoever

**Comment by chrisr-diffblue** [comment]
I agree that the numbers are somewhat arbitrary, and that it is mainly a social issue - however, _being_ a social issue means that people _expect_ the numbers to have a pattern, order, meaning, etc.... :-) Totally agree with Hannes hat we should pick one arbitrary convention, then stick with it.

Arguably, the most common convention people probably expect is major.minor.patch structure. Which _probably_ roughly corresponds in peoples minds to:
* major -> potentially breaking changes (to goto-program format, to command line behaviour, etc) expected to a large subset of the users. Basically the view that "if I bump a major version number then I might need to expect my workflow breaks.
* minor -> new features that don't break existing workflows
* patch -> bugfixes, don't expect it to break existing workflows, unless you happened to depend on broken behaviour. Tough luck, them's the breaks...

Thats just my opinion, which is no more valid than anyone elses.

**Comment by peterschrammel** [comment]
@chrisr-diffblue's scheme follows the common understanding (at least mine) of version numbers and I think we should follow that.
Goto-binary format changes should definitely be major version changes; major deprecation of command line options probably too.

**Comment by hannes-steffenhagen-diffblue** [comment]
@peterschrammel My preference would be deprecation in a minor release, removal in a major release. That way people get warned about possible coming breakages without upgrading to a number that says "this will probably break something".

**Comment by hannes-steffenhagen-diffblue** [comment]
**Conclusion**

In the absence of very strong opinions, I suggest the following moving forward:

We adopt an approach approximating SemVer. That is, our version numbers should be major.minor.patch. Regular releases (cadence TBD but probably weekly or biweekly) should normally increment the _minor_ version number. This is also where we can deprecate undesired features, i.e. _mark_ as deprecated, warn existing users.

Patch version increments should not be done as part of the regular releases, and instead should be reserved for critical bugfixes. Don't make a patch release if you're not confident your release contains nothing _but_ bugfixes.

Major version increments should be reserved for changes which we _expect_ will break downstream users scripts and/or workflows. This includes things like changing the goto binary format in such a way that old outputs can't be read by new version of our tools or vice versa, or removing deprecated functionality (removal of functionality should generally be preceded by deprecation!). Note that incrementing the major version every time a change technically _could_ break a downstream users scripts would lead to a weak signal, as basically _any_ detectable change _including_ bugfixes can do that. Instead, major version increments should signal that we expect _many_ users will have to review their workflows for potential breakages, not just _any_.

@peterschrammel @chrisr-diffblue @martin-cs @smowton 

Any further comments on this? If not I'll add this as written to our documentation so we have some guidance written down.

**Comment by chrisr-diffblue** [comment]
Looks good to me - that makes a good clear policy that should be easy to follow, and easy for end users to understand. Many thanks!

**Comment by martin-cs** [comment]
I like having major, minor and patch.  I like them having defined and documented meanings.  I like the specific major = "breaks your work-flow", minor = "probably won't break stuff" and patch = "really shouldn't break anything, only if you are relying on a buggy and incorrect behaviour".  If we could have the version number presented as x.y.z-GIT_ID in the tool that would be amazing. 

The only bit I don't get is why we need such rapid releases.  I mean, we can but at the moment I am not seeing a rate of change that justifies more than monthly releases.  If you need more than that a nightly build from `develop` should be fine?  Given the automation work you have been doing I guess I am missing a requirement / need.

**Comment by hannes-steffenhagen-diffblue** [comment]
@martin-cs Release cadence is kind of a separate discussion. We want it to be regular at any rate, and if there's a bugfix or new feature ideally we'd have an easy way to get it to end users who can't or don't want to build from source. Nightly builds are a possibility, the thing is that I'd prefer if people used regular releases instead because that gives us an immediate diagnostic tool - if they complain about some issue we can just check the version number which is increasing linearly rather than a pseudorandom hash.

**Comment by martin-cs** [comment]
@hannes-steffenhagen-diffblue If you want timely and linear increase but are not necessarily tied to features why not:

major.minor.YYYYMMDD
5.13.20080828 for example

That way you can cut a release whenever, say automated weekly *and* over-night fixes and you have one consistent numbering scheme and it tells you (and the user!) how up to date the release is?

**Comment by hannes-steffenhagen-diffblue** [comment]
@martin-cs The main reason against that is that the majority of people wouldn't expect the last component to mean "date". We could explain that in our documentation of course, but let's be honest the vast majority of users are never going to read it or at best skim over it. I'm a big fan of defaulting to whatever the majority probably expects whenever we can.

I'd like to hear your thoughts on why frequent releases are a problem though, because it's not obvious to me why that would the case.

**Comment by martin-cs** [comment]
They don't need to know it is a date!  It can be a secret magic number that only the developers understand! :smile: 

My point is that if the release criteria are "What day is it" then ... why not have that as part of the release number?  If we have a new minor number every N weeks then when someone reports an issue with 5.37 the first thing we will have to do is to work out when that was and if it is recent.  Having the date in the number skips that.

For me the frequency of release and the meaning of the version numbers are linked because they are about communicating expectations to the users.  If we have daily / weekly / bi-weekly releases and that uses the minor version number then we can't easily work out the difference between 5.39 and 5.47, for example.  Maybe it's just a month or so, but which one.

**Comment by martin-cs** [comment]
@hannes-steffenhagen-diffblue ( and @chenrui333 W.R.T. https://github.com/diffblue/cbmc/issues/5448 ) is this now resolved?  Can this issue be closed?
