### ISSUE TITLE
Ensure that all supported options are listed by --help

### ISSUE THREAD

**Issue by tautschnig** [diffblue/cbmc#547]
Even disregarding deprecated ones, there are numerous options that are parsed by various *_parse_options.cpp files, but aren't listed in their respective help() functions.

Ideally there were an automated check to avoid such problems to re-enter the code base.

**Comment by peterschrammel** [comment]
To reduce noise I'm in favour of a basic `--help` option and a complete `--help-full` (or any other suitable name).

**Comment by TGWDB** [comment]
This is a goal to achieve indefinitely. I'm closing this as it's extremely old, but if there are specific missing options now/in future please create an appropriate issue/PR.
