### ISSUE TITLE
A simple test that I failed to verify

### ISSUE THREAD

**Issue by wcventure** [diffblue/cbmc#5471]
CBMC version: 5.12.6 (cbadaa5)
Operating system: Linux DESKTOP-E4CE6JE 4.4.0-18362
Exact command line resulting in the issue: `cbmc ./test.c --function test --unwind 20`
What behaviour did you expect: 
`line 14 return value is -1: SUCCESS`
`line 14 return value is 0: SUCCESS`
What happened instead: 
`line 14 return value is -1: SUCCESS`
`line 14 return value is 0: FAILURE`

Dear all,
When I try to use CBMC to verify my function, I get FAILURE. 
Could you help me to find out what happened?

Here is my simple function. I make an assumption and I expect that CBMC can give me "assertion SUCCESS". I use the command `cbmc ./test.c --function test --unwind 20`. But the result is FAILURE. Why?

```C
int test(const int*s, unsigned int len)
{
	// case 0
	__CPROVER_assume(__CPROVER_r_ok(s, len) && len > 0 && __CPROVER_forall {unsigned int i; 0 <= i && i <= len && s[i]!=10 && s[i]!=20});

	int ret = 0;
	unsigned int i, j;
	for (i = 0; i < (len + 1); i++){
		if (s[i] == 10 || s[i] == 20)
			ret = -1;
	}
	
	// case 0
	__CPROVER_assert(ret==0, "return value is 0");
	
	return ret;
}
```

However, when I change the __CPROVER_assume and __CPROVER_assert to another case (ret == -1), the result can become TRUE. That is interesting. Why the first case can be FAILURE?
```C
int test(const int*s, unsigned int len)
{
	// case -1
	__CPROVER_assume(__CPROVER_r_ok(s, len) && len > 0 && __CPROVER_exists {unsigned int i; 0 <= i && i <= len && (s[i]==10 || s[i]==20)});

	int ret = 0;
	unsigned int i, j;
	for (i = 0; i < (len + 1); i++){
		if (s[i] == 10 || s[i] == 20)
			ret = -1;
	}
	
	// case -1
	__CPROVER_assert(ret==-1, "return value is -1");
	
	return ret;
}
```

**Comment by danielsn** [comment]
`__CPROVER_r_ok` has weird behaviour inside assumes.  This is a known issue. Try using --pointer-primitive-check to see if that's what is going on. Also try turning on unwinding assertions - its possible your unwind bounds are not strong enough.

**Comment by wcventure** [comment]
I try to use --pointer-primitive-check to see if that's what is going on.
`cbmc ./test.c --function test --unwind 25 --pointer-primitive-check`

The output is:
```
** Results:
./testM.c function test
[test.pointer_primitives.1] line 4 pointer in pointer primitive is neither null nor valid in R_OK((const void *)s, (__CPROVER_size_t)len): SUCCESS
[test.assertion.1] line 14 return value is 0: FAILURE

** 1 of 2 failed (2 iterations)
VERIFICATION FAILED
```

Could you help me to find out how to use cbmc to verify this simple function?
Also,  If I don't want to divide my program into two versions (case 0 and case -1). Can I handle them using one primitive in one version?

**Comment by tautschnig** [comment]
Attending to this more than a year later, and you've obviously since played with support for contracts: CBMC does not auto-generate objects for pointers that are passed to the top-level function. You can use `goto-harness` to accomplish this, or else manually write a verification harness that performs `malloc(sizeof(int) * len)`. If you're still interested in this example, can you let us know whether this addresses your problem?

**Comment by wcventure** [comment]
My problem has been solved. Thank you very much
