### ISSUE TITLE
Cprover should have an `__enum_in_range` primitive

### ISSUE THREAD

**Issue by danielsn** [diffblue/cbmc#5473]
It is currently difficult to use the `--enum-range-check` option, because it is hard to ensure in a harness that an enum is within range. IF there was a 
`__CPROVER_enum_is_in_range(e)` primitive, we could use it like 
`__CPROVER_assume(__CPROVER_enum_is_in_range(e))`
and 
`assert(__CPROVER_enum_is_in_range(e))`

**Comment by feliperodri** [comment]
@hannes-steffenhagen-diffblue is there anyone currently working on this issue? Any updates?

**Comment by TGWDB** [comment]
See [pull request here](https://github.com/diffblue/cbmc/pull/5808).

**Comment by TGWDB** [comment]
Fixed in https://github.com/diffblue/cbmc/pull/5808
