### ISSUE TITLE
Unexpected result with __CPROVER_w_ok and function pointers

### ISSUE THREAD

**Issue by feliperodri** [diffblue/cbmc#5477]
CBMC version: 5.12 (cbmc-5.12-507-gb0b322501)
Operating system: Ubuntu 18.04.3 LTS
Exact command line resulting in the issue: `make veryclean && make report`in the `/home/ubuntu/s2n/tests/cbmc/proofs/s2n_set_new`
What behaviour did you expect: At least 90% coverage results using (https://github.com/awslabs/aws-viewer-for-cbmc).
What happened instead: Coverage drops to 11% when checking a function pointer with `__CPROVER_w_ok`

In branch [diffblue_cprover_w_ok_function_ptr](https://github.com/feliperodri/s2n/tree/diffblue_cprover_w_ok_function_ptr), run `make veryclean && make report` in the proof harness located at `/home/ubuntu/s2n/tests/cbmc/proofs/s2n_set_new`. Assuming that you have [viewer](https://github.com/awslabs/aws-viewer-for-cbmc) installed, you'll get a coverage report with 11% coverage. CBMC cannot reach anything after the checking a function pointer with `__CPROVER_w_ok`.

**Comment by hannes-steffenhagen-diffblue** [comment]
I'm sorry, I'm having a hard time figuring out what exactly you are referring to. I don't see how the steps you are describing relate to `__CPROVER_w_ok` or function pointers. Also, I am not completely sure what behaviour you are expecting from `__CPROVER_w_ok` here – I would not expect that _either_ `__CPROVER_w_ok` _nor_`__CPROVER_r_ok` would work with function pointers at all, because function pointers are _not_ like regular pointers into memory.

In particular, in the absence of self-modifying code (which we cannot model in cbmc AFAIK) functions should _never_ be writable, so `__CPROVER_w_ok` should always fail even _if_ function pointers were like regular memory pointers (which again, they are not, neither in cbmc's memory model nor indeed in the C language itself).

The cprover memory primitives are mostly meant for internal use and very easy to misuse. If you _must_ use them, please refer to http://cprover.diffblue.com/memory-primitives.html

**Comment by feliperodri** [comment]
We were expecting that `__CPROVER_w_ok` or `__CPROVER_r_ok` would detect if the pointer is a function pointer and perform a simple nullness check on it, instead of always returning null. That way, we could have some consistency when checking nullness for all function parameters. Right now, s2n uses a macro called `notnull_check_ptr`, which is basically implemented as
```c
#ifdef CBMC
#    define S2N_OBJECT_PTR_IS_READABLE(ptr) S2N_MEM_IS_READABLE((ptr), sizeof(*(ptr)))
#    define S2N_OBJECT_PTR_IS_WRITABLE(ptr) S2N_MEM_IS_WRITABLE((ptr), sizeof(*(ptr)))
#    define S2N_MEM_IS_READABLE(base, len) (((len) == 0) || __CPROVER_r_ok((base), (len)))
#    define S2N_MEM_IS_WRITABLE(base, len) (((len) == 0) || __CPROVER_w_ok((base), (len)))
#else
/* the C runtime does not give a way to check these properties,
 * but we can at least check that the pointer is valid */
#    define S2N_OBJECT_PTR_IS_READABLE(ptr) ((ptr) != NULL)
#    define S2N_OBJECT_PTR_IS_WRITABLE(ptr) ((ptr) != NULL)
#    define S2N_MEM_IS_READABLE(base, len) (((len) == 0) || (base) != NULL)
#    define S2N_MEM_IS_WRITABLE(base, len) (((len) == 0) || (base) != NULL)
#endif /* CBMC */
```

In this case, we have the following function
```c
struct s2n_set *s2n_set_new(uint32_t element_size, int (*comparator)(const void*, const void*))
{
    notnull_check_ptr(comparator);
    struct s2n_blob mem = {0};
```

Therefore, our coverage for this function was always low because CBMC always returns in the first `notnull_check_ptr(comparator)` check (it always return false). @danielsn, in this case, should we create another macro specific for function pointers? @hannes-steffenhagen-diffblue Any thoughts?

**Comment by feliperodri** [comment]
We concluded we can't check for nullness of function pointers using CPROVER memory primitives.

**Comment by martin-cs** [comment]
@feliperodri I haven't been following this one closely so this may be stupid but you should be able to `assert(comparator == NULL)`.  At one point there was a patch that added this check to the end of any dispatch chain created by remove function pointers.

**Comment by feliperodri** [comment]
@martin-cs in our project, we were checking for nullness using the following macro
```c
#define S2N_MEM_IS_READABLE(base, len) (((len) == 0) || __CPROVER_r_ok((base), (len)))
```
So, you're right that I could simply be able to `assert(comparator == NULL)`, but my original question was if I was able to `__CPROVER_r_ok(comparator, sizeof(comparator))` or something similar. I have created now a specific macro to deal with function pointers using the former.

**Comment by martin-cs** [comment]
@feliperodri thanks for the explanation and glad to hear you got something working.
