### ISSUE TITLE
Parsing Errors when compiling C++ 

### ISSUE THREAD

**Issue by tegansb** [diffblue/cbmc#5489]
CBMC version: 5.13.0 
Operating system: macOS Catalina 
Exact command line resulting in the issue: cbmc test.cpp
where test.cpp is 
```C
#include <functional>
int main() {
    std::function<void()> report_success;
}
```

What behaviour did you expect: Parsing to succeed. 
What happened instead:
```
file /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/type_traits line 2233: parse error before '__decltype ( ( std'
file /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/type_traits line 4912: parse error before '} typedef signed char'
file /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/exception line 262: parse error before '__attribute__ ( ( noreturn'
file /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/exception line 271: parse error before '} ; template <'
file /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/exception line 275: parse error before '__attribute__ ( ( noreturn'
file /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/exception line 284: parse error before '} ; template <'
file /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/exception line 335: parse error before '} namespace std {'
file /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cstdint line 188: parse error before '} } namespace std'
file /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/typeinfo line 170: parse error before '} ; struct __unique_impl'
file /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/typeinfo line 266: parse error before '} ; class __attribute__'
PARSING ERROR
```

I encountered parsing errors when trying to compile C++ code. I have attached a minimal example, replicating the issue.

**Comment by martin-cs** [comment]
Thanks for the bug report.  The C++ parser does not handle more modern and template-heavy C++, this means it often runs into problems with parts of the standard library.  To the best of my knowledge there is no one working on this at the moment.  I think @peterschrammel was the last person to put serious work into it but that was some time ago.

**Comment by hannes-steffenhagen-diffblue** [comment]
Closing this for now as improvements to the C++ frontend that would allow this code to compile, while desirable, are very far off from our end. As of now this is expected.

**Comment by martin-cs** [comment]
@hannes-steffenhagen-diffblue instead of just closing this, could we add it as a `KNOWNBUG` so that if and when there are people to work on this, they have a starting point?
