### ISSUE TITLE
Build fails with Apple Clang 12 (clang-1200.0.32.2) due to use of reference types

### ISSUE THREAD

**Issue by mina1604** [diffblue/cbmc#5501]
Clang build fails due to the -WError flag, resulting in -Wrange-loop-analysis warnings being shown as errors. 
The issue arises in multiple files due to the use of `auto` instead of `auto&` since the compiler expects a non reference type for places where one iterates over a loop in such a way that creates a proxy/copy of the elements instead of a reference to the elements themselves.
e.g.

`
src/util/graph.h:635:20: error: loop variable 'succ' of type 'const std::__1::pair<const unsigned long, empty_edget>' creates a
      copy from type 'const std::__1::pair<const unsigned long, empty_edget>' [-Werror,-Wrange-loop-analysis]
    for(const auto succ : succs)`

CBMC version: 5.14.1 (cbmc-5.14.1-dirty)
Operating system: MacOS Catalina 10.15.6
Exact command line resulting in the issue: cmake --build build
What behaviour did you expect: building without errors
What happened instead: build fails

**Comment by hannes-steffenhagen-diffblue** [comment]
Thanks for reporting this. Yeah, this is a bit of an annoying issue. Workaround is obviously temporarily disabling -Werror (for CMake builds we set the flag in our root `CMakeLists.txt`, for Make builds we do it in `src/config.inc`)
