### ISSUE TITLE
Improve `check_for_looped_mallocs` in code contracts to use natural loops

### ISSUE THREAD

**Issue by feliperodri** [diffblue/cbmc#5530]
CBMC version: `>5.15`
Operating system: Ubuntu 18.04 or macOS Mojave 10.14.6
Exact command line resulting in the issue: N/A.
What behaviour did you expect: N/A.
What happened instead: Use `natural_loops`, as is done, e.g., in `dump_c`. That will directly provide you with a loop body, which can then be searched for those function calls.

Suggested in https://github.com/diffblue/cbmc/pull/5403.

**Comment by feliperodri** [comment]
We should only update `checked_for_looped_malloc` once issue https://github.com/diffblue/cbmc/issues/6168 is resolved.

**Comment by SaswatPadhi** [comment]
#6168 is now resolved and the fix has been merged, so may be we can take another look at this issue now.
