### ISSUE TITLE
Running compiled cbmc on Darwin/ARM64 violates 2 invariants

### ISSUE THREAD

**Issue by jeanparker** [diffblue/cbmc#5627]
CBMC version: 5.18.0
Operating system: macOS 11.0.1
Exact command line resulting in the issue: ./cbmc
What behaviour did you expect: No errors 
What happened instead: 
Invariant check failed
File: config.cpp:1035 function: set
Condition: ansi_c.char_is_unsigned == (static_cast<char>(255) == 255)
Reason: char_is_unsigned flag shall indicate system char unsignedness

Another invariant check will fail for the long double size since Apple implements some fundamental types of the C language  slightly different on ARM64:
https://developer.apple.com/documentation/xcode/writing_arm64_code_for_apple_platforms#//apple_ref/doc/uid/TP40013702-SW1

**Comment by tautschnig** [comment]
Thank you very much for your report. This should be fixed by #5628, but I don't currently have access to such a system to confirm this works as expected. Therefore, testing would be much appreciated!

**Comment by jeanparker** [comment]
Thanks, that was quick.
I tested the PR locally and the issue is gone.
