### ISSUE TITLE
filter_lint_by_diff fails on deleted files

### ISSUE THREAD

**Issue by tautschnig** [diffblue/cbmc#563]
I'm seeing the below assertion on #166 and others - and I'm led to believe this is happening whenever files are deleted.

The linter output is below (empty output means no errors).
Traceback (most recent call last):
  File "scripts/filter_lint_by_diff.py", line 18, in <module>
    assert filename.startswith("b/")
AssertionError

Best,
Michael

**Comment by smowton** [comment]
Fix in https://github.com/diffblue/cbmc/pull/564
