### ISSUE TITLE
Variable sensitivity ­– functions shouldn’t affect value of globals they don’t write to

### ISSUE THREAD

**Issue by hannes-steffenhagen-diffblue** [diffblue/cbmc#5653]
Take this test example:

```
int global = 0;
void remember(void) { }
int main(void) {
  remember();
  global = 1;
  remember();
  assert(global == 1);
}
```

We would expect the assertion to pass... but it doesn’t because `remember` has seen the state of `global` once and forevermore reports it back to us. I believe @martin-cs had some ideas for fixing this in a sound way in the past?

**Comment by martin-cs** [comment]
Try out `--three-way-merge --vsd --vsd-data-dependencies`, it is designed for exactly this use case and should work. There is some regression tests that demonstrate it.  The paper on the Toyota system has some of the description.  I believe that it has been independently invented as "sparse abstract interpretation".

**Comment by hannes-steffenhagen-diffblue** [comment]
Forgot about that!
