### ISSUE TITLE
CBMC does not ignore the is_padding comment on datatype fields

### ISSUE THREAD

**Issue by danielsn** [diffblue/cbmc#5818]
On a datatype_parameter, the field is marked with the following named sub if its padding
```
                    "#is_padding": {
                      "id": "1"
                    },
```

CBMC appears to consider two structs to have different types if they agree on all fields, but disagree on which ones have the `#is_padding` comments. Aren't comments supposed to be ignored when comparing equality?

**Comment by tautschnig** [comment]
On a second look, this doesn't seem to be `#is_padding` that's causing trouble. It's #5815, again, as a padding member looks like this:
```
    2:
      * type: unsignedbv
          * width: 24
      * #is_padding: 1
      * name: $pad2
``` 
Note the absence of `pretty_name`, which the C front-end otherwise does always seem to set.

**Comment by jimgrundy** [comment]
Dropping AWS label after review with @danielsn as there is no particular AWS interest.
