### ISSUE TITLE
Feature request: Saturating arithmatic

### ISSUE THREAD

**Issue by danielsn** [diffblue/cbmc#5841]
It would be really useful to have saturating arithmetic primitives in CBMC

**Comment by martin-cs** [comment]
This should be reasonably do-able but it would be good to know a bit more about what you want.  Are you using the internal back-end or an SMT solver?  Do you want signed or unsigned?  Do you have a particular implementation / system in mind?  What about the edge cases involving the limit value(s); what is LIMIT * 0, what is LIMIT / 0 or 0 / LIMIT?

**Comment by peterschrammel** [comment]
@danielsn, can you give a code example of a use case?

**Comment by martin-cs** [comment]
Note that https://github.com/diffblue/cbmc/issues/5405 would give a relatively simple and probably pretty good route to implementing them.

**Comment by danielsn** [comment]
I'm trying to implement operations like these: 
I'm trying to implement these:
https://doc.rust-lang.org/std/intrinsics/fn.saturating_add.html
https://doc.rust-lang.org/std/intrinsics/fn.saturating_sub.html
https://doc.rust-lang.org/std/primitive.u32.html#method.saturating_mul
