### ISSUE TITLE
Reduce number of variables in cnf

### ISSUE THREAD

**Issue by sbelodon** [diffblue/cbmc#5850]
Hi all,

I tried t generate cnf for simple code
`#include <assert.h>

int main() {
    char x;

    assert ((x&1)==0);
}`

**And it contains 17 variables:**

cbmc main.c
CBMC version 5.10 (cbmc-5.10) 64-bit x86_64 linux
Parsing main.c
Converting
Type-checking main
Generating GOTO Program
Adding CPROVER library (x86_64)
Removal of function pointers and virtual functions
Generic Property Instrumentation
Running with 8 object bits, 56 offset bits (default)
Starting Bounded Model Checking
size of program expression: 32 steps
simple slicing removed 5 assignments
Generated 1 VCC(s), 1 remaining after simplification
Passing problem to propositional reduction
converting SSA
Running propositional reduction
Post-processing
Solving with MiniSAT 2.2.1 with simplifier
**17 variables**, 13 clauses
SAT checker: instance is SATISFIABLE
Runtime decision procedure: 0.000493579s

**_Is there a way to reduce number of vars to 8?  (char is 8-bit type)_**
I'm asking because solver will be faster with less variables count.

**Comment by martin-cs** [comment]
Theoretically : yes.
Implementable : maybe.
Worth doing : probably not.

I don't know how much of this you already know so please forgive me if I am telling you things you consider basic.

1. CBMC (and other similar tools) use Boolean variables for a lot more than just variables.  They are used to represent path conditions / where is reachable.  They are used to represent assertion conditions.  The vast majority are used in expressing the operators, in this case '&' and '=='.  So your base number of `CHAR_BIT` variables  is a lower bound.  If you run with `--show-vcc` you will see the formulae that are being passed to the solver.
2. All modern SAT and SMT solvers have extensive preprocessing.  Often it is better to generate a more verbose, but simpler formula and let the preprocessor sort it out.  This is especially true if the smaller formulae requires complex code.
3. "Fewer variables solves faster" is, often true but TBH the performance of modern solvers is not well correlated with the number of variables.  It is often a much smaller factor than other things.

If you want to have a look at the variables and clause it generates, then use `--dimacs`.  It could be we are missing something in bit-wise propagation in the solver.

**Comment by martin-cs** [comment]
A few more thoughts:

- 5.10 is quite an old version; you might want to try with something more modern.
- `1` and `0` are both `int`s so evaluating the expression requires type promotion of `x`.
- `--slice-formula` is useful because it allows you to focus on the relevant parts of the formula generated.

**Comment by martin-cs** [comment]
Adding a return value (so that CBMC does not create a non-deterministic one, using another 32 bits) and using `--slice-formula` on a modern version of CBMC I get:

```
$ cat ~/tmp/can-delete/char.c
#include <assert.h>

int main() {
  char x;

  assert ((x&1)==0);

  return 0;
}

$ ./cbmc/cbmc ~/tmp/can-delete/char.c  --slice-formula
CBMC version 5.23.0 (cbmc-5.23.0-68-g6d11346ac4) 64-bit x86_64 linux
Parsing /home/martin/tmp/can-delete/char.c
Converting
Type-checking char
Generating GOTO Program
Adding CPROVER library (x86_64)
Removal of function pointers and virtual functions
Generic Property Instrumentation
Running with 8 object bits, 56 offset bits (default)
Starting Bounded Model Checking
Runtime Symex: 0.00162571s
size of program expression: 43 steps
slicing removed 20 assignments
Generated 1 VCC(s), 1 remaining after simplification
Runtime Postprocess Equation: 4.2057e-05s
Passing problem to propositional reduction
converting SSA
Runtime Convert SSA: 0.000157004s
Running propositional reduction
Post-processing
Runtime Post-process: 1.2891e-05s
Solving with MiniSAT 2.2.1 with simplifier
9 variables, 2 clauses
SAT checker: instance is SATISFIABLE
Runtime Solver: 0.000101225s
Runtime decision procedure: 0.000321796s

** Results:
/home/martin/tmp/can-delete/char.c function main
[main.assertion.1] line 6 assertion (x&1)==0: FAILURE

** 1 of 1 failed (2 iterations)
VERIFICATION FAILED
```

I suspect the extra variable is used to hold the value of the comparison.

**Comment by sbelodon** [comment]
thanks for the info!
