### ISSUE TITLE
Weird interactions between position of declarations and goto statements  

### ISSUE THREAD

**Issue by sree314** [diffblue/cbmc#5864]
CBMC version: 5.10 and 5.11
Operating system: Linux (Ubuntu 20.04LTS and 18.04LTS)
Exact command line resulting in the issue: cbmc --function d --trace --c99 /tmp/test2.c
What behaviour did you expect: All assertions should pass.
What happened instead: Two assertions fail.

I'm using CBMC to verify three-address code generated by student assignments. This example is one in which short-circuiting must be handled correctly:

```c
#include <stdio.h>
#include <assert.h>

void d(int x, int y, int z)
{
  x = 3;
  y = 5;
  z = 0;

  unsigned int t0 = x > y;
  if (t0 == 0)
    goto FALSE_LABEL_0;

  unsigned int t1 = y / z;
  unsigned int t2 = t1 > 2;
  unsigned int t3 = t2;
  goto END_LABEL_1;
  FALSE_LABEL_0:
  ;

  t3 = t0;
  END_LABEL_1:
  ;

  if (t3 == 0)
    goto FALSE_LABEL_2;

  z = 1;
  goto END_IF_LABEL_3;
  FALSE_LABEL_2:
  ;

  END_IF_LABEL_3:
  ;

  ;
  assert(z != 1);
  assert(z == 0);
  assert(x == 3);
  assert(y == 5);
}

int main() {
  d(0, 0, 0);
}
```

Here the z != 1 and z == 0 assertions fail. We tracked it down to the fact that the declaration for `unsigned int t3 = t2` is "skipped". If we move the declaration of `t3` to the top of the file as:

```c
void d(int x, int y, int z)
{
  x = 3;
  y = 5;
  z = 0;
  unsigned int t3;
  unsigned int t0 = x > y;
  ...
  t3 = t2;
  goto END_LABEL_1;
}
```
then all assertions pass. Alternatively, simply jumping to `END_IF_LABEL_3` instead of `FALSE_LABEL_0` in the first goto also fixes the problem. 

I can see why jumping over a declaration/definition might be wrong, but could find no reference to confirm this is verboten. GCC 9.3 compiles this code fine without any complaints.

**Comment by tautschnig** [comment]
Thank you for your detailed report! It seems that the bug was fixed in eaa7d93ac, which is part of CBMC 5.12 (and any later version).
