### ISSUE TITLE
Ubuntu 18.04 deb depends on libgcc-s1 which isn't in 18.04, it should depend on libgcc1 instead

### ISSUE THREAD

**Issue by sree314** [diffblue/cbmc#5875]
CBMC version: 5.24 (also older packages)
Operating system: Ubuntu 18.04
Exact command line resulting in the issue: dpkg -i ubuntu-18.04-cbmc-5.24.0-Linux.deb
What behaviour did you expect: CBMC gets installed
What happened instead: dpkg returns: cbmc : Depends: libgcc-s1 (>= 3.4) but it is not installable

libgcc-s1 isn't in Ubuntu 18.04: https://packages.ubuntu.com/search?suite=xenial&arch=amd64&keywords=libgcc-s1
Update: Sorry, Ubuntu 18.04 is bionic, not xenial: https://packages.ubuntu.com/search?suite=bionic&arch=amd64&keywords=libgcc-s1

The file libgcc_s.so.1 does exist, but is provided by the libgcc1 library in 18.04.

I tried manually extracting and running cbmc, and it does seem to work, so `dpkg -i --force-depends` should work.

**Comment by martin-cs** [comment]
Thanks for the bug report, this should be a reasonably straight-forward fix.

**Comment by hannes-steffenhagen-diffblue** [comment]
We've been able to produce this over here. No fix yet, but it seems like the package is being built on the wrong ubuntu version somehow? If I create the packages locally from ubuntu-18.04 they work fine. The dependencies are determined by `dpkg-shlibdeps` instead of being specified manually.

**Comment by sree314** [comment]
Yeah, I looked at release-packages.yaml, but the labels all seem to check out. It could be a GitHub issue?

**Comment by sree314** [comment]
Reading this:

https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu1804-README.md

It's clear that GitHub's ubuntu-18.04 is not standard -- it includes g++-7.5 to g++-10 which aren't included in the base distribution.

The package is built using g++-7.5
```
strings cbmc | grep GCC:
GCC: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
```

which isn't part of Bionic AFAICT.

**Comment by hannes-steffenhagen-diffblue** [comment]
🤦 Ah, I did not realise this. That is... very unfortunate.

**Comment by sree314** [comment]
Yes, I think GitHub should document that their 18.04 images are suitable for _running_, not for building. I opened an issue and mentioned this there.
