### ISSUE TITLE
[RFC] CBMC architecture configuration uses architecture-specific int width

### ISSUE THREAD

**Issue by tautschnig** [diffblue/cbmc#5878]
CBMC version: 5.24 (b26d347967)
Operating system: any
Exact command line resulting in the issue: n/a
What behaviour did you expect: Linking together goto binaries built on different platforms is possible
What happened instead: When writing goto binaries, CBMC uses `int` to create constants like `__CPROVER_architecture_int_width`. It's not obvious that such platform configuration options should be in the symbol table at all, and if they should live in there, their types should likely not be architecture-specific. `configt` places no requirement on those types, and could easily deal with `ID_integer` typed constants.

This is mostly an RFC and a note for possible future clean-up. There is no currently-known use case that's blocked by the existing implementation.

**Comment by kroening** [comment]
Sure, happy to change to `integer` -- the reason to have these in the symbol table is to do the right thing when linking. For now, that could be to reject linking binaries from different platforms when the architecture differs, but in the future it is conceivable that the linker learns how to glue binaries from different architectures together.

**Comment by martin-cs** [comment]
Multi-language linking is a use-case that I have seen but I haven't yet seen multi-architecture.

**Comment by feliperodri** [comment]
@tautschnig are you aware of any PRs that concludes this discussion? Should we keep this issue open?
