### ISSUE TITLE
How to minimize the number of loop indexes?

### ISSUE THREAD

**Issue by feliperodri** [diffblue/cbmc#5905]
CBMC version: 5.25
Operating system: MacOS Catalina
Exact command line resulting in the issue: --
What behaviour did you expect: --
What happened instead: --

We need to specify which loop we want to unwind in the program, but they might have multiple index. Any changes in the source code might change the loop index. Usually we list all possible indexes, but even this set might change too.

```Makefile
UNWINDSET += strlen.0:$(shell echo $$((1 + $(MAX_STRING_LEN))))
UNWINDSET += s2n_hex_string_to_bytes.2:$(shell echo $$((1 + $(MAX_STRING_LEN))))
UNWINDSET += s2n_hex_string_to_bytes.3:$(shell echo $$((1 + $(MAX_STRING_LEN))))
UNWINDSET += s2n_hex_string_to_bytes.6:$(shell echo $$((1 + $(MAX_STRING_LEN))))
UNWINDSET += s2n_hex_string_to_bytes.9:$(shell echo $$((1 + $(MAX_STRING_LEN))))
UNWINDSET += s2n_hex_string_to_bytes.16:$(shell echo $$((1 + $(MAX_STRING_LEN))))
UNWINDSET += s2n_hex_string_to_bytes.12:$(shell echo $$((1 + $(MAX_STRING_LEN))))
UNWINDSET += s2n_hex_string_to_bytes.15:$(shell echo $$((1 + $(MAX_STRING_LEN))))
UNWINDSET += s2n_hex_string_to_bytes.17:$(shell echo $$((1 + $(MAX_STRING_LEN))))
```

Is there a way to have a 1:1 map from loop indexes with actual loops in the program?

You can take a look at this example https://github.com/aws/s2n-tls/tree/main/tests/cbmc/proofs/s2n_hex_string_to_bytes to see this problem.

**Comment by tautschnig** [comment]
@feliperodri Could you please elaborate what you mean by "but they might have multiple index?" Yes, changes to the source code can affect the loop identifier. Having a unique identifier for a loop (that is not affected by source code changes) may seem desirable, but it's not entirely obvious how that would work. Even the "actual loops" part is not entirely unambiguous: CBMC treats each backwards control-flow jump as a loop. Looking at https://github.com/aws/s2n-tls/blob/f1092c05843aa34d3bd2a9645b23609a8780625d/utils/s2n_blob.c#L106, I'm assuming that some of the macros expand to code involving loops?

**Comment by feliperodri** [comment]
@tautschnig Perhaps, having a unique identifier for a loop would be troublesome, but could we have an option to where CBMC automatically apply the same bound across all identifiers? I just want to make this specification less brittle. For example, could we have a rule that if we specify a bound for a loop without adding the identifier, CBMC would automatically apply this bound across all identifiers? So, instead of writing 
```Makefile
UNWINDSET += s2n_hex_string_to_bytes.2:$(shell echo $$((1 + $(MAX_STRING_LEN))))
UNWINDSET += s2n_hex_string_to_bytes.3:$(shell echo $$((1 + $(MAX_STRING_LEN))))
UNWINDSET += s2n_hex_string_to_bytes.6:$(shell echo $$((1 + $(MAX_STRING_LEN))))
UNWINDSET += s2n_hex_string_to_bytes.9:$(shell echo $$((1 + $(MAX_STRING_LEN))))
UNWINDSET += s2n_hex_string_to_bytes.16:$(shell echo $$((1 + $(MAX_STRING_LEN))))
UNWINDSET += s2n_hex_string_to_bytes.12:$(shell echo $$((1 + $(MAX_STRING_LEN))))
UNWINDSET += s2n_hex_string_to_bytes.15:$(shell echo $$((1 + $(MAX_STRING_LEN))))
UNWINDSET += s2n_hex_string_to_bytes.17:$(shell echo $$((1 + $(MAX_STRING_LEN))))
```
one would write
```Makefile
UNWINDSET += s2n_hex_string_to_bytes:$(shell echo $$((1 + $(MAX_STRING_LEN))))
```
then CBMC would apply the same bound across all identifiers. This would be a less fragile option for functions with only one loop. Is it feasible?

**Comment by feliperodri** [comment]
Closing this issue now that we have support for labels in loop unwinding set. See https://github.com/diffblue/cbmc/pull/6508
