### ISSUE TITLE
Some regression test runners fail to `clean`

### ISSUE THREAD

**Issue by SaswatPadhi** [diffblue/cbmc#5910]
**Exact command line resulting in the issue:** `make clean` within `regression/cbmc`
**What behaviour did you expect:** `.out`, `.gb`, `.log` files should be removed
**What happened instead:** `find: illegal option -- n`

Some of the `regression/<suite>/Makefile`s use a use a `find` command to recursively search and remove temporary files, e.g. in `regression/cbmc/Makefile` we have:
```bash
find -name '*.out' -execdir $(RM) '{}' \;
```
This statement raises a syntax error on Mac OS (and probably *nix in general?) because `find` is missing a path argument. The following works as expected:
```bash
find . -name '*.out' -execdir $(RM) '{}' \;
```

Some other `Makefile`s use a `for` loop to iterate over subdirectories and remove temporary files, but that would only clean up until depth 1, e.g. in `regression/goto-instrument/Makefile` we have:
```bash
	@for dir in *; do \
		$(RM) tests.log; \
		if [ -d "$$dir" ]; then \
			cd "$$dir"; \
			$(RM) *.out *.gb; \
			cd ..; \
		fi \
	done
```
If cleaning until depth 1 is sufficient, the `for` loop could be replaced by `$(RM) tests.log */*.out */*.gb`. If it's not, then the find command above could be used.

There needs to be a global pass over all the `regression/` subdirectories to fix the `clean` action in `Makefile`s.

**Comment by TGWDB** [comment]
Addressed in [PR 5943](https://github.com/diffblue/cbmc/pull/5943) .

**Comment by SaswatPadhi** [comment]
Thanks!
