### ISSUE TITLE
Wrong simplification in try_evaluate_pointer_comparison

### ISSUE THREAD

**Issue by brenoguim** [diffblue/cbmc#5921]
CBMC version: latest (downloaded the tip of today)
Operating system: Linux x86_64
Exact command line resulting in the issue: ./cbmc main.c
What behaviour did you expect: SUCCESS on the assertion
What happened instead: FAILURE

Hello,

I noticed an unexpected behavior in the symbolic execution and crafted a testcase to expose the behavior.
I'm pretty convinced this is a bug, but maybe I'm missing something.

```cpp
#include <stdlib.h>
#include <assert.h>

int* get_ptr_minus_one(int* ptr)
{
    if (ptr) return ptr - 1;
    return 0;
}

int main()                                                                                                              
{
    int *begin = malloc(4*4);
    int *end = begin + 1;

    if (begin != get_ptr_minus_one(end))
        assert(0);
}
```

One more detail that indicates this being a bug is that replacing `malloc(4*4)` by `malloc(4*sizeof(int))` makes the assertion correctly pass.

Since I already debugged this a bit, I'll share the details in case it helps. (Notice I'm new to the codebase so the analysis might be off).

When we have a pointer comparison in the branch condition, the function https://github.com/diffblue/cbmc/blob/51c59e9e06e204f84e1b35bf7ad75439185300d7/src/goto-symex/symex_goto.cpp#L224 kicks in

It eventually will look over the value set of `get_ptr_minus_one(end)`
https://github.com/diffblue/cbmc/blob/51c59e9e06e204f84e1b35bf7ad75439185300d7/src/goto-symex/symex_goto.cpp#L107

 and check if it could possibly match `begin`
 https://github.com/diffblue/cbmc/blob/51c59e9e06e204f84e1b35bf7ad75439185300d7/src/goto-symex/symex_goto.cpp#L132
 
 If none of those match, then the pointer could not possibly match:
 https://github.com/diffblue/cbmc/blob/51c59e9e06e204f84e1b35bf7ad75439185300d7/src/goto-symex/symex_goto.cpp#L143
 
 That means, the two inputs being compared should be normalized to make sure that they always match if they are in fact the same symbol.
 However, I noticed scenarios in which they were not "normalized" and crafted this testcase.
 
 In this scenario, we have the comparison between the `&symex_dynamic::dynamic_object1` with `&symex_dynamic::dynamic_object1[0]`.
 
 Since they are not equal, they do not "match" (but should), so the code will say that the two pointers cannot be equal, reducing the guard to true, and always reaching the `assert(0)`.

The print of the two pointers being compared are the following:
 ```
 address_of
  * type: pointer
      * width: 64
      0: array
          * size: constant
              * type: unsignedbv
                  * width: 64
                  * #typedef: size_t
                  * #c_type: unsigned_long_int
              * value: 10
          * #dynamic: 1
          0: unsignedbv
              * width: 8
              * #c_type: unsigned_char
  0: symbol
      * type: array
          * size: constant
              * type: unsignedbv
                  * width: 64
                  * #typedef: size_t
                  * #c_type: unsigned_long_int
              * value: 4
          * #dynamic: 1
          0: unsignedbv
              * width: 8
              * #c_type: unsigned_char
      * identifier: symex_dynamic::dynamic_object1
      * expression: symbol
          * type: array
              * size: constant
                  * type: unsignedbv
                      * width: 64
                      * #typedef: size_t
                      * #c_type: unsigned_long_int
                  * value: 10
              * #dynamic: 1
              0: unsignedbv
                  * width: 8
                  * #c_type: unsigned_char
          * identifier: symex_dynamic::dynamic_object1
      * #SSA_symbol: 1
      * L1_object_identifier: symex_dynamic::dynamic_object1
```

and this:

```
address_of
  * type: pointer
      * width: 64
      0: unsignedbv                                                                                                     
          * width: 8
          * #c_type: unsigned_char
  0: index
      * type: unsignedbv
          * width: 8
          * #c_type: unsigned_char
      0: symbol
          * type: array
              * size: constant
                  * type: unsignedbv
                      * width: 64
                      * #typedef: size_t
                      * #c_type: unsigned_long_int
                  * value: 4
              * #dynamic: 1
              0: unsignedbv
                  * width: 8
                  * #c_type: unsigned_char
          * identifier: symex_dynamic::dynamic_object1 
          * expression: symbol
              * type: array
                  * size: constant
                      * type: unsignedbv
                          * width: 64
                          * #typedef: size_t
                          * #c_type: unsigned_long_int
                      * value: 10
                  * #dynamic: 1
                  0: unsignedbv
                      * width: 8
                      * #c_type: unsigned_char
              * identifier: symex_dynamic::dynamic_object1
          * #SSA_symbol: 1
          * L1_object_identifier: symex_dynamic::dynamic_object1
      1: constant
          * type: signedbv
              * width: 64
              * #c_type: signed_long_int
          * value: 0  
```

**Comment by brenoguim** [comment]
@andreast271 you might want to watch this one

**Comment by tautschnig** [comment]
Thank you very much for the detailed bug report and the debugging. With all your diagnosis already done, I chose to use `simplify_expr` to facilitate the normalisation, and this nicely solves the problem (cf. #5922).
