### ISSUE TITLE
CPROVER primitive for invalid pointers

### ISSUE THREAD

**Issue by feliperodri** [diffblue/cbmc#5925]
CBMC version: 5.15.0
Operating system: macOS Mojave
Exact command line resulting in the issue: `cbmc main.c --pointer-primitive-check`
What behaviour did you expect: Check whether `ptr_sizeof` is a valid pointer BEFORE calling CPROVER memory primitives and avoid "pointer primitive check" errors.
What happened instead: Get "pointer primitive check" failures.

```c
#include <stdlib.h>

#define MEM_IS_WRITABLE(base, len) (((len) == 0) || __CPROVER_r_ok((base), (len)))
#define NEW_MEM_IS_WRITABLE(base, len) (__CPROVER_malloc_size != 0 && (((len) == 0) || __CPROVER_r_ok((base), (len))))

int main() {
  unsigned int sz;
  void *ptr = malloc(sz);

  unsigned int sz_sizeof;
  void *ptr_sizeof = malloc(sz_sizeof);

  assert(MEM_IS_WRITABLE(ptr,sz));
  assert(MEM_IS_WRITABLE(ptr_sizeof,sizeof(*ptr_sizeof)));
  assert(NEW_MEM_IS_WRITABLE(ptr,sz));
  assert(NEW_MEM_IS_WRITABLE(ptr_sizeof,sizeof(*ptr_sizeof)));
}
```

I want to create a macro to check whether a pointer is readable or writable without leading to pointer primitive failures. CBMC returns an invalid pointer for `malloc(0)` allocations. How to check whether a pointer is valid or not BEFORE calling memory primitives? For example,
```c
assert(MEM_IS_WRITABLE(ptr_sizeof,sizeof(*ptr_sizeof)));
```
Here, if `sz_sizeof == 0`, than `ptr_sizeof` is an invalid pointer and `sizeof(*ptr_sizeof)` is 1.

**Comment by tautschnig** [comment]
Why would `#define MEM_IS_WRITABLE(base, len) __CPROVER_r_ok((base), (len))` not do the trick?

As a side note, `sizeof(*pointer)` will always return the size of the data type, it won't bear any resemblance with the size of the underlying allocation. `sizeof(void) == 1` is a GCC-ism.

**Comment by feliperodri** [comment]
I was confused by the use of `sizeof(*pointer)`, thus, `#define MEM_IS_WRITABLE(base, len) __CPROVER_r_ok((base), (len))` will do the trick.
