### ISSUE TITLE
SIGSEGV in loop acceleration with z3

### ISSUE THREAD

**Issue by SaswatPadhi** [diffblue/cbmc#5947]
**CBMC version:** `develop`
**Operating system:** Mac OS
**Exact command line resulting in the issue:** `make` in `regression/acceleration` with `z3` installed
**What behaviour did you expect:** Regression tests to pass
**What happened instead:** 3 of the regression tests crash with segmentation fault

This was exposed in #5944.

When `z3` is installed, the regression tests fail.
When `z3` is not installed, the regression tests pass!

`goto-instrument` seems to silently ignore errors in running the SMT solver, and treats errors as an UNSAT result!

**Comment by SaswatPadhi** [comment]
I linked a PR that fixes the issue of solver errors being ignored, ~~and changes the default solver from Z3 to CPROVER_SMT2.~~

But I am leaving this issue open because we should debug z3 issues with loop acceleration code at some point in the future.

**Comment by thomasspriggs** [comment]
This should be fixed in https://github.com/diffblue/cbmc/pull/5944/commits/fa657acfb8e43161a0cceab9c8ed61a10193b31c

**Comment by thomasspriggs** [comment]
This has been fixed as part of https://github.com/diffblue/cbmc/pull/5944.
