### ISSUE TITLE
Unexpected Behavior from Nondeterministic Function Pointer

### ISSUE THREAD

**Issue by KVISDAOWNER** [diffblue/cbmc#5969]
**CBMC version**: 5.24.0 (cbmc-5.24.0)
**Operating system**: Ubuntu 20.04.1 LTS
**Exact command line resulting in the issue**: cbmc file.c  --trace
**What behaviour did you expect**:
`foo` is only reachable from the `some1_entry` call. `bar` is unreachable.
Or
`foo` is reachable from `some1_entry` call. `foo` and `bar` are both reachable  from `some2_entry` call since `some2` is nondeterministic.

**What happened instead**:
`foo` is reachable from `some1_entry` call.
`foo` is reachable from `some2_entry` call. 
But `bar` is not reachable from `some2_entry` call.

**Code**:
```
typedef void(func)(int);

void foo(int c)
{
	__CPROVER_printf("This is foo and c is %d", c);
	__CPROVER_assert(0, "Reachability");
}

void bar(int c)
{
	__CPROVER_printf("This is bar and c is %d", c);
	__CPROVER_assert(0, "Reachability");
}

int main()
{
	char* some1;
	char* some2;

	__CPROVER_assume(some1 == &foo);

	func* some1_entry = (func*)some1;
	func* some2_entry = (func*)some2;

	some1_entry(1);
	some2_entry(2); //this can also call foo? but not bar??

	__CPROVER_assert(0, "Reachability");
}
```

**Comment by tautschnig** [comment]
The address of `bar` is never taken in this program, thus we assume that function pointers cannot resolve to it. You might argue this is unsound, but then this program is full of undefined behaviour anyway. So I'm not entirely sure this should be changed.

**Comment by TGWDB** [comment]
As tautschnig said `cbmc` does not assume that a function pointer can resolve to any possible address anywhere. If you wish to assume that `some2` can point to either `foo` or `bar` you can use a code fragment such as:
```
int nondet;
if(nondet) {
  some2 = &foo;
} else P
  some2 = &bar;
}
```
This will non-deterministically allow `cbmc` to determine that `some2` could resolve to `bar` and also reference `bar` in the program more generally.

**Comment by KVISDAOWNER** [comment]
Thank you for your answers. 

I am trying to model a function pointer that can point to any possible function (to model memory tampering attacks). So in my case, I would have liked it to take into consideration every function, not just the ones whose address had been evaluated. This could also be argued as unsound since one should probably consider all possible addresses and not only the addresses of functions.  

Anyway, my way of working around this is by doing something like you suggested (Thanks!):
```
typedef void(func)(int);

void foo(int c)
{
  __CPROVER_printf("This is foo and c is %d", c);
  __CPROVER_assert(0, "Reachability");
}

void bar(int c)
{
  __CPROVER_printf("This is bar and c is %d", c);
  __CPROVER_assert(0, "Reachability");
}

int main()
{
  &bar; //workaround
    
  char* some1;
  char* some2;
    
  __CPROVER_assume(some1 == &foo);
    
  func* some1_entry = (func*)some1;
  func* some2_entry = (func*)some2;

  some1_entry(1);  //still only calls foo
  some2_entry(2);  //this can now call both foo and bar

  __CPROVER_assert(0, "Reachability");
}
```

**Comment by TGWDB** [comment]
Good to hear this has solved the main issue.

There has been some research into checking programs for arbitrary jumps to try and detect vulnerabilities. A few links below, but very broadly there are limits to how effective this can be with model checking (including bounded model checking or statistical model checking), and also whether this can be done on source code or needs to be on the binary (or hardware).
[Combined software and hardware fault injection vulnerability detection](https://link.springer.com/article/10.1007%2Fs11334-020-00364-5)
[An automated and scalable formal process for detecting fault injection vulnerabilities in binaries](https://onlinelibrary.wiley.com/doi/abs/10.1002/cpe.4794)
[SymPLFIED: Symbolic program-level fault injection and error detection framework](https://ieeexplore.ieee.org/document/4630118)
[Lazart: A Symbolic Approach for Evaluation the Robustness of Secured Codes against Control Flow Injections](https://ieeexplore.ieee.org/document/6823883)
Also feel free to contact me directly.

Closing this as I think the behaviour is understood and a workaround achieved. Please feel free to reopen if you believe this is in error.
