### ISSUE TITLE
parsing error: syntax error before `strtof32'

### ISSUE THREAD

**Issue by ligurio** [diffblue/cbmc#5978]
CBMC version: CBMC version 5.10 (cbmc-5.10) 64-bit x86_64 linux
Operating system: Ubuntu 20.04 x86_64
Exact command line resulting in the issue:
```
$ git clone https://github.com/nginx/nginx/
$ cd nginx
$  ./auto/configure
$ cbmc --trace --z3 --bounds-check --unwind 5 -I/home/sergeyb/sources/nginx/src/http/modules/ -I/home/sergeyb/sources/nginx/src/event/ -I/home/sergeyb/sources/nginx/src/http/ -I/home/sergeyb/sources/nginx/src/os/unix/ -I/home/sergeyb/sources/nginx/objs/ -I/home/sergeyb/sources/nginx/src/core --function ngx_http_parse_header_line src/http/ngx_http_parse.c
```
What behaviour did you expect: successful C sources parsing
What happened instead: parsing error

`/usr/include/stdlib.h`:
```
 138 
 139 #if __HAVE_FLOAT32 && __GLIBC_USE (IEC_60559_TYPES_EXT)
 140 extern _Float32 strtof32 (const char *__restrict __nptr,
 141                           char **__restrict __endptr)
 142      __THROW __nonnull ((1));
 143 #endif
 144 
```

**Comment by tautschnig** [comment]
Thank you for your report! Would you be able to use a more recent version than 5.10? (We're at 5.26.1 at present.) This problem was fixed with c937b3f6061132, which is part of 5.12 (and all subsequent versions).

**Comment by ligurio** [comment]
@tautschnig Thanks for answer! I built a latest version and it works fine.

**Comment by tautschnig** [comment]
That's good to hear! Note that you may be able to just use pre-built binaries from https://github.com/diffblue/cbmc/releases to save some time.
