### ISSUE TITLE
Various questions about the cbmc package in fedora

### ISSUE THREAD

**Issue by vmihalko** [diffblue/cbmc#6024]
As a maintainer of cbmc package in fedora, there are two questions I want to ask:

1. I added an option to use the system sat solver because of the Fedora packaging guidelines. If you'd like I can create a pull-request. 

Is the sat solver patched by you "better" than the system one? 

From your point of view, is there any recommended SAT solver which should be used by default?

2. There is GCC 11.0.1 in fedora-rawhide, while the actual version in your CI jobs is 9.3.0. This causes various errors and warnings in build process of CBMC in fedora.

Would you mind adding for example fedora-34 to your CI jobs, or anything with the newer version of GCC?

**Comment by martin-cs** [comment]
Thank you for getting in touch.  I hope @NlightNFotis and @thomasspriggs can help with the CI.  As regards SAT solvers... it depends on what the system one is.  CBMC's default solver is MiniSAT which is not particularly modern but produces very consistent performance.  It would not be an unreasonable thing to do for a package maintainer to build and ship with CaDiCaL for example.  As for your changes, how does it differ to `--external-sat-solver`?

**Comment by NlightNFotis** [comment]
Hi @vmihalko, some quick thoughts from me on item 2:

* A stable version of fedora on CI is something that we will consider internally, and potentially implement (prioritised, of course, against our other commitments),
* Support for bleeding-edge environments (like fedora-rawhide) or experimental/development tool versions (like gcc 11.0.1, currently) is in my opinion not a good idea for a CI target. My rationale for this is that there are just too many moving parts in an constantly changing environment which will potentially distract us (as we will get a higher number of failures in that job that are a number of environment changes, but which we will have to investigate nonetheless).

**Comment by vmihalko** [comment]
Sorry for the ambiguity in my previous comment. I meant the difference between the [fedora (system) `minisat`](https://src.fedoraproject.org/rpms/minisat2) and the `minisat` patched by you at `/scripts/minisat-2.2.1-patch`. Which of them would you recommend for usage with CBMC?

**Comment by martin-cs** [comment]
@vmihalko I believe the patch is only needed to avoid compiler warnings.  I do not think it should affect performance.  If it does it would be very interesting to know.

**Comment by vmihalko** [comment]
@NlightNFotis, I understand your rationale, and I'm glad to hear that you will consider the stable version of fedora. 

@martin-cs If there is no performance difference, then I'll keep using the fedora system `minisat`.

Thank you both, for quick answers.

**Comment by martin-cs** [comment]
@vmihalko Forgive me if I am telling you things you already know but:

```
MINISAT2=/path/to/fedora/minisat/source make -jN all 
```

should work without you needing to alter CBMC at all.

**Comment by tautschnig** [comment]
> @vmihalko Forgive me if I am telling you things you already know but:
> 
> ```
> MINISAT2=/path/to/fedora/minisat/source make -jN all 
> ```
> 
> should work without you needing to alter CBMC at all.

Except ... not really. https://sources.debian.org/src/cbmc/5.12-5/debian/patches/minisat-debian/ is the patch I'm carrying in the Debian package. Though also (un-)setting `MINISAT2_LIB=` on the command line might actually do the trick.

**Comment by thomasspriggs** [comment]
It seems like you have answers on the 2 versions of minisat and what is involved in using a different version. I am going to close this out for the moment, but please feel free to reopen if you have further questions.
