### ISSUE TITLE
CBMC Stops at Converting SSA with Program including non deterministic floating point addition. 

### ISSUE THREAD

**Issue by shosho613** [diffblue/cbmc#6039]
My goal is to get CBMC to output the logical formula for a program when the input to the program is a non deterministically generated floating point value.
However, I have found that when the program includes addition of nondeterministic floating point numbers, the CBMC process cannot move past the "Converting SSA" step.
Below is a sample program that reproduces this potential bug.
[failing_program.txt](https://github.com/diffblue/cbmc/files/6313273/failing_program.txt)

I've tried passing in different backend solvers besides z3, but to no avail.
I've also tried the following command(not passing in any backend solver in the command line): `cbmc test.c --floatbv --outfile clauses.txt`
In this case,  CBMC completes its run, but it states verification is failed and clauses.txt is left empty.
Below is the log for that command:
[no_backend_passed_output.txt](https://github.com/diffblue/cbmc/files/6313320/no_backend_passed_output.txt)

Please let me know if there is some other command I can use to produce the logical formula that can work with this sample program. Thank you!

------

CBMC version: 5.6
Operating system: Ubuntu 18.04.2 LTS (WSL)
Exact command line resulting in the issue: `cbmc test.c  --z3 --floatbv --outfile clauses.txt`
What behaviour did you expect: Output the logical formula generated by z3 to clauses.txt
What happened instead:
```
CBMC version 5.6 64-bit x86_64 linux
Parsing test.c
file <command-line> line 0: <command-line>:0:0: warning: "__STDC_VERSION__" redefined
<built-in>: note: this is the location of the previous definition
Converting
Type-checking test
Generating GOTO Program
Adding CPROVER library (x86_64)
Removal of function pointers and virtual functions
Partial Inlining
Generic Property Instrumentation
Starting Bounded Model Checking
size of program expression: 41 steps
simple slicing removed 6 assignments
Generated 1 VCC(s), 1 remaining after simplification
Passing problem to SMT2
converting SSA```

Lagged and stopped at converting SSA stage, never passed it.

**Comment by tautschnig** [comment]
Thank you for your report! Would you mind trying a version newer than 5.6 (we're at 5.28.0 at this point)? With 5.28.0, the above example appears to work just fine.

**Comment by shosho613** [comment]
Thank you so much! I tried with the latest version and everything seems to be working as expected. Thanks for your help.
