### ISSUE TITLE
CBMC 5.29 performance slow down

### ISSUE THREAD

**Issue by markrtuttle** [diffblue/cbmc#6072]
CBMC version: 5.24 and 5.25 (and 5.29)
Operating system: Ubuntu20
Exact command line resulting in the issue: see below
What behaviour did you expect: termination
What happened instead: nontermination

I'm experiencing a slow down with 5.29 that I can't explain.  It seems to develop between 5.24 and 5.25.  To reproduce,

```
git clone git@github.com:FreeRTOS/FreeRTOS.git
cd FreeRTOS
git submodule update --init --checkout --recursive
cd FreeRTOS/Test/CBMC/proofs
python3 ./prepare.py
cd Queue/QueueGenericCreate/config_QueueGenericCreate_default
```

The following finishes in seconds

```
curl -L https://github.com/diffblue/cbmc/releases/download/cbmc-5.24.0/ubuntu-20.04-cbmc-5.24.0-Linux.deb --output ubuntu-20.04-cbmc-5.24.0-Linux.deb
sudo dpkg -i ubuntu-20.04-cbmc-5.24.0-Linux.deb

make veryclean cbmc
```

The following does not finish within a few hours

```
curl -L https://github.com/diffblue/cbmc/releases/download/cbmc-5.25.0/ubuntu-20.04-cbmc-5.25.0-Linux.deb --output ubuntu-20.04-cbmc-5.25.0-Linux.deb
sudo dpkg -i ubuntu-20.04-cbmc-5.25.0-Linux.deb

make veryclean cbmc
```

If I add --flush to C_CBMCFLAGS in FreeRTOS/FreeRTOS/Test/CBMC/proofs/Makefile.common, I can see that it quickly gets to the point of invoking MiniSAT, but the solver takes a long time.

**Comment by tautschnig** [comment]
It seems that `--pointer-overflow-check` makes all the difference here. ~I'm working out the exact commit~ It's 3acdb52dd6e07f345dbce21ad8cac826b310580d that's causing the performance regression, which made pointer-overflow checks actually meaningful at all.

**Comment by tautschnig** [comment]
I do believe that CBMC is (now) generating the correct constraints, they are just hard to solve, caused by the pointer arithmetic in lines 273 and 276 of Source/queue.c. I'll try to figure out what exactly is making it so hard to solve these.

**Comment by tautschnig** [comment]
My understanding based on some further experiments is that it's the multiplications in those lines mentioned that's causing the slow down. There's still some room for improvement, but there might be little we can do about this (multiplication is known to be hard).

**Comment by NlightNFotis** [comment]
@tautschnig I have identified (and verified) that the commit introducing the regression is: https://github.com/diffblue/cbmc/commit/3acdb52dd6e07f345dbce21ad8cac826b310580d

Do you see anything suspect in this commit? I will look further into that, but if you have any intuition as to what in this PR might be causing problems I would be grateful.

EDIT: Ahh, I see you had identified the commit some days ago - apologies, I hadn't noticed that.

**Comment by NlightNFotis** [comment]
Okay, some more info, more useful this time:

It is the change in `goto_check.cpp` that is introducing the regression:
* Without it, I see verification successful in <1s, and the number of clauses and variables are `179807 variables, 666054 clauses`.
* With it, the regression manifests and the number of clauses and variables are now `193823 variables, 743268 clauses`.

**Comment by tautschnig** [comment]
Having discussed this with @kroening, I further confirmed that the multiplications in lines 273 and 276 of Source/queue.c really are multiplications of two values that intentionally are not constant (there's no failure of constant propagation). Non-linear arithmetic is known to be expensive.

We already have support for arithmetic refinement (`src/solvers/refinement/refine_arithmetic.cpp`), which can be enabled via `--refine`. It's marked as experimental, and I didn't get an immediately obvious benefit when trying to use it. But that's perhaps the most promising route, if someone has time to dig into this.

**Comment by NlightNFotis** [comment]
I did an experiment running this with CaDiCaL as the backend solver, and the results are similar.

**Comment by markrtuttle** [comment]
Closing as a known problem with the complexity of multiplication.
