### ISSUE TITLE
tests fail on parsing `noexcept` and `decltype` in c++17 mode

### ISSUE THREAD

**Issue by vmihalko** [diffblue/cbmc#6090]
CBMC version: 5.29
Operating system: Fedora 34
Exact command line resulting in the issue: `ctest -L CORE`
What behaviour did you expect: all tests pass
What happened instead: 
`Failed test:  regression/cpp/virtual1/`
```
/usr/include/assert.h:69:1: error: parse error before '( true ) __attribute__'
      __THROW __attribute__ ((__noreturn__));
/usr/include/stdio.h:146:1: error: parse error before '( true ) ;'
 extern int remove (const char *__filename) __THROW;
PARSING ERROR
```
`Failed test: regression/cpp/Method_qualifier1`
```
/usr/include/c++/11/x86_64-redhat-linux/bits/c++config.h:2434:1: error: parse error before '; } namespace std'
   typedef decltype(nullptr)        nullptr_t;
/usr/include/assert.h:69:1: error: parse error before '( true ) __attribute__'
      __THROW __attribute__ ((__noreturn__));
PARSING ERROR
```

The problem is with parsing the `noexcept` and `decltype` expressions.

The reason of this problem is GCC 11 uses c++17 by default. If I specify `goto-cc -std=c++14/11/03`, then the mentioned tests pass.

**Comment by martin-cs** [comment]
I don't have a GCC 11 handy so is there any chance you could see if this:

https://github.com/diffblue/cbmc/pull/6144

fixes the problem.

**Comment by lzaoral** [comment]
Hi @martin-cs! Sorry for bumping but I've tried the correct solution proposed in #6144. I've run into some problems that I have described in a commentary in the aforementioned PR.

**Comment by martin-cs** [comment]
Thanks @lzaoral I will chase them down there.  I think @tautschnig 's patch was better than #6144 .

**Comment by martin-cs** [comment]
See https://github.com/diffblue/cbmc/pull/6402
