### ISSUE TITLE
CBMC in SVComp 16

### ISSUE THREAD

**Issue by niyasc** [diffblue/cbmc#61]
Hi,

This is not an issue but just few queries regarding cbmc in svcomp16.

- Which version of cbmc was used in svcomp-16?
- What are the command line options used when running cbmc in svcomp?
- How can I reproduce same results?

**Comment by tautschnig** [comment]
Hi,
As for all SV-COMP participants, full information is provided on the (SV-COMP website)[http://sv-comp.sosy-lab.org/2016/systems.php]. In brief, CBMC is run from within a wrapper script that invokes CBMC with increasing loop bounds. Furthermore appropriate properties and 32/64 bit configurations need to be picked up per category -- all of which is taken care of by the script, which is included in the archive available from the SV-COMP website.

Best,
Michael
