### ISSUE TITLE
Not to optimize the goto program?

### ISSUE THREAD

**Issue by theyoucheng** [diffblue/cbmc#610]
Let us consider the following program
```
int f(int x)
{
  return x;
}

int main()
{
  int a, b, c;
  // the 1st if
  if(a>b && b>c) ;
  // the 2nd if
  if(f(a)>b && b>c) ;

  return 0;
}
```
The goto program for the ``main`` function is something in below
````
main /* main */
        // 2 file main.c line 8 function main
        signed int a;
        // 3 file main.c line 8 function main
        signed int b;
        // 4 file main.c line 8 function main
        signed int c;
        // 5 file main.c line 10 function main
        IF !(a > b && b > c) THEN GOTO 1
        // 6 file main.c line 12 function main
     1: signed int return_value_f$1;
        // 7 file main.c line 12 function main
        f(a);
        // 8 file main.c line 12 function main
        return_value_f$1 = f#return_value;
        // 9 file main.c line 12 function main
        dead f#return_value;
        // 10 file main.c line 12 function main
        IF !(return_value_f$1 > b) THEN GOTO 2
        // 11 file main.c line 12 function main
        IF !(b > c) THEN GOTO 2
        // 12 file main.c line 14 function main
     2: main#return_value = 0;
        // 13 file main.c line 14 function main
        dead return_value_f$1;
        // 14 file main.c line 14 function main
        dead c;
        // 15 file main.c line 14 function main
        dead b;
        // 16 file main.c line 14 function main
        dead a;
        // 17 file main.c line 15 function main
        END_FUNCTION
````
The two 'if' statements in the `main` function have two different control structures in the goto program. It seems that when there is function call inside, the 'if' statement has been optimized. Is there a way to disable this kind of 'optimization'?

**Comment by tautschnig** [comment]
What do you mean by "optimized" - transformed, into two `if` statements? Can you (manually) write down the goto program you'd like to see?

**Comment by theyoucheng** [comment]
For the second 'if', ideally I would like to have the goto statement in the form of
````
        IF !(return_value_f$1 > b && b > c) goto 2
````
Any way I can achieve this, instead of breaking it into two 'IF's as it is currently done?

**Comment by tautschnig** [comment]
It seems the ordering in which cleaning expressions and rewriting them may need to be changed, or rather their interplay. Take a look at `goto_convertt::convert_ifthenelse`.

**Comment by theyoucheng** [comment]
Thanks, Michael! ``goto_convert::convert_ifthenelse`` is the right place to solve the problem.

**Comment by martin-cs** [comment]
On Sun, 2017-03-12 at 10:32 -0700, Youcheng Sun wrote:
> Thanks, Michael! ``goto_convert::convert_ifthenelse`` is the right place to solve the problem.

Ummm... be careful here; we shouldn't be changing the semantics of C...

**Comment by peterschrammel** [comment]
Question has been answered. Not sure anything came out of that. Closing.
