### ISSUE TITLE
windows error

### ISSUE THREAD

**Issue by yum7777** [diffblue/cbmc#6124]
Hi

i got error

```
cbmc.exe file1.c
CBMC version 5.30.0 (cbmc-5.30.0) 64-bit x86_64 windows
Parsing file1.c
The specified file could not be found.
CL Preprocessing failed
PARSING ERROR
```

**Comment by TGWDB** [comment]
Can you please provide more information. If `file1.c` in the right place? Does it `#include` other files that may be needed by `cbmc`? It would help us a lot if you can provide everything we need to reproduce the error.

**Comment by yum7777** [comment]
Hi @TGWDB 

I downloaded and tested the files in the tutorial.

Ref : https://raw.githubusercontent.com/diffblue/cbmc/develop/doc/cprover-manual/file1.c
http://www.cprover.org/cprover-manual/cbmc/tutorial/

**Comment by yum7777** [comment]
and i install Visual C++ redistributables

https://aka.ms/vs/16/release/vc_redist.x64.exe

**Comment by NlightNFotis** [comment]
Hi, @yum7777, the error message you shown us indicates that CBMC cannot find the file and open it for analysis.

Can you try passing the absolute file path to CBMC and tell us how it responds then? If it still fails, can you try opening the file using the absolute file path with another tool, say, `type`, to make sure that the file exists and is accessible from that path?

**Comment by NlightNFotis** [comment]
Closing this as we are lacking information to move forward with this.

If you think the problem persists, feel free to reopen the issue.
