### ISSUE TITLE
Analysis of file fails with exception thrown: byte_extract flatting with non-constant size: byte_extract_little_endian

### ISSUE THREAD

**Issue by NlightNFotis** [diffblue/cbmc#613]
Hello,

Testing `cbmc` on the MinisatC sources, I found out that for some functions, `cbmc` completely bugs out during analysis, throwing an exception with the following message: `byte_extract flatting with non-constant size: byte_extract_little_endian`.

This can be demonstrated by running the following command `cbmc --cover location --depth 1000 --function vecp_push vecp.c` on the following minimal test file (vecp.c) I have adapted from the minisat-c  sources:

```
#include <stdlib.h>
#include <stdio.h>

typedef struct vecp_t {
  int size;
  int cap;
  void **ptr;
} vecp;

static void vecp_new (vecp *new)
{
  new->size = 0;
  new->cap = 4;
  new->ptr = (void**) malloc(sizeof (void*)*new->cap);
}

static void vecp_delete (vecp *v)
{
  free(v->ptr);
}

static void** vecp_begin (vecp *v)
{
  return v->ptr;
}

static int vecp_size (vecp *v)
{
  return v->size;
}

static void vecp_resize (vecp *v, int k)
{
  v->size = k;
}

static void vecp_push (vecp *v, void *e)
{
  if (v->size == v->cap) {
    int newsize = v->cap * 2+1;
    v->ptr = (void**)realloc(v->ptr, sizeof(void*)*newsize);
    v->cap = newsize;
  }
  v->ptr[v->size++] = e;
}

void another (void)
{
   vecp something = {0, 0, NULL};
   vecp_new(&something);
   int b = 5;
   int *a = &b;
   vecp_push(&something, a);
}


int main (int argc, char **argv[])
{
   another();
   return 0;
}
```

From a little bit of research I did with regard to where exactly cbmc bugs out, it appears that in this specific configuration, control flow from `flatten_byte_extract` in `src/solvers/flattening/flatten_byte_operators.cpp` passes to `pointer_offset_bits` in `src/util/pointer_offset_size.cpp`, with an array type as the first parameter. In the consequent body of the if condition (which evaluates to true) is a call to `to_integer` (in `src/util/arith_tools.cpp`), whose first condition that checks if the expression is not constant `(!expr.is_constant())` to evaluate to true, causing `pointer_offset_bits` to return -1 to `flatten_byte_extract`, which on this value throws an exception with the message noted above.

**Comment by tautschnig** [comment]
The problem is the absence of initialisation - CBMC will assume that the pointer `v` (parameter of `vecp_push`) isn't valid, and the value of the `cap` member is unknown, consequently `newsize` is unknown.

**Comment by tautschnig** [comment]
With all the changes that happened to byte-operator lowering this test no longer fails.
