### ISSUE TITLE
Export DIMACS file without generating a solution

### ISSUE THREAD

**Issue by luke-croak** [diffblue/cbmc#6135]
CBMC version: 5.28.0 (cbmc-5.28.1-dirty)
Operating system: Ubuntu 20.04

I'm wanting to just export the generated formula from symbolic execution as a CNF and I don't want the the in-built solver to try and find a solution to it (for time and memory reasons). When I run CBMC with the "--dimacs" option it generates the information I want, but I believe it also makes a call to the in-built solver to generate a solution.

**Question:** Is there a way to export the DIMACS file without a call to the solver to generate a solution?

**Comment by tautschnig** [comment]
No, when invoke with `--dimacs`, no other solver is consulted. What is it that made you conclude that a solver was being invoked?

**Comment by luke-croak** [comment]
When I ran CBMC with `--dimacs` it contained the following output:
```
Solving with DIMACS CNF
Runtime Solver: 0.000111134s
Runtime decision procedure: 0.00112416s
p cnf 354 451
```
I inferred that this meant that a solver was being called to solve the CNF.

**Comment by martin-cs** [comment]
I can see how that could be a bit misleading but, no, that is the time spent in the "solver" which prints DIMACS.
