### ISSUE TITLE
Document quantifiers & code contracts support

### ISSUE THREAD

**Issue by SaswatPadhi** [diffblue/cbmc#6149]
Just a TODO ticket to properly document the code contracts support (Felipe -> function contracts, I -> loop contracts) at some point.

As Felipe suggested @ https://github.com/diffblue/cbmc/pull/6145#discussion_r638326431, we should also document the restricted quantifier support with the SAT backend. If this is already documented somewhere please point us to it.

**Comment by martin-cs** [comment]
Yes; a page in the manual about code contracts and how to do deductive verification would be *amazing* and would be make accessible all of the great work you have been doing.

I don't think the limitations of the SAT backend are documented anywhere.
