### ISSUE TITLE
Assigns clause should only check assignments over variables from the write set

### ISSUE THREAD

**Issue by feliperodri** [diffblue/cbmc#6154]
**CBMC version:** `develop` branch.
**Operating system:** N/A.
**Exact command line resulting in the issue:** N/A.
**What behaviour did you expect:** We only want to check assignments over variables from the write set. Local variables should be ignored.
What happened instead: When using assigns clause, CBMC checks for all assignments, even if they are over local variables.

**Comment by SaswatPadhi** [comment]
Context: https://github.com/diffblue/cbmc/pull/6108#discussion_r640038840
