### ISSUE TITLE
Name used in error trace is not `display_name`

### ISSUE THREAD

**Issue by vecchiot-aws** [diffblue/cbmc#6161]
CBMC version: 5.30.0
Operating system: macOS Big Sur 11.3.1
Exact command line resulting in the issue: `cbmc --trace --xml-ui --function main /Users/vecchiot/Documents/rmc/library/rmc/rmc_lib.c main.goto`
What behaviour did you expect: LHS name in the trace for assignments match the display_name.
What happened instead: LHS name does not consistently match base_name nor display_name.

Goto file: [main.goto.zip](https://github.com/diffblue/cbmc/files/6593786/main.goto.zip)

Details:

While developing the Rust Model Checker, we are trying to adjust the pretty names in the goto symbol table for Rust programs so that CBMC traces for Rust programs use Rust variables like "x" in place of the MIR variables like "_4" when the MIR debug information gives us the "_4" => "x" mapping. (We are using the Rust MIR to produce the goto binary.)

As a test, we set every pretty name to "TDELVx" in the goto symbol table and generated an error trace.  If we extract two assignments from the trace

```
<assignment assignment_type="state" base_name="x" display_name="TDELVx" hidden="false" identifier="_ZN4core6option15Option$LT$T$GT$3map17he6b2f93e771949a7E::1::var_4::x" mode="C" step_nr="735" enecccbcuglftehcgjejielfjubgudcnbnkdcigrukdh
thread="0">
  <location column="18" file="/Users/vecchiot/Documents/rmc/library/core/src/option.rs" function="_ZN4core6option15Option$LT$T$GT$3map17he6b2f93e771949a7E" line="487"/>
  <type>int</type>
  <full_lhs>x</full_lhs>
  <full_lhs_value binary="00000000000000000000000000000000">0</full_lhs_value>
</assignment>

<assignment assignment_type="state" base_name="main::alloc2" display_name="TDELVx" hidden="true" identifier="main::alloc2" mode="C" step_nr="26" thread="0">
  <type>struct main::alloc2::struct</type>
  <full_lhs>alloc2.0</full_lhs>
  <full_lhs_value>{  }</full_lhs_value>
</assignment>
```

you can see the display_name is set to the pretty name, but that the lhs in the assignment (that includes the full projection onto struct members and array elements) does not consistently use either the base name or the display name.

**Comment by NlightNFotis** [comment]
Hello @vecchiot-aws, I'm having some trouble extracting the requirements here. In this case:

```xml
<assignment assignment_type="state" base_name="main::alloc2" display_name="TDELVx" hidden="true" identifier="main::alloc2" mode="C" step_nr="26" thread="0">
  <type>struct main::alloc2::struct</type>
  <full_lhs>alloc2.0</full_lhs>
  <full_lhs_value>{  }</full_lhs_value>
</assignment>
```

CBMC appears to be right in the LHS, because the type is a struct, and it appears to be an assignment to it (or the first element of it). Regardless of that, I changed to code so that now, the same piece of code looks like this:

```xml
    <assignment assignment_type="state" base_name="main::alloc2" display_name="TDELVx" hidden="true" identifier="main::alloc2" mode="C" step_nr="26" thread="0">
      <type>struct main::alloc2::struct</type>
      <full_lhs>main::alloc2</full_lhs>
      <full_lhs_value>{  }</full_lhs_value>
    </assignment>
```

Is this closer to what you want it to be? The difference is that `base_name` is now being used for the `<full_lhs>` element.

**Comment by vecchiot-aws** [comment]
A few things:

1) That makes sense, it was just odd that we had three identifiers for the variable in the `assignment` tag, but none of them were the ones being used, so we weren't sure where the LHS names were coming from.
2) Using the `base_name` makes sense, though what's the purpose of `display_name` then?
3) Does this mean we will lose the projections that currently appear in the LHS (e.g. `alloc2.0`)? 

Thanks so much for your time!

**Comment by TGWDB** [comment]
> A few things:
> 
> 1. That makes sense, it was just odd that we had three identifiers for the variable in the `assignment` tag, but none of them were the ones being used, so we weren't sure where the LHS names were coming from.
> 2. Using the `base_name` makes sense, though what's the purpose of `display_name` then?

Answering both of these, there are three places that some kind of name appears in the example (i.e. an assignment in the trace).

### `base_name`

The `base_name` this shows the _unscoped_ name for the symbol being assigned to. Note that here unscoped means without the full scope information, but with function scope. For example, in the code below:
```
void update(int i) {
  while(i < 10) {
    counter = i;
    do_something(i)
  }
}
```
the `counter` variable would have an unscoped name like `update::counter` and scoped name like `update::counter!0@1#2` that takes into account which thread is running, which time the function `update` is called, and how many times through the inner loop this instances of the trace is.

### `display_name`

The `display_name` uses the internal `pretty_name` for the symbol that is meant to be the language specific display name. I suspect this is mostly used for human readable output and not any internal use.

Note that if the `pretty_name` is not defined, the `name` is returned instead. `name` is already in the trace output as `identifier` and this is the unique name for this symbol.

### `<full_lhs>...`

The `full_lhs` element does a call on the left hand side of the assignment and creates a string from this lookup. So this will in turn rely upon how the XML translates the given left hand side structure.

> 3. Does this mean we will lose the projections that currently appear in the LHS (e.g. `alloc2.0`)?

I believe that the example produced by @NlightNFotis would lose some of the detail on the `full_lhs` element.

> Thanks so much for your time!

I hope the above is helpful. Also it would be great if you could let us know if there is some particular change/issue still unresolved here, or whether the explanation is sufficient for you to resolve the trace work you're doing. (I think we had a lack of clarity on just what a solution is for you, and would like to know if we have achieved this or what a solution would be.)

**Comment by vecchiot-aws** [comment]
Sorry for not getting back to you sooner. This explanation is very helpful, and I think that we will be able to handle the original issue on our end by just displaying the `display_name` ourselves instead of the `full_lhs`. Thanks again for your help!
