### ISSUE TITLE
Missing Explanation for Clauses

### ISSUE THREAD

**Issue by luke-croak** [diffblue/cbmc#6224]
**CBMC version:** 5.28.0
**Operating system:** Ubuntu 20.04.2 LTS

**Exact command line resulting in the issue:** `cbmc example.c --write-solver-stats-to out.json`

**What behaviour did you expect:** For every clause an explanation of what part of the program the clause was generated from.

**What happened instead:** Some clauses had no corresponding explanation in the "out.json" file which indicates the line of the GOTO program or SSA expression which resulted in the clauses. E.g. for clauses 412 to clause 450 there is no reason given for why they're in the CNF generated by running `cbmc example.c --dimacs`.

I looked through the source code in "symex_target_equation.cpp" and it seemed that lines weren't added if the step was marked as ignore. Though apart from running the program with slicing, it didn't seem like this was ever set. So I'm confused why some clauses aren't accounted for in the JSON.

[example.zip](https://github.com/diffblue/cbmc/files/6808541/example.zip)

**Comment by martin-cs** [comment]
Thanks for this.  There are a few extra things that are added to the clause set, like "at least one assertion must be reachable and false".  I don't know how `--write-solver-stats-to` handles these.  I tend to use `--show-vcc` and `--slice-formula` when doing this kind of optimisation work.  A quick scan down the output with `--slice-formula` looks about right to me.
