### ISSUE TITLE
Output of `goto-instrument --dump-c` doesn't have function headers for `nondet_<type>()`

### ISSUE THREAD

**Issue by vecchiot-aws** [diffblue/cbmc#6229]
CBMC version: 5.34.0 (cbmc-5.32.1-183-gc50985444)
Operating system: macOS Big Sur v11.4

Exact command line resulting in the issue: 
`goto-cc test.c -o test.goto; goto-instrument --dump-c test.goto > test-dump-c.c`

`test.c`:
```
int main() {
    int a_int = nondet_int();
    char b_char = nondet_char();
    
    int c_int = non_int();
    char d_char = non_char();
    
    return 0;
}
```

What behaviour did you expect: A function header is generated for all functions which don't have one.

What happened instead: A function header is generated for the unrecognized functions that don't have one, but specific function calls with names `nondet_<type>()` don't get a header.
`test-dump-c.c`:
```
Reading GOTO program from 'test.goto'
// non_char
// file test.c line 6 function main
signed int non_char(void);
// non_int
// file test.c line 5 function main
signed int non_int(void);

// main
// file test.c line 1
signed int main()
{
  signed int a_int;
  signed int return_value_nondet_int=nondet_int();
  a_int = return_value_nondet_int;
  char b_char;
  signed int return_value_nondet_char=nondet_int();
  b_char = (char)return_value_nondet_char;
  signed int c_int;
  signed int return_value_non_int=non_int();
  c_int = return_value_non_int;
  char d_char;
  signed int return_value_non_char=non_char();
  d_char = (char)return_value_non_char;
  return 0;
}
```

Context: We want to be able to make the output of `--dump-c` compilable/runnable `C` code, but we then need function headers for each usage of a `nondet` function call. While in this particular example, it's easy to derive the type of the `nondet` from the name (e.g. `nondet_int()` returns an `int`), in the context of our project ([RMC](https://github.com/model-checking/rmc)), the generated `nondet` functions take the form `nondet_<k>()`, where `k` is a natural number, and some of the generated types are much more complex than just an `int`, making it hard to map back from name to type.

I understand that true `nondet` calls versus undefined functions are conceptually different, but it would be useful to have those headers generated regardless to allow compilation. If there is a reason why not, I'd love to hear!

Thanks for your time.

**Comment by martin-cs** [comment]
This might be a little bit of a fiddle because functions whose names start with `nondet_` are treated specially by CBMC.  Have a look at:

```
$ cat example.c
int f00(void);

int nondet_f00(void);

int main (int argc, char **argv) {
        int x = f00();
        int y = nondet_f00();

        return x;
}
$ cbmc --show-symbol-table example.c
$ cbmc --show-symbol-functions example.c
```

In the later the function call has been removed.  This happens during `goto_convert` (going from symbol-table to goto-program):

https://github.com/diffblue/cbmc/blob/06c563a76589ed00cc372d68e2819880537977b2/src/goto-programs/builtin_functions.cpp#L891

where calls to functions called `nondet_*` are converted to assignments to a non-det value rather than function calls.

The simplest work-around is to call your functions something else!

**Comment by tautschnig** [comment]
As Martin explained, this behaviour is actually intended. This is very much consistent with the example provided, which works just fine despite not having any declarations of the `nondet_*` functions. If function headers are wanted, the user is always free to use completely different names (without function body) to produce nondet symbols. I am, therefore, inclined to resolve this issue.
