### ISSUE TITLE
What portion of Vector instructions does CBMC support

### ISSUE THREAD

**Issue by danielsn** [diffblue/cbmc#6275]
We are using vector instructions in RMC. CBMC has partial support for vectors: it would be useful to know which operations are fully/partially/not supported.

Thanks.

**Comment by tautschnig** [comment]
With apologies for taking this long to respond. CBMC rewrites all vector operations in https://github.com/diffblue/cbmc/blob/develop/src/goto-programs/remove_vector.cpp. If there are any vector operations that are not, or not correctly, supported, then that would constitute a bug that we should fix as soon as possible.

Resolving for the time being, but please do raise any issues related to vectors that you might run into.
