### ISSUE TITLE
Should `struct_tag_typet` be removed and if so when?

### ISSUE THREAD

**Issue by martin-cs** [diffblue/cbmc#6283]
As I understand it, `struct_tag_typet` is needed to handle code like this:

```
struct my_struct;
struct other_struct {
 struct my_struct *s;
};
struct my_struct {
 struct other_struct *t;
};
```

`namespacet::follow_tag` is then used to convert from `struct_tag_typet` to `struct_tag` when all of the definitions are available.

A. Are all of the `struct_tag_typet` converted at some point?
B. If so, where?
C. If not, is it the responsibility of all code to call `namespacet::follow_tag` when doing type equality?

Paging @danielsn for a view on how the Rust front-end handles this.

**Comment by kroening** [comment]
A. No, they should not.
B. Hopefully nowhere.
C. No need; types are equal when they are == equal.

**Comment by martin-cs** [comment]
Thanks @kroening , so to avoid a mix we should prefer tagged types?

**Comment by kroening** [comment]
Yes!

**Comment by martin-cs** [comment]
Thanks for the prompt response.
