### ISSUE TITLE
Java type resolution in virtual calls

### ISSUE THREAD

**Issue by reuk** [diffblue/cbmc#629]
The following example tests a very basic iterator. CBMC is able to resolve the virtual calls, and verification succeeds:

```java
interface MyIterator {
    boolean hasNext();
    void next();
}

class MyImpl implements MyIterator {
    private boolean hn = true;
    public boolean hasNext() { return hn; }
    public void next() { hn = false; }
}

public class virtual3_Pass {
    public static void main(String[] args) {
        MyIterator i = new MyImpl();
        assert i.hasNext();
        i.next();
        assert !i.hasNext();
    }
}
```

Now, we modify the `main` to include a loop, using a virtual call as the loop predicate.

```java
    public static void main(String[] args) {
        MyIterator i = new MyImpl();
        while (i.hasNext()) {
            i.next();
        }
        assert true;
    }
```

CBMC appears to attempt to unwind the loop *before* resolving the variable type, which means that it doesn't terminate. In both cases, the virtual calls as represented in the goto program are very similar (i.e. they both branch depending on the variable type, in the same way), so the problem appears to be that the types are resolved too late, rather than the virtual calls being pruned incorrectly.

As this is a fundamental pattern in Java code, we should be able to model it. In particular, `ArrayList` becomes substantially less useful without iterators.

**Comment by cristina-david** [comment]
In order for the modelling to work, we need to provide an unwind bound when running CBMC. If the unwind bound is bigger than the model size (i.e. the array's maximum capacity), then the solver will figure out that the code after the loop is reachable.

**Comment by reuk** [comment]
I can confirm that the verification of the second snippet succeeds if I add `--unwind 5` to the CBMC command-line.
