### ISSUE TITLE
Primitive to havoc a slice of an object

### ISSUE THREAD

**Issue by feliperodri** [diffblue/cbmc#6291]
CBMC version: `develop` branch.
Operating system: N/A.
Exact command line resulting in the issue: N/A.

We have a havoc function for objects called `__CPROVER_havoc_object`. However, there are cases where one might want to havoc only a slice of the object. For instance,

```c
#include <assert.h>

struct tuple { int x[10]; int y; };

void foo(struct tuple *t)
{
  __CPROVER_havoc_object(t->x);
}

int main ()
{
  struct tuple t = {0};
  foo(&t);
  assert(t.y == 0);
}
```

In this case, the entire object will be havoced, but the intention was to havoc only `t->x`.

Assuming a pointer `ptr` that is represented by an object `ptr.object` and an offset `ptr.offset`, we could have a primitive called `__CPROVER_havoc_slice(ptr, size)`, which would havoc `size` bytes of `ptr.object` starting from `ptr.offset`.

**Comment by feliperodri** [comment]
cc. @jimgrundy @SaswatPadhi @remi-delmas-3000

**Comment by jimgrundy** [comment]
We have a more complete version of this request now with https://github.com/diffblue/cbmc/issues/6351, so let's close this can pick it up there.
