### ISSUE TITLE
support loading jars from war files

### ISSUE THREAD

**Issue by mgudemann** [diffblue/cbmc#632]
web application archive (WAR) files support packaging jar files within, in the `WEB-INF/lib` entry of the central directory. Currently, loading jar files that are not available as external files is not supported.

cf. #608

**Comment by thomasspriggs** [comment]
There doesn't seem to be anyone currently interested in pursuing adding this particular feature. Therefore I am going to close out this issue as a matter of cleaning out the stale open issues.
