### ISSUE TITLE
Create new __CPROVER_havoc_slice & __CPROVER_havoc_from primitives

### ISSUE THREAD

**Issue by jimgrundy** [diffblue/cbmc#6351]
We need the following new havoc primitives in CBMC:

```
void __CPROVER_havoc_slice(void *p, size_t s);
void __CPROVER_havoc_from (void *p);
```
(Reference implementation for havoc_object: [symex_other.cpp](https://github.com/diffblue/cbmc/blob/56adbb21ea443f07d29b6056016cbc86da6c7dec/src/goto-symex/symex_other.cpp#L244))

The semantics of these primitives are described below.

***__CPROVER_havoc_slice(void \*p, size_t s)***

_Precondition:_

```
s == 0 || __CPROVER_w_ok(p, s)
```

- If s is zero then no action is performed.
- If s is non-zero and p is a valid pointer to an object with at least s writable bytes starting at address p, that is if __CPROVER_w_ok(p, s),  then the effect is to replace the s bytes starting at address p with fresh symbolic values.

***__CPROVER_havoc_from(void \*p)***

_Precondition:_

```
p == NULL ||
     __CPROVER_OBJECT_SIZE(p) == __CPROVER_POINTER_OFFSET(p) ||
     __CPROVER_w_ok(p, __CPROVER_OBJECT_SIZE(p) - __CPROVER_POINTER_OFFSET(p))
```

- If p is NULL then no action is performed.
- Otherwise, equivalent to:
    `__CPROVER_havoc_slice(p, __CPROVER_OBJECT_SIZE(p) - __CPROVER_POINTER_OFFSET(p))`

**Comment by SaswatPadhi** [comment]
Only `__CPROVER_havoc_slice` should suffice. It might be desirable to minimize the number of new primitives we introduce.

#### Some reference material
* Implementation for `havoc_object`: https://github.com/diffblue/cbmc/blob/56adbb21ea443f07d29b6056016cbc86da6c7dec/src/goto-symex/symex_other.cpp#L244
* Implementation for `malloc`: https://github.com/diffblue/cbmc/blob/56adbb21ea443f07d29b6056016cbc86da6c7dec/src/ansi-c/library/stdlib.c#L139
* List of builtin functions: https://github.com/diffblue/cbmc/blob/develop/src/ansi-c/cprover_builtin_headers.h

**Comment by kroening** [comment]
Use an assignment, with the appropriate byte_extract expression on the left hand side.

**Comment by kroening** [comment]
In the long term, I'd like to shrink symex_other until it's gone.

**Comment by kroening** [comment]
Another option is to assign a byte array of the appropriate size to a dereferencing expression that has the same type. This avoids the low-level expression.

**Comment by NlightNFotis** [comment]
Hello, is #6430 related to this issue? It appears to be fulfilling the requirements of at least the first of the primitives requested, or am I mistaken?

**Comment by jimgrundy** [comment]
It is related, and, actually we can build havoc_from using havoc_slice, so we will only need the the one primitive, which Remi's PR implements.
