### ISSUE TITLE
goto_check treats `ID_and` / `and_exprt` in a non-commutative way

### ISSUE THREAD

**Issue by martin-cs** [diffblue/cbmc#6423]
While reviewing https://github.com/diffblue/cbmc/pull/6399 I wondered what is documented about it.

https://github.com/diffblue/cbmc/blob/ce2680b724d650c404468eb0070c8b402735ec66/src/util/simplify_utils.cpp#L51

suggests that `ID_and` it is associative and commutative.  However the handling of logical operations in `goto_check` is asymmetric:

https://github.com/diffblue/cbmc/blob/ce2680b724d650c404468eb0070c8b402735ec66/src/analyses/goto_check.cpp#L111
https://github.com/diffblue/cbmc/blob/ce2680b724d650c404468eb0070c8b402735ec66/src/analyses/goto_check.cpp#L1607

These were refactoring made in https://github.com/diffblue/cbmc/pull/4611/files .

This seems a bit risky as a simplify in a pass before `goto_check` (for example in `goto-analyzer --simplify`) can alter / break the conditions that are generated.

**Comment by kroening** [comment]
Indeed; goto_check is very closely coupled with what comes out of the C front-end. The plan is to make goto_check part of the C front-end to remove this ambiguity.

**Comment by jimgrundy** [comment]
Would it make sense to have different ireps for logical ands and short-circuit ands?

**Comment by kroening** [comment]
sure, might help

**Comment by martin-cs** [comment]
> Would it make sense to have different ireps for logical ands and
> short-circuit ands?

Maybe.  IIRC && and || are split into multiple gotos during
goto_convert so a && in the source code doesn't necessarily give an
ID_and in the goto-program when it gets to goto_check.  I am not sure
about assumes and asserts though.

**Comment by jimgrundy** [comment]
I've gotten good performance improvements out of CBMC replacing "a && b" with "a & b" in my code when
1/ a and b are both expressions that return only 1 or 0
2/ b is an expression that cannot fail
Is there an optimization that does that automatically? Could there be one?

**Comment by tautschnig** [comment]
Closing for ef4dd67e7031 actually moved `analyses/goto_check` to `ansi-c/goto_check_c`.
