### ISSUE TITLE
No way to install CBMC after `make -C src`

### ISSUE THREAD

**Issue by srogatch** [diffblue/cbmc#6443]
CBMC version: 5.43.0
Operating system: Ubuntu 20.04
Exact command line resulting in the issue: make -C src
What behaviour did you expect: a possibility to run `make -C src install`
What happened instead: there is no `install` target.

**Comment by tautschnig** [comment]
I've finally put together a PR that seeks to address this: #6637. My apologies for the time it took to get this done.
