### ISSUE TITLE
what's the proper command for running clang-format and cpplint locally before a commit/PR ?

### ISSUE THREAD

**Issue by remi-delmas-3000** [diffblue/cbmc#6457]
Hello, 

I'm using visualstudio-code's built-in support for clang-format and it seems to give slightly different results to what is run in CI. How can I run locally the exact same pass that CI would do ?
I also tried `git clang-format` but still get CI errors. 

The default clang-format version is 10.x on ubuntu 20_04 linux and 13.x on macOS running the latest xcode tools

(Same question for cpplint.)

Thank you!

**Comment by TGWDB** [comment]
The codebase is using `clang-format-7`.

**Comment by tautschnig** [comment]
@remi-delmas-3000, are you really seeing different formatting, or is it just that bits of the code base get formatted when CI does not expect them to be reformatted? Perhaps you could post examples?
