### ISSUE TITLE
A question about using loop invariants in CBMC

### ISSUE THREAD

**Issue by wcventure** [diffblue/cbmc#6460]
Hi there, 

I've been learning to use CBMC to verify my code. 

For some reason, the loop unwinding cannot unwind my loop repeatedly. And I found that CBMC can support the use of loop invariants to build loop contracts. I try to use the loop contract. But I don't know whether it is due to the limitations of CBMC itself, or my loop invariant is written incorrectly. I've tried to read a lot of examples in `regression/contracts`, but unfortunately, I haven't found similar examples.

This problem has plagued me for several days. Can someone help me look at the following code？

```C
#include <stdio.h>
#include <assert.h>
#include <malloc.h>

typedef struct Node {
    unsigned int ID;
    struct Node *next;
} Node;

void main()
{
    Node *p = malloc(sizeof(Node));
    Node *pTmp = 0;
    Node *next = 0;
	
    pTmp = p;
    int i;
    for (i = 0; i < 3; i++)
    {
        pTmp->next = malloc(sizeof(Node));
        pTmp = pTmp->next;
        pTmp->next = 0;
        pTmp->ID = i + 1;
    }

    pTmp = p;
    while (0 != pTmp)
	__CPROVER_loop_invariant(pTmp==__CPROVER_loop_entry(pTmp)->next || pTmp == __CPROVER_loop_entry(pTmp))
	__CPROVER_loop_invariant(__CPROVER_deallocated == __CPROVER_loop_entry(pTmp) || pTmp == __CPROVER_loop_entry(pTmp))
    {
        next = pTmp->next;
        free(pTmp);
        pTmp = next;
    }
}
```

**Comment by martin-cs** [comment]
> Hi there,
> 
> I've been learning to use CBMC to verify my code.

Hi!  Excellent; I hope you like it.


> For some reason, the loop unwinding cannot unwind my loop repeatedly.

Can you say a little more about what you mean?  Can it not unwind the
loop at all?  Does it unwind but not determine that the lower loop can
only be run 3 times?  Does it fail to find a particular error / fail to
prove something you feel it should?


> And I found that CBMC can support the use of loop invariants to build
> loop contracts.

There is support in goto-instrument for using loop invariants to
transform the code to remove loops.


>  I try to use the loop contract. But I don't know whether it is due
> to the limitations of CBMC itself, or my loop invariant is written
> incorrectly. I've tried to read a lot of examples in
> regression/contracts, but unfortunately, I haven't found similar
> examples.

I assume you have also found:

https://github.com/diffblue/cbmc/blob/develop/doc/cprover-manual/contracts-loops.md


> This problem has plagued me for several days. Can someone help me
> look at the following code？

Please could you post the commands you are running and the results? 
Also which version of CBMC are you using as the loop contracts support
is relatively new.

-- 
Martin is now a full time member of staff.

**Comment by wcventure** [comment]
> Please could you post the commands you are running and the results?

I use the following commands:
```
goto-cc -o test.goto test.c
goto-instrument --apply-loop-contracts test.goto test_inst.goto
cbmc test_inst.goto
```

> Also which version of CBMC are you using as the loop contracts support is relatively new.
```sh
5.43.0 (cbmc-5.43.0)
```



The Results:
```sh
Reading GOTO program from 'test.goto'
Function Pointer Removal
Virtual function removal
Cleaning inline assembler statements
Writing GOTO program to 'test_inst.goto'
CBMC version 5.43.0 (cbmc-5.43.0) 64-bit x86_64 linux
Reading GOTO program from file
Reading: test_inst.goto
Generating GOTO Program
Adding CPROVER library (x86_64)
Removal of function pointers and virtual functions
Generic Property Instrumentation
Running with 8 object bits, 56 offset bits (default)
Starting Bounded Model Checking
Unwinding loop main.0 iteration 1 file gitissue.c line 18 function main thread 0
Unwinding loop main.0 iteration 2 file gitissue.c line 18 function main thread 0
Unwinding loop main.0 iteration 3 file gitissue.c line 18 function main thread 0
aborting path on assume(false) at file gitissue.c line 27 function main thread 0
Runtime Symex: 0.0050856s
size of program expression: 273 steps
simple slicing removed 3 assignments
Generated 8 VCC(s), 1 remaining after simplification
Runtime Postprocess Equation: 1.85e-05s
Passing problem to propositional reduction
converting SSA
Runtime Convert SSA: 0.0007409s
Running propositional reduction
Post-processing
Runtime Post-process: 3.6e-05s
Solving with MiniSAT 2.2.1 with simplifier
1840 variables, 303 clauses
SAT checker: instance is SATISFIABLE
Runtime Solver: 0.000332s
Runtime decision procedure: 0.0011732s

** Results:
<builtin-library-malloc> function malloc
[malloc.assertion.1] line 26 max allocation size exceeded: SUCCESS
[malloc.assertion.2] line 31 max allocation may fail: SUCCESS

gitissue.c function main
[main.1] line 27 Check loop invariant before entry: SUCCESS
[main.2] line 27 Check that loop invariant is preserved: FAILURE
[main.precondition_instance.1] line 32 free argument must be NULL or valid pointer: SUCCESS
[main.precondition_instance.2] line 32 free argument must be dynamic object: SUCCESS
[main.precondition_instance.3] line 32 free argument has offset zero: SUCCESS
[main.precondition_instance.4] line 32 double free: SUCCESS
[main.precondition_instance.5] line 32 free called for new[] object: SUCCESS
[main.precondition_instance.6] line 32 free called for stack-allocated object: SUCCESS

** 1 of 10 failed (2 iterations)
VERIFICATION FAILED
```

**Comment by qinheping** [comment]
Hi! I tried your code on my machine and found two issues that block the proof. 

The first issue is that, in the second loop, the variable we iterate over is a pointer (`pTmp`), which is not supported in loop contracts yet. We are implementing this feature and hope to merge it soon.

Besides, the loop invariant misses the case that `pTmp` can also be the 3rd, the 4th nodes (we created 4 nodes), or NULL (at the end of the last iteration). So the first clause should be 
```
__CPROVER_loop_invariant(
  pTmp == __CPROVER_loop_entry(pTmp)->next ||
  pTmp == __CPROVER_loop_entry(pTmp)->next->next ||
  pTmp == __CPROVER_loop_entry(pTmp)->next->next->next || 
  pTmp == __CPROVER_loop_entry(pTmp) || 
  pTmp == 0
)
```

**Comment by wcventure** [comment]
Thank you all very much. But this example still doesn't work.

> The first issue is that, in the second loop, the variable we iterate over is a pointer (`pTmp`), which is not supported in loop contracts yet. We are implementing this feature and hope to merge it soon.

Good. I look forward to this feature.

> Besides, the loop invariant misses the case that `pTmp` can also be the 3rd, the 4th nodes (we created 4 nodes), or NULL (at the end of the last iteration)

Thank you. I think the "__CPROVER_loop_entry"  In your invariant would be "__CPROVER_loop_old".


Here I have another question. 
If I use a linked list with a large number of nodes, how to describe "`pTmp->next->...->next`" in the loop invariants. Do we have recursive logic?

**Comment by SaswatPadhi** [comment]
Hello,

> If I use a linked list with a large number of nodes, how to describe "pTmp->next->...->next" in the loop invariants. Do we have recursive logic?

We currently cannot. We are working on extending loop contracts to work on inductive data types like linked lists, but it's currently unsupported.

**Comment by jimgrundy** [comment]
Hi @wcventure. It's been a while. Our current status is that recursive logic isn't yet supported. It's on our wishlist, but I can't give you a timeline. Are there other questions we should answer, or can we close this request and pick it up again after some future release that would add this functionality?
