### ISSUE TITLE
Feature request: labels for function pointer restrictions

### ISSUE THREAD

**Issue by avanhatt** [diffblue/cbmc#6464]
[RMC](https://github.com/model-checking/rmc) is starting to use CBMC function pointer restrictions.

We have found CBMC's naming convention for identifying specific function pointer calls (indexed based on static placement, documented [here](http://cprover.diffblue.com/md__home_travis_build_diffblue_cbmc_doc_architectural_restrict-function-pointer.html)) to be difficult to use without introducing wrapper functions. It would be helpful if we could specify call sites using C labels instead:

That is, we would like to be able to use `"call_f" : [...], "call_g": [...]` instead of `"surrounding_fn.function_pointer_call.1" : [...], "surrounding_fn.function_pointer_call.2": [...]` for this example:
```C
void surrounding_fn(..) {
    call_f: (*f)(x);
    call_g: (*g)(y);
}
```

**Comment by danielsn** [comment]
This would also be useful for having meaningful and stable names for unwindsets

**Comment by danielsn** [comment]
I suspect the name would actually be `surrounding_fn::call_f` to ensure uniqueness

**Comment by tautschnig** [comment]
We first need to add a uniqueness check in the C front-end, which happily accepts the following at the moment:
````c
int main()
{
  int x;
label: x=1;
  goto label;
label: x=2;
}
````

**Comment by jimgrundy** [comment]
I'd love to be able to refer to loops by label rather than number when specifying unwindings. Is that feasible to add?

**Comment by tautschnig** [comment]
> I'd love to be able to refer to loops by label rather than number when specifying unwindings. Is that feasible to add?

#6508 (still in draft mode) now adds support for both loops and function pointers to be referred to by label.
