### ISSUE TITLE
VERIFICATION FAILED when use loop contract

### ISSUE THREAD

**Issue by xiaolangde** [diffblue/cbmc#6556]
CBMC version: 5.47.0
Operating system: Ubuntu 20.04.3 LTS
Exact command line resulting in the issue: goto-cc test.c -o a1.goto; goto-instrument --apply-loop-contracts a1.goto a2.goto; cbmc  a2.goto
What behaviour did you expect:  VERIFICATION SUCCESS
What happened instead: VERIFICATION FAILED with 2 errors

test.c :
```
#include <malloc.h>
typedef struct A {
    int a;
    int b;
    char *data;
}SA;

void initData(char *d, unsigned int n)
{
    unsigned int i = 0;
    for (; i < n; i++)
    __CPROVER_loop_invariant(i >= 0 && i <= n)
    __CPROVER_decreases(n - i)
    {
        char tmp;
        d[i] = tmp;  // v5.45 ok, v5.47 reports: Check that d[(signed long int)i] is assignable: FAILURE 
    }
}

int main(void)
{
    unsigned int size;
    __CPROVER_assume(size > 0);
    __CPROVER_assume(size < 10);
    SA *pa = malloc(sizeof(SA) + size);
    __CPROVER_assume(pa != NULL);
    pa->a = 0;
    pa->data = (char *)pa + sizeof(SA);
    initData(pa->data, size);
    __CPROVER_assert(pa->a == 0, "init data out of bound error");  // check failed.  bug??
    free(pa);
    return 0;
}
```

$ **goto-cc test.c -o a1.goto; goto-instrument --apply-loop-contracts a1.goto a2.goto; cbmc  a2.goto**
Reading GOTO program from 'a1.goto'
Function Pointer Removal
Virtual function removal
Cleaning inline assembler statements
Writing GOTO program to 'a2.goto'
CBMC version 5.47.0 (cbmc-5.47.0) 64-bit x86_64 linux
Reading GOTO program from file
Reading: a2.goto
Generating GOTO Program
Adding CPROVER library (x86_64)
Removal of function pointers and virtual functions
Generic Property Instrumentation
Running with 8 object bits, 56 offset bits (default)
Starting Bounded Model Checking
aborting path on assume(false) at file test.c line 11 function initData thread 0
Runtime Symex: 0.0126688s
size of program expression: 225 steps
simple slicing removed 30 assignments
Generated 39 VCC(s), 28 remaining after simplification
Runtime Postprocess Equation: 4.6368e-05s
Passing problem to propositional reduction
converting SSA
Runtime Convert SSA: 0.00992487s
Running propositional reduction
Post-processing
Runtime Post-process: 0.00797543s
Solving with CaDiCaL 1.4.1
10461 variables, 36033 clauses
SAT checker: instance is SATISFIABLE
Runtime Solver: 0.0134764s
Runtime decision procedure: 0.0235671s
Running propositional reduction
Solving with CaDiCaL 1.4.1
10461 variables, 36034 clauses
SAT checker: instance is SATISFIABLE
Runtime Solver: 0.0013594s
Runtime decision procedure: 0.00145639s
Running propositional reduction
Solving with CaDiCaL 1.4.1
10461 variables, 36035 clauses
SAT checker: instance is UNSATISFIABLE
Runtime Solver: 0.00524773s
Runtime decision procedure: 0.00532094s

** Results:
<builtin-library-malloc> function malloc
[malloc.assertion.1] line 26 max allocation size exceeded: SUCCESS
[malloc.assertion.2] line 31 max allocation may fail: SUCCESS

test.c function initData
[initData.1] line 11 Check loop invariant before entry: SUCCESS
[initData.3] line 11 Check that i is assignable: SUCCESS
[initData.4] line 11 Check that loop invariant is preserved: SUCCESS
[initData.5] line 11 Check decreases clause on loop iteration: SUCCESS
[initData.pointer_arithmetic.1] line 11 pointer arithmetic: dead object in (char *)&i + (signed long int)4ul: SUCCESS
[initData.pointer_arithmetic.27] line 11 pointer arithmetic: dead object in (char *)&i + (signed long int)4ul: SUCCESS
[initData.pointer_arithmetic.14] line 15 pointer arithmetic: dead object in &tmp + (signed long int)1ul: SUCCESS
**[initData.2] line 16 Check that d[(signed long int)i] is assignable: FAILURE**
[initData.pointer_arithmetic.2] line 16 pointer arithmetic: pointer NULL in (char *)d + (signed long int)i: SUCCESS
[initData.pointer_arithmetic.3] line 16 pointer arithmetic: pointer invalid in (char *)d + (signed long int)i: SUCCESS
[initData.pointer_arithmetic.4] line 16 pointer arithmetic: deallocated dynamic object in (char *)d + (signed long int)i: SUCCESS
[initData.pointer_arithmetic.5] line 16 pointer arithmetic: dead object in (char *)d + (signed long int)i: SUCCESS
[initData.pointer_arithmetic.6] line 16 pointer arithmetic: pointer outside object bounds in (char *)d + (signed long int)i: SUCCESS
[initData.pointer_arithmetic.7] line 16 pointer arithmetic: invalid integer address in (char *)d + (signed long int)i: SUCCESS
[initData.pointer_arithmetic.8] line 16 pointer arithmetic: pointer NULL in &((char *)d)[(signed long int)i] + (signed long int)1ul: SUCCESS
[initData.pointer_arithmetic.9] line 16 pointer arithmetic: pointer invalid in &((char *)d)[(signed long int)i] + (signed long int)1ul: SUCCESS
[initData.pointer_arithmetic.10] line 16 pointer arithmetic: deallocated dynamic object in &((char *)d)[(signed long int)i] + (signed long int)1ul: SUCCESS
[initData.pointer_arithmetic.11] line 16 pointer arithmetic: dead object in &((char *)d)[(signed long int)i] + (signed long int)1ul: SUCCESS
[initData.pointer_arithmetic.12] line 16 pointer arithmetic: pointer outside object bounds in &((char *)d)[(signed long int)i] + (signed long int)1ul: SUCCESS
[initData.pointer_arithmetic.13] line 16 pointer arithmetic: invalid integer address in &((char *)d)[(signed long int)i] + (signed long int)1ul: SUCCESS
[initData.pointer_arithmetic.15] line 16 pointer arithmetic: pointer NULL in d + (signed long int)i: SUCCESS
[initData.pointer_arithmetic.16] line 16 pointer arithmetic: pointer invalid in d + (signed long int)i: SUCCESS
[initData.pointer_arithmetic.17] line 16 pointer arithmetic: deallocated dynamic object in d + (signed long int)i: SUCCESS
[initData.pointer_arithmetic.18] line 16 pointer arithmetic: dead object in d + (signed long int)i: SUCCESS
[initData.pointer_arithmetic.19] line 16 pointer arithmetic: pointer outside object bounds in d + (signed long int)i: SUCCESS
[initData.pointer_arithmetic.20] line 16 pointer arithmetic: invalid integer address in d + (signed long int)i: SUCCESS
[initData.pointer_arithmetic.21] line 16 pointer arithmetic: pointer NULL in &d[(signed long int)i] + (signed long int)1ul: SUCCESS
[initData.pointer_arithmetic.22] line 16 pointer arithmetic: pointer invalid in &d[(signed long int)i] + (signed long int)1ul: SUCCESS
[initData.pointer_arithmetic.23] line 16 pointer arithmetic: deallocated dynamic object in &d[(signed long int)i] + (signed long int)1ul: SUCCESS
[initData.pointer_arithmetic.24] line 16 pointer arithmetic: dead object in &d[(signed long int)i] + (signed long int)1ul: SUCCESS
[initData.pointer_arithmetic.25] line 16 pointer arithmetic: pointer outside object bounds in &d[(signed long int)i] + (signed long int)1ul: SUCCESS
[initData.pointer_arithmetic.26] line 16 pointer arithmetic: invalid integer address in &d[(signed long int)i] + (signed long int)1ul: SUCCESS

test.c function main
**[main.assertion.1] line 30 init data out of bound error: FAILURE**
[main.precondition_instance.1] line 31 free argument must be NULL or valid pointer: SUCCESS
[main.precondition_instance.2] line 31 free argument must be dynamic object: SUCCESS
[main.precondition_instance.3] line 31 free argument has offset zero: SUCCESS
[main.precondition_instance.4] line 31 double free: SUCCESS
[main.precondition_instance.5] line 31 free called for new[] object: SUCCESS
[main.precondition_instance.6] line 31 free called for stack-allocated object: SUCCESS

** 2 of 41 failed (3 iterations)
**VERIFICATION FAILED**
cbmc a2.goto  0.08s user 0.01s system 99% cpu 0.091 total

$ **goto-cc test.c -o a1.goto; cbmc --unwind 11 a1.goto** 
CBMC version 5.47.0 (cbmc-5.47.0) 64-bit x86_64 linux
Reading GOTO program from file
Reading: a1.goto
Generating GOTO Program
Adding CPROVER library (x86_64)
Removal of function pointers and virtual functions
Generic Property Instrumentation
Running with 8 object bits, 56 offset bits (default)
Starting Bounded Model Checking
Unwinding loop initData.0 iteration 1 file test.c line 11 function initData thread 0
Unwinding loop initData.0 iteration 2 file test.c line 11 function initData thread 0
Unwinding loop initData.0 iteration 3 file test.c line 11 function initData thread 0
Unwinding loop initData.0 iteration 4 file test.c line 11 function initData thread 0
Unwinding loop initData.0 iteration 5 file test.c line 11 function initData thread 0
Unwinding loop initData.0 iteration 6 file test.c line 11 function initData thread 0
Unwinding loop initData.0 iteration 7 file test.c line 11 function initData thread 0
Unwinding loop initData.0 iteration 8 file test.c line 11 function initData thread 0
Unwinding loop initData.0 iteration 9 file test.c line 11 function initData thread 0
Unwinding loop initData.0 iteration 10 file test.c line 11 function initData thread 0
Not unwinding loop initData.0 iteration 11 file test.c line 11 function initData thread 0
Runtime Symex: 0.00810825s
size of program expression: 245 steps
simple slicing removed 30 assignments
Generated 7 VCC(s), 1 remaining after simplification
Runtime Postprocess Equation: 3.3602e-05s
Passing problem to propositional reduction
converting SSA
Runtime Convert SSA: 0.00247226s
Running propositional reduction
Post-processing
Runtime Post-process: 0.0854435s
Solving with CaDiCaL 1.4.1
57605 variables, 184359 clauses
SAT checker: instance is UNSATISFIABLE
Runtime Solver: 0.217783s
Runtime decision procedure: 0.220315s

** Results:
<builtin-library-malloc> function malloc
[malloc.assertion.1] line 26 max allocation size exceeded: SUCCESS
[malloc.assertion.2] line 31 max allocation may fail: SUCCESS

test.c function main
[main.assertion.1] line 30 init data out of bound error: SUCCESS
[main.precondition_instance.1] line 31 free argument must be NULL or valid pointer: SUCCESS
[main.precondition_instance.2] line 31 free argument must be dynamic object: SUCCESS
[main.precondition_instance.3] line 31 free argument has offset zero: SUCCESS
[main.precondition_instance.4] line 31 double free: SUCCESS
[main.precondition_instance.5] line 31 free called for new[] object: SUCCESS
[main.precondition_instance.6] line 31 free called for stack-allocated object: SUCCESS

** 0 of 9 failed (1 iterations)
**VERIFICATION SUCCESSFUL**

**Comment by remi-delmas-3000** [comment]
Hello!
Thank you for the report.

_Loop assigns clauses_ were recently introduced in CBMC contracts and this example needs one. These clauses let you specify a list of memory locations a loop is allowed to assign to. In your case the loop assigns to `i` using a side effect `i++` and also assigns to the (stack- or heap-allocated) object pointed to by `d`.  So the assigns clause would look like this:

```C
void initData(char *d, unsigned int n)
{
    unsigned int i = 0;
    for (; i < n; i++)
    __CPROVER_assigns(i, __CPROVER_POINTER_OBJECT(p)) // <---- HERE
    __CPROVER_loop_invariant(i >= 0 && i <= n)
    __CPROVER_decreases(n - i)
    {
        char tmp;
        d[i] = tmp;
    }
}
```

The explanation for this result:

```C
    __CPROVER_assert(pa->a == 0, "init data out of bound error");  // check failed.  bug??
```

is the following:

Since a single malloc'd object is used to store both the struct and the array, and the `pa->data` pointer points into this object:

```C
    SA *pa = malloc(sizeof(SA) + size);
    __CPROVER_assume(pa != NULL);
    pa->a = 0;
    pa->data = (char *)pa + sizeof(SA);
```

When the loop gets abstracted by its contract, the whole object pointed to by `pa->data`, which includes both the struct and the array, gets havocked and the whole struct becomes non-deterministic, which allows to falsify the assertion. Please note that the `pa->data` pointer also becomes non-deterministic and can become null or point to an invalid location. 

Currently, the solution would be to use two separate allocations for the struct and the data like so:

```C
#include <malloc.h>
typedef struct A {
    int a;
    int b;
    char *data;
} SA;

void initData(char *d, unsigned int n)
{
    unsigned int i = 0;
    for (; i < n; i++)
    __CPROVER_assigns(i, __CPROVER_POINTER_OBJECT(d))
    __CPROVER_loop_invariant(i >= 0 && i <= n)
    __CPROVER_decreases(n - i)
    {
        char tmp;
        d[i] = tmp;
    }
}

int main(void)
{
    unsigned int size;
    __CPROVER_assume(size > 0);
    __CPROVER_assume(size < 10);
    SA *pa = malloc(sizeof(SA));
    __CPROVER_assume(pa != NULL);
    pa->a = 0;
    pa->data = malloc(size);
    initData(pa->data, size);
    __CPROVER_assert(pa->a == 0, "init data out of bound error"); 
    free(pa->data);
    return 0;
}
```

In the future the contract language will let you specify that a slice of `size` bytes of the object pointed to by `p` is assignable, but this is not ready for release yet.

**Comment by xiaolangde** [comment]
My problem has been solved. Thank you very much! @remi-delmas-3000
