### ISSUE TITLE
Streamline Makefiles

### ISSUE THREAD

**Issue by allredj** [diffblue/cbmc#657]
There should be one filename per line in Makefiles.
Each line should end with an `\`, even the last one.
A list of lines should thus end with a comment such as:
`# Empty last line`.

This will make merging of branches much easier.

**Comment by thk123** [comment]
See #497 - I've been gradually introducing this approach as I modify make files anyway.

**Comment by allredj** [comment]
That's a good approach. We need to communicate further, as not everyone is aware of these guidelines (e.g. 055f515bd47004a6f12a898d1c3d2f1486078932).
Or else completely rewrite the Makefiles at once.

**Comment by martin-cs** [comment]
On Mon, 2017-03-20 at 06:58 -0700, Joel Allred wrote:
> That's a good approach. We need to communicate further, as not everyone is aware of these guidelines (e.g. 055f515bd47004a6f12a898d1c3d2f1486078932).
> Or else completely rewrite the Makefiles at once.

Perhaps it could be added to the lint script so that it continues to be
enforced.

**Comment by allredj** [comment]
It could. Who's in charge of that?

**Comment by thk123** [comment]
So in waiting for sprint planning I have finally written said script to sort out make files and updated the linked PR, thanks for nudging me to do this :)
