### ISSUE TITLE
Get Bit-Vector Output of a C code

### ISSUE THREAD

**Issue by mahantaf** [diffblue/cbmc#6572]
Given a sample program like the example you give in the paper, I want to get the output of that program in a Bit-Vector format:

input:

```c++
void test(int x, int y) {
  x = x + y;
  if(x != 1)
    x = 2;
  else
    x++;
  assert(x <= 3);
}
```
output:

```
C := x1 = x0 + y0 &
x2 = (x1 != 1)?2 : x1) &
x3 = ((x1 != 1 & z0)?x2 + 1 : x2)
V := x3 < 3
```
How is it possible?

CBMC version: 5.48.0
Operating system: Ubuntu 20.04
Exact command line resulting in the issue:
What behaviour did you expect:
What happened instead:

**Comment by tautschnig** [comment]
Would the output of `cbmc --program-only input.c` or `cbmc --show-vcc input.c` satisfy your needs? It it doesn't, can you please let us know what we could do to make it more helpful?

**Comment by mahantaf** [comment]
I want to input a c program and get a boolean formula of that program. Like the one mentioned in the CBMC article.

I have tried cbmc --program-only --function test ../../examples/test.c but it outputs this:

```
Program constraints:
// 25 
// 25 
// 0 file <built-in-additions> line 19
(1) SHARED_WRITE(__CPROVER_alloca_object#1)
// 0 file <built-in-additions> line 19
(2) __CPROVER_alloca_object#1 == NULL
// 1 file <built-in-additions> line 14
(3) SHARED_WRITE(__CPROVER_dead_object#1)
// 1 file <built-in-additions> line 14
(4) __CPROVER_dead_object#1 == NULL
// 2 file <built-in-additions> line 13
(5) SHARED_WRITE(__CPROVER_deallocated#1)
// 2 file <built-in-additions> line 13
(6) __CPROVER_deallocated#1 == NULL
// 3 file <built-in-additions> line 22
(7) SHARED_WRITE(__CPROVER_malloc_failure_mode_assert_then_assume#1)
// 3 file <built-in-additions> line 22
(8) __CPROVER_malloc_failure_mode_assert_then_assume#1 == 2
// 4 file <built-in-additions> line 21
(9) SHARED_WRITE(__CPROVER_malloc_failure_mode_return_null#1)
// 4 file <built-in-additions> line 21
(10) __CPROVER_malloc_failure_mode_return_null#1 == 1
// 5 file <built-in-additions> line 16
(11) SHARED_WRITE(__CPROVER_malloc_is_new_array#1)
// 5 file <built-in-additions> line 16
(12) __CPROVER_malloc_is_new_array#1 == FALSE
// 6 file <built-in-additions> line 23
(13) SHARED_WRITE(__CPROVER_max_malloc_size#1)
// 6 file <built-in-additions> line 23
(14) __CPROVER_max_malloc_size#1 == 36028797018963968ul
// 7 file <built-in-additions> line 17
(15) SHARED_WRITE(__CPROVER_memory_leak#1)
// 7 file <built-in-additions> line 17
(16) __CPROVER_memory_leak#1 == NULL
// 8 file <built-in-additions> line 15
(17) SHARED_WRITE(__CPROVER_new_object#1)
// 8 file <built-in-additions> line 15
(18) __CPROVER_new_object#1 == NULL
// 9 file <built-in-additions> line 8
(19) SHARED_WRITE(__CPROVER_next_thread_id#1)
// 9 file <built-in-additions> line 8
(20) __CPROVER_next_thread_id#1 == 0ul
// 10 file <built-in-additions> line 11
(21) __CPROVER_next_thread_key!0#1 == 0ul
// 11 file <built-in-additions> line 37
(22) SHARED_WRITE(__CPROVER_pipe_count#1)
// 11 file <built-in-additions> line 37
(23) __CPROVER_pipe_count#1 == 0u
// 12 file <built-in-additions> line 28
(24) __CPROVER_rounding_mode!0#1 == 0
// 13 file <built-in-additions> line 6
(25) __CPROVER_thread_id!0#1 == 0ul
// 14 file <built-in-additions> line 10
(26) __CPROVER_thread_key_dtors!0#1 == ARRAY_OF(((const void (*)(const void *))NULL))
// 15 file <built-in-additions> line 9
(27) __CPROVER_thread_keys!0#1 == ARRAY_OF(NULL)
// 16 file <built-in-additions> line 7
(28) SHARED_WRITE(__CPROVER_threads_exited#1)
// 16 file <built-in-additions> line 7
(29) __CPROVER_threads_exited#1 == ARRAY_OF(FALSE)
// 17 
// 26 file ../../examples/test.c line 3
// 27 file ../../examples/test.c line 3
(30) x!0@1#2 == nondet_symbol(symex::nondet0)
// 28 file ../../examples/test.c line 3
// 29 file ../../examples/test.c line 3
// 30 file ../../examples/test.c line 3
(31) y!0@1#2 == nondet_symbol(symex::nondet1)
// 31 file ../../examples/test.c line 3
// 32 file ../../examples/test.c line 3
// 32 file ../../examples/test.c line 3
// 32 file ../../examples/test.c line 3
(32) x!0@1#1 == x!0@1#2
// 32 file ../../examples/test.c line 3
(33) y!0@1#1 == y!0@1#2
// 18 file ../../examples/test.c line 4 function test
(34) x!0@1#2 == x!0@1#1 + y!0@1#1
// 19 file ../../examples/test.c line 5 function test
// 19 file ../../examples/test.c line 5 function test
(35) \guard#1 == !(x!0@1#2 == 1)
// 20 file ../../examples/test.c line 6 function test
(36) x!0@1#4 == 2
     guard: \guard#1
// 21 file ../../examples/test.c line 6 function test
// 22 file ../../examples/test.c line 8 function test
(37) x!0@1#5 == 2
     guard: !\guard#1
// 23 file ../../examples/test.c line 9 function test
(38) x!0@1#6 == 2
// 24 file ../../examples/test.c line 10 function test
// 35 
```

I do not know how I can parse this output and build the boolean formula from that.
Could you please help me? @tautschnig

**Comment by tautschnig** [comment]
Thank you for your feedback. Can you be more specific as to which "CBMC article" you are referring to? One way to get a Boolean formula is using `cbmc --function test ../../examples/test.c --dimacs --outfile /dev/stdout`, but I'm not sure that's the format you are after?

**Comment by mahantaf** [comment]
Yes, the article that I mentioned is [this](http://shelf2.library.cmu.edu/Tech/52490804.pdf)
And saying the boolean formula I mean this image:
<img width="599" alt="Screenshot 2022-01-15 at 10 25 51 PM" src="https://user-images.githubusercontent.com/18045221/149634430-0adf1749-5984-4bbe-830f-ae7d08f77528.png">


Actually, the previous command `--program-only` has some useful output:

```
x!0@1#2 == nondet_symbol(symex::nondet0)
y!0@1#2 == nondet_symbol(symex::nondet1)
x!0@1#1 == x!0@1#2
y!0@1#1 == y!0@1#2
x!0@1#2 == x!0@1#1 + y!0@1#1
\guard#1 == !(x!0@1#2 == 1)
x!0@1#4 == 2
     guard: \guard#1
x!0@1#5 == 2
     guard: !\guard#1
x!0@1#6 == 2
```

Do you know how can I get this output from the complete output of this command? @tautschnig

**Comment by tautschnig** [comment]
I'm glad the output of `--program-only` actually works for you. How about:
```
cbmc --program-only --function test ../../examples/test.c \
  --verbosity 0 | \
  sed -e '1,/^Program constraints:/d' | \
  egrep -v '(^//|__CPROVER)' | \
  sed 's/^([[:digit:]]*) //'
```
You might, of course, choose to implement this text filtering in a different language.

Edit: FWIW, work is underway to reduce the number of `__CPROVER_...` variables when they aren't necessary.

**Comment by mahantaf** [comment]
Yes, it works fine.

Thank you.

I have another question about this output, what are these symbols mean? (for example `!0@1#` in `x!0@1#5 == 2`)

**Comment by tautschnig** [comment]
These are the (extended) SSA indices for the thread (thread 0), function frame (frame 1) and then the assignment count within that frame and thread (assignment 5). There's some documentation in section "Static Single Assignment (SSA) Form" in http://cprover.diffblue.com/group__goto-symex.html#symex-overview.

**Comment by tautschnig** [comment]
Closing as I believe all questions have been addressed. Please feel free to re-open if I missed anything!

**Comment by mahantaf** [comment]
Hi again,

I have a quick question that maybe related to this topic
What is the size of BitVector that CBMC uses? (I mean in bits or bytes)

Thanks

**Comment by tautschnig** [comment]
> Hi again,
> 
> I have a quick question that maybe related to this topic What is the size of BitVector that CBMC uses? (I mean in bits or bytes)
> 
> Thanks

If you are using standard C syntax, CBMC will use the bit widths used on a particular platform and data type (see https://wiki.debian.org/ArchitectureSpecificsMemo, for example). You may, however, also use `__CPROVER_bitvector` to create a variable of non-standard bit width (see https://diffblue.github.io/cbmc/cprover-manual/md_api.html).

**Comment by mahantaf** [comment]
Thank you for your answer.

I have one more question. I actually used the --dmacs option to get the CNF version of a go-to BitVector program from CBMC. I wonder if there are any ways that I can reduce the number of variables and clauses on the 3-CNF generated by CBMC.

**Comment by tautschnig** [comment]
You could use `void test(__CPROVER_bitvector[2] x, __CPROVER_bitvector[2] y)` instead of `void test(int x, int y)`.

**Comment by mahantaf** [comment]
Thank you for your response. I used it and it worked.

I have one more question.
Is there any way to get a CNF formula of a function even when the assertion is passed? Because I can only get the CNF when the assertion is not passed and when the verification is successful it does not return the CNF.

For example, I have this code:
```c++
int sum(int a, int b) {
  return  a - b;
}

void test() {
  int c = sum(2, 2);
  assert(c == 4);
}
``` 
When I run `cbmc --function test sum.c --dimacs` the assertion will fail and I can see the CNF. However, when I run this code:

```c++
int sum(int a, int b) {
  return  a + b;
}

void test() {
  int c = sum(2, 2);
  assert(c == 4);
}
```

It just outputs the verification is successful and I cannot see the corresponding CNF formula.
Do you know how can I obtain it?
@tautschnig

**Comment by tautschnig** [comment]
You could use `--no-propagation` or `--no-simplify` (both of which are intentionally undocumented for they severely hamper performance on larger examples), both of which should make the assertion no longer trivially true.
