### ISSUE TITLE
CBMC should have a versioned brew tap

### ISSUE THREAD

**Issue by danielsn** [diffblue/cbmc#6750]
Currently, the only version of CBMC available on `brew` is the latest. This makes it difficult for tools that wish to pin to particular versions.  The supported path is to have a separate tap that allows versioned CBMC releases https://docs.brew.sh/Versions

This should not be difficult to maintain as part of the existing CBMC release process.

**Comment by tautschnig** [comment]
This has been addressed in #6817.
