### ISSUE TITLE
CBMC accepts `-<hex>` constants at the irep level, but does the wrong thing with them

### ISSUE THREAD

**Issue by danielsn** [diffblue/cbmc#6759]
CBMC should either error, or accept.

**Comment by adpaco-aws** [comment]
Attached [negative-hex-symtab.zip](https://github.com/diffblue/cbmc/files/8342911/negative-hex-symtab.zip) which includes a symbol table that reproduces the issue.

**Comment by adpaco-aws** [comment]
Also, is this something that could have been detected by validating the generated GotoC code?

**Comment by tautschnig** [comment]
This has been fixed in Kani, but I still need to get to the bottom of why this was accepted in the first place.

**Comment by tautschnig** [comment]
#6786 now does what Adrian proposed: `--validate-goto-model` will catch this issue. (The commit message in there also explains what was going with the example attached to this issue.) Kani has an open feature request in model-checking/kani#957 to enable these checks.
