### ISSUE TITLE
Conversion error running cbmc against code from openjdk regression suite

### ISSUE THREAD

**Issue by jgwilson42** [diffblue/cbmc#677]
I ran the command `cmbc Int.class` and got the following output:
```
CBMC version 5.7 64-bit x86_64 linux
Parsing ./Int.class
Java main class: Int
failed to load class `java.lang.Object'
failed to load class `java.lang.Class'
failed to load class `java.lang.String'
Converting
main method `Int' has no body
CONVERSION ERROR
```

The code for Int.class (taken from openjdk 1.8 regression tests) is:
```
class Int {
    Integer x;
    Int(int i) {x = new Integer(i);}
    public boolean equals(Object o) {
        Thread.yield();
        Int i = (Int)o;
        return x.equals(i.x);
    }

    public int hashCode() {return x.hashCode();}
}
```
The conversion error looks worrying to me, also running the same test against cbmc from around March 11th does not give the conversion error.

Please could you let me know what the CONVERSION ERROR means and if it should occur under these circumstances?

**Comment by jgwilson42** [comment]
The command to run this is `timeout 300 cbmc Int.class`

**Comment by TGWDB** [comment]
This does not appear to be a problem in the current version of jbmc. Please reopen if you believe closing this issue is erroneous.
