### ISSUE TITLE
`__CPROVER_allocated_memory` is undocumented

### ISSUE THREAD

**Issue by thomasspriggs** [diffblue/cbmc#6870]
I have not been able to find any existing documentation of the `__CPROVER_allocated_memory` intrinsic function. Without documentation of this intrinsic and its current implementation / intended use case it is non-trivial to work out what aspects of its observed functionality are intended or are bugs with the current implementation.

CBMC version:
Operating system:
Exact command line resulting in the issue:
What behaviour did you expect:
What happened instead:

**Comment by feliperodri** [comment]
[@diffblue/diffblue-opensource](https://github.com/orgs/diffblue/teams/diffblue-opensource)

**Comment by thomasspriggs** [comment]
I believe the current plan is to remove it. Therefore adding documentation beyond "This is deprecated. Don't use it." Wouldn't really be useful.

**Comment by thomasspriggs** [comment]
Aha! Documentation of the current behaviour is here - https://github.com/diffblue/cbmc/pull/7157
See also -

-  https://github.com/diffblue/cbmc/issues/6997
-  https://github.com/diffblue/cbmc/pull/6876
- https://github.com/diffblue/cbmc/issues/6871
- https://github.com/diffblue/cbmc/issues/6695

**Comment by tautschnig** [comment]
Closing via #7157.
