### ISSUE TITLE
clang support?

### ISSUE THREAD

**Issue by xx24678** [diffblue/cbmc#6906]
CBMC version: CBMC version 5.56.0 (cbmc-5.56.0) 64-bit x86_64 linux
Operating system: Linux
Exact command line resulting in the issue: goto-cc --verbosity=5 --native-compiler=clang -target aarch64-linux-gnu -c test.c -o test.o
What behaviour did you expect: CBMC correctly build the target code with all the args passed to clang compiler
What happened instead: it doesn't recognize the "-target" arg, and considers the `aarch64-linux-gnu` as the input file and causing problems.

**Comment by tautschnig** [comment]
Thank you for your report! #6908 (once merged) will address this issue.
