### ISSUE TITLE
goto-cc and goto-ld not generating valid object/elf files

### ISSUE THREAD

**Issue by xx24678** [diffblue/cbmc#6907]
CBMC version: CBMC version 5.56.0 (cbmc-5.56.0) 64-bit x86_64 linux
Operating system: Linux
Exact command line resulting in the issue: goto-cc test.c -o test && file test
What behaviour did you expect: the result "test" should be a valid elf file generated with the default compiler invoked by goto-cc
What happened instead: the result file is shown as data file

For complex firmware projects, the result binaries are usually manipulated by various GNU tools such as objcopy, etc. Those tools requires valid elf files otherwise will fail the build. This make it harder to do dropin compiler replacement with CBMC's `goto-cc` and `goto-ld` approach. Is it possible to modify this tool to generate valid object or elf files with the CBMC generated metadata either attached to the result file or stored in a separate file?

For example, if I run `goto-cc test.c -o test && file test`, the result file `test` should be valid elf files generated by the gcc tool; Any CBMC generated data should be either appended to the test file (without invalidating the file format). I don't know if this is possible, but if not, an alternative solution is to store it in a file whose name can be derived from the result file, for example, `test.cbmc`, or something similar.

With this, we can make dropin toolchain replacement and still get successful build.

**Comment by kroening** [comment]
You get the result you expect by using `goto-gcc` instead of `goto-cc`.

**Comment by xx24678** [comment]
thanks for the hint. That works.
