### ISSUE TITLE
[Question] JBMC and BigInteger: example

### ISSUE THREAD

**Issue by PeterMacGonagan** [diffblue/cbmc#6933]
Hello,

I'm trying to do some tests with BigInteger and JBMC. I've already done basic tests with integers with success.
But I don't get the correct answer with BigInteger.

Here is my code:

```
package my.petty.examples;

import java.math.BigInteger;
import org.cprover.CProver;
import static org.cprover.CProver.assume;

public class Simple {
    public static void main(String[] args) {
        CProver.enableNondet = false;
        CProver.enableAssume = false;
        CProver.enableConcurrency = false; 
        
        int unknown = CProver.nondetInt();
        assume(unknown>=0);
        assume(unknown<Integer.MAX_VALUE);
        
        BigInteger x = BigInteger.valueOf(unknown);        
        BigInteger y = BigInteger.valueOf(2);
        BigInteger r = y.add(x); //r=y+x

        //to get the value... in correct  format
        var xval = x.intValue();
        System.out.println("x=" + xval);
        
        //to change assert
        var rval = r.toString(); 
        //var rval = r.intValue(); 
        
        assert(!rval.equals("5")); //BUG if 
        //assert(rval!=5); //BUG if 
        //assert(r.compareTo(BigInteger.valueOf(5)) == 0); //BUG if 
    }
}
```

I don't get the correct answer. xval is equal to 0.
Note: convert BigInteger value to int or string because there are encoded in big endian and two-complement format.

Here is my command:
`jbmc -jar dist\testjbmc_bigint.jar --trace --java-assume-inputs-non-null --max-nondet-string-length 1024`

Could you help me, please? I just need a simple example with  BigInteger.

Thank you in advance.
Best Regards,
Peter

**Comment by tautschnig** [comment]
I should defer to @peterschrammel or @romainbrenguier for more authoritative answers, but I believe the problem here is that we don't ship a model of `java.math.BigInteger`. Any methods called from this package will return non-deterministic values.

**Comment by romainbrenguier** [comment]
@tautschnig is right, we don't ship a model of BigInteger in our models, see https://github.com/diffblue/java-models-library repository. You would need to add a model of this class to get non-deterministic values

**Comment by martin-cs** [comment]
Although this would be limited to the SMT back-end and might well be A Bad Idea in terms of performance.  Could it be modelled with `__CPROVER_integer`?

**Comment by PeterMacGonagan** [comment]
Ok, so it's not possible to use BigInteger. How hard is it to add it to the java-models-library?

**Comment by peterschrammel** [comment]
> How hard is it to add it to the java-models-library?

[BigInteger.java](https://github.com/keerath/openjdk-8-source/blob/master/jdk/src/share/classes/java/math/BigInteger.java) and dependent classes need to be added to java-models-library.
For many Java library classes, it's just sufficient to copy them.
Sometimes, however, the implementations are complex and often need simplification in order to be handled reasonably by JBMC. Such simplifications may include removing execution-performance related optimisations, e.g. caches; taking advantage of non-determinism + assume; or potentially more efficient backend encodings as @martin-cs is hinting at.

**Comment by martin-cs** [comment]
I have not looked at the Java BigInteger implementation but from looking at other BigNum implementations, modelling it, even with mathematical integers, may well perform better than using the literal implementation.

**Comment by PeterMacGonagan** [comment]
I could use an other library if it's more easier...
I'm not stuck with BigInteger but I need to perform at least computations on 256 bits numbers.

**Comment by martin-cs** [comment]
If you know the highest bit-width you want to use then `__CPROVER_bitvector` is probably a good bet.  But be aware that large bit-width non-linear problems are considered to be a Hard Problem and a subject of ongoing research by myself and others.

**Comment by PeterMacGonagan** [comment]
I already know for hard problem :) It's a very interesting.
I didn't know __CPROVER_bitvector, I'll try to use it.
Without support to BigInteger, I think that I'll use CMBC and try to implement my own library. I've already got some examples which works.
Thank you for your support.
