### ISSUE TITLE
[QUESTION] How to print the value of variables during CBMC's loop unwinding

### ISSUE THREAD

**Issue by eleehiga** [diffblue/cbmc#6953]
During loop unwindings. Like this example:
```
Unwinding loop strtod.0 iteration 15 file ../proof_helpers/functions.c line 37 function strtod thread 0
Unwinding loop time_to_sec.0 iteration 1 file ../test_code/snore.c line 80 function time_to_sec thread 0
Unwinding loop time_to_sec.0 iteration 2 file ../test_code/snore.c line 80 function time_to_sec thread 0
Unwinding loop time_to_sec.0 iteration 3 file ../test_code/snore.c line 80 function time_to_sec thread 0
Unwinding loop time_to_sec.0 iteration 4 file ../test_code/snore.c line 80 function time_to_sec thread 0
Unwinding loop time_to_sec.1 iteration 1 file ../test_code/snore.c line 72 function time_to_sec thread 0
Unwinding loop strtod.0 iteration 1 file ../proof_helpers/functions.c line 37 function strtod thread 0
```
Is there a way I can print the value or variables, like the variable `i`?

**Comment by tautschnig** [comment]
The closest you can get to seeing this _during_ symbolic execution is by running with `--verbosity 10`. Afterwards, however, you could also read it from the trace, but that likely does not match your expectation of "during CBMC's loop unwinding."

**Comment by eleehiga** [comment]
@tautschnig thank you, but how would you recommend me to debug why my program is having infinite loop unwindings? This is as I tried `--verbosity 10` but am having a hard time understanding the messages from that.

**Comment by tautschnig** [comment]
I just want to make sure I correctly understand your question: If you genuinely want to debug _why CBMC is struggling_ to determine the loop bound, then the following instructions may help. If, however, you just want to make sure CBMC does not keep unwinding, you'll want to use `--unwind` or `--unwindset`.

So if you genuinely want to debug, the following my help:
1. Run CBMC with some finite unrolling bound and add --program-only, piping the output to some text file.
2. Search for the source location where you expect the constant to appear. It may also help to have the output of --dump-c at hand for a good way to make sense of the variable names.
3. If you can manage to find the assignment/equality that doesn't have the expected constant on the right-hand side, work backwards from that right-hand side to see where you last had a constant. (Reverse-searching the right-hand side, which will then be a left-hand side, then again searching for the right-hand side of that equation, rinse and repeat.)
4. The expression where you flip from is-a-constant to is-a-symbol is the culprit.

**Comment by eleehiga** [comment]
@tautschnig Thank you as I genuinely want to debug. What do you mean by the "the source location where you expect the constant to appear"? Also it seems like --dump-c is not an option for CBMC, therefore is there another way you would recommend me to "make sense of the variable names"?

**Comment by tautschnig** [comment]
My apologies for slightly too terse an instruction! When I was referring to `--dump-c` I was thinking of `goto-instrument`'s option, but you might not even have to use this for your input is C code anyway, so just ignore that part of my advice. For the source location, however, this is the place in your original source code where you expected constant propagation to succeed. In the context of loops, it'll be the loop head that checks the condition. From the snippet you posted it might be `../test_code/snore.c line 80`.

**Comment by eleehiga** [comment]
@tautschnig No problem and that sounds good. But what do you mean by "assignment/equality that doesn't have the expected constant on the right-hand side"?

**Comment by tautschnig** [comment]
CBMC will stop unwinding a loop when it can determine that the loop condition necessarily evaluates to false. The only way that CBMC, at present, can do so is when this evaluation can be completed by the combined application of constant propagation and algebraic simplification. Therefore, it will be necessary that whatever contributes to the loop condition, for example a loop counter, evaluates to a constant. Consider the following example:
````c
// for.c
int main()
{
  for(int i=0; i<5; ++i)
    ;
}
````
Running `cbmc for.c --program-only` yields (among other output):
```
// 25 file for.c line 1
// 0 file for.c line 3 function main
// 1 file for.c line 3 function main
(26) i!0@1#2 == 0
// 2 file for.c line 3 function main
// 3 file for.c line 3 function main
(27) i!0@1#3 == 1
// 4 file for.c line 3 function main
// 2 file for.c line 3 function main
// 3 file for.c line 3 function main
(28) i!0@1#4 == 2
// 4 file for.c line 3 function main
// 2 file for.c line 3 function main
// 3 file for.c line 3 function main
(29) i!0@1#5 == 3
// 4 file for.c line 3 function main
// 2 file for.c line 3 function main
// 3 file for.c line 3 function main
(30) i!0@1#6 == 4
// 4 file for.c line 3 function main
// 2 file for.c line 3 function main
// 3 file for.c line 3 function main
(31) i!0@1#7 == 5
```
As you can see, (the SSA renamed version of) `i` has a constant as the right-hand side of each equality. CBMC, therefore, is able to determine that eventually `i < 5` no longer holds, and stops unwinding the loop.

Now consider the following variant of the program:
````c
int nondet_int();

int main()
{
  int n = nondet_int();
  for(int i=0; i<5; ++i)
    i += n;
}
````
In this case, a non-deterministic value is chosen and then added to `i` in each loop iteration. CBMC will no longer be able to determine when to stop unwinding the loop. Let's look at the output of `cbmc for.c --program-only --unwind 3` (the use of `--unwind` is now strictly necessary):
```
// 32 file for.c line 3
// 0 file for.c line 5 function main
// 1 file for.c line 5 function main
// 2 file for.c line 5 function main
(26) return_value_nondet_int!0@1#2 == nondet_symbol(symex::nondet0)
// 3 file for.c line 5 function main
(27) n!0@1#2 == return_value_nondet_int!0@1#2
// 4 file for.c line 6 function main
// 5 file for.c line 6 function main
(28) i!0@1#2 == 0
// 6 file for.c line 6 function main
// 7 file for.c line 7 function main
(29) i!0@1#3 == n!0@1#2
// 8 file for.c line 6 function main
(30) i!0@1#4 == i!0@1#3 + 1
// 9 file for.c line 6 function main
// 6 file for.c line 6 function main
// 6 file for.c line 6 function main
(31) \guard#1 == !(i!0@1#4 >= 5)
// 7 file for.c line 7 function main
(32) i!0@1#5 == i!0@1#4 + n!0@1#2
     guard: \guard#1
// 8 file for.c line 6 function main
(33) i!0@1#6 == i!0@1#5 + 1
     guard: \guard#1
// 9 file for.c line 6 function main
// 6 file for.c line 6 function main
// 6 file for.c line 6 function main
(34) \guard#2 == !(i!0@1#6 >= 5)
// 7 file for.c line 7 function main
(35) i!0@1#7 == i!0@1#6 + n!0@1#2
     guard: \guard#1 && \guard#2
// 8 file for.c line 6 function main
(36) i!0@1#8 == i!0@1#7 + 1
     guard: \guard#1 && \guard#2
// 9 file for.c line 6 function main
// 9 file for.c line 6 function main
(37) ASSUME(!(\guard#1 && \guard#2))
     guard: \guard#1 && \guard#2
// 10 file for.c line 7 function main
(38) i!0@1#9 == (\guard#1 ? i!0@1#6 : i!0@1#4)
// 13 file for.c line 8 function main
```
As you can see, only `i!0@1#2 == 0` has a constant as right-hand side, but all subsequent assignments to `i` have non-constant right-hand sides.

**Comment by eleehiga** [comment]
@tautschnig I understand and I will look for this, thank you.
