### ISSUE TITLE
What does `Loop invariant is not side-effect free` mean?

### ISSUE THREAD

**Issue by eleehiga** [diffblue/cbmc#6955]
For the following code:
```
#include <errno.h>
#include <limits.h>
#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

void test(char *s) {
	char *string_end;
	string_end = s + strlen(s);
	while(s < string_end)
		__CPROVER_loop_invariant(s > 0 && string_end > 0 && s[strlen(s)-1] == '\0')
		__CPROVER_decreases(string_end-s)
		{
			s++;
		}
}
```
Running the command `cbmc test.c --function test` yielded the following output:
```
CBMC version 5.58.0 (cbmc-5.58.0) 64-bit x86_64 linux
Parsing test.c
Converting
Type-checking test
Generating GOTO Program
Loop invariant is not side-effect free. (at: file test.c line 12 function test)
```
In that output I was wondering what the line `Loop invariant is not side-effect free` means?

**Comment by tautschnig** [comment]
Your loop invariant includes a call to `strlen`. We currently don't support function calls in loop invariants (or function contracts), even when those particular functions might be pure and not have side effects.

**Comment by eleehiga** [comment]
@tautschnig Thank you and hopefully you guys do support this in the future.
