### ISSUE TITLE
Document MMIO behaviour

### ISSUE THREAD

**Issue by danielsn** [diffblue/cbmc#6997]
Currently, there is no documentation for how `mmio` works and what its semantics is. Anyone using `mmio` will need documentation.

**Comment by jimgrundy** [comment]
Why is this medium @danielsn now that the allocated_memory is deprecated?

**Comment by jimgrundy** [comment]
I'm dropping "medium" as I don't know of a driving use case right now. Feel free to restore if you do @danielsn

**Comment by markrtuttle** [comment]
For the record, there is some description of the MMIO functionality in the CAV paper that added it:  https://link.springer.com/content/pdf/10.1007/s10703-020-00344-2.pdf
