### ISSUE TITLE
History variables treated as function calls with side effects within quantified expressions

### ISSUE THREAD

**Issue by akshayutture** [diffblue/cbmc#6998]
**CBMC version:** 5.60.0
**Operating system:** MacOS Monterey (12.3.1)

**Input file:**
```c
#include <stdlib.h>
main() {  
  int a[4];  
  for (int i = 0 ; i < 4 ; i++)
  __CPROVER_loop_invariant(__CPROVER_forall{ int j;
        (0 <= j && j < 4) 
        ==> (a[j]==__CPROVER_loop_old(a[j]))
  });
}
```

**Exact command line resulting in the issue:**
```console
$ goto-cc -o main.o main.c
main.c: In function 'main':
main.c:6:1: error: quantifier must not contain side effects
   __CPROVER_loop_invariant(__CPROVER_forall{ int j; 
CONVERSION ERROR
```

**What behaviour did you expect:** Code would successfully compile

**What happened instead:** goto-cc complained that the quantifier should not contain side effects. Removing `__CPROVER_loop_old()` makes the error disappear. Hence, the issue may potentially be that history variables  (i.e. `__CPROVER_loop_old(..)`) are treated as function calls with side effects inside loop contracts.

(This issue does not occur for the use of `__CPROVER_old()` in function contracts)

**Comment by SaswatPadhi** [comment]
Closing this as `__CPROVER_loop_old` is currently unsupported (#6302) and is expected to be compiled as a function call.

We should be using `__CPROVER_loop_entry` here, and that works as expected.
