### ISSUE TITLE
Add CBMC internal variable names to JSON goto trace output

### ISSUE THREAD

**Issue by forejtv** [diffblue/cbmc#70]
...to be able to distinguish e.g. global/local variables.

**Comment by peterschrammel** [comment]
why is this needed?

**Comment by forejtv** [comment]
from what I remember the problem was that from current errortrace files it is not possible to identify some of the variables uniquely, when global and local names coincide. This can then be an issue when visualising the trace, or when analysing it (e.g. using ML algorithms)

**Comment by peterschrammel** [comment]
Ok. That needs further clarification with @dcattaruzza and @aabate what "identify some of the variables uniquely" means, how this information is going to be used and what is the most appropriate solution.
