### ISSUE TITLE
How does JBMC detect a null pointer exception?

### ISSUE THREAD

**Issue by piyush-J** [diffblue/cbmc#7043]
Hi,

Thank you for this amazing project!

I am new to the field of verification. I was curious **how does JBMC verify a null pointer exception**? 

I have been using a Static Program Analysis (SPA)-based tool called [CheckerFramework](https://checkerframework.org/manual/#nullness-checker) to detect null pointer exceptions. I understand that JBMC is a Bounded Model Checker, so in simplified terms - it would create an SAT/SMT formula to find an assignment that results in a null dereference in the program, **is that correct**? 

I understand that JBMC would have no false positives, while CheckerFramework might. However, are there any **disadvantages** of using JBMC apart from the scalability issue? 

Lastly, can JBMC also **support the pluggable type qualifiers** as used by Nullness Checker in CheckerFramework?

Any help in this regard would be really useful. Thanks in advance!

--------------

EDIT: 

I just read this in the CAV 2018 JBMC paper:

> ESC/Java is a compile-time extended static checker, which detects common programming errors (e.g., null dereference, array bounds errors, and type cast errors)

So, does this mean that the null pointer check involves SPA (and not model checking) in JBMC?

**Comment by martin-cs** [comment]
@piyush-J @peterschrammel is the expert here so I will let him answer but a small advert first : `goto-analyzer` is our abstract interpreter which will work more like the CheckerFramework.  I don't know pluggable type qualifiers but there are quite a lot of interfaces in `goto-analyzer` in which you could add code to.  Hope this is of some interest / entertainment.

**Comment by peterschrammel** [comment]
> it would create an SAT/SMT formula to find an assignment that results in a null dereference in the program, is that correct?

Yes, that's correct.

> I understand that JBMC would have no false positives, while CheckerFramework might. 

This is true, in principle, but it depends on the properties of the models that you use for the libraries that your code depends on. The practical situation may be quite confusing: JBMC's models library (core-models.jar) is under-approximating (up to bugs). If your code uses methods that are not part of the models then the behaviour of these methods can be a mixture of under- and over-approximating behaviour. So, to avoid false positives, all methods used by your code need to have an under-approximating model.

> are there any disadvantages of using JBMC apart from the scalability issue?

The main disadvantage is scalability. This is also the reason why it is usually not possible to include the code of all dependent libraries in the analysis and models are used to replace their behaviour.

> can JBMC also support the pluggable type qualifiers as used by Nullness Checker in CheckerFramework?

JBMC supports `javax.validation.constraints.NotNull`and the corresponding Eclipse and JetBrains equivalents.

**Comment by piyush-J** [comment]
Thank you so much for your prompt responses @martin-cs and @peterschrammel!
