### ISSUE TITLE
A bug in SMT2 converter

### ISSUE THREAD

**Issue by hflsmax** [diffblue/cbmc#7053]
CBMC version: 5.11
Operating system: Ubuntu 20.04
Exact command line resulting in the issue: cbmc --z3 alias.c
What behaviour did you expect:
Should see assertion fail without any error
What happened instead:
Saw error message 
```
SMT2 solver returned error message:
        "line 55 column 120: operator is applied to arguments of the wrong sort"
```

Minimal reproducible program `alias.c`
```
#include <assert.h>

struct s {
    char a;
    char b[1];
};


int main() {
    struct s s1[1];
    char k;
    char *t = s1[0].b + k;
    *t = 42;
    assert(0);
}
```

**Comment by kroening** [comment]
This works with 5.62.0 -- may I suggest an update.

**Comment by hflsmax** [comment]
Thanks. I can confirm it works on newer version.
