### ISSUE TITLE
JBMC not creating outfile for smt backends

### ISSUE THREAD

**Issue by JonasKlamroth** [diffblue/cbmc#7071]
Im trying to have a look at the smt2 output of jbmc for some program. However when running jbmc with "--outfile file" no file is created. In particular it seems that the smt solver e.g. z3 isnt even used when running with --z3. 

CBMC version: 5.63.0
Operating system: ubuntu-20.04
Exact command line resulting in the issue: jbmc Test --function Test.m --z3 --outfile out.smt2
What behaviour did you expect: 
- the file "out.smt2" is created and contains some smt2 content
- similar to running a similar command with cbmc instead of jbmc the output indicates that an smt solver is called rather than a sat solver

What happened instead:
- no file is created
- the output still says: "SAT checker: instance is SATISFIABLE" no sign of an smt solver being called

As mentioned above if i do the same with cbmc and a similar file the expected behaviour is what happens.

Test.java:

```
public class Test {
      private int privInt = 0;
      public int pubInt = 0;
      public void m() {
          Test t = new Test();
          t.pubInt = 5;
          this.privInt = 4;
          int x = t.pubInt + this.privInt;
  
          assert x == 8;
      }
  }
```

**Comment by peterschrammel** [comment]
External SMT solvers are not supported by JBMC.
Clearly, the unsupported options (that were just inherited from CBMC) should be removed from the command line interface.

**Comment by JonasKlamroth** [comment]
ok thanks for the quick reply
