### ISSUE TITLE
`dirtyt` analysis and `OTHER` instructions ?

### ISSUE THREAD

**Issue by remi-delmas-3000** [diffblue/cbmc#7072]
CBMC version: 5.63.0 (cbmc-5.63.0-41-g5a7a0a8801-dirty)
Operating system: macOS

`dirtyt` uses `goto_programt::instructiont::apply` to search for dirty symbols in instructions. `goto_programt::instructiont::apply`  only visits the contents of an `OTHER` instruction if its `statement` attribute is an `ID_expression` :

```cpp
void goto_programt::instructiont::apply(
  std::function<void(const exprt &)> f) const
{
  switch(_type)
  {
  case OTHER:
    if(get_other().get_statement() == ID_expression)
      f(to_code_expression(get_other()).expression());
    break;
 ....
}
```

Since OTHER operations can also have `statement` be equal to `ID_array_set`, `ID_array_copy`, `ID_array_replace`, `ID_asm`, etc. is it possible that `dirtyt` would miss anything of importance ?

**Comment by martin-cs** [comment]
Using `OTHER` for array copy and replace (rather than using builtin functions) feels like a mistake.  It certainly wasn't implemented uniformly and the handling of `OTHER` is patchy at best.  See https://github.com/diffblue/cbmc/issues/4323 for the last discussion of this.  I think I agree with the conclusion that `OTHER` should be replaced or at least minimised, especially given the growth of use of builtin functions.

**Comment by tautschnig** [comment]
Notwithstanding what @martin-cs said: the changes in #7085 should be moved to the actual `dirtyt` implementation instead of code contracts rolling its own.

**Comment by martin-cs** [comment]
Agree with @tautschnig .  Let's not have multiple copies of the same code again; it takes ages to de-duplicate them.

**Comment by jimgrundy** [comment]
So, who's moving this code then? Michael seems to be doing a bunch of stuff, should we assign Remi?

**Comment by remi-delmas-3000** [comment]
I can take the action. If things break as a result I might need help.

**Comment by remi-delmas-3000** [comment]
> Notwithstanding what @martin-cs said: the changes in https://github.com/diffblue/cbmc/pull/7085 should be moved to the actual `dirtyt` implementation instead of code contracts rolling its own.

Could we also consider modifying `goto_programt::instructiont::apply` to traverse all subnodes of `OTHER` instructions and not just ID_expression ?

**Comment by martin-cs** [comment]
On Tue, 2022-09-06 at 13:59 -0700, Rémi Delmas wrote:
> I can take the action. If things break as a result I might need help.

Happy to help if needed.

**Comment by martin-cs** [comment]
> Could we also consider modifying goto_programt::instructiont::apply
> to traverse all subnodes of OTHER instructions and not just
> ID_expression ?

Yes... unfortunately there is not a complete list of what this can be
or what the intended semantics are.  
https://github.com/diffblue/cbmc/issues/4323 is my best attempt.

To be honest, I think we should just remove OTHER or at least give it a
semantics of "It is fine to ignore these" or "If you find an OTHER that
you do not recognise, it could do *anything*, including havoc and non-
termination".

**Comment by remi-delmas-3000** [comment]
Fixed by https://github.com/diffblue/cbmc/pull/7106
