### ISSUE TITLE
Rendered doxygen is out of date and needs further work

### ISSUE THREAD

**Issue by tautschnig** [diffblue/cbmc#7112]
This is a specific aspect of #7006: unless we decide to abandon doxygen in favour of some other documentation approach, the following need to be addressed:

- [ ] http://cprover.diffblue.com is out of date (as can be seen by comparing http://cprover.diffblue.com/md__home_travis_build_diffblue_cbmc_doc__a_d_r_release_process.html and its source https://github.com/diffblue/cbmc/blob/develop/doc/ADR/release_process.md)
- [ ] We need an improved doxygen front page that makes clear that this is seriously maintained documentation.
- [ ] It may be preferable to use GitHub pages (either diffblue.github.io or cprover.github.io) over cprover.diffblue.com (which also triggers a warning when trying to use HTTPS).

**Comment by tautschnig** [comment]
Pinging some people here: @NlightNFotis @jimgrundy @remi-delmas-3000

**Comment by jimgrundy** [comment]
Also pinging @markrtuttle

**Comment by jimgrundy** [comment]
It seems like the natural place to host documentation for github.com/diffblue/cbmc is diffblue.github.io. Unless... deep breath, we want to think about moving github.com/diffblue/cbmc over to github.com/cprover/cbmc, but maybe we can contemplate that for later and for now do diffblue.github.io

**Comment by markrtuttle** [comment]
See comment https://github.com/diffblue/cbmc/issues/7006#issuecomment-1245848220 for some discussion.

**Comment by tautschnig** [comment]
I believe this can be closed once 1) #7149 is merged and 2) the gh-pages publication is enabled. The latter requires action from people with admin permissions, hence my assignment to people who I believe have these.

**Comment by tautschnig** [comment]
Closing as https://diffblue.github.io/cbmc/ is now live.
