### ISSUE TITLE
[QUESTION] controlling the degree of parallelism in CBMC

### ISSUE THREAD

**Issue by pietrobraione** [diffblue/cbmc#7138]
We are doing some experiments with multiple CBMC instances running concurrently on a multi-core machine. As I understand CBMC parallelizes its work across multiple threads. To make our experiments more reproducible we would like to be sure that, when a CBMC instance runs, it may use at most N cores, with N fixed. Is there a way to configure that?

**Comment by tautschnig** [comment]
At present (though this may change in future), CBMC does _not_ use multi-threading (unless you choose to use a solving back-end that itself uses multiple threads), unless you are making use of the script added in #6895.

**Comment by thomasspriggs** [comment]
I am going to close this issue out as it appears to have been comprehensively answered and there has been no further response from the person raising it. Please feel free to re-open if you have further related queries.
