### ISSUE TITLE
"__CPROVER_printf()" doesn't support '%ld", "%hd" and "%Lf"

### ISSUE THREAD

**Issue by rladydpf1** [diffblue/cbmc#7147]
CBMC version: 5.43
Operating system: ubuntu 20.04
Exact command line resulting in the issue: cbmc --trace test.c
What behaviour did you expect:
```
Trace for main.assertion.1:
10
10
10
10.0
10.0
```
What happened instead:
```
Trace for main.assertion.1:
%ld
%llu
%hhd
%lf
%Lf
```

test.c:
```
int main() {
    __CPROVER_printf("%ld", 10);
    __CPROVER_printf("%llu", 10);
    __CPROVER_printf("%hhd", 10);
    __CPROVER_printf("%lf", 10.0);
    __CPROVER_printf("%Lf", 10.0);
    assert(0);
}
```

**Comment by tautschnig** [comment]
Note to self: this requires extending `printf_formattert::process_format` to handle length modifiers.
