### ISSUE TITLE
In this specific program, `goto-cc` can be used to generate goto files  in the `x86` architecture. However, in the `arm64` architecture, an error is reported.

### ISSUE THREAD

**Issue by Jerry-zhxf** [diffblue/cbmc#7156]
**CBMC version**: 5.65.1 (cbmc-5.65.1)
**Architecture**: arm64
**OS**: linux
**gcc**: 9.4.0
**Exact command line resulting in the issue**:
```
goto-cc  --export-file-local-symbols -Wall --object-bits 8  -I/root/test_bug /root/test_bug/test.c /root/test_bug/test1.c /root/test_bug/test2.c -o /root/test_bug/gotos/project1.goto
```
**Program**:
test.h
```
#include <stdbool.h>

bool util_func(int a)
__CPROVER_ensures(__CPROVER_return_value == true || __CPROVER_return_value == false)
{
    if (a > 0) {
        return true;
    } else {
        return false;
    }
}

int test1(int a);
int test2(int a);

void top_func(int a, int b);
```
test1.c
```
#include "test.h"

int test1(int a)
{
    return util_func(a);
}
```
test2.c
```
#include "test.h"

int test2(int a)
{
    return util_func(a);
}
```
test.c
```
#include "test.h"

void top_func(int a, int b) {
    if (a > 0) {
        test1(b);
    } else {
        test2(b);
    }
}
```
**What behaviour did you expect**:
```
CBMC version: 5.60.0 (cbmc-5.60.0)
Architecture: x86_64
OS: linux
gcc: 9.4.0
```
In the above environment, the program can generate goto files normally.
![image](https://user-images.githubusercontent.com/36923038/192282817-f587aaa2-b32a-4f8e-9ecc-79f735d071e3.png)

**What happened instead(in arm64)**:
![image](https://user-images.githubusercontent.com/36923038/192281736-00f681d4-1bde-4f15-96c9-9ccc174cba56.png)

**Comment by tautschnig** [comment]
I'll take a look at fixing what we do about linking code contracts.
