### ISSUE TITLE
Partial correctness with cyclic dependencies of recursive functions

### ISSUE THREAD

**Issue by feliperodri** [diffblue/cbmc#7187]
CBMC version: 5.67.0
Operating system: N/A

Consider the following `test.c` file:

```c
int a(unsigned i)
  __CPROVER_requires(i <= 1)
  __CPROVER_ensures(
      false
  )
{
    return i == 0 ? i : b(i - 1);
}

int b(unsigned i)
  __CPROVER_requires(i <= 1)
  __CPROVER_ensures(
      false
  )
{
    return i == 0 ? i : a(i - 1);
}
```

We observe the following behavior with CBMC currently:
 * Running `--enforce-contract a` produces a proof failure, as expected
 * Running `--enforce-contract a --replace-call-with-contract b` produces no failures, and verification succeeds!
 * Of course, we haven’t verified the contract b and so unsoundness on replacing its contract is not surprising. Similarly, if we instead do `--enforce-contract a --replace-call-with-contract b` first, that would produce no failures either; `a` and `b` are semantically equivalent indeed.

The problem here is that we can’t use the following principle for (mutually) recursive functions:
> enforce contracts on the function being verified, replace calls to all others with their contracts

This principle above is fine for all non-recursive cases, and for recursive cases we should be checking the call graph and showing a error so as to prevent possibly unsound results

We should look into the call graph of the called functions and check for possible recursion. We should make sure that transitive closure of all enforced functions are completely disjoint from transitive closure of all replaced functions

Possible solutions in this could be:
* [short term] fail with an error — Possibly unsound replacement of 'b' was requested
* [long term] generate a warning and inline the called function:
  * warning — Refusing to replace ‘b’ with its contract since it calls the enforced function 'a'
  * then, inline the function b within the body of a

**Comment by feliperodri** [comment]
@remi-delmas-3000 haven't you address this issue with the latest DFCC work?

**Comment by remi-delmas-3000** [comment]
It seems like injecting `assume(false);` when replacing `a`'s or `b`'s call by its contract is the core problem here, not so much mutual recursion. A genuine solution would be vacuity and sensitivity checking for contracts (independently of the function that implements the contract).

However, experimenting with CBMC v5.71.0, I cannot reproduce the problem described in the issue (i.e. proving false):

Checking `a` without replacing `b` fails during instrumentation (recursive call to `a` detected):
```
❯ goto-instrument --enforce-contract a a.out b.out
Reading GOTO program from 'a.out'
Function Pointer Removal
Virtual function removal
Cleaning inline assembler statements
Enforcing contracts
file rec.c line 19 function b: recursion is ignored on call to 'a'
Recursive call to 'a' during inlining
Numeric exception : 0
```

Instrumenting `a` while replacing `b` succeeds, but the analysis fails to prove the post condition of `a`:

```c
❯ goto-instrument --enforce-contract a --replace-call-with-contract b a.out b.out
Reading GOTO program from 'a.out'
...
Writing GOTO program to 'b.out'

❯ cbmc b.out
CBMC version 5.71.0 (cbmc-5.71.0-45-g3815192387) 64-bit x86_64 macos
Reading GOTO program from file b.out
...

** Results:
rec.c function a
[a.postcondition.1] line 7 Check ensures clause: FAILURE

rec.c function b
[b.precondition.1] line 10 Check requires clause of b in a: SUCCESS

** 1 of 2 failed (2 iterations)
VERIFICATION FAILED
```

Contracts with DFCC has experimental support for recursive functions using `--enforce-contract-rec`.

```c
// in rec.c
#include <stdlib.h>
#include <stdbool.h>

int a(unsigned i)
  __CPROVER_requires(i <= 1)
  __CPROVER_ensures(
      false
  )
{
    return i == 0 ? i : b(i - 1);
}

int b(unsigned i)
  __CPROVER_requires(i <= 1)
  __CPROVER_ensures(
      false
  )
{
    return i == 0 ? i : a(i - 1);
}

int main() {
    unsigned i;
    a(i);
}
```

We instrument contract checking for `a` without replacing b by its contract :

```c
❯ goto-cc rec.c
❯ goto-instrument --dfcc main --enforce-contract-rec a a.out b.out
❯ cbmc b.out
...
[a.precondition.1] line 5 Check requires clause of contract contract::a for function a: SUCCESS
[a.postcondition.1] line 7 Check ensures clause of contract contract::a for function a: FAILURE

** 1 of 48 failed (2 iterations)
VERIFICATION FAILED
```

**Comment by remi-delmas-3000** [comment]
With DFCC, whenever `--enforce-contract f` is used, a dynamic check is inserted to detect reentering `f` while checking it and fail the analysis (`--enforce-contract-rec f` must be used to handle recursive calls to `f` by checking the preconditions of the contract and assuming the postconditions on the recursive call).

So I was expecting to have the dynamic recursion check fail when using `--enforce-contract a` instead of `--enforce-cotnract-rec a`, but it is not the case:

```c
❯ goto-instrument --dfcc main --enforce-contract a a.out b.out
...
Writing GOTO program to 'b.out'

❯ cbmc b.out
CBMC version 5.71.0 (cbmc-5.71.0-45-g3815192387) 64-bit x86_64 macos
...
rec.c function a
[a.no_recursive_call.1] line 4 No recursive call to function a when checking contract a: SUCCESS
[a.single_top_level_call.1] line 4 Only a single top-level call to function a when checking contract a: SUCCESS
[a.postcondition.1] line 7 Check ensures clause of contract contract::a for function a: FAILURE

** 1 of 37 failed (2 iterations)
VERIFICATION FAILED

```

And indeed, because of the precondition `i <= 1` a recursive call to `a` is not possible from `a` (neither is a recursive call to `b` from `b`).

If I relax the preconditions to `true` to allow recursive calls, and instrument with DFCC `--enforce-contract a` instead of `--enforce-contract-rec a` then the dynamic recursion check fails as expected:

```c
cbmc b.out
...
rec.c function a
[a.no_recursive_call.1] line 4 No recursive call to function a when checking contract a: FAILURE
[a.postcondition.1] line 7 Check ensures clause of contract contract::a for function a: FAILURE

** 2 of 37 failed (3 iterations)
VERIFICATION FAILED
```

So it seems like we could mark the issue as resolved.
