### ISSUE TITLE
Warning for functions with "empty" contracts

### ISSUE THREAD

**Issue by feliperodri** [diffblue/cbmc#7192]
CBMC version: 5.67.0
Operating system: N/A

# Summary
If we ask CBMC to use a contract as an abstraction for a function, then the function must have a contract.

# Basic Ask
When checking some function "f" complies with its contract we may ask CBMC to abstract calls to another function "g" by using g's contract. This should produce an error if no contract has been associated with g.

# Background
Each function contract is comprised of 3 components:
* requires: defaults to "true"
* assigns: defaults to "empty"
* ensures: defaults to "true"

Since each component of a contract has an agreed default we could consider every function to have a contract, even if none was supplied. However, this is unlikely to represent user intent. So, if a user wants to abstract a function with its contract in an analysis they should be required to write, at least a partial, contract for the function.  If they do not, if all three contract components are missing, the result is an error.

# Additionally
Further, since it is clearer to supply a contract component than to rely on the default we should emit a warning for each missing contract component if some contract component be present, but not all three.

**Comment by feliperodri** [comment]
@remi-delmas-3000 haven't you address this issue with the latest DFCC work?

**Comment by remi-delmas-3000** [comment]
All clauses are optional in a contract. When omitted the defaults are as follows:

- `__CPROVER_requires(true)`
- `__CPROVER_ensures(true)`
- `__CPROVER_assigns()`
- `__CPROVER_frees()`

We allowed omitting clauses for brevity and better user experience, which results in having to assume default values for omitted clauses, which results in assuming the default contract above for all functions.

Would it be satisfactory to emit a warning if the lists of assigns/frees targets and requires/ensures expressions is empty ?
