### ISSUE TITLE
Treatment of undefined functions in function contracts is unsound

### ISSUE THREAD

**Issue by feliperodri** [diffblue/cbmc#7193]
CBMC version: 5.67.0
Operating system: N/A

# Problem

If CBMC encounters a call to a function with an unknown definition it replaces that call with a nondeterministic value of the appropriate type — representing the unknown function’s return value. However, a function can do more than return a value (it can also write to its arguments and other memory), so this abstraction is not sound.
This unsoundness has been witnessed in code with typos where a typo in a function make can cause a proof to pass where as a the code without the typo will fail (because the function when correctly called writes to memory).

# Recommended Solution

The sound option would be to replace a call to an undefined function with abort/assert(false); This may be unpalatable to some CBMC users, but it should be available as an option, one that AWS should use by default.

# Importance

Functions with unknown definitions are included as warnings in the results, but this is an insufficient communication of risk of unsoundness. Also, the list of functions for which warnings are reported is gathered via an over-approximating reachability analysis and includes functions that may not be reachable, and so users may feel that these warnings may be ignored after inspection. This places too much reliance on manual inspection to check soundness.

# Related Issue To Be Addressed Together

CBMC produces coverage statistics for all functions considered reachable by an over-approximated reachability analysis. This has lead to reports that look bad because they contain functions with no-coverage. Users "fix" this by excluding these functions from the analysis using the REMOVE_FUNCTION_BODY option. This has two problems

+ The function with the removed body, while excluded from the coverage analysis, now generates a warning about an undefined function being used. This is undesirable as the report now looks bad in a different way. It also encourages the user to ignore this class of warnings, which is dangerous because unsoundness can lurk here (as discussed above).

+ Suppose the definition of the function under analysis changes now and the function becomes reachable. Now the unsoundness comes into play and we may get a false proof. However, if instead of treating these functions as non-deterministic values we instead treated them as aborts there would be no unsoundness issue.

When a user specifically excludes a function from analysis the result should be 1) that the function is excluded from the coverage report, and 2) that if the function is called that should be a model checking fail.

**Comment by feliperodri** [comment]
@remi-delmas-3000 haven't you address this issue with the latest DFCC work?

**Comment by remi-delmas-3000** [comment]
fixed by https://github.com/diffblue/cbmc/pull/7359
