### ISSUE TITLE
Check purity of loop contracts

### ISSUE THREAD

**Issue by feliperodri** [diffblue/cbmc#7207]
CBMC version: 5.67.0
Operating system: N/A

Check purity of loop contracts.

**Comment by feliperodri** [comment]
the internal mechanics for checking side effects is now available through https://github.com/diffblue/cbmc/pull/6887, but loop contracts need to be ported over to DFCC)

**Comment by qinheping** [comment]
The purity check is already of loop contracts is implemented.
Invariant clauses: https://github.com/diffblue/cbmc/blob/develop/src/goto-programs/goto_convert.cpp#L877
Decreases clauses: https://github.com/diffblue/cbmc/blob/develop/src/goto-programs/goto_convert.cpp#L891
Assigns clauses: https://github.com/diffblue/cbmc/blob/develop/src/ansi-c/c_typecheck_code.cpp#L505

**Comment by qinheping** [comment]
The purity checks of loop contracts are already implemented.
Invariant clauses: https://github.com/diffblue/cbmc/blob/develop/src/goto-programs/goto_convert.cpp#L877
Decreases clauses: https://github.com/diffblue/cbmc/blob/develop/src/goto-programs/goto_convert.cpp#L891
Assigns clauses: https://github.com/diffblue/cbmc/blob/develop/src/ansi-c/c_typecheck_code.cpp#L505
