### ISSUE TITLE
Size of BitVectors used in CBMC

### ISSUE THREAD

**Issue by mahantaf** [diffblue/cbmc#7236]
Hello,

I have a quick question:
What is the size of BitVector that CBMC uses? (I mean in bits or bytes)

**Comment by tautschnig** [comment]
If you are using standard C syntax, CBMC will use the bit widths used on a particular platform and data type (see https://wiki.debian.org/ArchitectureSpecificsMemo, for example). You may, however, also use __CPROVER_bitvector to create a variable of non-standard bit width (see https://diffblue.github.io/cbmc/cprover-manual/md_api.html).
