### ISSUE TITLE
Change the "about" description of the repo to reference the new documentation site

### ISSUE THREAD

**Issue by jimgrundy** [diffblue/cbmc#7301]
Our github page has this at the very top (right):

> About
> C Bounded Model Checker
> 
> [www.cprover.org/cbmc](http://www.cprover.org/cbmc)
> Resources

That link instead should go to https://diffblue.github.io/cbmc/

I'd change it, but I think only diffblue can do that. The instructions on how to change it are here:
https://github.com/orgs/community/discussions/22456

**Comment by TGWDB** [comment]
Done by Peter, closing.
