### ISSUE TITLE
Type-checking for vector data type assignments is too restrictive

### ISSUE THREAD

**Issue by adpaco-aws** [diffblue/cbmc#7302]
CBMC version: 5.69.1

In this Kani example:
```rust
#![feature(repr_simd, platform_intrinsics)]

#[repr(simd)]
#[allow(non_camel_case_types)]
#[derive(Clone, Copy, PartialEq, Eq)]
pub struct i64x2(i64, i64);

#[repr(simd)]
#[allow(non_camel_case_types)]
#[derive(Clone, Copy, PartialEq, Eq)]
pub struct u64x2(u64, u64);

#[repr(simd)]
#[allow(non_camel_case_types)]
#[derive(Clone, Copy, PartialEq, Eq)]
pub struct u32x2(u32, u32);

#[repr(simd)]
#[allow(non_camel_case_types)]
#[derive(Clone, Copy, PartialEq, Eq)]
pub struct u32x4(u32, u32, u32, u32);

extern "platform-intrinsic" {
    fn simd_eq<T, U>(x: T, y: T) -> U;
}

#[kani::proof]
fn main() {
    let x = u64x2(0, 0);
    let y = u64x2(0, 1);

    unsafe {
        let w: i64x2 = simd_eq(x, y);
        assert!(w == i64x2(-1, 0));

        let z: u32x2 = simd_eq(x, y);
        assert!(z == u32x2(u32::MAX, 0));
}
```
CBMC crashes with the invariant violation:
```
--- begin invariant violation report ---
Invariant check failed
File: ../src/goto-symex/goto_symex.cpp:48 function: symex_assign
Condition: lhs.type() == rhs.type()
Reason: assignments must be type consistent
```

Type-checking is too restrictive here. AFAIK Rust allows assignments between two different vectors if they have the same number of elements (e.g., u64x2 can be converted into a i64x2 or u32x2, but not a u32x4).

I'm about to open a PR for this, will refer to this issue in our test and keep you posted.

**Comment by thomasspriggs** [comment]
Have you tried inserting a typecast expression? If I remember correctly it is mandatory for typecasts at that stage of CBMC to be explicit.

**Comment by adpaco-aws** [comment]
Hey @thomasspriggs , thanks for the answer!

After some more work, we realized that CBMC was right about this. For the return type, we were generating the same type as the operands, but that's not allowed in Rust (but the front-end can't detect this problem, as SIMD types depend on the back-end). The solution is to extend Kani's type-checker for CBMC expressions so it takes into account the expected return type.

It's great that CBMC detected this problem. Thanks!
