### ISSUE TITLE
Documentation formatting is broken on Developer-Guide/Code-Organization Page

### ISSUE THREAD

**Issue by jimgrundy** [diffblue/cbmc#7397]
Take a look at this page of our documentation: https://diffblue.github.io/cbmc/folder-walkthrough.html
The formatting is all messed up.

**Comment by NlightNFotis** [comment]
Yeah, the `<tt>` tags are, I believe, an artefact of an older system based on another markup format (I believe it was restructured text), that we haven't translated in our new format.

I'll try to spin up a PR to fix that on an ASAP basis (it's a small change) but there are bound to be more of these around, and we're going to have to fix them on a case-by-case basis, unless there's some decision to systematically go through all of the docs pages and find any mechanical translation issues.
