### ISSUE TITLE
Function seems to be defined but isn't picked up by CBMC

### ISSUE THREAD

**Issue by adpaco-aws** [diffblue/cbmc#7446]
CBMC version: 5.72.0 (and Kani version in [this branch](https://github.com/adpaco-aws/rmc/tree/update-toolchain-2022-12-04))
Operating system: Ubuntu 20.04
Exact command line resulting in the issue: `RUSTFLAGS="--edition 2018" ./scripts/kani tests/kani/AsyncAwait/manual_spawn.rs`
What behaviour did you expect: Verification success.
What happened instead: Verification failure. Apparently, one of the main functions required for verification (`run` in `impl Scheduler`) is reported as missing. The function is reachable from `arc_spawn_deterministic_test` so that's enough to fail verification.
```
SUMMARY:
 ** 1 of 404 failed (403 undetermined)
Failed Checks: Function `<manual_spawn::Scheduler>::run::<manual_spawn::RoundRobin>` with missing definition is unreachable

VERIFICATION:- FAILED
Verification Time: 0.99017805s
```

What's confusing about this example is that the function appears in the `show-goto-functions` output (note: the mangled name could be different in other environments):
```
Scheduler::run::<RoundRobin> /* _RINvMs_Cscr6Rv5o3ouE_12manual_spawnNtB5_9Scheduler3runNtB5_10RoundRobinEB5_ */
[...]
```
But it doesn't seem to be picked up by CBMC. The result of running CBMC directly on the GotoC output is the same: it fails to find the function, which is being called from the `block_on` method:
```
Scheduler::block_on::<[async block@manual_spawn.rs:192:9: 199:10], RoundRobin> /* _RINvMs_Cscr6Rv5o3ouE_12manual_spawnNtB5_9Scheduler8block_onNCNvB5_28arc_spawn_deterministic_test0NtB5_10RoundRobinEB5_ */
[...]
        CALL _RINvMs_Cscr6Rv5o3ouE_12manual_spawnNtB5_9Scheduler3runNtB5_10RoundRobinEB5_(_RINvMs_Cscr6Rv5o3ouE_12manual_spawnNtB5_9Scheduler8block_onNCNvB5_28arc_spawn_deterministic_test0NtB5_10RoundRobinEB5_::1::var_8, _RINvMs_Cscr6Rv5o3ouE_12manual_spawnNtB5_9Scheduler8block_onNCNvB5_28arc_spawn_deterministic_test0NtB5_10RoundRobinEB5_::1::var_9)
        // 200 file /home/ubuntu/kani/tests/kani/AsyncAwait/manual_spawn.rs line 122 column 9 function Scheduler::block_on::<[async block@manual_spawn.rs:192:9: 199:10], RoundRobin>
[...]
```

Are we looking at this right? Note that this part of our toolchain update. It could be the case that a change there has triggered a bug in CBMC, but we shouldn't discard the possibility of Kani doing something wrong here.

**Comment by zhassan-aws** [comment]
This issue is no longer blocking Kani because we've dropped the referenced branch (https://github.com/adpaco-aws/rmc/tree/update-toolchain-2022-12-04).

**Comment by tautschnig** [comment]
I don't think this is a matter of an undefined function, that's perhaps just Kani's interpretation of the assertion. It appears that even in the very initial goto binary that arises out of `symtab2gb` the assertion already fails:
```
$ cbmc manual_spawn.out --function manual_spawn::arc_spawn_deterministic_test | grep FAILURE | grep -v REACHABILITY
[_RINvMs_Cscr6Rv5o3ouE_12manual_spawnNtB5_9Scheduler3runNtB5_10RoundRobinEB5_.1] assertion: FAILURE
```
It seems that this assertion is generated by trying to expand a function pointer, but then there are no candidates. The reason for the not-so-informative comment is the absence of a source location on the original instruction. The instruction in question is (with two preceding instructions as context):
```
        // Labels: bb8
    10: ASSIGN _RINvMs_Cscr6Rv5o3ouE_12manual_spawnNtB5_9Scheduler3runNtB5_10RoundRobinEB5_::1::var_22::fut := _RINvMs_Cscr6Rv5o3ouE_12manual_spawnNtB5_9Scheduler3runNtB5_10RoundRobinEB5_::1::var_19.Some.0
        // 3306 file /home/ub-backup/tautschn/kani.git/tests/kani/AsyncAwait/manual_spawn.rs line 101 column 23 function Scheduler::run::<RoundRobin>
        ASSIGN _RINvMs_Cscr6Rv5o3ouE_12manual_spawnNtB5_9Scheduler3runNtB5_10RoundRobinEB5_::1::var_25 := address_of(*_RINvMs_Cscr6Rv5o3ouE_12manual_spawnNtB5_9Scheduler3runNtB5_10RoundRobinEB5_::1::var_22::fut)
        // 3307 no location
        CALL _RINvMs_Cscr6Rv5o3ouE_12manual_spawnNtB5_9Scheduler3runNtB5_10RoundRobinEB5_::1::var_24 := _RNvMs5_NtCsfUZ6P22yUZA_4core3pinINtB5_3PinINtNtCsh26b8QhjJs9_5alloc5boxed3BoxDNtNtNtB7_6future6future6Futurep6OutputuNtNtB7_6marker4SyncEL_EE6as_mutCscr6Rv5o3ouE_12manual_spawn(_RINvMs_Cscr6Rv5o3ouE_12manual_spawnNtB5_9Scheduler3runNtB5_10RoundRobinEB5_::1::var_25)
```
The corresponding Rust code is (with line numbers, line 101 is the one of interest):
````rust
 93     /// Runs the scheduler with the given scheduling plan until all tasks have completed
 94     pub fn run(&mut self, mut scheduling_plan: impl SchedulingStrategy) {
 95         let waker = unsafe { Waker::from_raw(NOOP_RAW_WAKER) };
 96         let cx = &mut Context::from_waker(&waker);
 97         while self.num_running > 0 {
 98             let (index, can_assume_running) = scheduling_plan.pick_task(self.num_tasks);
 99             let task = &mut self.tasks[index];
100             if let Some(fut) = task.as_mut() {
101                 match fut.as_mut().poll(cx) {
102                     std::task::Poll::Ready(()) => {
103                         self.num_running -= 1;
104                         let _prev = std::mem::replace(task, None);
105                     }
106                     std::task::Poll::Pending => (),
107                 }
108             } else if let SchedulingOptimization::CanAssumeRunning = can_assume_running {
109                 #[cfg(kani)]
110                 kani::assume(false); // useful so that we can assume that a nondeterministically picked task is st    ill running
111             }
112         }
113     }
````
So I'd argue this needs to be fixed in Kani, I'm not sure why there is no candidate for this function pointer.
