### ISSUE TITLE
Potential inconsistency in dereferencing unknown pointers in cbmc.

### ISSUE THREAD

**Issue by rodionov** [diffblue/cbmc#7463]
CBMC version: 5.72.1 (cbmc-5.72.1-20-g6f404636d3-dirty)
Operating system: Debian 12

When running CBMC on the following code snippet it was observed that the assertion in `_test` is hit only for the cases when the value of variable `i` is either 1 or 4, while it is expected to hit the assertion for all possible value of the variable: 1,2,3,4.

Contents of `test.c`:

```
#include <assert.h>
#include <stdio.h>

struct list_head {
  struct list_head *next, *prev;
};

struct linked_obj {
  struct list_head list_entry;
};

void _test(struct linked_obj *obj) {
  int i = 0;
  struct list_head *next = &obj->list_entry;

  next = next->next;
  if (next == NULL)
    goto done;
  else
    i ++;

  next = next->next;
  if (next == NULL)
    goto done;
  else
    i ++;

  next = next->next;
  if (next == NULL)
    goto done;
  else
    i ++;

  next = next->next;
  if (next == NULL)
    goto done;
  else
    i ++;

done:
  if (i == 1) __CPROVER_assert(0, "assert1"); // cbmc hits assertion
  if (i == 2) __CPROVER_assert(0, "assert2"); // assertion isn't hit
  if (i == 3) __CPROVER_assert(0, "assert3"); // assertion isn't hit
  if (i == 4) __CPROVER_assert(0, "assert4"); // cbmc hits assertion

  return;
}


void test(void) {
  struct linked_obj obj;
  _test(&obj);
}
```

Exact command line resulting in the issue: `cbmc --function test --unwind 5 --no-library --trace --trace-show-code --trace-show-function-calls --slice-formula test.c`

Looking at the equations produced by symex (via `cbmc --function test --unwind 5 --no-library --trace --trace-show-code --trace-show-function-calls --slice-formula --show-vcc test.c`) for `assert2` we get:

```
{-1} _test::1::next!0@1#3 = test::1::obj!0@1#1..list_entry..next
{-2} goto_symex::\guard#1 ⇔ (_test::1::next!0@1#3 = NULL)
{-3} _test::1::next!0@1#5 = _test::1::next$object#0..next
{-4} goto_symex::\guard#2 ⇔ (_test::1::next!0@1#5 = NULL)
{-5} _test::1::next!0@1#7 = _test::1::next$object#0..next
{-6} goto_symex::\guard#3 ⇔ (_test::1::next!0@1#7 = NULL)
{-7} _test::1::next!0@1#9 = _test::1::next$object#0..next
{-8} goto_symex::\guard#4 ⇔ (_test::1::next!0@1#9 = NULL)
{-9} _test::1::i!0@1#7 = (goto_symex::\guard#4 ? 3 : 4)
{-10} _test::1::i!0@1#8 = (goto_symex::\guard#3 ? 2 : _test::1::i!0@1#7)
{-11} _test::1::i!0@1#9 = (¬goto_symex::\guard#1 ∧ goto_symex::\guard#2 ? 1 : _test::1::i!0@1#8)
{-12} _test::1::i!0@1#10 = (goto_symex::\guard#1 ? 0 : _test::1::i!0@1#9)
{-13} goto_symex::\guard#5 ⇔ (_test::1::i!0@1#10 = 1)
{-14} _test::1::i!0@1#12 = (goto_symex::\guard#5 ? 1 : _test::1::i!0@1#10)
{-15} goto_symex::\guard#6 ⇔ (_test::1::i!0@1#12 = 2)
├──────────────────────────
{1} ¬goto_symex::\guard#6
```

This shows that the same `_test::1::next$object#0` is being used for last three `next = next->next;` statements ({-3}, {-5}, {-7}) in the code snippet above and which probably explains why we hit assertions only for `i == 1` and `i == 4`.

Is this behaviour (i.e. that the same `_test::1::next$object#0` is being used for different L2 values of `next`) expected for symex due to some limitations related to modeling pointers in CBMC or it is an issue (i.e. for example, `_test::1::next$object#0`, `_test::1::next$object#1` and `_test::1::next$object#2` should be used for `_test::1::next!0@1#5`, `_test::1::next!0@1#7` and `_test::1::next!0@1#9` respectively)?

For example, the following version of `test.c` (i.e. instead of using the same `next` variable for different elements of the linked list we use different variables) doesn't demonstrate this behavior:

```
void _test_fixed(struct linked_obj *obj) {
  int i = 0;
  struct list_head *next0 = &obj->list_entry;

  struct list_head *next1 = next0->next;
  if (next1 == NULL)
    goto done;
  else
    i ++;

  struct list_head *next2 = next1->next;
  if (next2 == NULL)
    goto done;
  else
    i ++;

  struct list_head *next3 = next2->next;
  if (next3 == NULL)
    goto done;
  else
    i ++;

  struct list_head *next4 = next3->next;
  if (next4 == NULL)
    goto done;
  else
    i ++;

done:
  if (i == 1) __CPROVER_assert(0, "assert1"); // cbmc hits assertion
  if (i == 2) __CPROVER_assert(0, "assert2"); // cbmc hits assertion
  if (i == 3) __CPROVER_assert(0, "assert3"); // cbmc hits assertion
  if (i == 4) __CPROVER_assert(0, "assert4"); // cbmc hits assertion

  return;
}

void test(void) {
  struct linked_obj obj;
  _test_fixed(&obj);
}
```

For comparison, here is a list of equations generated for this modification of the test case:

```
{-1} _test_fixed::1::next1!0@1#2 = test::1::obj!0@1#1..list_entry..next
{-2} goto_symex::\guard#1 ⇔ (_test_fixed::1::next1!0@1#2 = NULL)
{-3} _test_fixed::1::next2!0@1#2 = _test_fixed::1::next1$object#0..next
{-4} goto_symex::\guard#2 ⇔ (_test_fixed::1::next2!0@1#2 = NULL)
{-5} _test_fixed::1::next3!0@1#2 = _test_fixed::1::next2$object#0..next
{-6} goto_symex::\guard#3 ⇔ (_test_fixed::1::next3!0@1#2 = NULL)
{-7} _test_fixed::1::next4!0@1#2 = _test_fixed::1::next3$object#0..next
{-8} goto_symex::\guard#4 ⇔ (_test_fixed::1::next4!0@1#2 = NULL)
{-9} _test_fixed::1::i!0@1#7 = (goto_symex::\guard#4 ? 3 : 4)
{-10} _test_fixed::1::i!0@1#8 = (goto_symex::\guard#3 ? 2 : _test_fixed::1::i!0@1#7)
{-11} _test_fixed::1::i!0@1#9 = (¬goto_symex::\guard#1 ∧ goto_symex::\guard#2 ? 1 : _test_fixed::1::i!0@1#8)
{-12} _test_fixed::1::i!0@1#10 = (goto_symex::\guard#1 ? 0 : _test_fixed::1::i!0@1#9)
{-13} goto_symex::\guard#5 ⇔ (_test_fixed::1::i!0@1#10 = 1)
{-14} _test_fixed::1::i!0@1#12 = (goto_symex::\guard#5 ? 1 : _test_fixed::1::i!0@1#10)
{-15} goto_symex::\guard#6 ⇔ (_test_fixed::1::i!0@1#12 = 2)
├──────────────────────────
{1} ¬goto_symex::\guard#6
```

In this case the formula contains 3 different instances of symbolic variables `_test_fixed::1::next31$object#0`, `_test_fixed::1::next2$object#0` and `_test_fixed::1::next3$object#0` (vs a single `_test::1::next$object#0` in the previous case) for  last three `next = next->next;` statements. Thus, it probably could help reaching `assert2` and `assert3` cases.

**Comment by tautschnig** [comment]
Apart from the fact that your test code seems to be incomplete (it's lacking a definition of `struct linked_obj`): the behaviour you are seeing is to be expected for we use https://github.com/diffblue/cbmc/blob/develop/src/pointer-analysis/add_failed_symbols.h#L30..L36. As you are asking about a case of undefined behaviour I would argue that CBMC isn't wrong in what it is doing.

Nonetheless: would you mind elaborating what behaviour you'd like to see, and why you think it would be the "right" behaviour?

**Comment by rodionov** [comment]
> Apart from the fact that your test code seems to be incomplete (it's lacking a definition of struct linked_obj)

Sorry for missing this, updated the snippet in the original comment with the definition of `struct linked_obj` and rewrote assertions using `__CPROVER_assert`.

> Nonetheless: would you mind elaborating what behaviour you'd like to see, and why you think it would be the "right" behaviour?

I would like cbmc to report all 4 violations: `assert1`, `assert2`, `assert3` and `assert4`. Currently, it reports violations for the properties `assert1` and `assert4` only. These corresponds to the following cases:

1) `assert1` -- `obj.list_entry.next != NULL` and  `obj.list_entry.next->next == NULL` (i.e. there are only two elements in the linked list: `&obj.list_entry` and `obj.list_entry.next`)
2) `assert2` -- `obj.list_entry.next != NULL` and  `obj.list_entry.next->next != NULL` and `obj.list_entry.next->next->next == NULL` (i.e. there are only three elements in the linked list: `&obj.list_entry`, `obj.list_entry.next` and `obj.list_entry.next->next`)
3) `assert3` -- `obj.list_entry.next != NULL` and  `obj.list_entry.next->next != NULL` and `obj.list_entry.next->next->next != NULL` and `obj.list_entry.next->next->next->next == NULL` (i.e. there are only four elements in the linked list: `&obj.list_entry`, `obj.list_entry.next`, `obj.list_entry.next->next` and `obj.list_entry.next->next->next`)
4) `assert4` -- `obj.list_entry.next != NULL` and  `obj.list_entry.next->next != NULL` and `obj.list_entry.next->next->next != NULL` and `obj.list_entry.next->next->next->next != NULL` and `obj.list_entry.next->next->next->next->next == NULL` (i.e. there are only five elements in the linked list: `&obj.list_entry`, `obj.list_entry.next`, `obj.list_entry.next->next`, `obj.list_entry.next->next->next` and `obj.list_entry.next->next->next->next`)

I would expect cbmc to model cases 2) and 3) to catch `assert2` and `assert3` -- in the test harness `void test(void)` I don't put any constraints on the local variable `obj`, thus, in theory such configurations of the linked list are possible... Especially, given that in `_test_fixed` routine all 4 properties are reported as violated.

**Comment by tautschnig** [comment]
> I would expect cbmc to model cases 2) and 3) to catch `assert2` and `assert3` -- in the test harness `void test(void)` I don't put any constraints on the local variable `obj`, thus, in theory such configurations of the linked list are possible... Especially, given that in `_test_fixed` routine all 4 properties are reported as violated.

Well, as I said: what you have here is undefined behaviour, you are dereferencing uninitialised pointers. `goto-harness` can create an environment that does not suffer from such a problem (as a replacement of your entry point). But if you'd want this in CBMC's symbolic execution then you seem to be asking for some form of object factory. Let's for a moment assume we had such a feature: what assumptions would you make about what `next` can or cannot point to?

**Comment by rodionov** [comment]
> goto-harness can create an environment that does not suffer from such a problem (as a replacement of your entry point)

Thanks for pointing this out! I will check it out. I intentionally didn't initialize `obj` variable in the test harness assuming that cbmc symex engine will handle dereferencing uninitialized pointers and would automatically model the linked list with arbitrary number of elements in it. Looks like it doesn't work like this and I would need to build the linked list either manually in the harness or by using `goto-harness` tool for it...

> Let's for a moment assume we had such a feature: what assumptions would you make about what next can or cannot point to?

I would make the following assumptions: `next` could be either `NULL` or a non-NULL pointer to some memory location containing a valid object which could be dereferenced later -- `next->next` or casting `next` to some struct type and accessing a field: `struct _str *p = (struct __str *)next; p->some_field`. I wouldn't make assumptions about potential aliasing -- I would always assume that `next->next` and `next->next->next` point to different objects although this is obviously unsound.

As a bigger context, the main motivation for this -- is to be able to handle such loops as bellow where I would like to check some properties of `p->...`

```
while(next->next != NULL) {
  next = next->next;
  struct __str *p = (struct __str *)next;
  // do something with p->...
}
```

**Comment by tautschnig** [comment]
> I would make the following assumptions: `next` could be either `NULL` or a non-NULL pointer to some memory location containing a valid object which could be dereferenced later -- `next->next` or casting `next` to some struct type and accessing a field: `struct _str *p = (struct __str *)next; p->some_field`. I wouldn't make assumptions about potential aliasing -- I would always assume that `next->next` and `next->next->next` point to different objects although this is obviously unsound.

I'd say `goto-harness` will construct exactly such an environment for you. As an alternative, consider function contracts (with memory predicates): https://diffblue.github.io/cbmc/contracts-memory-predicates.html

Your assumptions are consistent with what we might expect in a well-behaved program, but C wouldn't have any such guarantee. So I'm not entirely sure we should seek to bake this into CBMC. The above tooling might be the better route forward.

**Comment by rodionov** [comment]
Thank you for the explanation, @tautschnig! I think this resolves the issue.
