### ISSUE TITLE
Release a *.deb package for Ubuntu 22.04

### ISSUE THREAD

**Issue by celinval** [diffblue/cbmc#7474]
CBMC version: 5.74
Operating system: Ubuntu 22.04
Exact command line resulting in the issue: Download the *.deb package for the [latest release](https://github.com/diffblue/cbmc/releases) for Ubuntu 22.04.
What behaviour did you expect: That a package would exist for Ubuntu 22.04.
What happened instead: I had to install using the package created for Ubuntu 20.04.

**Comment by NlightNFotis** [comment]
Hello, this is something we definitely plan to do in the near future, along with dropping support for Ubuntu 18.04. The reason we need to do this is that we depend on GitHub Actions for running CI, and it's sunsetting the Ubuntu 18.04 runners in the [near future](https://github.blog/changelog/2022-08-09-github-actions-the-ubuntu-18-04-actions-runner-image-is-being-deprecated-and-will-be-removed-by-12-1-22/).

Will this affect you in any way? Do you depend on Ubuntu 18.04 somehow?

**Comment by celinval** [comment]
We still support 18.04, but we will likely drop it sometime this year. We don't have a date for that yet.

**Comment by thomasspriggs** [comment]
We can add a Ubuntu 22.04 package on top of the existing packages / git hub actions release jobs. Support for Ubuntu 18.04 is a separate issue. I am going to start looking at adding the new package.

**Comment by celinval** [comment]
Sounds good! Thank you

**Comment by thomasspriggs** [comment]
The Ubuntu 22.04 package is now available from the release page and it is included in the release automation for future releases - https://github.com/diffblue/cbmc/releases
