### ISSUE TITLE
Incremental Loops ignores `--smt2`

### ISSUE THREAD

**Issue by mgudemann** [diffblue/cbmc#7528]
CBMC version: * *      CBMC 5.75.0 (cbmc-5.75.0-2-gfb65095aee) 64-bit     * *                                                                                                                             
Operating system: Linux
Exact command line resulting in the issue: cbmc --incremental-loop f.0 --function f il.c --smt2
What behaviour did you expect: that Z3 is used instead of bit-blasting and MiniSAT
What happened instead: MiniSAT is used

running the above command line produces
```
CBMC version 5.75.0 (cbmc-5.75.0-2-gfb65095aee) 64-bit x86_64 linux
Parsing il.c                                   
Converting
Type-checking il               
file il.c line 5 function f: function 'assert' is not declared
Generating GOTO Program
Adding CPROVER library (x86_64)
Removal of function pointers and virtual functions
Generic Property Instrumentation
Running with 8 object bits, 56 offset bits (default)
Starting Bounded Model Checking
Current unwinding: 1
Unwinding loop f.0 iteration 1 file il.c line 4 function f thread 0
Incremental status: INCONCLUSIVE
Current unwinding: 2
Unwinding loop f.0 iteration 2 file il.c line 4 function f thread 0
Incremental status: INCONCLUSIVE
Current unwinding: 3
Unwinding loop f.0 iteration 3 file il.c line 4 function f thread 0
Incremental status: INCONCLUSIVE
Current unwinding: 4
Unwinding loop f.0 iteration 4 file il.c line 4 function f thread 0
Incremental status: INCONCLUSIVE
Current unwinding: 5
Unwinding loop f.0 iteration 5 file il.c line 4 function f thread 0
Passing problem to refinement loop with MiniSAT 2.2.1 with simplifier
size of program expression: 32 steps
simple slicing removed 2 assignments
Generated 5 VCC(s), 1 remaining after simplification
Runtime Postprocess Equation: 3.3763e-05s
converting SSA
Running refinement loop with MiniSAT 2.2.1 with simplifier
BV-Refinement: post-processing
BV-Refinement: iteration 1
33 variables, 0 clauses
SAT checker: instance is SATISFIABLE
BV-Refinement: got SAT, and it simulates => SAT 
Total iterations: 1
Runtime decision procedure: 0.000431449s
```
Z3 is used with this command line
```
cbmc --unwind 5 --function f il.c --smt2
```
i.e. specifying the bound explicitly. I think Z3 should be usable for incremental loops here.

**Comment by peterschrammel** [comment]
The `--incremental-loop` option requires the `bv_refinementt` backend solver (see https://github.com/diffblue/cbmc/blob/develop/src/goto-checker/solver_factory.cpp#L144), which is backed by a SAT solver. We haven't got an equivalent implementation backed by an SMT solver yet.
Ideally, CBMC should abort with an error saying that `--smt2` is not supported with `--incremental-loop` .

**Comment by mgudemann** [comment]
Thank you for the answer. I had wondered why this do not stop with the unsupported message. So would be possible but currently not implemented with external SMT solver support.
