### ISSUE TITLE
Include cadical in the CBMC homebrew package

### ISSUE THREAD

**Issue by zhassan-aws** [diffblue/cbmc#7555]
CaDiCaL is included in CBMC 5.77.0's Ubuntu release packages (and can be selected via `--sat-solver cadical`), but isn't included in the MacOS homebrew package (e.g. see https://github.com/model-checking/kani/actions/runs/4206558765/jobs/7300202957#step:5:221). This is a tracking issue for including it in the MacOS homebrew package starting with the next CBMC release.

CBMC version: 5.77.0
Operating system: MacOS
Exact command line resulting in the issue: `cbmc --sat-solver cadical`
What behaviour did you expect: CaDiCaL is used
What happened instead:
```
The specified solver, 'cadical', is not available. The default solver will be used instead.
```

**Comment by zhassan-aws** [comment]
Per an offline discussion with @NlightNFotis, the homebrew formula for CBMC needs to be updated to include cadical:

https://github.com/Homebrew/homebrew-core/blob/2c206559b9d13cfe766ec1523ed264ec4c1639e6/Formula/cbmc.rb

**Comment by NlightNFotis** [comment]
I have submitted a PR against homebrew fixing this issue at https://github.com/Homebrew/homebrew-core/pull/124543.

**Comment by zhassan-aws** [comment]
Thanks @NlightNFotis!

**Comment by zhassan-aws** [comment]
Confirmed that CBMC 5.78.0's MacOS homebrew package includes CaDiCaL 🎉 
```
% sw_vers
ProductName:            macOS
ProductVersion:         13.0
BuildVersion:           22A380
% cbmc --version
5.78.0 (cbmc-5.78.0)
% cbmc --sat-solver cadical a.c | grep Solving
Solving with CaDiCaL sc2021
```

Thanks for taking care of this @NlightNFotis.

Closing this issue as completed.
