### ISSUE TITLE
Incorrect/inconsistent sizing in determining struct - field ordering dependent

### ISSUE THREAD

**Issue by Bo-Yuan-Huang** [diffblue/cbmc#7596]
CBMC version: 5.78.0 (from Docker image `diffblue/cbmc:5.78.0`)
Operating system: Ubuntu 20.04.5 LTS (Focal Fossa)
Exact command line resulting in the issue: `docker run --rm -v $(pwd):/DUV diffblue/cbmc:5.78.0 cbmc --64 /DUV/test.c`
What behaviour did you expect: Verification pass -- two struct having the same size.
What happened instead: Verification fail -- two structs interpreted as of size 64 and 68, respectively.

Example code:
``` c
#define PADDING_SIZE (64 - sizeof(unsigned char) - sizeof(unsigned int))

typedef struct {
  unsigned char uchar;
  unsigned int uint;
  unsigned char padding[PADDING_SIZE];
} a_t;

typedef struct {
  unsigned int uint;
  unsigned char uchar;
  unsigned char padding[PADDING_SIZE];
} b_t;

int main() {
  assert (sizeof(a_t) == sizeof(b_t));
  return 0;
}
```

**Comment by brenoguim** [comment]
This fails in GCC as well https://godbolt.org/z/WvTYd73eG
You might want to look into padding and alignment to know exactly the struct layout.
In struct `a_t`, the compiler has to add 3 bytes of padding between `uchar` and `uint` to make sure `uint` is aligned to 4 byte boundary.
In the second case however, no padding between `uint` and `uchar` is necessary because `uchar` can be placed in any byte since its alignment is 1.

**Comment by Bo-Yuan-Huang** [comment]
Thanks for the prompt response. A version with `aligned` and `packed` attributes will also trigger the issue (see below). GCC and Clang are ok with the annotated example.

``` c
#define PADDING_SIZE (64 - sizeof(unsigned char) - sizeof(unsigned int))

typedef struct __attribute__((packed, aligned(64))) {
  unsigned char uchar;
  unsigned int uint;
  unsigned char padding[PADDING_SIZE];
} a_t;

typedef struct __attribute__((packed, aligned(64))) {
  unsigned int uint;
  unsigned char uchar;
  unsigned char padding[PADDING_SIZE];
} b_t;

int main() {
  assert (sizeof(a_t) == sizeof(b_t));
  return 0;
}
```

**Comment by tautschnig** [comment]
Thank you for this carefully crafted test. It seems we had a bug in combining packing and alignment information. Fixed in https://github.com/diffblue/cbmc/pull/7597.
