### ISSUE TITLE
All tests in current master failing

### ISSUE THREAD

**Issue by tautschnig** [diffblue/cbmc#763]
The merge of #624 appears to have broken master:
```
Assertion failed: x==i (irep_ids.cpp: initialize_string_container: 62)
```

**Comment by forejtv** [comment]
@reuk Can you have a look at this please?

**Comment by reuk** [comment]
When writing the irep_ids.def file, I forgot to add the initial entry for an empty string. With this back in place, everything seems to work.

**Comment by tautschnig** [comment]
I'm a bit confused about the PRs. Can we have one PR that just fixes the issue (instead of reverting at large), and closes this issue via the commit message? Thanks!

**Comment by reuk** [comment]
Yes, sorry, should be a couple of minutes
