### ISSUE TITLE
Tests failing on appveyor: `signed long int` vs `signed long long int`

### ISSUE THREAD

**Issue by forejtv** [diffblue/cbmc#769]
AppVeyor fails on some of the tests (https://ci.appveyor.com/project/diffblue/cbmc/build/1.0.667), for example `approx-array-variable-const-fp` fails because the regexp
```
^\s*IF fp_tbl\[\(signed long int\)i\] == f2 THEN GOTO [0-9]$
```
is not matched. There is a line
```
        IF fp_tbl[(signed long long int)i] == f2 THEN GOTO 1
```
in the output, though. Two more tests fail, for a similar reason.

We have seen a similar problem with @thk123 before. Thomas, is it fine if I change the regexp so that it *also* matches `signed long long int`?

**Comment by thk123** [comment]
I don't understand - but this test is to be checking we optimise the correct function calls away, not the syntax of accessing an array index - I think the check would be as correct with the following regex:

```regex
^\s*IF fp_tbl\[.*] == f2 THEN GOTO [0-9]$
```

**Comment by tautschnig** [comment]
Note that on 64-bit Windows `long int` is still only 32 bits wide - thus all array index types are `long long int`. Hence the failures - but indeed might not care all that much about the index type. (Just one note: there is one `\` missing in @thk123's suggestion.

**Comment by forejtv** [comment]
I'll create a PR in due course.
