### ISSUE TITLE
Question: how does CBMC --refine option work?

### ISSUE THREAD

**Issue by rladydpf1** [diffblue/cbmc#7719]
CBMC version: 5.43

I looked at some tools for abstraction, like Blast and CPAChecker.
Do these tools work in a similar way to CBMC --refine?
I also found SATABS (SAT-based Predicate Abstraction for C), so I guess CBMC --refine may use SATABS.
Please provide me with a brief description of the refine option.

**Comment by martin-cs** [comment]
> Do these tools work in a similar way to CBMC --refine?
No.
* BLAST is a fairly classical predicate abstraction tool.  The abstraction is program -> automata and the refinement is using predicates abstraction.
* CPAChecker is a suite of tools so one has to be rather careful about exactly what it does, it very much depends on how it is configured.  They do have a predicate abstraction engine that was similar to BLAST at one point but I think is now closer to an interpolant based tool.
* CBMC's --refine option is approximating the formula and refinement is modifying the formula.


> I also found SATABS (SAT-based Predicate Abstraction for C), so I guess CBMC --refine may use SATABS.
SATABS has been unmaintained for quite some time now.  The most I know is here:
https://github.com/diffblue/cbmc/issues/6735#issuecomment-1071617718


> Please provide me with a brief description of the refine option.
If you have a formula you can overapproximate the set of models by leaving out part of the formula.  Either whole expressions or parts of a conjunct or even parts of single operation.  If it is UNSAT then the original must be UNSAT as well.  If it is SAT then you need to check if it is actually a model of the original or if it is introduced by the approximation.  If it is introduced then you need to undo the approximation and solve again.

If you have a formula you can underapproximate the set of models by adding things to the formula.  You can add whole expressions, drop parts of a disjunct or fix bits within a single operation.  If it is SAT then the original must be SAT as well.  If it is UNSAT then you need to check if it is actually a proof of the original or if it requires using the things introduced by the approximation.  If it is introduced then you need to undo the approximation and solve again.

These are the two "sides" of the approximation loop.  You can do both at the same time if you like.

HTH

**Comment by rladydpf1** [comment]
thank you for your explanation.

**Comment by rladydpf1** [comment]
I've tried CBMC --refine to some extent. 
What I found here was that if there is no float expressions in the target code, CBMC --refine doesn't do abstraction.
In other say, CBMC --refine abstracts only floating-point bit-vectors like:
```
...
Found assumption for '613/floatbv_div' in proof (state 0)
Found assumption for '614/floatbv_plus' in proof (state 0)
BV-Refinement: got UNSAT, and the proof fails, refining
BV-Refinement: iteration 2
89462534 variables, 280521651 clauses
SAT checker: instance is SATISFIABLE
Found spurious '0/floatbv_plus' (state 0)
Found spurious '1/floatbv_div' (state 0)
...
```

I expected that CBMC --refine will perform similarly to SATABS (https://link.springer.com/chapter/10.1007/978-3-540-31980-1_40). What is the difference between SATABS and CBMC --refine?
I would appreciate it if you could let me know any related research papers of CBMC --refine.

**Comment by peterschrammel** [comment]
There's a paper that describes it: http://www.kroening.com/papers/fmcad2009.pdf
