### ISSUE TITLE
Compiling with cadical needs a flag to turn off optional compiler warnings

### ISSUE THREAD

**Issue by martinlester** [diffblue/cbmc#7725]
CBMC version: 5.83.0
Operating system: Debian 12
Exact command line resulting in the issue: cmake -S . -Bbuild -Dsat_impl="cadical" ; cmake --build build
What behaviour did you expect: Successful compilation with cadical as SAT solver.
What happened instead: Compilation error.

Lots of errors like this:

````
solver.cpp:259:3: error: ‘nonnull’ argument ‘this’ compared to NULL [-Werror=nonnull-compare]
````

I can work around this by configuring with something like this instead:

````
cmake -S . -Bbuild -DCMAKE_CXX_FLAGS="-Wnonnull-compare"
````

**Comment by tautschnig** [comment]
I have filed an [issue against CaDiCaL](https://github.com/arminbiere/cadical/issues/54) to get this fixed upstream.
