### ISSUE TITLE
Simpler "all checks on" command line option please

### ISSUE THREAD

**Issue by rod-chapman** [diffblue/cbmc#7746]
I want to use CBMC with contracts and loop invariants where soundness is the default behaviour.

I am tired of having to remember all the "--*-check" options and writing them in scripts or in Makefiles.

Could you apply an "--all-checks" option please to turn them all on (or, at least, the majority of checks that make sense for this use case)?

I am using CBMC 5.84 on macOS presently.

**Comment by remi-delmas-3000** [comment]
On can also use CBMC through the cbmc-starter-kit, which provides the desired defaults, and also generate a html reports and coverage summaries.

**Comment by tautschnig** [comment]
Closing as with CBMC 6 all undefined-behaviour checks are now enabled by default.
