### ISSUE TITLE
realpath failed: Invalid argument when using goto-gcc

### ISSUE THREAD

**Issue by lyb1234567** [diffblue/cbmc#7765]
Hello,
I am new to goto-gcc. I try to use it to Compile the source files into a GOTO binary. And i want to use goto-cc to link multiple c files. But it gave me the realpath error when i am using it

CBMC version:  CBMC version 5.12 (cbmc-5.12) 64-bit x86_64 linux
Operating system: Ubuntu 22.04.1 LTS
Exact command line resulting in the issue: goto-cc file1.c file2.c file3.c main.c -o myprogram        
What behaviour did you expect: It should generate a file named myprogram directly
What happened instead:  realpath failed: Invalid argument

**Comment by tautschnig** [comment]
Thank you for your report. Would you be able to try a newer version of the package as available from our releases page? We acknowledge that the Debian/Ubuntu packages need updating, and are actively working on this. For the time being, however, only GitHub has the latest releases.

**Comment by lyb1234567** [comment]
Problem solved !!
Thanks a lot

**Comment by NlightNFotis** [comment]
Hello,

I'm going ahead and closing this issue, but feel free to open a new one if you have any more questions.
