### ISSUE TITLE
What is different between location coverage and statements coverage?

### ISSUE THREAD

**Issue by thefvckingworld** [diffblue/cbmc#7766]
I am testing the statements coverage of a program,  I using [--cover location] option to execute cbmc, and the code is as follows:

    void main(void) {
    
        int a = 1;
        int b = 2;
        int c = 3;
        int d = 2;
        int e = 3;
        int f = 5;
        int g = 6;
        int h = 6;
        int i = 6;
        int j = 6;
        int k = 6;
        int l = 6;
        int m = 6;
        int n = 6;
        int o = 6;
        int p = 6;
        int q = 6;
        int r = 6;
        int s = 6;
    
        if (a < 0) {
            a = 2;
        }
    }

My expected statement coverage is 19 / 21= 90.4%, because the codition a < 0  is false.
The actual result is 66.7%。

Maybe I misunderstood the location option and look forward to a reply.

CBMC version: 5.80.0
Operating system: windows
Exact command line resulting in the issue: cbmc -gcc --arch i386 test.c --cover location --xml-ui --show-test-suite > result_statements.xml
What behaviour did you expect: the code coverage is 90.4%
What happened instead: the code coverage is 66.7%

**Comment by NlightNFotis** [comment]
Hello,

I've run your code past `cbmc` via: `$ cbmc --cover location /tmp/cover.c` with `/tmp/cover.c` being the code you've listed in the OP, and the complete output that I get is:

```sh
CBMC version 5.84.0 (cbmc-5.84.0-25-g1cc4a4ba21) 64-bit arm64 macos
Parsing /tmp/cover.c
Converting
Type-checking cover
Generating GOTO Program
Adding CPROVER library (arm64)
Removal of function pointers and virtual functions
Generic Property Instrumentation
Rewriting existing assertions as assumptions
Running with 8 object bits, 56 offset bits (default)
Starting Bounded Model Checking
Runtime Symex: 0.00433367s
size of program expression: 57 steps
Generated 2 VCC(s), 2 remaining after simplification
Runtime Postprocess Equation: 1.3458e-05s
Passing problem to propositional reduction
converting SSA
Runtime Convert SSA: 0.000969292s
Running propositional reduction
Post-processing
Runtime Post-process: 8.584e-06s
Solving with MiniSAT 2.2.1 with simplifier
608 variables, 0 clauses
SAT checker: instance is SATISFIABLE
Runtime Solver: 0.000228791s
Runtime decision procedure: 0.00125579s

** coverage results:
[main.coverage.1] file /tmp/cover.c line 3 function main block 1 (lines /tmp/cover.c:main:3-21,23): SATISFIED
[main.coverage.2] file /tmp/cover.c line 24 function main block 2 (lines /tmp/cover.c:main:24): FAILED
[main.coverage.3] file /tmp/cover.c line 26 function main block 3 (lines /tmp/cover.c:main:26): SATISFIED

** 2 of 3 covered (66.7%)
** Used 2 iterations
```

The output explains that it checked coverage of *blocks*, which is consistent with the explanation at the top of the file `src/goto-instrument/cover_instrument_location.cpp`, which states `/// Coverage Instrumentation for Location, i.e. Basic Blocks`.

So, the output is correct, but it seems like you were working under the assumption that the location refers to lines of code, whereas it refers to [basic blocks](https://en.wikipedia.org/wiki/Basic_block). Under that interpretation, it has split it into 3 basic blocks, only one of which is not covered (the one that contains the statement in the consequent branch of your `if` statement), which seems consistent with my expectations of how it should work given the code you presented and the implementation of the module.

Does that answer your question?

**Comment by thefvckingworld** [comment]
> Hello,
> 
> I've run your code past `cbmc` via: `$ cbmc --cover location /tmp/cover.c` with `/tmp/cover.c` being the code you've listed in the OP, and the complete output that I get is:
> 
> ```shell
> CBMC version 5.84.0 (cbmc-5.84.0-25-g1cc4a4ba21) 64-bit arm64 macos
> Parsing /tmp/cover.c
> Converting
> Type-checking cover
> Generating GOTO Program
> Adding CPROVER library (arm64)
> Removal of function pointers and virtual functions
> Generic Property Instrumentation
> Rewriting existing assertions as assumptions
> Running with 8 object bits, 56 offset bits (default)
> Starting Bounded Model Checking
> Runtime Symex: 0.00433367s
> size of program expression: 57 steps
> Generated 2 VCC(s), 2 remaining after simplification
> Runtime Postprocess Equation: 1.3458e-05s
> Passing problem to propositional reduction
> converting SSA
> Runtime Convert SSA: 0.000969292s
> Running propositional reduction
> Post-processing
> Runtime Post-process: 8.584e-06s
> Solving with MiniSAT 2.2.1 with simplifier
> 608 variables, 0 clauses
> SAT checker: instance is SATISFIABLE
> Runtime Solver: 0.000228791s
> Runtime decision procedure: 0.00125579s
> 
> ** coverage results:
> [main.coverage.1] file /tmp/cover.c line 3 function main block 1 (lines /tmp/cover.c:main:3-21,23): SATISFIED
> [main.coverage.2] file /tmp/cover.c line 24 function main block 2 (lines /tmp/cover.c:main:24): FAILED
> [main.coverage.3] file /tmp/cover.c line 26 function main block 3 (lines /tmp/cover.c:main:26): SATISFIED
> 
> ** 2 of 3 covered (66.7%)
> ** Used 2 iterations
> ```
> 
> The output explains that it checked coverage of _blocks_, which is consistent with the explanation at the top of the file `src/goto-instrument/cover_instrument_location.cpp`, which states `/// Coverage Instrumentation for Location, i.e. Basic Blocks`.
> 
> So, the output is correct, but it seems like you were working under the assumption that the location refers to lines of code, whereas it refers to [basic blocks](https://en.wikipedia.org/wiki/Basic_block). Under that interpretation, it has split it into 3 basic blocks, only one of which is not covered (the one that contains the statement in the consequent branch of your `if` statement), which seems consistent with my expectations of how it should work given the code you presented and the implementation of the module.
> 
> Does that answer your question?

yes, It's the answer I want. Thanks for replying. I misunderstood the function of the location option.

**Comment by NlightNFotis** [comment]
No problem.

I'm going to go ahead and close this issue.

Feel free to open a new one if you have any other questions.
