### ISSUE TITLE
cbmc 5.7 build failure with gcc 7

### ISSUE THREAD

**Issue by jamesjer** [diffblue/cbmc#777]
Building on a Fedora F26 (prerelease) x86_64 machine with gcc 7.0.1:

qbf/qbf_bdd_core.cpp: In member function 'void qbf_bdd_coret::compress_certificate()':
qbf/qbf_bdd_core.cpp:448:46: error: 'begin' was not declared in this scope
         for(const quantifiert &quantifier2 : quantifier)
                                              ^~~~~~~~~~
qbf/qbf_bdd_core.cpp:448:46: note: suggested alternative:
In file included from /usr/include/c++/7/string:51:0,
                 from /usr/include/c++/7/bits/locale_classes.h:40,
                 from /usr/include/c++/7/bits/ios_base.h:41,
                 from /usr/include/c++/7/ios:42,
                 from /usr/include/c++/7/istream:38,
                 from /usr/include/c++/7/fstream:38,
                 from qbf/qbf_bdd_core.cpp:10:
/usr/include/c++/7/bits/range_access.h:87:5: note:   'std::begin'
     begin(_Tp (&__arr)[_Nm])
     ^~~~~
qbf/qbf_bdd_core.cpp:448:46: error: 'end' was not declared in this scope
         for(const quantifiert &quantifier2 : quantifier)
                                              ^~~~~~~~~~
qbf/qbf_bdd_core.cpp:448:46: note: suggested alternative:
In file included from /usr/include/c++/7/string:51:0,
                 from /usr/include/c++/7/bits/locale_classes.h:40,
                 from /usr/include/c++/7/bits/ios_base.h:41,
                 from /usr/include/c++/7/ios:42,
                 from /usr/include/c++/7/istream:38,
                 from /usr/include/c++/7/fstream:38,
                 from qbf/qbf_bdd_core.cpp:10:
/usr/include/c++/7/bits/range_access.h:97:5: note:   'std::end'
     end(_Tp (&__arr)[_Nm])
     ^~~

The version of qbf_bdd_coret::compress_certificate from cbmc 5.6 compiles cleanly.

**Comment by tautschnig** [comment]
Fixed via 5df0da69.
