### ISSUE TITLE
CBMC 5.82 - Memory Explosion on estimating coverage of a simple program

### ISSUE THREAD

**Issue by FlorianBarrau** [diffblue/cbmc#7791]
# Description 
CBMC version: 5.82
Operating system: Windows or Linux
Exact command line resulting in the issue: `cbmc -gcc --arch amd64 main.c inputs.c --cover location --object-bits 16`
What behaviour did you expect: Coverage Estimation
What happened instead: Memory Explosion

CBMC 5.82 seems to have a memory explosion on this simple program attached.
The main function calls the `read_inputs` that only assigns some global variables. 
I just want to estimate the coverage of this program. However, after only 20 000 iterations CBMC takes up to 7Go RAM memory.
Please note that this program is already limited to the minimum. In other words, some other function might follow `read_inputs`

The main program is as follows
```C
/*
 *
 * This is a simplified version reproducing CBMC Memory Explosion
 *
 */
#include "inputs.h"
int main(void)
{
    unsigned int step;
    step = 0;
    for(step = 0; step <=93150; step++)
    {
        read_inputs(0, step);
    }
    return 0;
}

```
# How to reproduce the issue
1. Download and unzip the source code [CBMC_MemoryLeaksForGithubv3.zip](https://github.com/diffblue/cbmc/files/11947248/CBMC_MemoryLeaksForGithubv3.zip)
2. Run `cbmc -gcc --arch amd64 main.c inputs.c --cover location --object-bits 16` 
3. If you want to compile `gcc -g main.c inputs.c  -o kid.out`

# Some Insights or Questions
1. It seems that the core of the problem is the high number of iterations in the for loop.
2. In my opinion, the options `--unwind` or `--depth` are irrelevant because it would bias the coverage estimation. Limiting the search depth or the unwind  would not provide an exhaustive coverage analysis, missing some "if" conditions in the file `inputs.c`
3. Are there ways to re-write the program to be more suitable for CBMC ?
5. Any other ideas?
Thank you

**Comment by thomasspriggs** [comment]
1. Yes, more loop unwinding means more memory usage.
2. Yes, the unwind limit can affect coverage results.
3. Maybe. This depends on exactly what you want to analyse. For example a coverage check of any single step could be much faster -
```
unsigned nondet_unsigned();

#include "inputs.h"
int main(void)
{
    unsigned int step = nondet_unsigned();
    __CPROVER_assume(step <= 93150);
    read_inputs(0, step);
    hypothetical_rest_of_example();
    return 0;
}
```
Yes, this is substituting your presumed actual `main.c` for more of an analysis harness, which means it is no longer an analysis of your actual main function.

4. If you need to analyse state transitions, then you could use a test harness which starts at any step and then applies a limited number of loop iterations of the state update code.

**Comment by FlorianBarrau** [comment]
Thank you very much for your answer. I had tried 3. and 4. on our hypothetical_rest_of_example, and unfortunately the coverage result does not make any sense for the following reasons
1. The configuration you propose assumes that the program has dependencies between subsequent states. 
2. The program has a global state, and the execution of a step implies a change on this global state, and impacts the future states of some sub-functions. 

In my opinion, It would have worked if the hypothetical_rest_of_example would not have a global state. However, in my case there is no choice but to unroll the whole loop, which will impact the memory, and therefore it is basically a limitation of bounded model checkers in general. 

Please let me know if you have other ideas, or if I am wrong with my conclusion. 
Thank you again for your help.

**Comment by thomasspriggs** [comment]
I don't have any further ideas that would help with this. I am going to close out this issue as my understanding is that the performance is as expected when unwinding large loops.
