### ISSUE TITLE
[Performance] redundant copies in the source code

### ISSUE THREAD

**Issue by sdingcn** [diffblue/cbmc#7792]
Hello,

I'm developing a code analyzer for finding performance issues in C++ code, and by running the analyzer on this project I found some places where adding `std::move` might reduce the number of redundant copies for large objects. Not sure how much performance gain can be achieved. Here are two such examples.

https://github.com/diffblue/cbmc/blob/6066b3409ce440b4e92215594d6367aa89abedcc/src/solvers/flattening/bv_utils.cpp#L675

https://github.com/diffblue/cbmc/blob/6066b3409ce440b4e92215594d6367aa89abedcc/src/goto-harness/function_call_harness_generator.cpp#L139

Any comments are welcome!

**Comment by kroening** [comment]
Yes, adding `std::move` in both cases would work, and would offer a small benefit. Please do a PR!

**Comment by TGWDB** [comment]
Closing as fixed by #7793
