### ISSUE TITLE
CBMC ran out of memory

### ISSUE THREAD

**Issue by rladydpf1** [diffblue/cbmc#7805]
CBMC version: 5.43
Operating system: Ubuntu 20.04, 187 GB memory
Exact command line resulting in the issue: `cbmc target.c --unwind 110  --trace`
What behaviour did you expect: I expected that CBMC will use all available memory (187 GB) and monitered the memory usage of CBMC using top.
What happened instead: CBMC only uses 80 GB and outputs "ran out of memory":
```
Parsing results/obj-follow/p1/origin/target.c
Converting
Type-checking target
Generating GOTO Program
Adding CPROVER library (x86_64)
Removal of function pointers and virtual functions
Generic Property Instrumentation
Running with 8 object bits, 56 offset bits (default)
Starting Bounded Model Checking
Runtime Symex: 81.0392s
size of program expression: 2297762 steps
simple slicing removed 8 assignments
Generated 110 VCC(s), 75 remaining after simplification
Runtime Postprocess Equation: 0.854424s
Passing problem to propositional reduction
converting SSA
Runtime Convert SSA: 142.208s
Running propositional reduction
Post-processing
Runtime Post-process: 0.0111566s
Solving with MiniSAT 2.2.1 with simplifier
131354697 variables, 569938740 clauses
SAT checker ran out of memory
Runtime Solver: 1600.64s
Runtime decision procedure: 1743.07s
** Results:
results/obj-follow/p1/origin/target.c function check_property
[check_property.assertion.1] line 611 assertion !(((new_speed > 150) && !(((direction_adjustment < 15) && (direction_adjustment > -15))))): ERROR
** 0 of 1 failed (1 iterations)
VERIFICATION ERROR
```

I thought that there could be two potential scenarios: first, there might be a memory limit within CBMC itself, and second, the Linux OOM (Out of Memory) killer could kill CBMC. However, there were no explicit memory limits for the process, user, or CBMC in my Linux system.

**Comment by martin-cs** [comment]
It's running out of memory in MiniSAT so an easy work-around would be to use a different SAT solver or SMT solver.

For performance MiniSAT uses 32 bit datatypes, even on 64bit platforms.  So the number of literals is limited to `2^{31}`:
https://github.com/niklasso/minisat/blob/37dc6c67e2af26379d88ce349eb9c4c6160e8543/minisat/core/SolverTypes.h#L51

But possibly more of a problem for you is the custom allocator which uses 32 bit identifiers:
https://github.com/niklasso/minisat/blob/37dc6c67e2af26379d88ce349eb9c4c6160e8543/minisat/mtl/Alloc.h#L91

You have just over $2^{29}$ variables so I wonder if that pushes you over an allocation limit.

It would be possible to change the types but it comes at a large performance hit.  I would suggest trying a more modern solver like CaDiCaL or similar.
