### ISSUE TITLE
[Question] Could not find goto-cc in the windows MSI

### ISSUE THREAD

**Issue by FlorianBarrau** [diffblue/cbmc#7832]
Hello i realized that there is no goto-cc executable available in the MSI provided 
Is there a limitation?
Or maybe i missed something
Thank you very much

**Comment by NlightNFotis** [comment]
I think on windows the binary we produce is called `goto-cl`. Let me have a look to verify that.

**Comment by NlightNFotis** [comment]
Yeah, just verified that.

On windows, we build `goto-cl` (the binary is named `goto-cl.exe` - https://github.com/diffblue/cbmc/actions/runs/5691178379/job/15425893231#step:9:1796

That's to mirror the compiler personality available in that environment (`cl.exe`).
