### ISSUE TITLE
html report of CBMC runs

### ISSUE THREAD

**Issue by ylevhariamzn** [diffblue/cbmc#7865]
CBMC version: 5.87
Operating system: Rocky Linux
Exact command line resulting in the issue:
What behaviour did you expect:
What happened instead:

I am looking at the html report for both coverage, and assertion, violations, as my souce base is relatively large (400 include files, and 120 c files), I would like a way to "not" see all the cluter of the functions that my proff has not used

e.g 

0.00 (0/37) 	al_uart_snps_read 	proofs/Stage2LoadLoadAndExecute/bootrom/HAL/pbs/src/al_hal_uart_snps.c
0.00 (0/2) 	al_spi_dbg_pasw_en 	proofs/Stage2LoadLoadAndExecute/bootrom/HAL/proprietary/drivers/spi_dbg_pasw/al_hal_spi_dbg_pasw.c
0.00 (0/16) 	al_spi_dbg_pasw_set_ex 	proofs/Stage2LoadLoadAndExecute/bootrom/HAL/proprietary/drivers/spi_dbg_pasw/al_hal_spi_dbg_pasw.c
0.00 (0/6) 	al_spi_dbg_pasw_sw_ovrd_set 	proofs/Stage2LoadLoadAndExecute/bootrom/HAL/proprietary/drivers/spi_dbg_pasw/al_hal_spi_dbg_pasw.c
0.00 (0/1) 	al_reg_write32_func 	proofs/Stage2LoadLoadAndExecute/bootrom/HAL/shared/chi_bridge/src/al_hal_chi_bridge.c
0.00 (0/1) 	al_reg_write64_func 	proofs/Stage2LoadLoadAndExecute/bootrom/HAL/shared/chi_bridge/src/al_hal_chi_bridge.c
0.00 (0/6) 	_al_ssu_hik_derivation_cnt_get 	proofs/Stage2LoadLoadAndExecute/bootrom/HAL/ssu/proprietary/src/al_hal_ssu.c
0.00 (0/27) 	al_ssu_derivation_nonce_set 	proofs/Stage2LoadLoadAndExecute/bootrom/HAL/ssu/proprietary/src/al_hal_ssu.c
0.00 (0/33) 	al_ssu_harden 	proofs/Stage2LoadLoadAndExecute/bootrom/HAL/ssu/proprietary/src/al_hal_ssu.c
0.00 (0/60) 	al_ssu_hardening_type_info_get 	proofs/Stage2LoadLoadAndExecute/bootrom/HAL/ssu/proprietary/src/al_hal_ssu.c
0.00 (0/5) 	al_ssu_hardening_type_is_global 	proofs/Stage2LoadLoadAndExecute/bootrom/HAL/ssu/proprietary/src/al_hal_ssu.c
0.00 (0/26) 	al_ssu_hik_derivation_cnt_inc 	proofs/Stage2LoadLoadAndExecute/bootrom/HAL/ssu/proprietary/src/al_hal_ssu.c
0.00 (0/52) 	al_ssu_hik_derive 	proofs/Stage2LoadLoadAndExecute/bootrom/HAL/ssu/proprietary/src/al_hal_ssu.c
0.00 (0/36) 	al_ssu_hik_flush_derived 	proofs/Stage2LoadLoadAndExecute/bootrom/HAL/ssu/proprietary/src/al_hal_ssu.c
0.00 (0/17) 	al_ssu_init 	proofs/Stage2LoadLoadAndExecute/bootrom/HAL/ssu/proprietary/src/al_hal_ssu.c

**Comment by tautschnig** [comment]
Issue in CBMC viewer, moved over to https://github.com/model-checking/cbmc-viewer/issues/145.
