### ISSUE TITLE
Inconsistent goto program after 'cbmc --unwind'

### ISSUE THREAD

**Issue by theyoucheng** [diffblue/cbmc#792]
Let's consider the piece of code below.
`````
int main(void) {
  int i=0;
  while(i<5) {
    i++;
    assert(i!=3);
  }
 return 0;
}
`````
If we run `cbmc main.c --unwind 2`, the result 'VERIFICATION SUCCESSFUL' is as expected. However, its goto program seems to be inconsistent and corresponds to the default case without unwinding: `cbmc main.c --unwind 2 --show-goto-functions`
`````
main /* main */
        // 0 file main.c line 3 function main
        signed int i;
        // 1 file main.c line 3 function main
        i = 0;
        // 2 file main.c line 4 function main
     1: IF !(i < 5) THEN GOTO 2
        // 3 file main.c line 5 function main
        i = i + 1;
        // 4 file main.c line 6 function main
        ASSERT i != 3 // assertion i != 3
        // 5 file main.c line 4 function main
        GOTO 1
        // 6 file main.c line 8 function main
     2: main#return_value = 0;
        // 7 file main.c line 8 function main
        dead i;
        // 8 file main.c line 9 function main
        END_FUNCTION
`````

**Comment by tautschnig** [comment]
CBMC will only be unwinding loops during symbolic execution - I think you are looking for the result that `goto-instrument --unwind 2` would produce?

**Comment by theyoucheng** [comment]
On 4/10/17 12:36 PM, Michael Tautschnig wrote:
>
> CBMC will only be unwinding loops during symbolic execution - I think 
> you are looking for the result that |goto-instrument --unwind 2| would 
> produce?
>
Thanks Michael. This output is reasonable then.

BTW, if I check the 'guard' literal for the assignment 'i++', this guard 
is always 'True'... Is this something expected?

Youcheng


-- 
Youcheng Sun
Research Assistant
Department of Computer Science
University of Oxford
Wolfson Building, Parks Road
Oxford OX1 3QD
https://sites.google.com/site/theyoucheng/

**Comment by tautschnig** [comment]
Where exactly are you checking this guard - would you mind pasting some code, and details at which point in the overall work flow you are calling this code?

**Comment by tautschnig** [comment]
While the context I have just requested would be useful for disambiguation: during symbolic execution this guard will always be true as constant propagation (and simplification) will figure this out. You'd be getting a different result if you did one of --no-propagation or --no-simplify.

**Comment by theyoucheng** [comment]
On 4/10/17 1:01 PM, Michael Tautschnig wrote:
>
> While the context I have just requested would be useful for 
> disambiguation: during symbolic execution this guard will always be 
> true as constant propagation (and simplification) will figure this 
> out. You'd be getting a different result if you did one of 
> --no-propagation or --no-simplify.
>

Thanks so much Michael!

I am dealing with the 'fault localization'. There is a method 
'collect_guards' that collects execution blocks, so that it has to 
detect different 'guards'. This procedure worked fine with 'if' blocks, 
however, as I reported earlier, it failed to recognize 'while' loop 
guards. By specifying the '--no-propagation' option, the guards 
collected look correct.

Youcheng



-- 
Youcheng Sun
Research Assistant
Department of Computer Science
University of Oxford
Wolfson Building, Parks Road
Oxford OX1 3QD
https://sites.google.com/site/theyoucheng/

**Comment by theyoucheng** [comment]
On 4/10/17 1:00 PM, Michael Tautschnig wrote:
>
> Where exactly are you checking this guard - would you mind pasting 
> some code, and details at which point in the overall work flow you are 
> calling this code?
>
Here it is

````
/*******************************************************************\

Function: fault_localizationt::collect_guards

   Inputs:

  Outputs:

  Purpose:

\*******************************************************************/

void fault_localizationt::collect_guards(lpointst &lpoints)
{
   for(symex_target_equationt::SSA_stepst::const_iterator
       it=bmc.equation.SSA_steps.begin();
       it!=bmc.equation.SSA_steps.end(); it++)
   {
     if(it->is_assignment() &&
        it->assignment_type==symex_targett::STATE &&
        !it->ignore)
     {
       if(!it->guard_literal.is_constant())
       {
         lpoints[it->guard_literal].target=it->source.pc;
         lpoints[it->guard_literal].score=0;
       }
     }

     // reached failed assertion?
     if(it==failed)
       break;
   }
}

````
If not specifying '--no-propagation', the 'it->guard_literal' for a 
while loop will be always 'True'.

-- 
Youcheng Sun
Research Assistant
Department of Computer Science
University of Oxford
Wolfson Building, Parks Road
Oxford OX1 3QD
https://sites.google.com/site/theyoucheng/

**Comment by tautschnig** [comment]
I think you might just have a case where constant propagation would equally cause trouble with an `if` - just build a program where the if/else branching can be determined through constant propagation. Conversely, you might build an example where the loop guard cannot be figured out via constant propagation.
