### ISSUE TITLE
CBMC reporting unexpected assertion failures

### ISSUE THREAD

**Issue by andrea1775** [diffblue/cbmc#7943]
Hi, 
I encountered the following issue in CBMC: 
If you invoke "cbmc test.c" (see [test.zip](https://github.com/diffblue/cbmc/files/12855036/test.zip)) on the following file, CBMC outputs that both assertions fail, whereas if we replace the assumption by   "__VERIFIER_assume(&dst >= &src)", we get 0 assertion failures (as expected). So how come that CBMC reports the assertions as failing in test.c?
CBMC version: 5.12
Operating system: Ubuntu 22.04 (64 bit)
Exact command line resulting in the issue: cbmc test.c

**Comment by martin-cs** [comment]
Hi @andrea1775 and thanks for the bug report.  The version in Ubuntu is really quite old and a lot of bugs have been fixed.  Could you try a more modern version and let us know if that helps?  There is a package pre-built for Ubuntu 22.04 here: https://github.com/diffblue/cbmc/releases

**Comment by tautschnig** [comment]
Copying the source code in here to facilitate discussion:
````c
#include <assert.h>
extern void __VERIFIER_assume(int cond);
int main() {
  int src;
  int dst;
  assert(&dst < &src);
  __VERIFIER_assume(&dst > &src);
  assert(0);
  return 0;
}
````
In the `assert` statement, you are comparing pointers to different objects. This is undefined behaviour (C11 6.5.8, paragraph 5), and CBMC is free to provide whatever answer here.
