### ISSUE TITLE
src/util/message.h - `messaget()` (empty `messaget` constructor)

### ISSUE THREAD

**Issue by NlightNFotis** [diffblue/cbmc#8017]
Cleanup empty `messaget()` constructor (marked `DEPRECATED`) under `src/util/message.h`

**Comment by NlightNFotis** [comment]
The following PR is resolving (partially?) this issue: https://github.com/diffblue/cbmc/pull/4050

**Comment by tautschnig** [comment]
This has been resolved in 8110e31ee862.
