### ISSUE TITLE
ansi_c_languaget::to_expr doesn't work

### ISSUE THREAD

**Issue by thk123** [diffblue/cbmc#807]
I am trying to use `ansi_c_languaget::to_expr`. The following code doesn't appear to do anything useful

```C++
ansi_c_languaget lang;
exprt declaration;
symbol_tablet symbol_table;
namespacet ns(symbol_table);
bool result=lang.to_expr("int s;", "", declaration, ns);
```

The result is true (i.e. the operation has failed). This appear to be because it transforms the code and compiles:

`void __my_expression = (void) (\n"+code+"\n);");`

Where `code` is `int s;`

Removing this step and just compiling code, the result it false (i.e. the operation has succeeded), but `declaration.id()==ID_nil`. I would expect an exprt representing a declaration of a symbol.

**Comment by tautschnig** [comment]
I don't think your example would constitute proper use: you are trying to parse a statement, not an expression. Take a look at goto-instrument/model_argc_argv.cpp for an example parsing statements.

**Comment by tautschnig** [comment]
The only way to resolve this issue could be better documentation, or should it just be closed as is? @thk123 ?

**Comment by thk123** [comment]
Hi sorry this stopped blocking me - I think this still doesn't work even for reasonable RHS code but I've now lost the example - we can just close this for now - if/when I try to use it again I'll open a new issue with more detail
