### ISSUE TITLE
Build with system CaDiCaL

### ISSUE THREAD

**Issue by kotopesutility** [diffblue/cbmc#8113]
Could you add CMake option to build cbmc with system installed CaDiCaL?

CBMC version: 5.95.1
Operating system: ALT Linux
Exact command line resulting in the issue:
What behaviour did you expect: Build with system CaDiCaL
What happened instead: it tries to download CaDiCaL last release

**Comment by tautschnig** [comment]
Would you have some pointers as to where/which CaDiCaL files can be found? A pointer to pre-built RPMs would also work. Thank you!

**Comment by kotopesutility** [comment]
Sorry, like this?
https://packages.fedoraproject.org/pkgs/cadical/cadical-devel/fedora-rawhide.html#files

**Comment by tautschnig** [comment]
Could you please give https://github.com/diffblue/cbmc/pull/8159 a try and let us know whether this works as expected? Thank you!

**Comment by kotopesutility** [comment]
> Could you please give #8159 a try and let us know whether this works as expected? Thank you!

It works! Cool! Thank you!
