### ISSUE TITLE
Semantics of assert statements

### ISSUE THREAD

**Issue by salvadorer** [diffblue/cbmc#8223]
Hey,
I'm working with CBMC 5.95.1 and I noticed that CBMC does not add asserted conditions to the path conditions. For e.g.:
```
#include <assert.h>

extern int __VERIFIER_nondet_int(void);

int main() {
  int x = __VERIFIER_nondet_int();
  assert(x < 0);
  assert(x <= 0);
 }
```
CBMC would report a warning about both assertions but there's actually no value for x that can trigger the second assertion.

**Comment by tautschnig** [comment]
That's indeed true, see #5866: we might revisit this at some point, but until then please redefine the `assert` macro like this: 
```
#undef assert
#define assert(C) __CPROVER_assert((C), "assertion"); __CPROVER_assume(C)
```

**Comment by martin-cs** [comment]
@salvadorer Just for interest, this is why they don't alter the path condition:

https://github.com/diffblue/cbmc/pull/2031
https://github.com/diffblue/cbmc/commit/92b92d6032d4f0492603d2f85db5b52d6798b04c

I'm still reasonably convinced this is the correct design decision.

**Comment by tautschnig** [comment]
Closing as this is documented behaviour.
