### ISSUE TITLE
CBMC-6.0.0 fails if local variable name overloads name of quantified variable in contract

### ISSUE THREAD

**Issue by rod-chapman** [diffblue/cbmc#8337]
CBMC version: 6.0.0-preview (built 17th June 2024)
Operating system: macOS
Exact command line resulting in the issue: make TARGET=init_st
What behaviour did you expect: success
What happened instead:

CBMC fails on the latest examples here:
 https://github.com/rod-chapman/cbmc-examples/tree/main/arrays

In particular, see the init_st() function.

Attempt to verify with
 make TARGET=init_st

results in
```
rodchap@f4d4889dcf6d arrays % make TARGET=init_st
rm -f *.goto
goto-cc --function init_st_harness -DCBMC -o ar.goto ar.c
ar.c: In function 'init_st':
ar.c:171:1: error: symbol 'init_st::1::i' redefined with a different type:
Original: unsigned int
     New: size_t
     size_t i;
CONVERSION ERROR
make: *** [ar.goto] Error 1

```

This appears to be because the quantified variable "i" in the "ensures" contract (in ar.h) has the same name as a local variable "i" in the function body. This should not happen - I assume that quentified variables are supposed to have their own scope and possibly their own name-space.

Changing the name of the quantified variable so it doesn't clash appears to make this problem go away.

**Comment by tautschnig** [comment]
I am unable to reproduce this at this time - the code in the repository has evolved, but I tried the following snippet that should be close to what this may have looked like in the past:
````c
int main()
{
  __CPROVER_size_t i;
  char dst[5];
  for (i = 0; i < 5; i++)
    __CPROVER_loop_invariant(__CPROVER_forall { int i; (0 <= i && i < 5) ==> dst[i] == 0 } )
    {
      dst[i] = 0;
    }
}
````
The above compiles just fine. More information would be appreciated.

**Comment by rod-chapman** [comment]
I have restored a simplified and reproducible test case here:
 https://github.com/rod-chapman/cbmc-examples/tree/main/issues/8337
It still fails with wavefront CBMC 6.0.1
