### ISSUE TITLE
no bounds check assertion

### ISSUE THREAD

**Issue by Anthonysdu** [diffblue/cbmc#8351]
```c
#include <assert.h>
extern int __VERIFIER_nondet_int();
int main() {
  int arr[3];
  int a = __VERIFIER_nondet_int();
  if (a >= 0)
    return 0;
  arr[a] = 1;
  assert(arr[a] == 1);
}
```
The assertion in the program does not hold because there is an array bound violation when a < 0. and cbmc outputs `assertion arr[a] == 1: FAILURE`. However, for my understanding, cbmc by default doesnot enable bound check unless using` --bounds-check`, can you briefly why cbmc can still report the bug? Does it mean cbmc doesn't assume there is no bounds violation? thank you!

**Comment by kroening** [comment]
We don't guarantee any particular semantics for programs with undefined behavior, i.e., the result you get depends on specific choices made by the reasoning engines.

It's worth noting that version 6 enables the array bounds check by default.
