### ISSUE TITLE
goto-cc 6.0.0 fails compilation of s2n-tls unit on Linux, but works on macOS

### ISSUE THREAD

**Issue by rod-chapman** [diffblue/cbmc#8358]
I'm seeing a difference between goto-cc 6.0.0 on macOS and Linux.  The unit in question is tests/cbmc/sources/cbmc_utils.c in the s2n-rls repo.

On macOS:
```
sources % goto-cc --version
clang version 15.0.0 (goto-cc 6.0.0 (cbmc-6.0.0-2-g14254e0a5d))

Copyright (C) 2006-2018 Daniel Kroening, Christoph Wintersteiger
CBMC version: 6.0.0 (cbmc-6.0.0-2-g14254e0a5d)
Architecture: arm64
OS: macos
clang: 15.0.0
rodchap@f4d4889dcf6d sources % goto-cc  -c -Wall -I../../.. -I../../../tests/cbmc/include -I../../../tests/cbmc/aws-verification-model-for-libcrypto/include -DCBMC=1 -DCBMC_OBJECT_BITS=8 cbmc_utils.c
```
works fine. But the same on Ubuntu Linux:
```
sources$ goto-cc --version
gcc (goto-cc 6.0.0 (cbmc-6.0.0)) 11.4.0

Copyright (C) 2006-2018 Daniel Kroening, Christoph Wintersteiger
CBMC version: 6.0.0 (cbmc-6.0.0)
Architecture: x86_64
OS: linux
gcc: 11.4.0
ubuntu@ip-172-31-24-211:~/s2n/s2n-tls-rod/tests/cbmc/sources$ goto-cc  -c -Wall -I/home/ubuntu/s2n/s2n-tls-rod -I/home/ubuntu/s2n/s2n-tls-rod/tests/cbmc/include  -DCBMC=1 -DCBMC_OBJECT_BITS=8 cbmc_utils.c
cbmc_utils.c: In function 'assert_rc_decrement_on_evp_pkey_ctx':
cbmc_utils.c:203:1: error: member operator got incomplete struct_tag type on left hand side
         assert(storage->pkey->references == storage->pkey_refs - 1);
CONVERSION ERROR
```
Note that "goto-cc --version" reports clang 15.0.0 on macOS, but gcc 11.4.0 on Linux. Is that significant perhaps?

**Comment by tautschnig** [comment]
Could you please attach preprocessed source to this issue? You can obtain these by adding -E to the goto-cc commands. 

Edit: Also, please add the s2n-tls commit id you are working off of.

Thank you!

**Comment by rod-chapman** [comment]
If I run gcc directly on that source file, I get a slightly more detailed error message:
```
In file included from cbmc_utils.c:16:
cbmc_utils.c: In function ‘assert_rc_decrement_on_evp_pkey_ctx’:
cbmc_utils.c:203:29: error: invalid use of incomplete typedef ‘EVP_PKEY’ {aka ‘struct evp_pkey_st’}
  203 |         assert(storage->pkey->references == storage->pkey_refs - 1);
      |                             ^~
```

**Comment by tautschnig** [comment]
> If I run gcc directly on that source file, I get a slightly more detailed error message:

So this isn’t a goto-cc issue?!

**Comment by rod-chapman** [comment]
Well... it seems that the compiler upon which goto-cc is built and/or based on seems to matter in some way. Here is the expanded source attached.
[cbmc_utils_expanded.c.gz](https://github.com/user-attachments/files/15956087/cbmc_utils_expanded.c.gz)

**Comment by tautschnig** [comment]
> cbmc_utils_expanded.c.gz

Is this Linux or macOS? Could you please provide the other one as well?

**Comment by rod-chapman** [comment]
That one was pre-processed on Linux.

**Comment by rod-chapman** [comment]
Here it is again, this time expanded with clang 15.0.0 on macOS...
[cbmc_utils_expanded_macos.c.gz](https://github.com/user-attachments/files/15956376/cbmc_utils_expanded_macos.c.gz)

**Comment by kroening** [comment]
`goto-gcc` simply calls `gcc`, passing through any arguments, `goto-clang` calls `clang`, and so on. We should find a way of clarifying whether an error message is generated by the underlying compiler, or by our own parser/typechecker.

**Comment by tautschnig** [comment]
The difference here is on your Linux system you appear to have OpenSSL's header files installed in the default include search path of the preprocessor (and you don't use `-nostdinc`). With those header files installed, `crypto/s2n_evp.h` will bring in `/usr/include/openssl/evp.h` instead of `tests/cbmc/aws-verification-model-for-libcrypto/include/openssl/evp.h` (as is the case in your macOS run).

Closing as this doesn't seem an issue on goto-cc's side. Please feel free to reopen with more info if you still think that goto-cc needs to be changed in any way.

**Comment by rod-chapman** [comment]
Ah... that makes sense. The instructions in the s2n-tls README file tell me to install "libssl-dev" to build s2n-tls on Linux, so that makes sense. Now... I will ask the s2n-tls developers how they handle this case.
