### ISSUE TITLE
Simple error message if --smt2 set and no Z3 on PATH

### ISSUE THREAD

**Issue by rod-chapman** [diffblue/cbmc#8362]
cbmc 6.0.0 indicates that proof has failed if --smt2 is set and Z3 is not on PATH. This makes it difficult to know what's gone wrong, especially in CI and GitHub runners.

A simple error message like

"Z3 not installed"

would be helpful.

**Comment by tautschnig** [comment]
With #8378 you will now get `error running SMT2 solver: execvp z3 failed: No such file or directory`.
