### ISSUE TITLE
List of C/C++ Compiler Support

### ISSUE THREAD

**Issue by QinyuanWu** [diffblue/cbmc#8372]
I read in the [CPROVER documentation](https://diffblue.github.io/cbmc/cprover_documentation.html#:~:text=CBMC%20is%20a%20Bounded%20Model%20Checker%20for%20C,compiler%20extensions%20provided%20by%20gcc%20and%20Visual%20Studio.) that CBMC support most compiler extensions provided by gcc and Visual Studio. Is this information still update to date and can we get a list of compilers that are currently support by CBMC? Note this is the compiler for the C/C++ code to be verified.

Thank you!

CBMC version: 6.0.0
Operating system: Ubuntu 22.04

**Comment by tautschnig** [comment]
It is correct that we try to support GCC, Visual Studio, and also Clang (extensions). We do not run any test suite that would permit claiming completeness here, and we'd also have to do a full cross-product of compilers (and different versions thereof) and the hardware and operating systems that are targetted. Instead, we do a best-effort approach and would appreciate any issues reporting hitherto unsupported features as and when you need them.

Closing for now, but please feel free to re-open if you have suggestions for a different approach.
