### ISSUE TITLE
Model loop invariant with __CPROVER_loop_entry and __CPROVER_loop_old

### ISSUE THREAD

**Issue by QinyuanWu** [diffblue/cbmc#8374]
I want to understand the usage of `__CPROVER_loop_entry` and `__CPROVER_loop_old` for loop invariants as these are currently not documented. 
I'm trying to write a loop contract for this while loop with the invariant that the unsigned integer `cbData` will always be less than its original value when passed in as a function parameter before entering the loop:    

```c
while( cbData >= 64 ) // cbData is a function parameter
    __CPROVER_assigns( cbData, A, B, C, D, T, r, __CPROVER_whole_object( buf ), __CPROVER_whole_object( ha ), __CPROVER_whole_object( W ) )
    __CPROVER_loop_invariant( cbData <= __CPROVER_loop_entry(cbData) ) // is this correct?
    __CPROVER_decreases( cbData )
    {
        //
        // Capture the input into W[0..15]
        //
        for( r=0; r<16; r++ )
        __CPROVER_assigns( r, __CPROVER_whole_object( W ) )
        __CPROVER_loop_invariant( r <= 16 )
        __CPROVER_decreases( 16 - r )
        {
            W[r] = SYMCRYPT_LOAD_MSBFIRST32( &pbData[ 4*r ] );
        }

        //
        // Expand the message
        //
        A = W[15];
        B = W[14];
        D = W[0];
        for( r=16; r<64; r+= 2 )
        __CPROVER_assigns( A, B, C, D, T, r, __CPROVER_whole_object( buf ), __CPROVER_whole_object( ha ), __CPROVER_whole_object( W ) )
        __CPROVER_loop_invariant( r <= 64 && A==W[r-1] B==W[r-2] && D == W[r-16])  // is this correct?
        __CPROVER_decreases( 64 - r )
        {
            // Loop invariant: A=W[r-1], B = W[r-2], D = W[r-16]

            //
            // Macro for one word of message expansion.
            // Invariant:
            // on entry: a = W[r-1], b = W[r-2], d = W[r-16]
            // on exit:  W[r] computed, a = W[r-1], b = W[r], c = W[r-15]
            //
            #define EXPAND( a, b, c, d, r ) \
                        c = W[r-15]; \
                        b =  d + LSIGMA1( b ) + W[r-7] + LSIGMA0( c ); \
                        W[r] = b; \

            EXPAND( A, B, C, D, r );
            EXPAND( B, A, D, C, (r+1));

            #undef EXPAND
        }

        A = ha[7];
        B = ha[6];
        C = ha[5];
        D = ha[4];

        for( r=0; r<64; r += 4 )
        __CPROVER_assigns( A, B, C, D, T, r, __CPROVER_whole_object( buf ), __CPROVER_whole_object( ha ), __CPROVER_whole_object( W ) )
        __CPROVER_loop_invariant( r <= 64 )
        __CPROVER_decreases( 64 - r )
        {
            //
            // Loop invariant:
            // A, B, C, and D are the a,b,c,d values of the current state.
            // W[r] is the next expanded message word to be processed.
            // W[r-8 .. r-5] contain the current state words h, g, f, e.
            //

            //
            // Macro to compute one round
            //
            #define DO_ROUND( a, b, c, d, t, r ) \
                t = W[r] + CSIGMA1( W[r-5] ) + W[r-8] + CH( W[r-5], W[r-6], W[r-7] ) + SymCryptSha256K[r]; \
                W[r-4] = t + d; \
                d = t + CSIGMA0( a ) + MAJ( c, b, a );

            DO_ROUND( A, B, C, D, T, r );
            DO_ROUND( D, A, B, C, T, (r+1) );
            DO_ROUND( C, D, A, B, T, (r+2) );
            DO_ROUND( B, C, D, A, T, (r+3) );
            #undef DO_ROUND
        }

        buf[3] = ha[7] = buf[3] + A;
        buf[2] = ha[6] = buf[2] + B;
        buf[1] = ha[5] = buf[1] + C;
        buf[0] = ha[4] = buf[0] + D;
        ha[3] += W[r-5];
        ha[2] += W[r-6];
        ha[1] += W[r-7];
        ha[0] += W[r-8];

        pbData += 64;
        cbData -= 64;
    }

```
I have several questions:
1. Is the use of `__CPROVER_loop_invariant( cbData <= __CPROVER_loop_entry(cbData) )` correct here? 
2. What is `__CPROVER_loop_old` used for? 
3. For the two inner for loops, there are invariants specified in the comments, does the loop invariant(`__CPROVER_loop_invariant( r <= 64 && A==W[r-1] B==W[r-2] && D == W[r-16]) `) correct reflected that? How do we or is it possible to specify loop invariant for the on entry and on exit invariants as listed in the comments?

Appreciate the guidance!

CBMC version: 6.0.1
Operating system: Ubuntu

**Comment by qinheping** [comment]
> I have several questions:
> 
>     1. Is the use of `__CPROVER_loop_invariant( cbData <= __CPROVER_loop_entry(cbData) )` correct here?

`__CPROVER_loop_entry(x)` is used to refer to the snapshot of `x` right before the entry of the loop. So, `cbData <= __CPROVER_loop_entry(cbData)` means `cbData` is no more than its value right before the entry of the loop. 

>     2. What is `__CPROVER_loop_old` used for?

`__CPROVER_loop_old` is deprecated and should not be used.

>     3. For the two inner for loops, there are invariants specified in the comments, does the loop invariant(`__CPROVER_loop_invariant( r <= 64 && A==W[r-1] B==W[r-2] && D == W[r-16]) `) correct reflected that? How do we or is it possible to specify loop invariant for the on entry and on exit invariants as listed in the comments?

I proved the first inner loop with the following loop contracts:

```c
int main()
{
  int W[100];
  int A = W[15];
  int B = W[14];
  int C;
  int D = W[0];
  for(unsigned r = 16; r < 64; r += 2)
    __CPROVER_loop_invariant(r >= 16 && r%2==0&&
      r <= 64 && A == W[r-1] && B == W[r - 2] &&
      D == W[r - 16]) // is this correct?
      __CPROVER_decreases(100 - r)
    {
// Loop invariant: A=W[r-1], B = W[r-2], D = W[r-16]

//
// Macro for one word of message expansion.
// Invariant:
// on entry: a = W[r-1], b = W[r-2], d = W[r-16]
// on exit:  W[r] computed, a = W[r-1], b = W[r], c = W[r-15]
//
unsigned x = 0;
#define EXPAND(a, b, c, d, rr)                                                  \
  c = W[rr - 15];                                                               \
  x = rr-15;                              \
  b = d +  b + W[rr - 7] + c;                                  \
  W[rr] = b;

      EXPAND(A, B, C, D, r);
      EXPAND(B, A, D, C, (r + 1));

#undef EXPAND
    }
}
```
You can try to prove it with the following command line
```
goto-cc main.c
goto-instrument --dfcc main --apply-loop-contracts a.out b.out
cbmc b.out
```

For the second loop, I think a similar loop contracts will work. Note that `r%4==0` is required.

Feel free to reopen if you have further questions.

**Comment by QinyuanWu** [comment]
Thank you @qinheping! 
May I confirm that `__CPROVER_loop_entry(cbData)` means `cbData` is always no more than its value right before **the first iteration** of the loop? For example, if `cbData` is passed into the function with a value of 64 and there is no modification to the value before encountering the loop, then the loop invariant means CBMC will check whether `cbData <= 64` before and after every iteration of the loop.

For the inner loop contract, is there a specific reason to use the value of 100 for the decrease clause?

**Comment by qinheping** [comment]
> Thank you @qinheping! May I confirm that `__CPROVER_loop_entry(cbData)` means `cbData` is always no more than its value right before **the first iteration** of the loop? For example, if `cbData` is passed into the function with a value of 64 and there is no modification to the value before encountering the loop, then the loop invariant means 
CBMC will check whether `cbData <= 64` before and after every iteration of the loop.

Yes, it is `__CPROVER_loop_entry(cbData)` is 64. You can imagine that we do a snapshot for the underlying variable, e.g.,

```c
int main(int x){

int snapshot_x = x;
while(...)
__CPROVER_loop_invariant(x <= __CPROVER_loop_entry(x)) //equivalent to x <= snapshot_x
{
...
}
return 0;
}
```


> For the inner loop contract, is there a specific reason to use the value of 100 for the decrease clause?

I tend to use a larger constant to get rid of thinking about what is the exact bound of `r`.  `64` should also work here.

**Comment by QinyuanWu** [comment]
@qinheping Thank you! It works now on my end. I've opened a separate [issue](https://github.com/QinyuanWu/SymCrypt-CBMC/blob/main/CBMC/proofs/Makefile-project-defines) for the cbmc-starter-kit pipeline for missing the `--object-bits` and `--unwind` flag.
