### ISSUE TITLE
Parsing error with MAYBE_UNUSED

### ISSUE THREAD

**Issue by ligurio** [diffblue/cbmc#8474]
CBMC version: 5.95.1 (cbmc-5.95.1)
Operating system: Ubuntu 22.04 x86_64
Exact command line resulting in the issue: `/bin/goto-cc ../proofs/rb.c -o rb`
What behaviour did you expect: Successful compilation.
What happened instead:

Parsing error:
```
../proofs/rb.c:1:1: error: syntax error before 'static'
 rb_gen_ext_key(MAYBE_UNUSED static inline, test_, tree_t, node_t, node,
PARSING ERROR
```

rb.c:

```c
rb_gen_ext_key(MAYBE_UNUSED static inline, test_, tree_t, node_t, node,
               node_cmp, int, key_node_cmp);

int main()
{
}
```

**Comment by tautschnig** [comment]
Could you please provide the preprocessed source rather than a snippet that in itself isn't valid C?

**Comment by tautschnig** [comment]
If https://codesearch.debian.net/search?q=rb_gen_ext_key&literal=0 is what we are looking at, then the macros should expand to something like
````c
__attribute__((unused)) static inline void foo()
{
}
````
which we parse just fine.

**Comment by ligurio** [comment]
Sorry, it was my bad.

`unit.h` included in a C file had lack of macros `MAYBE_UNUSED` and this was report by `goto-cc` as a parsing error.
