### ISSUE TITLE
Ubuntu 16.10 VPATH Build for Code Coverage Fails

### ISSUE THREAD

**Issue by jgwilson42** [diffblue/cbmc#948]
**Observed Behaviour**

When running `get_coverage.sh` on Ubuntu 16.10 I get the following error:
```
james_wilson@ubuntu:~/source/cbmc-db/regression$ ./get_coverage.sh 
INFO: Checking lcov is installed [OK]
INFO: setting up vpath build [ERROR]
ERROR: See ./coverage_X8gJs/cbmc_coverage.out for more information
james_wilson@ubuntu:~/source/cbmc-db/regression$ cat ./coverage_X8gJs/cbmc_coverage.out 
lcov: LCOV version 1.12
cp: cannot stat 'jsil/jsil_lex.yy.cpp': No such file or directory
james_wilson@ubuntu:~/source/cbmc-db/regression$ 
```
**Expected Behaviour**

Code coverage report.

**Version**

CBMC master Latest commit d999e56

**Steps to Reproduce**
1. On a clean ubuntu VM (gcloud)
2. Install packages from COMPILING
3. Install g++
4. `cd regression`
5. `./get_coverage.sh`

**Comment by tautschnig** [comment]
Taking ownership of this as I wrote that vpath build script in the first place.
