### ISSUE TITLE
Build no longer uses -O2 by default

### ISSUE THREAD

**Issue by tautschnig** [diffblue/cbmc#962]
As of  10eb073 running `make` without overwriting `CXXFLAGS` will no longer do optimised builds. This will cause severe performance penalties as the code base relies on compiler optimisation a lot.

At minimum, the instructions in "COMPILING" should be updated. I would, however, suggest that optimisations be re-enabled.

**Comment by martin-cs** [comment]
That's very concerning and I don't think that kind of change should be
part of a fix.

**Comment by NathanJPhillips** [comment]
Are you sure you have the right commit reference? I don't see the change that removes optimisation there.

**Comment by tautschnig** [comment]
The problem is that `CXXFLAGS += ...` in "config.inc" will cause `CXXFLAGS ?= ...` in "common" not to have any effect.

**Comment by NathanJPhillips** [comment]
I see. That does seem to be a problem. Shouldn't optimisation be added in config.inc rather than common? Unfortunately I've been moved off CBMC as part of our two month sprint, otherwise I'd suggest I do a PR to make that change.

**Comment by tautschnig** [comment]
@NathanJPhillips No worries - I've put up #969 that ought to address this. Comments/reviews appreciated.
